### ISSUE TITLE
[Crash] IllegalStateException in GeckoEngineView

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/android-components#10049]
[Crash stats](https://crash-stats.mozilla.org/signature/?product=Fenix&signature=java.lang.IllegalStateException%3A%20at%20mozilla.components.browser.engine.gecko.GeckoEngineView.render%28GeckoEngineView.kt%3A18%29&version=87.0.0&date=%3C2021-04-08T16%3A14%3A35%2B00%3A00&date=%3E%3D2021-04-01T16%3A14%3A35%2B00%3A00) 

GV confirms this is an AC crash: https://bugzilla.mozilla.org/show_bug.cgi?id=1651096

```
java.lang.IllegalStateException
	at mozilla.components.browser.engine.gecko.GeckoEngineView.render(GeckoEngineView.kt:18)
	at mozilla.components.feature.session.engine.EngineViewPresenter.access$onTabToRender(EngineViewPresenter.kt:9)
	at mozilla.components.feature.session.engine.EngineViewPresenter$start$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:2)
	at mozilla.components.support.ktx.kotlinx.coroutines.flow.FlowKt$ifAnyChanged$$inlined$filter$1$2.emit(Collect.kt:19)
	at mozilla.components.feature.session.engine.EngineViewPresenter$start$1$invokeSuspend$$inlined$map$1$2.emit(Collect.kt:7)
	at kotlinx.coroutines.flow.FlowKt.emitAllImpl$FlowKt__ChannelsKt(Unknown Source:13)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
	at android.os.Handler.handleCallback(Handler.java:907)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

```

**Comment by mcarare** [comment]
This is already tracked in https://github.com/mozilla-mobile/android-components/issues/9081. 
STR in : https://github.com/mozilla-mobile/fenix/issues/18127.

**Comment by Mugurell** [comment]
Eliza's STRs do not trigger this crash anymore - https://bugzilla.mozilla.org/show_bug.cgi?id=1651096#c9
Let's wait a bit more to see if there's any change in the reported crashes.

**Comment by csadilek** [comment]
Duping to #9081.

Closing as fixes have landed, see:
https://bugzilla.mozilla.org/show_bug.cgi?id=1651096
https://bugzilla.mozilla.org/show_bug.cgi?id=1741899
