### ISSUE TITLE
[Crash] RuntimeException in GeckoEngine.onShutdown

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/android-components#10073]
Crash report: https://crash-stats.mozilla.org/report/index/5eeb97c6-0717-433a-a6a7-1d4a00210412

Java stack trace:
```
java.lang.RuntimeException
	at mozilla.components.browser.engine.gecko.GeckoEngine$2.onShutdown(GeckoEngine.kt:1)
	at org.mozilla.geckoview.GeckoRuntime$1.handleMessage(GeckoRuntime.java:3)
	at org.mozilla.gecko.EventDispatcher$3.run(EventDispatcher.java:1)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:220)
	at android.app.ActivityThread.main(ActivityThread.java:7437)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:500)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:865)
```

**Comment by mcarare** [comment]
I think this crash is intentional, `RuntimeException` is thrown when the runtime is in an unrecoverable state. The exception detail message is related in this report but in Sentry it should be "GeckoRuntime is shutting down".
Maybe @pocmo can confirm this is intentional. Thank you!

**Comment by pocmo** [comment]
Yes, that was added intentionally. Let's involve the GeckoView team and see if they can help figure out why this is happening.

CC @agi

**Comment by mcarare** [comment]
Waiting on feedback from the GeckoView team.

**Comment by agi** [comment]
Sorry I completely missed this! Yes this is intentional, unfortunately it's not easy to know what's going on here. I think we need to add more metadata to this so that we can understand why this is happening, I opened https://bugzilla.mozilla.org/show_bug.cgi?id=1708580 for that.

**Comment by csadilek** [comment]
Duping to https://bugzilla.mozilla.org/show_bug.cgi?id=1708580.
