### ISSUE TITLE
Crash: IllegalStateException cache is closed

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#10125]
Sentry Nightly  https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/9840379/
Sentry Beta https://sentry.prod.mozaws.net/operations/firefox-beta/?query=is%3Aunresolved+cache+is+closed
Sentry Stable https://sentry.prod.mozaws.net/operations/firefox/?query=is%3Aunresolved+cache+is+closed

```
java.lang.IllegalStateException: cache is closed
    at com.jakewharton.disklrucache.DiskLruCache.checkNotClosed(DiskLruCache.java:2)
    at com.jakewharton.disklrucache.DiskLruCache.edit(DiskLruCache.java:2)
    at mozilla.components.browser.icons.utils.IconDiskCache.putResources(IconDiskCache.kt:5)
    at mozilla.components.browser.icons.processor.DiskIconProcessor.process(DiskIconProcessor.kt:2)
    at mozilla.components.browser.icons.BrowserIcons.access$loadIconInternal(BrowserIcons.kt:31)
    at mozilla.components.browser.icons.BrowserIcons$loadIcon$1.invokeSuspend(BrowserIcons.kt:2)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    at java.lang.Thread.run(Thread.java:762)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-91)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793152

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
