### ISSUE TITLE
Intermittent UI test failure - ui-samples-glean java.lang.IllegalArgumentException: Work with id d83fd10d-6432-44f1-986f-22145e608173 is not enqueued!

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/android-components#10134]
### Firebase Test Run:
https://console.firebase.google.com/project/moz-android-components-230120/testlab/histories/bh.acacddb44ee28c64/matrices/5061116035626006094/executions/bs.a8c0b4a10f653247
### Stacktrace:
```
java.lang.IllegalArgumentException: Work with id d83fd10d-6432-44f1-986f-22145e608173 is not enqueued!

     FATAL EXCEPTION: GleanAPIPool
Process: org.mozilla.samples.glean.debug, PID: 20668
java.lang.IllegalArgumentException: Work with id d83fd10d-6432-44f1-986f-22145e608173 is not enqueued!
	at androidx.work.testing.TestScheduler.setAllConstraintsMet(TestScheduler.java:110)
	at androidx.work.testing.TestWorkManagerImpl.setAllConstraintsMet(TestWorkManagerImpl.java:107)
	at mozilla.telemetry.glean.utils.WorkManagerUtilsKt$testFlushWorkManagerJob$1$1.invokeSuspend(WorkManagerUtils.kt:35)
	at mozilla.telemetry.glean.utils.WorkManagerUtilsKt$testFlushWorkManagerJob$1$1.invoke(Unknown Source:10)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:102)
	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:148)
	at kotlinx.coroutines.TimeoutKt.withTimeout(Timeout.kt:44)
	at mozilla.telemetry.glean.utils.WorkManagerUtilsKt$testFlushWorkManagerJob$1.invokeSuspend(WorkManagerUtils.kt:28)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at mozilla.telemetry.glean.utils.WorkManagerUtilsKt.testFlushWorkManagerJob(WorkManagerUtils.kt:27)
	at mozilla.telemetry.glean.utils.WorkManagerUtilsKt.testFlushWorkManagerJob$default(WorkManagerUtils.kt:26)
	at mozilla.telemetry.glean.scheduler.PingUploadWorker$Companion.enqueueWorker$glean_release(PingUploadWorker.kt:71)
	at mozilla.telemetry.glean.GleanInternalAPI.submitPingByNameSync$glean_release(Glean.kt:740)
	at mozilla.telemetry.glean.scheduler.MetricsPingScheduler.collectPingAndReschedule$glean_release(MetricsPingScheduler.kt:307)
	at mozilla.telemetry.glean.scheduler.MetricsPingScheduler.schedule(MetricsPingScheduler.kt:226)
	at mozilla.telemetry.glean.GleanInternalAPI$initializeInternal$1.invokeSuspend(Glean.kt:298)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
```
### Build: 
https://github.com/mozilla-mobile/android-components/commit/7425e13d075f737f548e3cecd04446628afa8c12

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-98)

**Comment by Archaeopteryx** [comment]
cc @badboy This has failed twice in the last 24h.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794874

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
