### ISSUE TITLE
Fix nimbus integration in samples-glean app

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#10253]
This is a follow-up to https://github.com/mozilla-mobile/android-components/pull/10144 which broken nimbus integration in `samples-glean`. Let's fix this up in this issue.

cc @jhugman

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-216)

**Comment by grigoryk** [comment]
In #10144 i fixed the build issue, but the sample now crashes on startup with:
```
05-12 16:08:36.601  8653  8653 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mozilla.samples.glean.debug/org.mozilla.samples.glean.MainActivity}: org.mozilla.experiments.nimbus.internal.NimbusErrorException$DatabaseNotReady: Initialization of the database is not yet complete
05-12 16:08:36.601  8653  8653 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
05-12 16:08:36.601  8653  8653 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
05-12 16:08:36.601  8653  8653 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
05-12 16:08:36.601  8653  8653 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
05-12 16:08:36.601  8653  8653 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
05-12 16:08:36.601  8653  8653 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
05-12 16:08:36.601  8653  8653 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
05-12 16:08:36.601  8653  8653 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
05-12 16:08:36.601  8653  8653 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
05-12 16:08:36.601  8653  8653 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-12 16:08:36.601  8653  8653 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
05-12 16:08:36.601  8653  8653 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
05-12 16:08:36.601  8653  8653 E AndroidRuntime: Caused by: org.mozilla.experiments.nimbus.internal.NimbusErrorException$DatabaseNotReady: Initialization of the database is not yet complete
05-12 16:08:36.601  8653  8653 E AndroidRuntime: 	at org.mozilla.experiments.nimbus.internal.NimbusError.intoException(nimbus.kt:956)
05-12 16:08:36.601  8653  8653 E AndroidRuntime: 	at org.mozilla.experiments.nimbus.internal.NimbusClient.getExperimentBranch(nimbus.kt:1557)
05-12 16:08:36.601  8653  8653 E AndroidRuntime: 	at org.mozilla.experiments.nimbus.Nimbus.getExperimentBranch(Nimbus.kt:317)
05-12 16:08:36.601  8653  8653 E AndroidRuntime: 	at org.mozilla.samples.glean.MainActivity.configureButton(MainActivity.kt:103)
05-12 16:08:36.601  8653  8653 E AndroidRuntime: 	at org.mozilla.samples.glean.MainActivity.setupNimbusExperiments(MainActivity.kt:78)
05-12 16:08:36.601  8653  8653 E AndroidRuntime: 	at org.mozilla.samples.glean.MainActivity.onCreate(MainActivity.kt:58)
05-12 16:08:36.601  8653  8653 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7802)
05-12 16:08:36.601  8653  8653 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7791)
05-12 16:08:36.601  8653  8653 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
05-12 16:08:36.601  8653  8653 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
05-12 16:08:36.601  8653  8653 E AndroidRuntime: 	... 11 more
```

**Comment by csadilek** [comment]
This was fixed as part of https://github.com/mozilla-mobile/fenix/issues/20269.
