### ISSUE TITLE
Subscribing to FxA push failed at login

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#10368]
Seeing this on Nightly right after logging in:
```
        AccountObserver  I  Subscribing to FxA push failed at login.
                         I  mozilla.appservices.push.CommunicationError: Error(Communication Error: "Unhandled client error 410 : \"{\\\"code\\\": 410, \\\"errno\\\": 103, \\\"error\\\": \\\"\\\", \\\"more_info\\\": \\\"http://auto
                            push.readthedocs.io/en/latest/http.html#error-codes\\\", \\\"message\\\": \\\"Request did not validate UAID not found\\\"}\"")
                         I      at mozilla.appservices.push.RustError.intoException(RustError.kt:13)
                         I      at mozilla.appservices.push.PushManager.subscribe(PushManager.kt:13)
                         I      at mozilla.components.feature.push.RustPushConnection.subscribe(Connection.kt:4)
                         I      at mozilla.components.feature.push.AutoPushFeature$subscribe$$inlined$ifInitialized$lambda$2.invokeSuspend(AutoPushFeature.kt:5)
                         I      at mozilla.components.feature.push.AutoPushFeature$subscribe$$inlined$ifInitialized$lambda$2.invoke(Unknown Source:10)
                         I      at mozilla.components.feature.push.ext.CoroutineScopeKt$launchAndTry$2.invokeSuspend(CoroutineScope.kt:5)
                         I      at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
                         I      at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
                         I      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                         I      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                         I      at java.lang.Thread.run(Thread.java:923)
                    App  W  Non-fatal error occurred in AutoPushFeature.
                         W  mozilla.appservices.push.CommunicationError: Error(Communication Error: "Unhandled client error 410 : \"{\\\"code\\\": 410, \\\"errno\\\": 103, \\\"error\\\": \\\"\\\", \\\"more_info\\\": \\\"http://auto
                            push.readthedocs.io/en/latest/http.html#error-codes\\\", \\\"message\\\": \\\"Request did not validate UAID not found\\\"}\"")
                         W      at mozilla.appservices.push.RustError.intoException(RustError.kt:13)
                         W      at mozilla.appservices.push.PushManager.subscribe(PushManager.kt:13)
                         W      at mozilla.components.feature.push.RustPushConnection.subscribe(Connection.kt:4)
                         W      at mozilla.components.feature.push.AutoPushFeature$subscribe$$inlined$ifInitialized$lambda$2.invokeSuspend(AutoPushFeature.kt:5)
                         W      at mozilla.components.feature.push.AutoPushFeature$subscribe$$inlined$ifInitialized$lambda$2.invoke(Unknown Source:10)
                         W      at mozilla.components.feature.push.ext.CoroutineScopeKt$launchAndTry$2.invokeSuspend(CoroutineScope.kt:5)
                         W      at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
                         W      at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
                         W      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                         W      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                         W      at java.lang.Thread.run(Thread.java:923)
```

**Comment by jonalmeida** [comment]
Same as https://github.com/mozilla-mobile/android-components/issues/10366 where we need changes from a-s/autopush to fix it:  mozilla-services/autopush#1445.
