### ISSUE TITLE
NPE while trying to submit to Sentry

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#10367]
Seeing this on Nightly:
```
    mozac/CrashReporter  I  Caught Exception report submitted to 2 services
            logins::ffi  E  Invalid login: Login already exists
             System.err  W  SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
                         W  SLF4J: Defaulting to no-operation (NOP) logger implementation
                         W  SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
        DefaultDispatch  W  type=1400 audit(0.0:371): avc: denied { read } for name="version" dev="proc" ino=4026531958 scontext=u:r:untrusted_app:s0:c18,c257,c512,c768 tcontext=u:object_r:proc_version:s0 tclass=file permissive=0 a
                            pp=org.mozilla.fenix
             System.err  W  MDC binding unsuccessful.
                         W  Reported exception:
                         W  java.lang.NullPointerException
                         W      at org.slf4j.MDC.<clinit>(MDC.java:1)
                         W      at org.slf4j.MDC.getCopyOfContextMap(MDC.java:1)
                         W      at io.sentry.connection.AsyncConnection.send(AsyncConnection.java:2)
                         W      at io.sentry.connection.BufferedConnection$2.send(BufferedConnection.java:3)
                         W      at io.sentry.SentryClient.sendEvent(SentryClient.java:19)
                         W      at mozilla.components.lib.crash.service.SentryService.report(SentryService.kt:39)
                         W      at mozilla.components.lib.crash.CrashReporter$submitCaughtException$1.invokeSuspend(CrashReporter.kt:4)
                         W      at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
                         W      at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
                         W      at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
                         W      at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-310)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795422

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
