### ISSUE TITLE
Intermittent mozilla.components.feature.intent.processing.TabIntentProcessorTest - open or select tab on ACTION_NDEF_DISCOVERED intent

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/android-components#10615]
### Firebase Test Run:
https://treeherder.mozilla.org/logviewer?job_id=345326842&repo=android-components
### Stacktrace:
```
  TEST: open or select tab on ACTION_NDEF_DISCOVERED intent
    [Robolectric] mozilla.components.feature.intent.processing.TabIntentProcessorTest.open or select tab on ACTION_NDEF_DISCOVERED intent: sdk=28; resources=binary
    I/MonitoringInstr: Instrumentation started!
    D [WebExtensionsMiddleware] No engine session for new active tab (be1e9d64-d65f-450f-8bdf-01970a23638d)
    D [CreateEngineSessionMiddleware] Request to create engine session for tab be1e9d64-d65f-450f-8bdf-01970a23638d
    D [CreateEngineSessionMiddleware] Created engine session for tab be1e9d64-d65f-450f-8bdf-01970a23638d
    D [WebExtensionsMiddleware] No engine session for new active tab (aab51691-0aec-4eb2-b5f9-703d0f67cd8e)
    D [WebExtensionsMiddleware] No engine session for new active tab (be1e9d64-d65f-450f-8bdf-01970a23638d)
  FAILURE

java.lang.AssertionError: expected:<TabSessionState(id=be1e9d64-d65f-450f-8bdf-01970a23638d, content=ContentState(url=https://mozilla.org, private=false, title=, progress=0, loading=false, searchTerms=, securityInfo=SecurityInfoState(secure=false, host=, issuer=), thumbnail=null, icon=null, download=null, share=null, hitResult=null, promptRequests=[], findResults=[], windowRequest=null, searchRequest=null, fullScreen=false, layoutInDisplayCutoutMode=0, canGoBack=false, canGoForward=false, webAppManifest=null, firstContentfulPaint=false, history=HistoryState(items=[], currentIndex=0), permissionHighlights=PermissionHighlightsState(isAutoPlayBlocking=false), permissionRequestsList=[], appPermissionRequestsList=[], pictureInPictureEnabled=false, loadRequest=null, refreshCanceled=false, recordingDevices=[], desktopMode=false, appIntent=null), trackingProtection=TrackingProtectionState(enabled=false, blockedTrackers=[], loadedTrackers=[], ignoredOnTrackingProtection=false), engineState=EngineState(engineSession=null, engineSessionState=null, initializing=false, engineObserver=null, crashed=false, timestamp=null, initialLoadFlags=mozilla.components.concept.engine.EngineSession$LoadUrlFlags@4), extensionState={}, mediaSessionState=null, contextId=null, source=ACTION_VIEW, parentId=null, lastAccess=0, lastMediaAccess=0, readerState=ReaderState(readerable=false, active=false, checkRequired=false, connectRequired=false, baseUrl=null, activeUrl=null), historyMetadata=null)> but was:<TabSessionState(id=be1e9d64-d65f-450f-8bdf-01970a23638d, content=ContentState(url=https://mozilla.org, private=false, title=, progress=0, loading=false, searchTerms=, securityInfo=SecurityInfoState(secure=false, host=, issuer=), thumbnail=null, icon=null, download=null, share=null, hitResult=null, promptRequests=[], findResults=[], windowRequest=null, searchRequest=null, fullScreen=false, layoutInDisplayCutoutMode=0, canGoBack=false, canGoForward=false, webAppManifest=null, firstContentfulPaint=false, history=HistoryState(items=[], currentIndex=0), permissionHighlights=PermissionHighlightsState(isAutoPlayBlocking=false), permissionRequestsList=[], appPermissionRequestsList=[], pictureInPictureEnabled=false, loadRequest=null, refreshCanceled=false, recordingDevices=[], desktopMode=false, appIntent=null), trackingProtection=TrackingProtectionState(enabled=false, blockedTrackers=[], loadedTrackers=[], ignoredOnTrackingProtection=false), engineState=EngineState(engineSession=null, engineSessionState=null, initializing=true, engineObserver=null, crashed=false, timestamp=null, initialLoadFlags=mozilla.components.concept.engine.EngineSession$LoadUrlFlags@4), extensionState={}, mediaSessionState=null, contextId=null, source=ACTION_VIEW, parentId=null, lastAccess=0, lastMediaAccess=0, readerState=ReaderState(readerable=false, active=false, checkRequired=false, connectRequired=false, baseUrl=null, activeUrl=null), historyMetadata=null)>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at mozilla.components.feature.intent.processing.TabIntentProcessorTest.open or select tab on ACTION_NDEF_DISCOVERED intent(TabIntentProcessorTest.kt:173)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:601)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:260)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:154)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy5.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:119)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
### Build: 
https://github.com/mozilla-mobile/android-components/commit/642cde5c0de45e608d759deb95db0ff5aea2b1ca

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17263)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794869

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
