### ISSUE TITLE
Intermittent UI test failure - com.google.api.client.googleapis.json.GoogleJsonResponseException: 503 Service Unavailable

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/android-components#10628]
This intermittent failure affected the 7 latest pushes to android-components. For the 5 pushes before, the tasks didn't run or were permanently busted (from https://github.com/mozilla-mobile/android-components/commit/03da5481d07abf8c7a71c29ffbfb46db20b3df5d). The other interesting change is the upgrade to Java 11 (#10335). Does the server erroneously claim a 503 if there are bad or too many requests? cc @pocmo 

### Firebase Test Run:
https://treeherder.mozilla.org/logviewer?job_id=345326832&repo=android-components&lineNumber=7672
### Stacktrace:
```
[task 2021-07-15T16:56:45.372Z]  Smart Flank cache hit: 0% (0 / 18)
[task 2021-07-15T16:56:45.373Z]   Shard times: 2160s
[task 2021-07-15T16:56:45.373Z] 
[task 2021-07-15T16:56:45.382Z]   Saved 1 shards to /builds/worker/artifacts/results/android_shards.json
[task 2021-07-15T16:56:45.651Z]   Uploading [android_shards.json] to https://console.developers.google.com/storage/browser/android-components_test_artifacts/2021-07-15_16-56-36.553260_jCOx/...
[task 2021-07-15T16:56:56.287Z]   Uploading [samples-browser-gecko-debug.apk] to https://console.developers.google.com/storage/browser/android-components_test_artifacts/2021-07-15_16-56-36.553260_jCOx/....
[task 2021-07-15T16:57:05.539Z]   Uploading [browser-engine-gecko-debug-androidTest.apk] to https://console.developers.google.com/storage/browser/android-components_test_artifacts/2021-07-15_16-56-36.553260_jCOx/...
[task 2021-07-15T16:57:25.601Z] com.google.api.client.googleapis.json.GoogleJsonResponseException: 503 Service Unavailable
[task 2021-07-15T16:57:25.601Z] POST https://testing.googleapis.com/v1/applicationDetailService/getApkDetails
[task 2021-07-15T16:57:25.601Z] {
[task 2021-07-15T16:57:25.601Z]   "code": 503,
[task 2021-07-15T16:57:25.602Z]   "errors": [
[task 2021-07-15T16:57:25.602Z]     {
[task 2021-07-15T16:57:25.602Z]       "domain": "global",
[task 2021-07-15T16:57:25.602Z]       "message": "The service is currently unavailable.",
[task 2021-07-15T16:57:25.602Z]       "reason": "backendError"
[task 2021-07-15T16:57:25.602Z]     }
[task 2021-07-15T16:57:25.602Z]   ],
[task 2021-07-15T16:57:25.602Z]   "message": "The service is currently unavailable.",
[task 2021-07-15T16:57:25.602Z]   "status": "UNAVAILABLE"
[task 2021-07-15T16:57:25.602Z] }
[task 2021-07-15T16:57:25.602Z] 	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
[task 2021-07-15T16:57:25.602Z] 	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:118)
[task 2021-07-15T16:57:25.602Z] 	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:37)
[task 2021-07-15T16:57:25.602Z] 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:428)
[task 2021-07-15T16:57:25.602Z] 	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1111)
[task 2021-07-15T16:57:25.602Z] 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:514)
[task 2021-07-15T16:57:25.602Z] 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:455)
[task 2021-07-15T16:57:25.602Z] 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565)
[task 2021-07-15T16:57:25.602Z] 	at ftl.client.google.AppDetailsKt.getAndroidAppDetails(AppDetails.kt:7)
[task 2021-07-15T16:57:25.602Z] 	at ftl.run.platform.RunAndroidTestsKt.reportPackageName(RunAndroidTests.kt:101)
[task 2021-07-15T16:57:25.602Z] 	at ftl.run.platform.RunAndroidTestsKt.access$reportPackageName(RunAndroidTests.kt:1)
[task 2021-07-15T16:57:25.602Z] 	at ftl.run.platform.RunAndroidTestsKt$runAndroidTests$2.invokeSuspend(RunAndroidTests.kt:54)
[task 2021-07-15T16:57:25.602Z] 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[task 2021-07-15T16:57:25.602Z] 	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
[task 2021-07-15T16:57:25.602Z] 	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
[task 2021-07-15T16:57:25.602Z] 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
[task 2021-07-15T16:57:25.602Z] 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
[task 2021-07-15T16:57:25.602Z] 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
[task 2021-07-15T16:57:25.602Z] 	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
[task 2021-07-15T16:57:25.602Z] 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
[task 2021-07-15T16:57:25.602Z] 	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
[task 2021-07-15T16:57:25.602Z] 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
[task 2021-07-15T16:57:25.602Z] 	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
[task 2021-07-15T16:57:25.602Z] 	at ftl.domain.RunTestAndroidKt.invoke(RunTestAndroid.kt:66)
[task 2021-07-15T16:57:25.602Z] 	at ftl.presentation.cli.firebase.test.android.AndroidRunCommand.run(AndroidRunCommand.kt:54)
[task 2021-07-15T16:57:25.602Z] 	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
[task 2021-07-15T16:57:25.602Z] 	at picocli.CommandLine.access$1300(CommandLine.java:145)
[task 2021-07-15T16:57:25.602Z] 	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
[task 2021-07-15T16:57:25.602Z] 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
[task 2021-07-15T16:57:25.602Z] 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
[task 2021-07-15T16:57:25.602Z] 	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
[task 2021-07-15T16:57:25.602Z] 	at picocli.CommandLine.execute(CommandLine.java:2078)
[task 2021-07-15T16:57:25.602Z] 	at ftl.Main$main$1.invoke(Main.kt:12)
[task 2021-07-15T16:57:25.602Z] 	at ftl.Main$main$1.invoke(Main.kt:10)
[task 2021-07-15T16:57:25.602Z] 	at ftl.run.exception.ExceptionHandlerKt.withGlobalExceptionHandling(ExceptionHandler.kt:28)
[task 2021-07-15T16:57:25.602Z] 	at ftl.run.exception.ExceptionHandlerKt.withGlobalExceptionHandling(ExceptionHandler.kt:17)
[task 2021-07-15T16:57:25.602Z] 	at ftl.Main.main(Main.kt:10)
```
### Build: 
https://github.com/mozilla-mobile/android-components/commit/642cde5c0de45e608d759deb95db0ff5aea2b1ca

**Comment by Archaeopteryx** [comment]
The failing tasks are not randomly distributed, e.g. `ui-components` and `ui-sitepermissions` are very often affected.

**Comment by pocmo** [comment]
#10667

**Comment by AaronMT** [comment]
Should be seeing more ✔️ now https://github.com/mozilla-mobile/android-components/issues/10667#issuecomment-891882439
