### ISSUE TITLE
Android Autofill: IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#10792]
```
java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
    at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:102)
    at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:8)
    at androidx.appcompat.app.AppCompatDialog.setContentView(AppCompatDialog.java:1)
    at androidx.appcompat.app.AlertDialog.onCreate(AlertDialog.java:6)
    at android.app.Dialog.dispatchOnCreate(Dialog.java:494)
    at android.app.Dialog.show(Dialog.java:342)
    at androidx.fragment.app.DialogFragment.onStart(DialogFragment.java:4)
    at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:8)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:9)
    at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:73)
    at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:5)
    at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:22)
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1340)
    at android.app.Activity.performStart(Activity.java:7200)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2920)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
    at android.app.ActivityThread.-wrap11
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
    at android.os.Handler.dispatchMessage(Handler.java:105)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6944)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/12315808

**Comment by pocmo** [comment]
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/11775017

**Comment by pocmo** [comment]
They are all about `AutofillUnlockActivity`:
Unable to start activity ComponentInfo{org.mozilla.fenix/org.mozilla.fenix.autofill.AutofillUnlockActivity}

12 events, 6 users.

**Comment by pocmo** [comment]
Looks like "unlock" and "confirm" do indeed use different themes:
https://github.com/mozilla-mobile/fenix/blob/main/app/src/nightly/AndroidManifest.xml#L7-L13

**Comment by pocmo** [comment]
This happened for a user in Beta too. I am not sure why though. It's not reproducible for me.
