### ISSUE TITLE
Flaky test on engine-gecko-nightly GeckoEngineSessionTest.kt:272

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#1083]
This test fun `saveState()` have been failing intermittently  GeckoEngineSessionTest.kt:272
```
:support-base:packageDebugAssets
:support-ktx:mergeDebugShaders
:support-ktx:compileDebugShaders
:support-ktx:generateDebugAssets
:support-ktx:packageDebugAssets
:support-utils:mergeDebugShaders
:support-utils:compileDebugShaders
:support-utils:generateDebugAssets
:support-utils:packageDebugAssets
:browser-engine-gecko-nightly:mergeDebugAssets
:browser-engine-gecko-nightly:generateDebugUnitTestConfig
:browser-engine-gecko-nightly:mockableAndroidJar
:browser-engine-gecko-nightly:processDebugUnitTestJavaRes
:browser-engine-gecko-nightly:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug
:browser-engine-gecko-nightly:testDebugUnitTest

mozilla.components.browser.engine.gecko.GeckoEngineSessionTest > saveState FAILED
    java.lang.UnsatisfiedLinkError at GeckoEngineSessionTest.kt:272
42 tests completed, 1 failed
:browser-engine-gecko-nightly:testDebugUnitTest FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':browser-engine-gecko-nightly:testDebugUnitTest'.
> There were failing tests. See the report at: file:///build/android-components/components/browser/engine-gecko-nightly/build/reports/tests/testDebugUnitTest/index.html
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 5m 47s
265 actionable tasks: 261 executed, 4 up-to-date
[taskcluster 2018-10-17 14:29:09.572Z] === Task Finished ===
[taskcluster 2018-10-17 14:29:09.572Z] Unsuccessful task run with exit code: 1 completed in 559.804 seconds
```

**Comment by pocmo** [comment]
Locally or on taskcluster? Or both? :)

**Comment by Amejia481** [comment]
It's only happening on taskcluster.
I've tried to simulated it on my machine without luck

**Comment by Amejia481** [comment]
I happened to me twice with this PR https://github.com/mozilla-mobile/android-components/pull/1074/
I just updated the changelog and the test failed(🔴 ) and I re-triggered the build and now it passed(🍏 )

**Comment by Amejia481** [comment]
The same test failing in this PR https://github.com/mozilla-mobile/android-components/pull/1068

```
mozilla.components.browser.engine.gecko.GeckoEngineSessionTest > saveState FAILED
    java.lang.UnsatisfiedLinkError at GeckoEngineSessionTest.kt:273
45 tests completed, 1 failed
:browser-engine-gecko-nightly:testReleaseUnitTest FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':browser-engine-gecko-nightly:testReleaseUnitTest'.
> There were failing tests. See the report at: file:///build/android-components/components/browser/engine-gecko-nightly/build/reports/tests/testReleaseUnitTest/index.html
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 6m 21s
300 actionable tasks: 295 executed, 5 up-to-date
[taskcluster 2018-10-17 22:30:17.127Z] === Task Finished ===
[taskcluster 2018-10-17 22:30:17.127Z] Unsuccessful task run with exit code: 1 completed in 393.038 seconds

```

**Comment by pocmo** [comment]
It's happening more often. I'll move it into the next sprint - if no one picks it up earlier. Maybe we are able to reproduce it locally inside the Docker image. However the `UnsatisfiedLinkError` is very weird. This test doesn't seem to need to load anything.

**Comment by Amejia481** [comment]
👍

**Comment by pocmo** [comment]
It's surprising that this is only failing with GeckoView Nightly.

**Comment by Amejia481** [comment]
As far as I know it's only happening in TC, I wasn't able to replicate locally.

**Comment by pocmo** [comment]
I tried inside the Docker image and wasn't successful either.

**Comment by Amejia481** [comment]
😢

**Comment by pocmo** [comment]
I was wondering whether this could be a data visibility issue and we are accidentally calling saveState() on an actual GeckoSession sometimes. However I couldn't verify that.

**Comment by pocmo** [comment]
Maybe we should temporarily disable the test while we figure out what's going on.

**Comment by Amejia481** [comment]
Yes, I believe it will be better!

**Comment by Amejia481** [comment]
We could delete the test, until we figure out, this way we don't have dead code!

**Comment by pocmo** [comment]
Now after merge day I'm curious whether we will see this in Beta too.

**Comment by Amejia481** [comment]
@pocmo  our favorite friend is here now in beta flavor :stuck_out_tongue_winking_eye:
https://github.com/mozilla-mobile/android-components/pull/1162

```
> Task :support-utils:compileDebugShaders
> Task :support-utils:generateDebugAssets
> Task :support-utils:packageDebugAssets
> Task :browser-engine-gecko-beta:mergeDebugAssets
> Task :browser-engine-gecko-beta:generateDebugUnitTestConfig
> Task :browser-engine-gecko-beta:mockableAndroidJar
> Task :browser-engine-gecko-beta:processDebugUnitTestJavaRes
> Task :browser-engine-gecko-beta:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug
> Task :browser-engine-gecko-beta:testDebugUnitTest
mozilla.components.browser.engine.gecko.GeckoEngineSessionTest > loadUrl FAILED
    java.lang.UnsatisfiedLinkError at GeckoEngineSessionTest.kt:162
46 tests completed, 1 failed
> Task :browser-engine-gecko-beta:testDebugUnitTest FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':browser-engine-gecko-beta:testDebugUnitTest'.
> There were failing tests. See the report at: file:///build/android-components/components/browser/engine-gecko-beta/build/reports/tests/testDebugUnitTest/index.html
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 5m 43s
267 actionable tasks: 267 executed
[taskcluster 2018-10-24 17:41:24.348Z] === Task Finished ===
[taskcluster 2018-10-24 17:41:24.348Z] Unsuccessful task run with exit code: 1 completed in 349.182 seconds

```

**Comment by csadilek** [comment]
I've activated debug logging and got more details:

```
18:28:35.065 [DEBUG] [TestEventLogger] mozilla.components.browser.engine.gecko.GeckoEngineSessionTest > saveState FAILED
18:28:35.065 [DEBUG] [TestEventLogger]     java.lang.UnsatisfiedLinkError: org.mozilla.gecko.EventDispatcher.disposeNative()V
18:28:35.065 [DEBUG] [TestEventLogger]         at org.mozilla.gecko.EventDispatcher.disposeNative(Native Method)
18:28:35.065 [DEBUG] [TestEventLogger]         at org.mozilla.gecko.EventDispatcher$1.run(EventDispatcher.java:104)
18:28:35.065 [DEBUG] [TestEventLogger]         at android.os.Handler.handleCallback(Handler.java:790)
18:28:35.065 [DEBUG] [TestEventLogger]         at android.os.Handler.dispatchMessage(Handler.java:99)
18:28:35.065 [DEBUG] [TestEventLogger]         at org.robolectric.shadows.ShadowMessageQueue.dispatchMessage(ShadowMessageQueue.java:141)
18:28:35.065 [DEBUG] [TestEventLogger]         at org.robolectric.shadows.ShadowMessageQueue.access$100(ShadowMessageQueue.java:32)
18:28:35.065 [DEBUG] [TestEventLogger]         at org.robolectric.shadows.ShadowMessageQueue$1.run(ShadowMessageQueue.java:120)
18:28:35.065 [DEBUG] [TestEventLogger]         at org.robolectric.util.Scheduler$ScheduledRunnable.run(Scheduler.java:362)
18:28:35.065 [DEBUG] [TestEventLogger]         at org.robolectric.util.Scheduler.runOneTask(Scheduler.java:261)
18:28:35.065 [DEBUG] [TestEventLogger]         at org.robolectric.util.Scheduler.advanceTo(Scheduler.java:242)
18:28:35.065 [DEBUG] [TestEventLogger]         at org.robolectric.util.Scheduler.advanceBy(Scheduler.java:225)
18:28:35.065 [DEBUG] [TestEventLogger]         at org.robolectric.util.Scheduler.advanceBy(Scheduler.java:215)
18:28:35.065 [DEBUG] [TestEventLogger]         at org.robolectric.util.Scheduler.runOrQueueRunnable(Scheduler.java:334)
18:28:35.065 [DEBUG] [TestEventLogger]         at org.robolectric.util.Scheduler.postDelayed(Scheduler.java:156)
18:28:35.065 [DEBUG] [TestEventLogger]         at org.robolectric.util.Scheduler.postDelayed(Scheduler.java:145)
18:28:35.065 [DEBUG] [TestEventLogger]         at org.robolectric.shadows.ShadowMessageQueue.enqueueMessage(ShadowMessageQueue.java:127)
18:28:35.065 [DEBUG] [TestEventLogger]         at android.os.MessageQueue.enqueueMessage(MessageQueue.java)
18:28:35.065 [DEBUG] [TestEventLogger]         at android.os.Handler.enqueueMessage(Handler.java:662)
18:28:35.065 [DEBUG] [TestEventLogger]         at android.os.Handler.sendMessageAtTime(Handler.java:631)
18:28:35.065 [DEBUG] [TestEventLogger]         at android.os.Handler.sendMessageDelayed(Handler.java:601)
18:28:35.065 [DEBUG] [TestEventLogger]         at android.os.Handler.post(Handler.java:357)
18:28:35.065 [DEBUG] [TestEventLogger]         at mozilla.components.browser.engine.gecko.GeckoEngineSession$saveState$1.doResume(GeckoEngineSession.kt:132)
18:28:35.065 [DEBUG] [TestEventLogger]         at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
18:28:35.065 [DEBUG] [TestEventLogger]         at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:168)
18:28:35.065 [DEBUG] [TestEventLogger]         at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:13)
18:28:35.065 [DEBUG] [TestEventLogger]         at kotlinx.coroutines.experimental.EventLoopBase.processNextEvent(EventLoop.kt:166)
18:28:35.065 [DEBUG] [TestEventLogger]         at kotlinx.coroutines.experimental.BlockingCoroutine.joinBlocking(Builders.kt:69)
18:28:35.065 [DEBUG] [TestEventLogger]         at kotlinx.coroutines.experimental.BuildersKt__BuildersKt.runBlocking(Builders.kt:45)
18:28:35.065 [DEBUG] [TestEventLogger]         at kotlinx.coroutines.experimental.BuildersKt.runBlocking(Unknown Source)
18:28:35.065 [DEBUG] [TestEventLogger]         at kotlinx.coroutines.experimental.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:35)
18:28:35.065 [DEBUG] [TestEventLogger]         at kotlinx.coroutines.experimental.BuildersKt.runBlocking$default(Unknown Source)
18:28:35.065 [DEBUG] [TestEventLogger]         at mozilla.components.browser.engine.gecko.GeckoEngineSession.saveState(GeckoEngineSession.kt:129)
18:28:35.065 [DEBUG] [TestEventLogger]         at mozilla.components.browser.engine.gecko.GeckoEngineSessionTest.saveState(GeckoEngineSessionTest.kt:273)
18:28:35.066 [DEBUG] [TestEventLogger]         at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
18:28:35.066 [DEBUG] [TestEventLogger]         at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
18:28:35.066 [DEBUG] [TestEventLogger]         at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
18:28:35.066 [DEBUG] [TestEventLogger]         at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
18:28:35.066 [DEBUG] [TestEventLogger]         at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:570)
18:28:35.066 [DEBUG] [TestEventLogger]         at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:253)
18:28:35.066 [DEBUG] [TestEventLogger]         at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
18:28:35.066 [DEBUG] [TestEventLogger]         at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
18:28:35.066 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
18:28:35.066 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
18:28:35.066 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
18:28:35.066 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
18:28:35.066 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
18:28:35.066 [DEBUG] [TestEventLogger]         at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
18:28:35.066 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
18:28:35.066 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:106)
18:28:35.066 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
18:28:35.066 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
18:28:35.066 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:66)
18:28:35.066 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
18:28:35.066 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
18:28:35.066 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
18:28:35.066 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
18:28:35.066 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
18:28:35.066 [DEBUG] [TestEventLogger]         at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
18:28:35.066 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:117)
18:28:35.066 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
18:28:35.066 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
18:28:35.066 [DEBUG] [TestEventLogger]         at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
18:28:35.066 [DEBUG] [TestEventLogger]         at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
18:28:35.066 [DEBUG] [TestEventLogger]         at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
18:28:35.066 [DEBUG] [TestEventLogger]         at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
18:28:35.066 [DEBUG] [TestEventLogger]         at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
18:28:35.066 [DEBUG] [TestEventLogger]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
18:28:35.066 [DEBUG] [TestEventLogger]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
18:28:35.066 [DEBUG] [TestEventLogger]         at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
18:28:35.066 [DEBUG] [TestEventLogger]         at java.lang.Thread.run(Thread.java:748)
```

**Comment by csadilek** [comment]
The difference between the working and non-working case seems to be that we have a handler attached. We attach one in saveState. In Beta, and Nightly, when the EventDispatcher is disposed it checks for that. I will prepare a PR to test.

In general, we probably shouldn't mess around with ThreadUtils.sGeckoHandler in `saveState` but that's for another time.

**Comment by Amejia481** [comment]
@csadilek 💪 💪
