### ISSUE TITLE
Crash in [@ java.lang.OutOfMemoryError: at java.io.ByteArrayOutputStream.<init>(ByteArrayOutputStream.java)]

### ISSUE THREAD

**Issue by fluffyemily** [mozilla-mobile/android-components#10842]
Crash report: https://crash-stats.mozilla.org/report/index/08b78adb-a36a-4f5e-8faf-2bd6d0210813

Java stack trace:
```
java.lang.OutOfMemoryError
	at java.io.ByteArrayOutputStream.<init>(ByteArrayOutputStream.java:63)
	at androidx.core.app.AppOpsManagerCompat.readBytes(AppOpsManagerCompat.java:1)
	at mozilla.components.browser.thumbnails.utils.ThumbnailDiskCache.getThumbnailData$browser_thumbnails_release(ThumbnailDiskCache.kt:3)
	at mozilla.components.browser.thumbnails.storage.ThumbnailStorage.access$loadThumbnailInternal(ThumbnailStorage.kt:6)
	at mozilla.components.browser.thumbnails.storage.ThumbnailStorage$loadThumbnail$1.invokeSuspend(ThumbnailStorage.kt:2)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17632)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793231

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
