### ISSUE TITLE
Intermittent test failure - mozilla.components.service.glean.GleanFromJavaTest - testInitGleanWithConfiguration - thread '<unnamed>' panicked at 'No database found', glean-core/src/lib.rs:563:35

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/android-components#10972]
### Firebase Test Run:
https://treeherder.mozilla.org/logviewer?job_id=351243640&repo=android-components
### Stacktrace:
```
SUITE: mozilla.components.service.glean.GleanFromJavaTest
  TEST: testInitGleanWithConfiguration
    Downloading: org/robolectric/android-all/9-robolectric-4913185-2/android-all-9-robolectric-4913185-2.pom from repository sonatype at https://oss.sonatype.org/content/groups/public/
    Transferring 2K from sonatype
    Downloading: org/sonatype/oss/oss-parent/9/oss-parent-9.pom from repository sonatype at https://oss.sonatype.org/content/groups/public/
    Transferring 6K from sonatype
    Downloading: org/robolectric/android-all/9-robolectric-4913185-2/android-all-9-robolectric-4913185-2.jar from repository sonatype at https://oss.sonatype.org/content/groups/public/
    Transferring 118099K from sonatype
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.robolectric.util.ReflectionHelpers (file:/builds/worker/fetches/android-gradle-dependencies/central/org/robolectric/shadowapi/4.1/shadowapi-4.1.jar) to field java.lang.reflect.Field.modifiers
WARNING: Please consider reporting this to the maintainers of org.robolectric.util.ReflectionHelpers
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
    [Robolectric] mozilla.components.service.glean.GleanFromJavaTest.testInitGleanWithConfiguration: sdk=28; resources=binary
    Downloading: org/robolectric/android-all/8.1.0-robolectric-4611349/android-all-8.1.0-robolectric-4611349.pom from repository sonatype at https://oss.sonatype.org/content/groups/public/
    Transferring 2K from sonatype
    Downloading: org/robolectric/android-all/8.1.0-robolectric-4611349/android-all-8.1.0-robolectric-4611349.jar from repository sonatype at https://oss.sonatype.org/content/groups/public/
    Transferring 95237K from sonatype
    Called loadFromPath(/system/framework/framework-res.apk, true); mode=binary sdk=28
    I/AssetManager: no overlays.list file found
    I/PackageBackwardCompatibility: Could not find android.content.pm.OrgApacheHttpLegacyUpdater, ignoring
    I/PackageBackwardCompatibility: Could not find android.content.pm.AndroidTestBaseUpdater, ignoring
    I/MonitoringInstr: Instrumentation started!
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 1
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 1
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 1
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 0
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 0
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 0
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 0
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 0
  SUCCESS

  TEST: testGleanExperimentsAPIWithDefaults
    [Robolectric] mozilla.components.service.glean.GleanFromJavaTest.testGleanExperimentsAPIWithDefaults: sdk=28; resources=binary
    I/MonitoringInstr: Instrumentation started!
    I/glean/Dispatchers: Task queued for execution and delayed until flushed
  SUCCESS

  TEST: testInitGleanWithDefaults
    [Robolectric] mozilla.components.service.glean.GleanFromJavaTest.testInitGleanWithDefaults: sdk=28; resources=binary
    I/MonitoringInstr: Instrumentation started!
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 1
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 1
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 1
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 0
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 0
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 0
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 0
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 0
    E/glean/Glean: Glean should not be initialized multiple times
  SUCCESS

  TEST: testGleanExperimentsAPIWithOptional
    I/glean/Dispatchers: Task queued for execution and delayed until flushed
    I/glean/Dispatchers: Task queued for execution and delayed until flushed
    [Robolectric] mozilla.components.service.glean.GleanFromJavaTest.testGleanExperimentsAPIWithOptional: sdk=28; resources=binary
    I/glean/Dispatchers: Task queued for execution and delayed until flushed
    I/glean/Dispatchers: Task queued for execution and delayed until flushed
    E/glean/Glean: Could not get own package info, unable to report build id and display version
    I/MonitoringInstr: Instrumentation started!
    I/glean/Dispatchers: Task queued for execution and delayed until flushed
  SUCCESS


SUITE: mozilla.components.service.glean.GleanTest
  TEST: Glean correctly initializes and records a metric
    [Robolectric] mozilla.components.service.glean.GleanTest.Glean correctly initializes and records a metric: sdk=28; resources=binary
    I/MonitoringInstr: Instrumentation started!
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 1
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 1
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 1
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 0
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 0
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 0
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 0
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 0
    I/glean/MetricsPingSched: The application just updated. Send metrics ping now.
    I/glean/MetricsPingSched: Collecting the 'metrics' ping, now = 1631371189444, startup = true, reason = upgrade
thread '<unnamed>' panicked at 'No database found', glean-core/src/lib.rs:563:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
  SKIPPED
```
### Build: 
https://github.com/mozilla-mobile/android-components/commit/d5208406164d2fba92f8787a3d2a1ba7d78dc554

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17853)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794922

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
