### ISSUE TITLE
Crash in [@ java.lang.IllegalStateException: at org.mozilla.geckoview.GeckoSession.acquireDisplay(GeckoSession.java:2355)]

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/android-components#11021]
Custom tab UI tests are frequently hitting this crash in Focus Android (branch: main) and Reference-Browser on Firebase Test Lab

Custom Tabs UI Test: https://github.com/mozilla-mobile/focus-android/blob/main/app/src/androidTest/java/org/mozilla/focus/activity/CustomTabTest.kt#L87

Device: Pixel 2 (API 28)

https://console.firebase.google.com/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/9129736503036960145/executions/bs.6fdab438f6e6d38d

Similarly in reference-browser, same crash with custom tabs.

https://console.firebase.google.com/project/moz-reference-browser-230023/testlab/histories/bh.b4e77beaed81bc1c/matrices/8616762649932617835/executions/bs.de8e9c7b769cd159

If you would like access to this Firebase project let me know.

```Log
java.lang.IllegalStateException: SET SESSION: Current activity: CustomTabActivity hashcode 122034635 Other activity: MainActivity hashcode 124848962
       FATAL EXCEPTION: main
Process: org.mozilla.focus.debug, PID: 8000
java.lang.IllegalStateException: SET SESSION: Current activity: CustomTabActivity hashcode 122034635 Other activity: MainActivity hashcode 124848962
	at mozilla.components.browser.engine.gecko.GeckoEngineView.render(GeckoEngineView.kt:129)
	at mozilla.components.feature.session.engine.EngineViewPresenter.renderTab(EngineViewPresenter.kt:85)
	at mozilla.components.feature.session.engine.EngineViewPresenter.onTabToRender(EngineViewPresenter.kt:61)
	at mozilla.components.feature.session.engine.EngineViewPresenter.access$onTabToRender(EngineViewPresenter.kt:23)
	at mozilla.components.feature.session.engine.EngineViewPresenter$start$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:135)
	at mozilla.components.support.ktx.kotlinx.coroutines.flow.FlowKt$ifAnyChanged$$inlined$filter$1$2.emit(Collect.kt:143)
	at mozilla.components.feature.session.engine.EngineViewPresenter$start$1$invokeSuspend$$inlined$map$1$2.emit(Collect.kt:137)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:62)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl(Channels.kt:1)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:148)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:525)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:484)
	at androidx.test.espresso.base.UiControllerImpl.injectMotionEvent(UiControllerImpl.java:236)
	at androidx.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:162)
	at androidx.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:139)
	at androidx.test.espresso.action.Tap.sendSingleTap(Tap.java:170)
	at androidx.test.espresso.action.Tap.access$100(Tap.java:31)
	at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:47)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:137)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:366)
	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:255)
	at androidx.test.espresso.ViewInteraction.access$100(ViewInteraction.java:65)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:158)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:155)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.IllegalStateException: Display already acquired
	at org.mozilla.geckoview.GeckoSession.acquireDisplay(GeckoSession.java:2355)
	at org.mozilla.geckoview.GeckoView.setSession(GeckoView.java:460)
	at mozilla.components.browser.engine.gecko.GeckoEngineView.render(GeckoEngineView.kt:116)
```

**Comment by jonalmeida** [comment]
This is consistently reproducible with the steps from https://github.com/mozilla-mobile/focus-android/issues/5533.

**Comment by AaronMT** [comment]
Who might know what's needed for Focus/R-B?

**Comment by AndiAJ** [comment]
> This is consistently reproducible with the steps from [mozilla-mobile/focus-android#5533](https://github.com/mozilla-mobile/focus-android/issues/5533) in Focus and Reference Browser, but not Fenix.
> 
> Something must have changed then where a patch was put for Fenix but not the other projects.

Hi @jonalmeida , I think it crashed on Fenix as well [#21030](https://github.com/mozilla-mobile/fenix/issues/21030#issuecomment-942179627)

**Comment by jonalmeida** [comment]
@pocmo @csadilek do you know what we can do here? I'm not sure where to proceed next.

**Comment by csadilek** [comment]
Focus fix for this crash was: https://github.com/mozilla-mobile/focus-android/pull/6304

See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1741899
