### ISSUE TITLE
[Crash] NPE parsing search terms

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#11051]
Found these crashes in Fenix. We should uplift the fix too:
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/12639135/
https://sentry.prod.mozaws.net/operations/firefox-beta/issues/13012936/

```
java.lang.NullPointerException: key
    at android.net.Uri.getQueryParameter(Uri.java:1712)
    at mozilla.components.feature.search.ext.SearchEngineKt.parseSearchTerms(SearchEngine.kt:9)
    at mozilla.components.feature.search.ext.SearchEngineKt.parseSearchTerms(SearchEngine.kt:4)
    at org.mozilla.fenix.historymetadata.HistoryMetadataMiddleware.createHistoryMetadata(HistoryMetadataMiddleware.kt:24)
    at org.mozilla.fenix.historymetadata.HistoryMetadataMiddleware.invoke(HistoryMetadataMiddleware.kt:51)
    at mozilla.components.lib.state.internal.ReducerChainBuilder$build$1$1.invoke(ReducerChainBuilder.kt:3)
```

**Comment by csadilek** [comment]
Low number of users and cause is that we can find the search term parameter via our placeholder. Interestingly, it shouldn't be possible to even add a search engine without the placeholder so not clear how these users ended up without one, maybe leftovers. We can still be tolerant to it and simple not detect search terms, and don't crash.
