### ISSUE TITLE
Intermittent test failure: RegionMiddlewareTest - "Dispatches cached home region and update later"

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#11238]
```
[task 2021-11-09T10:45:46.577Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
[task 2021-11-09T10:45:46.579Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
[task 2021-11-09T10:45:46.579Z] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[task 2021-11-09T10:45:46.579Z] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[task 2021-11-09T10:45:46.579Z] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[task 2021-11-09T10:45:46.579Z] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[task 2021-11-09T10:45:46.579Z] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[task 2021-11-09T10:45:46.579Z] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[task 2021-11-09T10:45:46.579Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
[task 2021-11-09T10:45:46.579Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
[task 2021-11-09T10:45:46.579Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
[task 2021-11-09T10:45:46.579Z] 	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
[task 2021-11-09T10:45:46.579Z] 	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
[task 2021-11-09T10:45:46.579Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2021-11-09T10:45:46.579Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2021-11-09T10:45:46.579Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2021-11-09T10:45:46.579Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[task 2021-11-09T10:45:46.579Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
[task 2021-11-09T10:45:46.579Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[task 2021-11-09T10:45:46.579Z] 	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
[task 2021-11-09T10:45:46.579Z] 	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
[task 2021-11-09T10:45:46.579Z] 	at com.sun.proxy.$Proxy5.processTestClass(Unknown Source)
[task 2021-11-09T10:45:46.579Z] 	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:121)
[task 2021-11-09T10:45:46.583Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2021-11-09T10:45:46.583Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2021-11-09T10:45:46.583Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2021-11-09T10:45:46.583Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[task 2021-11-09T10:45:46.584Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
[task 2021-11-09T10:45:46.586Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[task 2021-11-09T10:45:46.586Z] 	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
[task 2021-11-09T10:45:46.586Z] 	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
[task 2021-11-09T10:45:46.586Z] 	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
[task 2021-11-09T10:45:46.586Z] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
[task 2021-11-09T10:45:46.587Z] 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
[task 2021-11-09T10:45:46.587Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[task 2021-11-09T10:45:46.587Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[task 2021-11-09T10:45:46.587Z] 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
[task 2021-11-09T10:45:46.587Z] 	at java.base/java.lang.Thread.run(Thread.java:829)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18590)

**Comment by pocmo** [comment]
Happened in https://github.com/mozilla-mobile/android-components/pull/11237

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795450

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
