### ISSUE TITLE
InvalidRecord: InvalidLogin::DuplicateLogin

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#11251]
https://sentry.prod.mozaws.net/operations/firefox-beta/issues/14655345/?referrer=github_plugin

```
mozilla.appservices.logins.InvalidRecord: InvalidLogin::DuplicateLogin
    at mozilla.appservices.logins.LoginsStorageException$ErrorHandler.read(logins.kt:7)
    at mozilla.appservices.logins.LoginsStorageException$ErrorHandler$lift$1.invoke(logins.kt:2)
    at mozilla.appservices.logins.LoginsStorageException$ErrorHandler$lift$1.invoke(logins.kt:1)
    at mozilla.appservices.logins.LoginsKt.liftFromRustBuffer(logins.kt:2)
    at mozilla.appservices.logins.LoginsStorageException$ErrorHandler.lift(logins.kt:2)
    at mozilla.appservices.logins.LoginsStorageException$ErrorHandler.lift(logins.kt:1)
    at mozilla.appservices.logins.LoginStore.addOrUpdate(logins.kt:17)
    at mozilla.appservices.logins.DatabaseLoginsStorage.addOrUpdate(DatabaseLoginsStorage.kt:3)
    at mozilla.components.service.sync.logins.SyncableLoginsStorage$addOrUpdate$2.invokeSuspend(SyncableLoginsStorage.kt:6)
    at mozilla.components.service.sync.logins.SyncableLoginsStorage$addOrUpdate$2.invoke(SyncableLoginsStorage.kt:2)
    at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:1)
    at kotlinx.coroutines.BuildersKt.withContext
    at mozilla.components.service.sync.logins.SyncableLoginsStorage.addOrUpdate(SyncableLoginsStorage.kt:1)
    at mozilla.components.service.sync.logins.GeckoLoginStorageDelegate$onLoginSave$1.invokeSuspend(GeckoLoginStorageDelegate.kt:6
```

**Comment by pocmo** [comment]
In Fenix 95.0.0 Beta 1 and 2.

**Comment by bendk** [comment]
Just opened an a-s issue for the root problem here.

One thing I'm wondering about is if we could handle this on the a-c side.  `GeckoLoginStorageDelegate` doesn't use `SyncableLoginsStorage`, it uses the abstract interface from `mozilla.components.concept.storage`.  When I was implementing the new logins code, I noticed that those interfaces don't list any exceptions so I didn't list them there.  Was there a decision that the abstract interfaces shouldn't list exceptions and if so is there any way for `GeckoLoginStorageDelegate` still catch errors?

**Comment by pocmo** [comment]
> Was there a decision that the abstract interfaces shouldn't list exceptions

To my knowledge there was no such decision - and I think it would be absolutely reasonable to add some to `concept-storage` and translate between them, if we think that's something we need.

CC @grigoryk
