### ISSUE TITLE
Intermittent feature-intent test failure - mozilla.components.feature.intent.processing.TabIntentProcessorTest - open or select tab on ACTION_VIEW intent

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/android-components#11318]
### Firebase Test Run:
[Provide a Firebase test run report link here showcasing the problem](https://treeherder.mozilla.org/logviewer?job_id=358999384&repo=android-components)
### Stacktrace:
```
  TEST: open or select tab on ACTION_VIEW intent
    [Robolectric] mozilla.components.feature.intent.processing.TabIntentProcessorTest.open or select tab on ACTION_VIEW intent: sdk=28; resources=binary
    I/MonitoringInstr: Instrumentation started!
    D [WebExtensionsMiddleware] No engine session for new active tab (3cbaa207-5c31-4418-8eb0-2996d93e9e5c)
    D [CreateEngineSessionMiddleware] Request to create engine session for tab 3cbaa207-5c31-4418-8eb0-2996d93e9e5c
    D [CreateEngineSessionMiddleware] Created engine session for tab 3cbaa207-5c31-4418-8eb0-2996d93e9e5c
    D [WebExtensionsMiddleware] No engine session for new active tab (e9bd97ec-5857-4d38-8ee4-5ab86948dbb0)
    D [WebExtensionsMiddleware] No engine session for new active tab (3cbaa207-5c31-4418-8eb0-2996d93e9e5c)
    D [WebExtensionsMiddleware] No engine session for new active tab (3cbaa207-5c31-4418-8eb0-2996d93e9e5c)
  FAILURE

java.lang.AssertionError: expected:<TabSessionState(id=3cbaa207-5c31-4418-8eb0-2996d93e9e5c, content=ContentState(url=http://mozilla.org, private=false, title=, progress=0, loading=false, searchTerms=, securityInfo=SecurityInfoState(secure=false, host=, issuer=), thumbnail=null, icon=null, download=null, share=null, hitResult=null, promptRequests=[], findResults=[], windowRequest=null, searchRequest=null, fullScreen=false, layoutInDisplayCutoutMode=0, canGoBack=false, canGoForward=false, webAppManifest=null, firstContentfulPaint=false, history=HistoryState(items=[], currentIndex=0), permissionHighlights=PermissionHighlightsState(notificationChanged=false, cameraChanged=false, locationChanged=false, microphoneChanged=false, persistentStorageChanged=false, mediaKeySystemAccessChanged=false, autoPlayAudibleChanged=false, autoPlayInaudibleChanged=false, autoPlayAudibleBlocking=false, autoPlayInaudibleBlocking=false), permissionRequestsList=[], appPermissionRequestsList=[], pictureInPictureEnabled=false, loadRequest=null, refreshCanceled=false, recordingDevices=[], desktopMode=false, appIntent=null, showToolbarAsExpanded=false, previewImageUrl=null), trackingProtection=TrackingProtectionState(enabled=false, blockedTrackers=[], loadedTrackers=[], ignoredOnTrackingProtection=false), engineState=EngineState(engineSession=null, engineSessionState=null, initializing=false, engineObserver=null, crashed=false, timestamp=null, initialLoadFlags=mozilla.components.concept.engine.EngineSession$LoadUrlFlags@4), extensionState={}, mediaSessionState=null, contextId=null, source=ActionView(caller=null), restored=false, parentId=null, lastAccess=0, createdAt=1637694450274, lastMediaAccessState=LastMediaAccessState(lastMediaUrl=, lastMediaAccess=0, mediaSessionActive=false), readerState=ReaderState(readerable=false, active=false, checkRequired=false, connectRequired=false, baseUrl=null, activeUrl=null), historyMetadata=null)> but was:<TabSessionState(id=3cbaa207-5c31-4418-8eb0-2996d93e9e5c, content=ContentState(url=http://mozilla.org, private=false, title=, progress=0, loading=false, searchTerms=, securityInfo=SecurityInfoState(secure=false, host=, issuer=), thumbnail=null, icon=null, download=null, share=null, hitResult=null, promptRequests=[], findResults=[], windowRequest=null, searchRequest=null, fullScreen=false, layoutInDisplayCutoutMode=0, canGoBack=false, canGoForward=false, webAppManifest=null, firstContentfulPaint=false, history=HistoryState(items=[], currentIndex=0), permissionHighlights=PermissionHighlightsState(notificationChanged=false, cameraChanged=false, locationChanged=false, microphoneChanged=false, persistentStorageChanged=false, mediaKeySystemAccessChanged=false, autoPlayAudibleChanged=false, autoPlayInaudibleChanged=false, autoPlayAudibleBlocking=false, autoPlayInaudibleBlocking=false), permissionRequestsList=[], appPermissionRequestsList=[], pictureInPictureEnabled=false, loadRequest=null, refreshCanceled=false, recordingDevices=[], desktopMode=false, appIntent=null, showToolbarAsExpanded=false, previewImageUrl=null), trackingProtection=TrackingProtectionState(enabled=false, blockedTrackers=[], loadedTrackers=[], ignoredOnTrackingProtection=false), engineState=EngineState(engineSession=null, engineSessionState=null, initializing=true, engineObserver=null, crashed=false, timestamp=null, initialLoadFlags=mozilla.components.concept.engine.EngineSession$LoadUrlFlags@4), extensionState={}, mediaSessionState=null, contextId=null, source=ActionView(caller=null), restored=false, parentId=null, lastAccess=0, createdAt=1637694450274, lastMediaAccessState=LastMediaAccessState(lastMediaUrl=, lastMediaAccess=0, mediaSessionActive=false), readerState=ReaderState(readerable=false, active=false, checkRequired=false, connectRequired=false, baseUrl=null, activeUrl=null), historyMetadata=null)>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at mozilla.components.feature.intent.processing.TabIntentProcessorTest.open or select tab on ACTION_VIEW intent(TabIntentProcessorTest.kt:127)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:601)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:260)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:154)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy5.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:121)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
### Build: 
https://github.com/mozilla-mobile/android-components/commit/677e24ca0dc1df5c2f22c18b51538a189286b245

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18744)

**Comment by csadilek** [comment]
Duping to https://github.com/mozilla-mobile/android-components/issues/10615.
