### ISSUE TITLE
Intermittent gradle-dependencies - org.mozilla.fenix.utils.BrowsersCacheTest - cached list of browsers change before-after installation when cache is invalidated

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/android-components#11470]
### Firebase Test Run:
https://treeherder.mozilla.org/logviewer?job_id=362813028&repo=fenix
### Stacktrace:
```
SUITE: org.mozilla.fenix.utils.BrowsersCacheTest
  TEST: resetting the cache should empty it
  SUCCESS

  TEST: cached list of browsers change before-after installation when cache is invalidated
  FAILURE

java.lang.NullPointerException
	at org.robolectric.shadows.ShadowApplicationPackageManager.queryComponentsInManifest(ShadowApplicationPackageManager.java:646)
	at org.robolectric.shadows.ShadowApplicationPackageManager.queryIntentComponents(ShadowApplicationPackageManager.java:546)
	at org.robolectric.shadows.ShadowApplicationPackageManager.queryIntentActivities(ShadowApplicationPackageManager.java:517)
	at android.app.ApplicationPackageManager.queryIntentActivities(ApplicationPackageManager.java)
	at mozilla.components.support.utils.Browsers$Companion.findResolvers(Browsers.kt:383)
	at mozilla.components.support.utils.Browsers$Companion.findResolvers$default(Browsers.kt:365)
	at mozilla.components.support.utils.Browsers.resolveBrowsers(Browsers.kt:231)
	at mozilla.components.support.utils.Browsers.browsers$lambda-0(Browsers.kt:101)
	at mozilla.components.support.utils.Browsers.<init>(Browsers.kt:98)
	at mozilla.components.support.utils.Browsers$Companion.all(Browsers.kt:316)
	at org.mozilla.fenix.utils.BrowsersCache.all(BrowsersCache.kt:37)
	at org.mozilla.fenix.utils.BrowsersCacheTest.cached list of browsers change before-after installation when cache is invalidated(BrowsersCacheTest.kt:82)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:570)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:278)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
### Build: 
https://github.com/mozilla-mobile/fenix/commit/0c48f4469acc44984e6001c90a7a8cadfa8e692a

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19033)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794926

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
