### ISSUE TITLE
Intermittent UI test failure - ui-samples-glean - org.mozilla.samples.glean.MainActivityTest - checkGleanClickData - java.lang.ClassCastException: androidx.work.impl.WorkManagerImpl cannot be cast to androidx.work.testing.TestWorkManagerImpl

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/android-components#11547]
### Firebase Test Run:
https://console.firebase.google.com/project/moz-android-components-230120/testlab/histories/bh.acacddb44ee28c64/matrices/6186708473554195496/executions/bs.4bd04668e6fcf414
### Stacktrace:
```
 Fatal exception

java.lang.ClassCastException: androidx.work.impl.WorkManagerImpl cannot be cast to androidx.work.testing.TestWorkManagerImpl

       FATAL EXCEPTION: GleanAPIPool
Process: org.mozilla.samples.glean.debug, PID: 7315
java.lang.ClassCastException: androidx.work.impl.WorkManagerImpl cannot be cast to androidx.work.testing.TestWorkManagerImpl
	at androidx.work.testing.WorkManagerTestInitHelper.getTestDriver(WorkManagerTestInitHelper.java:88)
	at mozilla.telemetry.glean.utils.WorkManagerUtilsKt$testFlushWorkManagerJob$1$1.invokeSuspend(WorkManagerUtils.kt:34)
	at mozilla.telemetry.glean.utils.WorkManagerUtilsKt$testFlushWorkManagerJob$1$1.invoke(WorkManagerUtils.kt)
	at mozilla.telemetry.glean.utils.WorkManagerUtilsKt$testFlushWorkManagerJob$1$1.invoke(WorkManagerUtils.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:100)
	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:148)
	at kotlinx.coroutines.TimeoutKt.withTimeout(Timeout.kt:44)
	at mozilla.telemetry.glean.utils.WorkManagerUtilsKt$testFlushWorkManagerJob$1.invokeSuspend(WorkManagerUtils.kt:28)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at mozilla.telemetry.glean.utils.WorkManagerUtilsKt.testFlushWorkManagerJob(WorkManagerUtils.kt:27)
	at mozilla.telemetry.glean.utils.WorkManagerUtilsKt.testFlushWorkManagerJob$default(WorkManagerUtils.kt:26)
	at mozilla.telemetry.glean.scheduler.PingUploadWorker$Companion.enqueueWorker$glean_release(PingUploadWorker.kt:71)
	at mozilla.telemetry.glean.GleanInternalAPI.submitPingByNameSync$glean_release(Glean.kt:669)
	at mozilla.telemetry.glean.scheduler.MetricsPingScheduler.collectPingAndReschedule$glean_release(MetricsPingScheduler.kt:305)
	at mozilla.telemetry.glean.scheduler.MetricsPingScheduler.schedule(MetricsPingScheduler.kt:262)
	at mozilla.telemetry.glean.GleanInternalAPI$initialize$1.invokeSuspend(Glean.kt:250)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
```
### Build: 
https://github.com/mozilla-mobile/android-components/commit/84a50a62ff78306f661f713129043e523482039f

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19149)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794929

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
