### ISSUE TITLE
Updating target SDK to 31+ for apps causes a crash with media notifications

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#11563]
This was seen in R-B and Focus.

```
    java.lang.IllegalArgumentException: org.mozilla.reference.browser: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.buildServicePendingIntent(PendingIntent.java:724)
        at android.app.PendingIntent.getService(PendingIntent.java:686)
        at mozilla.components.feature.media.notification.MediaNotificationKt.toNotificationData(MediaNotification.kt:105)
        at mozilla.components.feature.media.notification.MediaNotificationKt.access$toNotificationData(MediaNotification.kt:1)
        at mozilla.components.feature.media.notification.MediaNotificationKt$toNotificationData$1.invokeSuspend(Unknown Source:13)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
```

**Comment by jonalmeida** [comment]
In Fenix, the fix is a bit confusing to me: https://github.com/mozilla-mobile/fenix/pull/23080

I'm not sure how it evades the need for making the PendingIntent mutable.

**Comment by jonalmeida** [comment]
> In Fenix, the fix is a bit confusing to me: [mozilla-mobile/fenix#23080](https://github.com/mozilla-mobile/fenix/pull/23080)
> 
> I'm not sure how it evades the need for making the PendingIntent mutable.

I tried upgrading WM in AC to see if fixed the R-B/Focus crashes - it did not for me.
