### ISSUE TITLE
Intermittent support-migration - mozilla.components.support.migration.FennecMigratorTest - migrations versioning basics

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/android-components#11644]
### Firebase Test Run:
https://treeherder.mozilla.org/logviewer?job_id=366020387&repo=android-components
### Stacktrace:
```
  TEST: migrations versioning basics
    [Robolectric] mozilla.components.support.migration.FennecMigratorTest.migrations versioning basics: sdk=28; resources=binary
    I/MonitoringInstr: Instrumentation started!
    I/glean/Dispatchers: Task queued for execution and delayed until flushed
    I/glean/Dispatchers: Task queued for execution and delayed until flushed
    I/glean/Dispatchers: Task queued for execution and delayed until flushed
    I/glean/Dispatchers: Task queued for execution and delayed until flushed
    D [FennecProfile] profiles.ini: false
    D [FennecProfile] No profiles found
    I/glean/Dispatchers: Task queued for execution and delayed until flushed
    D [FennecMigrator] Executing VersionedMigration(migration=mozilla.components.support.migration.Migration$History@305217f0, version=1)
    D [FennecMigrator] Migrating history...
    D [FennecMigrator] Migrated history.
    D [FennecMigrator] Migrated VersionedMigration(migration=mozilla.components.support.migration.Migration$History@305217f0, version=1)
    I/glean/Dispatchers: Task queued for execution and delayed until flushed
    D [FennecMigrator] Executing VersionedMigration(migration=mozilla.components.support.migration.Migration$Bookmarks@7e8c974c, version=1)
    D [FennecMigrator] Migrating bookmarks...
    D [FennecMigrator] Migrated bookmarks.
    D [FennecMigrator] Migrated VersionedMigration(migration=mozilla.components.support.migration.Migration$Bookmarks@7e8c974c, version=1)
    I/glean/Dispatchers: Task queued for execution and delayed until flushed
    D [FennecMigrator] Executing VersionedMigration(migration=mozilla.components.support.migration.Migration$PinnedSites@320f19f1, version=1)
    D [FennecMigrator] Migrated VersionedMigration(migration=mozilla.components.support.migration.Migration$PinnedSites@320f19f1, version=1)
    I/glean/Dispatchers: Task queued for execution and delayed until flushed
    I/glean/Dispatchers: Task queued for execution and delayed until flushed
    D [FennecMigrator] No migrations to run. Fennec install - true.
    I/glean/Dispatchers: Task queued for execution and delayed until flushed
    D [FennecProfile] profiles.ini: false
    D [FennecProfile] No profiles found
    D [FennecMigrator] Executing VersionedMigration(migration=mozilla.components.support.migration.Migration$OpenTabs@7c85b64d, version=1)
    D [FennecMigrator] Migrating session...
    D [FennecSessionImporter] Filtering migrated sessions (size=6, index=5)
    D [FennecSessionImporter] - Rewriting about:reader URL (about:reader?url=https%3A%2F%2Fwww.theverge.com%2F2019%2F9%2F18%2F20871860%2Fhuawei-mate-30-photos-videos-leak-watch-gt-2-fitness-band-tv-android-tablet-harmony-os): https://www.theverge.com/2019/9/18/20871860/huawei-mate-30-photos-videos-leak-watch-gt-2-fitness-band-tv-android-tablet-harmony-os
    D [FennecSessionImporter] Migrated sessions filtered (size=6, index=5)
    D [FennecMigrator] Loading migrated session snapshot...
    D [FennecMigrator] Migrated VersionedMigration(migration=mozilla.components.support.migration.Migration$OpenTabs@7c85b64d, version=1)
    I/glean/Dispatchers: Task queued for execution and delayed until flushed
  FAILURE

java.lang.AssertionError: No action of type class mozilla.components.browser.state.action.TabListAction$RestoreAction found
	at mozilla.components.support.test.middleware.CaptureActionsMiddleware.findLastAction(CaptureActionsMiddleware.kt:44)
	at mozilla.components.support.test.middleware.CaptureActionsMiddleware.assertLastAction(CaptureActionsMiddleware.kt:64)
	at mozilla.components.support.migration.FennecMigratorTest$migrations versioning basics$1.invokeSuspend(FennecMigratorTest.kt:269)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at mozilla.components.support.migration.FennecMigratorTest.migrations versioning basics(FennecMigratorTest.kt:174)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:601)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:260)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:154)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy5.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:121)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
### Build: 
https://github.com/mozilla-mobile/android-components/commit/d2c2a49bb6e7322541d66abdf89bf01e5835f5e8

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19322)

**Comment by csadilek** [comment]
Migration code was removed. Closing.
