### ISSUE TITLE
Having large text can crash the app when long pressing on search toolbar input field.

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/android-components#11678]
See https://github.com/mozilla-mobile/fenix/issues/22958#issuecomment-1031621030 in Fenix.

STR:

Hava really long text (over 200 k characters) copied in clipboard.
Long pressing the `InlineAutocompleteEditText` causes a crash:

```
2022-02-07 16:40:34.000 3939-3939/org.mozilla.fenix.debug E/MessageQueue-JNI: java.lang.RuntimeException: android.os.DeadSystemException
        at android.content.ClipboardManager.getPrimaryClip(ClipboardManager.java:137)
        at android.widget.TextView.canPasteAsPlainText(TextView.java:12583)
        at android.widget.Editor$TextActionModeCallback.populateMenuWithItems(Editor.java:4026)
        at android.widget.Editor$TextActionModeCallback.onCreateActionMode(Editor.java:3961)
        at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onCreateActionMode(DecorView.java:2595)
        at com.android.internal.policy.DecorView.startActionMode(DecorView.java:913)
        at com.android.internal.policy.DecorView.startActionModeForChild(DecorView.java:869)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1008)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1008)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1008)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1008)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1008)
        at android.view.View.startActionMode(View.java:7324)
        at android.widget.Editor.startInsertionActionMode(Editor.java:2129)
        at android.widget.TextView.onTouchEvent(TextView.java:10859)
        at mozilla.components.ui.autocomplete.InlineAutocompleteEditText.onTouchEvent(InlineAutocompleteEditText.kt:785)
        at android.view.View.dispatchTouchEvent(View.java:13416)
```

**Comment by mcarare** [comment]
eng note: this can be reproduced on the sample browser also.

**Comment by mcarare** [comment]
Closed in https://github.com/mozilla-mobile/android-components/pull/11690.
