### ISSUE TITLE
Intermittent several build and test failures - glean: NameError: name '_UnpackAlias' is not defined

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/android-components#11714]
### Firebase Test Run:
https://treeherder.mozilla.org/logviewer?job_id=367733195&repo=android-components
### Stacktrace:
```
> Task :support-sync-telemetry:gleanGenerateMetricsDocsForRelease FAILED
Glean SDK - generating docs for /builds/worker/checkouts/src/components/support/sync-telemetry/metrics.yaml in /builds/worker/checkouts/src/components/support/sync-telemetry/docs
Glean SDK - generating docs for /builds/worker/checkouts/src/components/support/sync-telemetry/pings.yaml in /builds/worker/checkouts/src/components/support/sync-telemetry/docs

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':support-sync-telemetry:gleanGenerateMetricsDocsForRelease'.
> Glean documentation generation failed.
  
  Traceback (most recent call last):
    File "/builds/worker/.gradle/glean/bootstrap-4.5.11/Miniconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/builds/worker/.gradle/glean/bootstrap-4.5.11/Miniconda3/lib/python3.7/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/builds/worker/.gradle/glean/bootstrap-4.5.11/Miniconda3/lib/python3.7/site-packages/glean_parser/__main__.py", line 19, in <module>
      from . import coverage as mod_coverage
    File "/builds/worker/.gradle/glean/bootstrap-4.5.11/Miniconda3/lib/python3.7/site-packages/glean_parser/coverage.py", line 13, in <module>
      from .metrics import ObjectTree
    File "/builds/worker/.gradle/glean/bootstrap-4.5.11/Miniconda3/lib/python3.7/site-packages/glean_parser/metrics.py", line 15, in <module>
      from . import pings
    File "/builds/worker/.gradle/glean/bootstrap-4.5.11/Miniconda3/lib/python3.7/site-packages/glean_parser/pings.py", line 14, in <module>
      from . import util
    File "/builds/worker/.gradle/glean/bootstrap-4.5.11/Miniconda3/lib/python3.7/site-packages/glean_parser/util.py", line 20, in <module>
      import jsonschema  # type: ignore
    File "/builds/worker/.gradle/glean/bootstrap-4.5.11/Miniconda3/lib/python3.7/site-packages/jsonschema/__init__.py", line 29, in <module>
      from jsonschema.protocols import Validator
    File "/builds/worker/.gradle/glean/bootstrap-4.5.11/Miniconda3/lib/python3.7/site-packages/jsonschema/protocols.py", line 23, in <module>
      from typing_extensions import Protocol, runtime_checkable
    File "/builds/worker/.gradle/glean/bootstrap-4.5.11/Miniconda3/lib/python3.7/site-packages/typing_extensions.py", line 494, in <module>
      OrderedDict = typing._alias(collections.OrderedDict, (KT, VT))
    File "/builds/worker/.gradle/glean/bootstrap-4.5.11/Miniconda3/lib/python3.7/typing.py", line 1191, in _alias
      return _GenericAlias(origin, params, special=True, inst=inst)
    File "/builds/worker/.gradle/glean/bootstrap-4.5.11/Miniconda3/lib/python3.7/typing.py", line 613, in __init__
      self.__parameters__ = _collect_type_vars(params)
    File "/builds/worker/.gradle/glean/bootstrap-4.5.11/Miniconda3/lib/python3.7/site-packages/typing_extensions.py", line 143, in _collect_type_vars
      not isinstance(t, _UnpackAlias)
```
### Build: 
https://github.com/mozilla-mobile/android-components/commit/9aafc261847febbcff9d1c71d5c31b9b90010f71

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19481)

**Comment by Archaeopteryx** [comment]
@badboy Could you take a look at this?

**Comment by badboy** [comment]
This was an issue in a dependency and fixed in a release about 6 hours ago (https://github.com/python/typing/blob/master/typing_extensions/CHANGELOG).
Fresh runs shouldn't fail anymore.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795436

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
