### ISSUE TITLE
Crash in [@ mozilla.appservices.logins.LoginsStorageException$InvalidRecord: at mozilla.appservices.logins.LoginsStorageException$ErrorHandler.read(logins.kt:7)] 

### ISSUE THREAD

**Issue by bendk** [mozilla-mobile/android-components#11767]
Crash report: https://crash-stats.mozilla.org/report/index/6efccb60-0608-4b72-bba1-9fb5b0220214

Java stack trace:
```
mozilla.appservices.logins.LoginsStorageException$InvalidRecord
	at mozilla.appservices.logins.LoginsStorageException$ErrorHandler.read(logins.kt:7)
	at mozilla.appservices.logins.LoginsStorageException$ErrorHandler$lift$1.invoke(logins.kt:2)
	at mozilla.appservices.logins.LoginsStorageException$ErrorHandler$lift$1.invoke(logins.kt:1)
	at mozilla.appservices.logins.LoginsKt.liftFromRustBuffer(logins.kt:2)
	at mozilla.appservices.logins.LoginsStorageException$ErrorHandler.lift(logins.kt:2)
	at mozilla.appservices.logins.LoginsStorageException$ErrorHandler.lift(logins.kt:1)
	at mozilla.appservices.logins.LoginStore.findLoginToUpdate(logins.kt:17)
	at mozilla.appservices.logins.DatabaseLoginsStorage.findLoginToUpdate(DatabaseLoginsStorage.kt:3)
	at mozilla.components.service.sync.logins.SyncableLoginsStorage$findLoginToUpdate$2.invokeSuspend(SyncableLoginsStorage.kt:8)
	at mozilla.components.service.sync.logins.SyncableLoginsStorage$findLoginToUpdate$2.invoke(SyncableLoginsStorage.kt:2)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:1)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:9)
	at mozilla.components.service.sync.logins.SyncableLoginsStorage.findLoginToUpdate(SyncableLoginsStorage.kt:1)
	at mozilla.components.service.sync.logins.DefaultLoginValidationDelegate$shouldUpdateOrCreateAsync$1.invokeSuspend(DefaultLoginValidationDelegate.kt:6)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)
```

reported from https://www.reddit.com/r/firefox/comments/ss5re7/firefox_crashes_on_android_12_when_i_try_to_sign/

* https://crash-stats.mozilla.org/signature/?product=Fenix&signature=mozilla.appservices.logins.LoginsStorageException%24InvalidRecord%3A%20at%20mozilla.appservices.logins.LoginsStorageException%24ErrorHandler.read%28logins.kt%3A7%29
* https://sentry.prod.mozaws.net/operations/firefox/?query=is%3Aunresolved+InvalidLogin%3A%3AIllegalFieldValue

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19634)

**Comment by bendk** [comment]
I think these are the steps to reproduce:
  - Login to a new site
  - When when save password dialog appears, delete all chars from the password field
  - Add or delete a char from the username field
  - If the bug is present, Fenix will crash.

**Comment by csadilek** [comment]
Fix landed in https://github.com/mozilla-mobile/android-components/pull/11768.
