### ISSUE TITLE
Crash in [@ mozilla.appservices.autofill.AutofillException$OpenDatabaseException: at mozilla.appservices.autofill.AutofillException$ErrorHandler.read(autofill.kt:13)]

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/android-components#11810]
Crash report: https://crash-stats.mozilla.org/report/index/e253923f-0356-4d52-9106-f9e700220224

Bugzilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1757968

Java stack trace:
```
mozilla.appservices.autofill.AutofillException$OpenDatabaseException
	at mozilla.appservices.autofill.AutofillException$ErrorHandler.read(autofill.kt:13)
	at mozilla.appservices.autofill.AutofillException$ErrorHandler$lift$1.invoke(autofill.kt:2)
	at mozilla.appservices.autofill.AutofillException$ErrorHandler$lift$1.invoke(autofill.kt:1)
	at mozilla.appservices.autofill.AutofillKt.liftFromRustBuffer(autofill.kt:2)
	at mozilla.appservices.autofill.AutofillException$ErrorHandler.lift(autofill.kt:2)
	at mozilla.appservices.autofill.AutofillException$ErrorHandler.lift(autofill.kt:1)
	at mozilla.appservices.autofill.Store.<init>(autofill.kt:13)
	at mozilla.components.service.sync.autofill.AutofillCreditCardsAddressesStorage$conn$2.invoke(AutofillCreditCardsAddressesStorage.kt:5)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:5)
	at mozilla.components.service.sync.autofill.AutofillCreditCardsAddressesStorage.getConn$service_sync_autofill_release(AutofillCreditCardsAddressesStorage.kt:1)
	at mozilla.components.service.sync.autofill.AutofillCreditCardsAddressesStorage$warmUp$2.invokeSuspend(AutofillCreditCardsAddressesStorage.kt:6)
	at mozilla.components.service.sync.autofill.AutofillCreditCardsAddressesStorage$warmUp$2.invoke(AutofillCreditCardsAddressesStorage.kt:2)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:1)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at org.mozilla.fenix.FenixApplication$initVisualCompletenessQueueAndQueueTasks$queueInitStorageAndServices$1$1.invokeSuspend(FenixApplication.kt:16)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)
```

**Comment by mhammond** [comment]
crashstats link says the underlying exception is `Message: Error opening database: Error executing SQL: database or disk is full `

**Comment by kbrosnan** [comment]
This looks to be the same as https://github.com/mozilla/application-services/issues/4872
