### ISSUE TITLE
Crash in [@ java.lang.IllegalStateException: at androidx.fragment.app.Fragment.getParentFragmentManager(Fragment.java)]

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/android-components#11837]
This is not a new crash signature, but its volume spiked in the 97.1 and 97.2 releases.

Crash report: https://crash-stats.mozilla.org/report/index/6d83bc00-0dce-4f9f-bc8a-ec6230220310

Java stack trace:
```
java.lang.IllegalStateException
	at androidx.fragment.app.Fragment.getParentFragmentManager(Fragment.java:2)
	at androidx.fragment.app.DialogFragment.dismissInternal(DialogFragment.java:16)
	at mozilla.components.feature.prompts.PromptFeature$start$2$invokeSuspend$$inlined$collect$1.emit(Collect.kt:31)
	at mozilla.components.support.ktx.kotlinx.coroutines.flow.FlowKt$ifAnyChanged$$inlined$filter$1$2.emit(Collect.kt:19)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:14)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt:1)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6388)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:930)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:820)
```

Bugzilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1759003

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19792)

**Comment by csadilek** [comment]
Crash seems to have tapered off. Closing for upstream bug https://bugzilla.mozilla.org/show_bug.cgi?id=1759003.
