### ISSUE TITLE
3rd party logins autofill failing after unlock because of a parcelling error of ParsedStructure

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/android-components#11892]
Seen in https://github.com/mozilla-mobile/fenix/issues/24257#issuecomment-1072412944

```
2022-03-18 15:21:55.007 1722-1791/? E/Parcel: Class not found when unmarshalling: mozilla.components.feature.autofill.structure.ParsedStructure
    java.lang.ClassNotFoundException: mozilla.components.feature.autofill.structure.ParsedStructure
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at android.os.Parcel.readParcelableCreator(Parcel.java:3338)
        at android.os.Parcel.readParcelable(Parcel.java:3272)
        at android.os.Parcel.readValue(Parcel.java:3174)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3567)
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
        at android.os.BaseBundle.unparcel(BaseBundle.java:236)
        at android.os.Bundle.putAll(Bundle.java:292)
        at android.content.Intent.fillIn(Intent.java:10288)
        at com.android.server.am.PendingIntentRecord.sendInner(PendingIntentRecord.java:315)
        at com.android.server.wm.ActivityTaskManagerService.startActivityIntentSender(ActivityTaskManagerService.java:1222)
        at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:1577)
        at android.os.Binder.execTransactInternal(Binder.java:1165)
        at android.os.Binder.execTransact(Binder.java:1134)
```

Fixing this also help with the issues from https://github.com/mozilla-mobile/fenix/issues/23707

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19895)

**Comment by csadilek** [comment]
Fixed by https://github.com/mozilla-mobile/android-components/pull/11893.
