### ISSUE TITLE
Intermittent UI test failure - feature-downloads - calling tryAgain starts the download again

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/android-components#11904]
### Firebase Test Run:
https://treeherder.mozilla.org/logviewer?job_id=371699671&repo=android-components
### Stacktrace:
```
[task 2022-03-20T14:40:38.108Z]   TEST: calling tryAgain starts the download again
[task 2022-03-20T14:40:38.108Z]     Intent = Intent { act=android.intent.action.DOWNLOAD_COMPLETE (has extras) }; Matching wrappers: [Wrapper[receiver=[mozilla.components.feature.downloads.manager.AndroidDownloadManager@30da2794], context=[android.app.ContextImpl@678ed4c7], intentFilter=[android.content.IntentFilter@32d31ddc]]]
[task 2022-03-20T14:40:38.207Z]   FAILURE
[task 2022-03-20T14:40:38.207Z] 
[task 2022-03-20T14:40:38.208Z] java.lang.AssertionError
[task 2022-03-20T14:40:38.208Z] 	at org.junit.Assert.fail(Assert.java:86)
[task 2022-03-20T14:40:38.208Z] 	at org.junit.Assert.assertTrue(Assert.java:41)
[task 2022-03-20T14:40:38.208Z] 	at org.junit.Assert.assertTrue(Assert.java:52)
[task 2022-03-20T14:40:38.208Z] 	at mozilla.components.feature.downloads.manager.AndroidDownloadManagerTest.calling tryAgain starts the download again(AndroidDownloadManagerTest.kt:86)
[task 2022-03-20T14:40:38.208Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2022-03-20T14:40:38.208Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2022-03-20T14:40:38.208Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2022-03-20T14:40:38.208Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[task 2022-03-20T14:40:38.208Z] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[task 2022-03-20T14:40:38.208Z] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[task 2022-03-20T14:40:38.208Z] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[task 2022-03-20T14:40:38.208Z] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[task 2022-03-20T14:40:38.208Z] 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
[task 2022-03-20T14:40:38.208Z] 	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:591)
[task 2022-03-20T14:40:38.208Z] 	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:274)
[task 2022-03-20T14:40:38.208Z] 	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:88)
[task 2022-03-20T14:40:38.209Z] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[task 2022-03-20T14:40:38.209Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[task 2022-03-20T14:40:38.209Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[task 2022-03-20T14:40:38.210Z] 	at java.base/java.lang.Thread.run(Thread.java:829)
```
### Build: 
https://github.com/mozilla-mobile/android-components/commit/1e84e397335b4ab495a9ccc0b1bd466a9a5f160a

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19910)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794910

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
