### ISSUE TITLE
Intermittent UI test failure - mozilla.components.feature.downloads.AbstractFetchDownloadServiceTest - onDestroy cancels all running jobs

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/android-components#11953]
### Firebase Test Run:
https://treeherder.mozilla.org/logviewer?job_id=373228016&repo=android-components
### Stacktrace:
```
  TEST: onDestroy cancels all running jobs
    D [AbstractFetchDownloadService] Starting download for 9cdc37a8-d206-49c8-9974-49151f7a899a
    D [AbstractFetchDownloadService] Fetching download for 9cdc37a8-d206-49c8-9974-49151f7a899a
    D [AbstractFetchDownloadService] starting copyInChunks 9cdc37a8-d206-49c8-9974-49151f7a899a currentBytesCopied 0
  FAILURE

Wanted but not invoked:
abstractFetchDownloadService.performDownload$feature_downloads_release(
    <Capturing argument>,
    <any boolean>
);
-> at mozilla.components.feature.downloads.AbstractFetchDownloadService.performDownload$feature_downloads_release(AbstractFetchDownloadService.kt:666)

However, there were exactly 16 interactions with this mock:
abstractFetchDownloadService.registerNotificationActionsReceiver$feature_downloads_release();
-> at mozilla.components.feature.downloads.AbstractFetchDownloadServiceTest$onDestroy cancels all running jobs$1.invokeSuspend(AbstractFetchDownloadServiceTest.kt:1291)

abstractFetchDownloadService.getContext$feature_downloads_release();
-> at mozilla.components.feature.downloads.AbstractFetchDownloadService.registerNotificationActionsReceiver$feature_downloads_release(AbstractFetchDownloadService.kt:512)

abstractFetchDownloadService.getBroadcastReceiver$feature_downloads_release();
-> at mozilla.components.feature.downloads.AbstractFetchDownloadService.registerNotificationActionsReceiver$feature_downloads_release(AbstractFetchDownloadService.kt:512)

abstractFetchDownloadService.onStartCommand(
    Intent { act=ACTION_DOWNLOAD (has extras) },
    0,
    0
);
-> at mozilla.components.feature.downloads.AbstractFetchDownloadServiceTest$onDestroy cancels all running jobs$1.invokeSuspend(AbstractFetchDownloadServiceTest.kt:1292)

abstractFetchDownloadService.getStore();
-> at mozilla.components.feature.downloads.AbstractFetchDownloadService.onStartCommand(AbstractFetchDownloadService.kt:252)

abstractFetchDownloadService.handleDownloadIntent$feature_downloads_release(
    DownloadState(url=https://example.com/file.txt, fileName=file.txt, contentType=null, contentLength=null, currentBytesCopied=0, status=INITIATED, userAgent=null, destinationDirectory=Download, referrerUrl=null, skipConfirmation=false, id=9cdc37a8-d206-49c8-9974-49151f7a899a, sessionId=null, private=false, createdTime=1648996767224, response=null, notificationId=null)
);
-> at mozilla.components.feature.downloads.AbstractFetchDownloadService.onStartCommand(AbstractFetchDownloadService.kt:258)

abstractFetchDownloadService.getStore();
-> at mozilla.components.feature.downloads.AbstractFetchDownloadService.handleDownloadIntent$feature_downloads_release(AbstractFetchDownloadService.kt:288)

abstractFetchDownloadService.setForegroundNotification$feature_downloads_release(
    DownloadJobState(job="coroutine#468":StandaloneCoroutine{Active}@724b92e3, state=DownloadState(url=https://example.com/file.txt, fileName=file.txt, contentType=null, contentLength=null, currentBytesCopied=0, status=DOWNLOADING, userAgent=null, destinationDirectory=Download, referrerUrl=null, skipConfirmation=false, id=9cdc37a8-d206-49c8-9974-49151f7a899a, sessionId=null, private=false, createdTime=1648996767224, response=null, notificationId=272114981), currentBytesCopied=0, status=DOWNLOADING, foregroundServiceId=272114981, downloadDeleted=false, notifiedStopped=false, lastNotificationUpdate=0, createdTime=1648996767226)
);
-> at mozilla.components.feature.downloads.AbstractFetchDownloadService.handleDownloadIntent$feature_downloads_release(AbstractFetchDownloadService.kt:298)

abstractFetchDownloadService.updateNotificationGroup$feature_downloads_release();
-> at mozilla.components.feature.downloads.AbstractFetchDownloadService.setForegroundNotification$feature_downloads_release(AbstractFetchDownloadService.kt:595)

abstractFetchDownloadService.getContext$feature_downloads_release();
-> at mozilla.components.feature.downloads.AbstractFetchDownloadService.updateNotificationGroup$feature_downloads_release(AbstractFetchDownloadService.kt:546)

abstractFetchDownloadService.getStyle();
-> at mozilla.components.feature.downloads.AbstractFetchDownloadService.updateNotificationGroup$feature_downloads_release(AbstractFetchDownloadService.kt:548)

abstractFetchDownloadService.getContext$feature_downloads_release();
-> at mozilla.components.feature.downloads.AbstractFetchDownloadService.updateNotificationGroup$feature_downloads_release(AbstractFetchDownloadService.kt:550)

abstractFetchDownloadService.startForeground(
    100,
    Notification(channel=mozac.feature.downloads.generic pri=1 contentView=null vibrate=null sound=null defaults=0x0 flags=0x240 color=0xff607d8b groupKey=mozac.feature.downloads.group vis=PRIVATE)
);
-> at mozilla.components.feature.downloads.AbstractFetchDownloadService.setForegroundNotification$feature_downloads_release(AbstractFetchDownloadService.kt:605)

abstractFetchDownloadService.$$robo$getData();
-> at android.app.Service.startForeground(Service.java)

abstractFetchDownloadService.onStart(
    Intent { act=ACTION_DOWNLOAD (has extras) },
    0
);
-> at android.app.Service.$$robo$$android_app_Service$onStartCommand(Service.java:497)

abstractFetchDownloadService.getDownloadJobs$feature_downloads_release();
-> at mozilla.components.feature.downloads.AbstractFetchDownloadServiceTest$onDestroy cancels all running jobs$1.invokeSuspend(AbstractFetchDownloadServiceTest.kt:1294)


	at mozilla.components.feature.downloads.AbstractFetchDownloadService.performDownload$feature_downloads_release(AbstractFetchDownloadService.kt:666)
	at mozilla.components.feature.downloads.AbstractFetchDownloadServiceTest$onDestroy cancels all running jobs$1.invokeSuspend(AbstractFetchDownloadServiceTest.kt:1297)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at mozilla.components.feature.downloads.AbstractFetchDownloadServiceTest.onDestroy cancels all running jobs(AbstractFetchDownloadServiceTest.kt:1269)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:591)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:274)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:88)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
### Build: 
https://github.com/mozilla-mobile/android-components/commit/3da16acfcf9471b29eff578ad1e9bdc162cd7c91

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20043)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793217

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
