### ISSUE TITLE
Crash in [@ java.io.FileNotFoundException: at java.io.FileOutputStream.open(Native Method)]

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/android-components#11970]
Crash report: https://crash-stats.mozilla.org/report/index/f06aa9e5-50c8-4a80-91b9-08e2b0220406

This looks like a regression in Fenix v100. Socorro has 48 crash reports from 9 different installations, all with v100. Was this bug fixed in v101?

https://crash-stats.mozilla.org/signature/?release_channel=nightly&product=Focus&product=Fenix&version=100.0a1&signature=java.io.FileNotFoundException%3A%20at%20java.io.FileOutputStream.open%28Native%20Method%29&date=%3E%3D2021-10-07T17%3A53%3A00.000Z&date=%3C2022-04-07T17%3A53%3A00.000Z&_columns=date&_columns=product&_columns=version&_columns=build_id&_columns=platform&_columns=reason&_columns=address&_columns=install_time&_columns=startup_crash&_sort=-date&page=1#summary

Java stack trace:
```
java.io.FileNotFoundException
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:169)
	at com.jakewharton.disklrucache.DiskLruCache.rebuildJournal(DiskLruCache.java:3)
	at com.jakewharton.disklrucache.DiskLruCache.open(DiskLruCache.java:16)
	at mozilla.components.browser.icons.utils.IconDiskCache.getIconResourcesCache(IconDiskCache.kt:4)
	at mozilla.components.browser.icons.utils.IconDiskCache.getResources(IconDiskCache.kt:3)
	at mozilla.components.browser.icons.preparer.DiskIconPreparer.prepare(DiskIconPreparer.kt:3)
	at mozilla.components.browser.icons.BrowserIconsKt.access$prepare(BrowserIcons.kt:2)
	at mozilla.components.browser.icons.BrowserIcons$loadIconInternalAsync$1.invokeSuspend(BrowserIcons.kt:7)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20100)

**Comment by kbrosnan** [comment]
This crash looks like an emulator. 

> <html><body>


samsung | SM-G988N | 25 (REL) | x86 | 46 | 95.8%
-- | -- | -- | -- | -- | --



</body>
</html>

The Samsung S20 is not an x86 device and it shipped with Android 10 upgrade to 11. The crashes happened on Android 7.1 (API 25).

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793213

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
