### ISSUE TITLE
Intermittent UI test failure - mozilla.components.feature.downloads.manager.AndroidDownloadManagerTest - sendBroadcast with valid downloadID must call onDownloadStopped after download

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/android-components#11994]
### Firebase Test Run:
https://treeherder.mozilla.org/logviewer?job_id=374228603&repo=android-components
### Stacktrace:
```
  TEST: sendBroadcast with valid downloadID must call onDownloadStopped after download
    Intent = Intent { act=android.intent.action.DOWNLOAD_COMPLETE (has extras) }; Matching wrappers: [Wrapper[receiver=[mozilla.components.feature.downloads.manager.AndroidDownloadManager@26e9a2bc], context=[android.app.ContextImpl@68e1a369], intentFilter=[android.content.IntentFilter@6e79be9c]]]
  FAILURE

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at mozilla.components.feature.downloads.manager.AndroidDownloadManagerTest.sendBroadcast with valid downloadID must call onDownloadStopped after download(AndroidDownloadManagerTest.kt:148)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:591)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:274)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:88)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
### Build: 
https://github.com/mozilla-mobile/android-components/commit/661ade54ee1b0f865fb5d19076c5b0b3560cfd20

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20143)

**Comment by mcarare** [comment]
Seen again in https://github.com/mozilla-mobile/android-components/pull/12501

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793202

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
