### ISSUE TITLE
Permanent non-fatal CI task message java.io.FileNotFoundException: https://dl.google.com/android/repository/sys-img/android-desktop/sys-img2-2.xml

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/android-components#12052]
This issue started on April 18 or 19. Tasks in CI log
```
[task 2022-04-23T13:47:44.431Z] > Configure project :support-migration
[task 2022-04-23T13:47:44.431Z] Requires glean_parser==5.0.1
[task 2022-04-23T13:47:44.731Z] 
[task 2022-04-23T13:47:44.731Z] > Configure project :support-sync-telemetry
[task 2022-04-23T13:47:44.731Z] Requires glean_parser==5.0.1
[task 2022-04-23T13:47:46.831Z] IO exception while downloading manifest:
[task 2022-04-23T13:47:46.831Z] java.io.FileNotFoundException: https://dl.google.com/android/repository/sys-img/android-desktop/sys-img2-2.xml
[task 2022-04-23T13:47:46.831Z] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1920)
[task 2022-04-23T13:47:46.831Z] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
[task 2022-04-23T13:47:46.831Z] 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
[task 2022-04-23T13:47:46.832Z] 	at com.android.sdklib.repository.legacy.remote.internal.DownloadCache.openUrl(DownloadCache.java:246)
[task 2022-04-23T13:47:46.832Z] 	at com.android.sdklib.repository.legacy.remote.internal.DownloadCache.downloadAndCache(DownloadCache.java:622)
[task 2022-04-23T13:47:46.832Z] 	at com.android.sdklib.repository.legacy.remote.internal.DownloadCache.openCachedUrl(DownloadCache.java:545)
[task 2022-04-23T13:47:46.832Z] 	at com.android.sdklib.repository.legacy.LegacyDownloader.downloadAndStream(LegacyDownloader.java:65)
[task 2022-04-23T13:47:46.832Z] 	at com.android.repository.impl.downloader.LocalFileAwareDownloader.downloadAndStream(LocalFileAwareDownloader.java:51)
[task 2022-04-23T13:47:46.832Z] 	at com.android.repository.impl.manager.RemoteRepoLoaderImpl.lambda$fetchPackages$0(RemoteRepoLoaderImpl.java:138)
[task 2022-04-23T13:47:46.832Z] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[task 2022-04-23T13:47:46.832Z] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[task 2022-04-23T13:47:46.832Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[task 2022-04-23T13:47:46.832Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[task 2022-04-23T13:47:46.832Z] 	at java.base/java.lang.Thread.run(Thread.java:829)
[task 2022-04-23T13:47:46.832Z] 
[task 2022-04-23T13:47:47.132Z] Checking the license for package Android SDK Build-Tools 30.0.2 in /builds/worker/fetches/android-sdk-linux/licenses
[task 2022-04-23T13:47:47.132Z] License for package Android SDK Build-Tools 30.0.2 accepted.
```
See e.g. https://treeherder.mozilla.org/logviewer?job_id=375561147&repo=android-components
This failure is not fatal.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20271)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793225

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
