### ISSUE TITLE
PlacesException$UnexpectedPlacesException: Error executing SQL: Invalid column type Null at index: 0, name: score

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#12099]
Sentry crash link: https://sentry.io/organizations/mozilla/issues/3150733599/

https://github.com/mozilla-mobile/fenix/pull/25092#issuecomment-1116785997

When upgrading Fenix to 93.0.1, our UI tests are catching a runtime error with the new upgrade:

```
mozilla.appservices.places.uniffi.PlacesException$UnexpectedPlacesException: Unexpected error: Error executing SQL: Invalid column type Null at index: 0, name: score

       FATAL EXCEPTION: DefaultDispatcher-worker-18
Process: org.mozilla.fenix.debug, PID: 10964
mozilla.appservices.places.uniffi.PlacesException$UnexpectedPlacesException: Unexpected error: Error executing SQL: Invalid column type Null at index: 0, name: score
	at mozilla.appservices.places.uniffi.FfiConverterTypePlacesError.read(places.kt:2605)
	at mozilla.appservices.places.uniffi.FfiConverterTypePlacesError$lift$1.invoke(places.kt:2599)
	at mozilla.appservices.places.uniffi.FfiConverterTypePlacesError$lift$1.invoke(places.kt:2599)
	at mozilla.appservices.places.uniffi.PlacesKt.liftFromRustBuffer(places.kt:207)
	at mozilla.appservices.places.uniffi.FfiConverterTypePlacesError.lift(places.kt:2599)
	at mozilla.appservices.places.uniffi.PlacesException$ErrorHandler.lift(places.kt:2593)
	at mozilla.appservices.places.uniffi.PlacesException$ErrorHandler.lift(places.kt:2592)
	at mozilla.appservices.places.uniffi.PlacesConnection.getHistoryHighlights(places.kt:3849)
	at mozilla.appservices.places.PlacesReaderConnection.getHighlights$suspendImpl(PlacesConnection.kt:240)
	at mozilla.appservices.places.PlacesReaderConnection.getHighlights(Unknown Source:0)
	at mozilla.components.browser.storage.sync.PlacesHistoryStorage.getHistoryHighlights$suspendImpl(PlacesHistoryStorage.kt:271)
	at mozilla.components.browser.storage.sync.PlacesHistoryStorage.getHistoryHighlights(Unknown Source:0)
	at org.mozilla.fenix.home.recentvisits.RecentVisitsFeature$start$1$highlights$1.invokeSuspend(RecentVisitsFeature.kt:61)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
  
```

https://user-images.githubusercontent.com/1370580/166608002-f2361b3e-08af-4a4f-9580-e57ebe01ce36.mp4

**Comment by jonalmeida** [comment]
I can't reproduce this locally when I try to imitate the automation in the video above.
