### ISSUE TITLE
Intermittent unit test failure - mozilla.components.feature.prompts.PromptFeatureTest - WHEN onConfirm is called on a SaveCreditCard dialog THEN a confirm request will consume the dialog

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/android-components#12143]
### Firebase Test Run:
https://treeherder.mozilla.org/logviewer?job_id=377613775&repo=android-components
### Stacktrace:
```
  TEST: WHEN onConfirm is called on a SaveCreditCard dialog THEN a confirm request will consume the dialog
    D [PromptFeature] Ignoring received SaveCreditCard because PromptFeature.creditCardValidationDelegate is null. If you are trying to autofill credit cards, try attaching a CreditCardValidationDelegate to PromptFeature
  FAILURE

java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at mozilla.components.feature.prompts.PromptFeatureTest.WHEN onConfirm is called on a SaveCreditCard dialog THEN a confirm request will consume the dialog(PromptFeatureTest.kt:2061)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:591)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:274)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:88)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
### Build: 
https://github.com/mozilla-mobile/android-components/commit/8b8db2d131ae91a3ce879130f19430809cb2d7db

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/FNXV2-20439)

**Comment by Archaeopteryx** [comment]
@gabrielluong We are still [observing the failure](https://treeherder.mozilla.org/logviewer?job_id=378628752&repo=android-components).

**Comment by jonalmeida** [comment]
I'm going to take a look at this today because I can reproduce it locally quite easily.

**Comment by jonalmeida** [comment]
This test is rather difficult to fix because the feature triggers async actions that not always scheduled by the time we call `BrowserStore#waitUntilIdle`.

I've tried a few things like, adding a few of those calls around the place as well as keeping the `joinBlocking` but until we try and change the API to expose the CoroutineScope(s) that the feature uses to observe the store, we can't ensure that the test runs sequentially. In real world situations, this might not really come across at all, but there is potential for it if we're able to reproduce this in a unit test.

One of my hacky ideas was to try and access the scope of the BrowserStore so that we can combine them within the unit test, but it wouldn't be a good fix even if it did work (it didn't):

```kotlin
@Test
fun theTest() = runTestOnMain {
  val scopeField = Store::class.java.getDeclaredField("scope")
  scopeField.isAccessible = true
  val scope = scopeField.get(store) as CoroutineScope
  scope.coroutineContext + coroutineContext

  // proceed to run the test.
}
```
