### ISSUE TITLE
CreditCardSaveDialogFragment Crash - NumberFormatException java.lang.Integer in parseInt

### ISSUE THREAD

**Issue by MozillaNoah** [mozilla-mobile/android-components#12188]
[Crash link](https://sentry.io/organizations/mozilla/issues/3268443335/?project=6295546&query=is%3Aunresolved+level%3Afatal+firstSeen%3A-1w&sort=freq&statsPeriod=14d)

Stack trace:

> java.lang.NumberFormatException: For input string: ""
    at java.lang.Integer.parseInt(Integer.java:627)
    at java.lang.Integer.parseInt(Integer.java:650)
    at mozilla.components.concept.storage.CreditCardEntry.getExpiryDate(CreditCardsAddressesStorage.kt:4)
    at mozilla.components.feature.prompts.creditcard.CreditCardSaveDialogFragment.onViewCreated(CreditCardSaveDialogFragment.kt:8)
    at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:30)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:24)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:68)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:10)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:14)
    at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:1)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8669)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20487)

**Comment by gabrielluong** [comment]
We are basically failing here https://searchfox.org/mozilla-mobile/source/android-components/components/concept/storage/src/main/java/mozilla/components/concept/storage/CreditCardsAddressesStorage.kt#266-267 because the user could have either the expiry month or year not filled in and then submitting the form which will prompt the save credit card dialog.

I think we should just return an empty string if either of those fields are missing.
