### ISSUE TITLE
Intermittent test failure - Dispatchers.Main is used concurrently with setting it

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#12230]
I saw this while debugging https://github.com/mozilla-mobile/android-components/issues/12143 locally:
```
Dispatchers.Main is used concurrently with setting it
java.lang.IllegalStateException: Dispatchers.Main is used concurrently with setting it
	at kotlinx.coroutines.test.internal.TestMainDispatcher$NonConcurrentlyModifiable.concurrentRW(TestMainDispatcher.kt:70)
	at kotlinx.coroutines.test.internal.TestMainDispatcher$NonConcurrentlyModifiable.setValue(TestMainDispatcher.kt:86)
	at kotlinx.coroutines.test.internal.TestMainDispatcher.resetDispatcher(TestMainDispatcher.kt:40)
	at kotlinx.coroutines.test.TestDispatchers.resetMain(TestDispatchers.kt:37)
	at mozilla.components.support.test.rule.MainCoroutineRule.finished(MainCoroutineRule.kt:54)
	at org.junit.rules.TestWatcher.finishedQuietly(TestWatcher.java:117)
	at org.junit.rules.TestWatcher.access$400(TestWatcher.java:46)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:64)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:591)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:274)
```

@Mugurell do you have any hints about this since you worked on upgrading our coroutine testing recently?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20564)

**Comment by Mugurell** [comment]
Not sure how a concurrent read-write may happen since we rely on JUnit callback which I expect will ensure the calls about when a test is finished and another one starts are somehow synchronized.
Thinking specifically about this maybe we should first call `setMain` and `resetMain` [in MainCoroutineRule](https://github.com/mozilla-mobile/android-components/blob/a5bd96fc21e8afd0da9d73f2d816aa4e97ec1f3b/components/support/test/src/main/java/mozilla/components/support/test/rule/MainCoroutineRule.kt#L47-L54) before calling `super`.

**Comment by jonalmeida** [comment]
Similar failures in CI (PromptFeature again): https://github.com/mozilla-mobile/android-components/issues/12321

**Comment by YuraLaguta** [comment]
Facing the same issue looks like the order of call won't help because the super implementations are empty
<img width="799" alt="Screen Shot 2022-07-11 at 4 28 28 pm" src="https://user-images.githubusercontent.com/1853043/178202582-48456eb4-e2b2-4478-8985-4b79f212ecd2.png">

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794861

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
