### ISSUE TITLE
Intermittent UI test failure - checkGleanClickData

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/android-components#12311]
### Firebase Test Run:
https://console.firebase.google.com/u/0/project/moz-android-components-230120/testlab/histories/bh.acacddb44ee28c64/matrices/7325812674678277604/executions/bs.742ba2c943b871a
### Stacktrace:
`java.lang.AssertionError: Assertion failed
at mozilla.telemetry.glean.GleanInternalAPI.testSetLocalEndpoint$glean_release(Glean.kt:469)
at mozilla.telemetry.glean.testing.GleanTestLocalServer.starting(GleanTestLocalServer.kt:46)
at org.junit.rules.TestWatcher.startingQuietly(TestWatcher.java:108)
at org.junit.rules.TestWatcher.access$000(TestWatcher.java:46)
at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:53)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:162)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:444)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1837)`
### Build: 
on main 6/9: https://github.com/mozilla-mobile/android-components/pull/12248

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20686)

**Comment by AaronMT** [comment]
Failed again in https://github.com/mozilla-mobile/android-components/pull/12337

https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/KxaUMX1jTSSylyJZdhcSNg/runs/0/artifacts/public/logs/live_backing.log

and again in https://github.com/mozilla-mobile/android-components/pull/12344

https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/cSTouiZ8QAOZsqPHd6KpUA/runs/1/artifacts/public/logs/live_backing.log

**Comment by AaronMT** [comment]
This is pretty much permanent failure daily. @badboy

**Comment by badboy** [comment]
> This is pretty much permanent failure daily. @badboy

Yikes. In that case we can disable it for now. We won't get around to taking a closer look for another couple of days (though I'm prioritizing it now). I'm not super worried about this. It is surely just a timing issue and it's always gonna be hard to get it just right.

**Comment by AndiAJ** [comment]
Failed 2x on 8/1

[Firebase link](https://console.firebase.google.com/u/0/project/moz-android-components-230120/testlab/histories/bh.acacddb44ee28c64/matrices/8737182914675105237/executions/bs.2c3baa1d1f57ad76/testcases/2)

java.lang.AssertionError: Assertion failed
	at mozilla.telemetry.glean.GleanInternalAPI.afterInitialize$glean_release(Glean.kt:475)
	at mozilla.telemetry.glean.GleanInternalAPI.testSetLocalEndpoint$glean_release(Glean.kt:499)
	at mozilla.telemetry.glean.testing.GleanTestLocalServer.starting(GleanTestLocalServer.kt:46)
	at org.junit.rules.TestWatcher.startingQuietly(TestWatcher.java:108)
	at org.junit.rules.TestWatcher.access$000(TestWatcher.java:46)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:53)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:162)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:444)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1837)
    

[Firebase link](https://console.firebase.google.com/u/0/project/moz-android-components-230120/testlab/histories/bh.acacddb44ee28c64/matrices/7765070928163995771/executions/bs.9ffd2785d3f541b8/testcases/2)

java.lang.AssertionError: Assertion failed
	at mozilla.telemetry.glean.GleanInternalAPI.afterInitialize$glean_release(Glean.kt:475)
	at mozilla.telemetry.glean.GleanInternalAPI.testSetLocalEndpoint$glean_release(Glean.kt:499)
	at mozilla.telemetry.glean.testing.GleanTestLocalServer.starting(GleanTestLocalServer.kt:46)
	at org.junit.rules.TestWatcher.startingQuietly(TestWatcher.java:108)
	at org.junit.rules.TestWatcher.access$000(TestWatcher.java:46)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:53)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:162)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:444)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1837)

**Comment by AndiAJ** [comment]
Failed 1x on 8/2 on **Nexus 6, Virtual, API Level 21** 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-android-components-230120/testlab/histories/bh.acacddb44ee28c64/matrices/5956995596410830954/executions/bs.e598147b28ba4165/testcases/2) 

java.lang.AssertionError: Assertion failed
	at mozilla.telemetry.glean.GleanInternalAPI.afterInitialize$glean_release(Glean.kt:475)
	at mozilla.telemetry.glean.GleanInternalAPI.testSetLocalEndpoint$glean_release(Glean.kt:499)
	at mozilla.telemetry.glean.testing.GleanTestLocalServer.starting(GleanTestLocalServer.kt:46)
	at org.junit.rules.TestWatcher.startingQuietly(TestWatcher.java:108)
	at org.junit.rules.TestWatcher.access$000(TestWatcher.java:46)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:53)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:162)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:444)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1837)

**Comment by badboy** [comment]
I commited faulty code, so instead of fixing it I just shifted around what error message we'll see.

**Comment by badboy** [comment]
Should hopefully be fixed now with #12631 landed

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794856

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
