### ISSUE TITLE
Intermittent mozilla.components.feature.prompts.PromptFeatureTest - When dialogs are being abused prompts are not allowed

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/android-components#12321]
### Firebase Test Run:
https://treeherder.mozilla.org/logviewer?job_id=380997982&repo=android-components
### Stacktrace:
```
[task 2022-06-11T14:39:31.735Z]   TEST: Selecting a login confirms the request
[task 2022-06-11T14:39:31.735Z]   SUCCESS
[task 2022-06-11T14:39:31.735Z] 
[task 2022-06-11T14:39:31.735Z]   TEST: When dialogs are being abused prompts are not allowed
[task 2022-06-11T14:39:31.735Z]   FAILURE
[task 2022-06-11T14:39:31.735Z] 
[task 2022-06-11T14:39:31.735Z] java.lang.IllegalStateException: Dispatchers.Main is used concurrently with setting it
[task 2022-06-11T14:39:31.735Z] 	at kotlinx.coroutines.test.internal.TestMainDispatcher$NonConcurrentlyModifiable.concurrentRW(TestMainDispatcher.kt:70)
[task 2022-06-11T14:39:31.735Z] 	at kotlinx.coroutines.test.internal.TestMainDispatcher$NonConcurrentlyModifiable.setValue(TestMainDispatcher.kt:86)
[task 2022-06-11T14:39:31.735Z] 	at kotlinx.coroutines.test.internal.TestMainDispatcher.resetDispatcher(TestMainDispatcher.kt:40)
[task 2022-06-11T14:39:31.735Z] 	at kotlinx.coroutines.test.TestDispatchers.resetMain(TestDispatchers.kt:37)
[task 2022-06-11T14:39:31.735Z] 	at mozilla.components.support.test.rule.MainCoroutineRule.finished(MainCoroutineRule.kt:54)
[task 2022-06-11T14:39:31.735Z] 	at org.junit.rules.TestWatcher.finishedQuietly(TestWatcher.java:117)
[task 2022-06-11T14:39:31.735Z] 	at org.junit.rules.TestWatcher.access$400(TestWatcher.java:46)
[task 2022-06-11T14:39:31.735Z] 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:64)
[task 2022-06-11T14:39:31.735Z] 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[task 2022-06-11T14:39:31.735Z] 	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:591)
[task 2022-06-11T14:39:31.735Z] 	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:274)
[task 2022-06-11T14:39:31.735Z] 	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:88)
[task 2022-06-11T14:39:31.735Z] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[task 2022-06-11T14:39:31.735Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[task 2022-06-11T14:39:31.735Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[task 2022-06-11T14:39:31.735Z] 	at java.base/java.lang.Thread.run(Thread.java:829)
[task 2022-06-11T14:39:31.735Z] 	Suppressed: org.robolectric.android.internal.AndroidTestEnvironment$UnExecutedRunnablesException: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(Looper.getMainLooper()).idle() call.
```
### Build: 
https://github.com/mozilla-mobile/android-components/commit/809abce10077ebe30bc40be6028ad96d5dccd956

**Comment by jonalmeida** [comment]
@Archaeopteryx if you see this happening again, could you comment in https://github.com/mozilla-mobile/android-components/issues/12230 which is linked to the speculative fix for these kinds of bugs?
