### ISSUE TITLE
Intermittent UI test failure - < BaselinePingTest. validateBaselinePing >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/android-components#12594]
### Stacktrace:
java.lang.AssertionError: Assertion failed
	at mozilla.telemetry.glean.GleanInternalAPI.afterInitialize$glean_release(Glean.kt:475)
	at mozilla.telemetry.glean.GleanInternalAPI.testSetLocalEndpoint$glean_release(Glean.kt:499)
	at mozilla.telemetry.glean.testing.GleanTestLocalServer.starting(GleanTestLocalServer.kt:46)
	at org.junit.rules.TestWatcher.startingQuietly(TestWatcher.java:108)
	at org.junit.rules.TestWatcher.access$000(TestWatcher.java:46)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:53)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:162)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:444)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
    
### Build: Failed 1x on 8/2 **Pixel 3, API Level 28**

cc @badboy

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21195)

**Comment by AaronMT** [comment]
Occurred in https://github.com/mozilla-mobile/android-components/pull/12619 @ https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/bd4rSpsyTv2yffOhf9Wj1w/runs/0/artifacts/public/logs/live_backing.log

(@badboy)

**Comment by AndiAJ** [comment]
Failed 1x on 8/15 [Firebase link](https://console.firebase.google.com/u/0/project/moz-android-components-230120/testlab/histories/bh.acacddb44ee28c64/matrices/8488878266920440058/executions/bs.d15a38d6ab5339e3/testcases/1)

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String okhttp3.mockwebserver.RecordedRequest.getPath()' on a null object reference
	at org.mozilla.samples.glean.pings.BaselinePingTest.waitForPingContent(BaselinePingTest.kt:92)
	at org.mozilla.samples.glean.pings.BaselinePingTest.waitForPingContent$default(BaselinePingTest.kt:83)
	at org.mozilla.samples.glean.pings.BaselinePingTest.validateBaselinePing(BaselinePingTest.kt:125)

**Comment by csadilek** [comment]
This isn't new. Duping to https://github.com/mozilla-mobile/android-components/issues/11340.
