### ISSUE TITLE
SDK upgrade breaks decision task

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1337]
In a case where the Android plugin updates the SDK it prints something to stdout, e.g. from debugging the SDK 28 update PR:

```
Checking the license for package Android SDK Platform 28 in /build/android-sdk/licenses
License for package Android SDK Platform 28 accepted.
Preparing "Install Android SDK Platform 28 (revision: 6)".
"Install Android SDK Platform 28 (revision: 6)" ready.
Installing Android SDK Platform 28 in /build/android-sdk/platforms/android-28
"Install Android SDK Platform 28 (revision: 6)" complete.
"Install Android SDK Platform 28 (revision: 6)" finished.
```

This breaks our decision tasks: https://tools.taskcluster.net/groups/BXVk92rmTyi1HRPPN4CrUg/tasks/BXVk92rmTyi1HRPPN4CrUg/runs/0/logs/public%2Flogs%2Flive.log

```
+ python automation/taskcluster/decision_task.py
Traceback (most recent call last):
  File "automation/taskcluster/decision_task.py", line 119, in <module>
    modules = [':' + artifact['name'] for artifact in lib.module_definitions.from_gradle()]
  File "/build/android-components/automation/taskcluster/lib/module_definitions.py", line 18, in from_gradle
    gradle_modules = json.loads(output)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

```

**Comment by pocmo** [comment]
CC @mitchhentges @JohanLorenzo @MihaiTabara

**Comment by pocmo** [comment]
This specific output should go away after updating the Docker image and when Gradle doesn't need to update the SDK on task run anymore. However this may come back in one form or another.

**Comment by mitchhentges** [comment]
Hmm, I'm surprised that `--quiet` doesn't have Gradle suppress children output.
I'll provide a PR to delineate the `printModules` JSON line

**Comment by MihaiTabara** [comment]
Tackled by @mitchhentges within https://github.com/mozilla-mobile/android-components/pull/1359
