### ISSUE TITLE
(GeckoEngineSession$createNavigationDelegate) IllegalArgumentException: Parameter specified as non-null is null

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1383]
From the reference browser: https://github.com/mozilla-mobile/reference-browser/issues/193

```
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter uri
    at mozilla.components.browser.engine.gecko.GeckoEngineSession$createNavigationDelegate$1.onLoadError
    at org.mozilla.geckoview.GeckoSession$2.handleMessage(GeckoSession.java:345)
    at org.mozilla.geckoview.GeckoSession$2.handleMessage(GeckoSession.java:176)
    at org.mozilla.geckoview.GeckoSessionHandler.handleMessage(GeckoSessionHandler.java:79)
    at org.mozilla.gecko.EventDispatcher$3.run(EventDispatcher.java:356)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6680)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by csadilek** [comment]
This crash is caused by our logic to process `ACTION_SEND` intents.

When we're processing a share intent, we check whether or not the shared text is a URL. If it is, we load it, otherwise we trigger a search. There are a bunch of issues with our implementation for this:

- When we trigger a search, we create a session with the initial URL set to the shared text which is causing the crash. It's an invalid URL and the subsequent `onLoadError` will get a null `uri` passed.

- We could fix this and set the URL to `about:blank` until the search loads, but that wouldn't work because of this bug in GeckoView: https://bugzilla.mozilla.org/show_bug.cgi?id=1441059. We'd end up with `about:blank`, not the search URL. So, we need to look into providing a way to directly trigger a search on a new tab/new session. We need a separate use case implementation for this so we don't have to create a new session with a temporary URL and then immediately trigger the search use case on it. Basically, we need to avoid the two quick calls to `loadUri`.

- Once we fixed that, we might still see this error as apps might have persisted the session with this invalid state. So, we have to make `uri` in `onLoadError` nullable if we care about this.

- Finally, instead of just checking if the text is a URL we should check it contains a URL, and use the first one. This would be consistent with the behaviour in Fennec. We can do this later as a follow-up though.
