### ISSUE TITLE
Can't open places db on API22-23: org.mozilla.places.InvalidPlaceInfo: Error executing SQL: unable to open database file

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#1420]
Saw this w/ reference browser initial, but it reproduces in the `sample-browser` in API22 emulator.
https://github.com/mozilla-mobile/reference-browser/issues/253
```
E/AndroidRuntime( 5162): org.mozilla.places.InvalidPlaceInfo: Error executing SQL: unable to open database file
E/AndroidRuntime( 5162): 	at org.mozilla.places.RustError.intoException(RustError.kt:51)
E/AndroidRuntime( 5162): 	at org.mozilla.places.PlacesConnection.<init>(PlacesConnection.kt:318)
E/AndroidRuntime( 5162): 	at mozilla.components.browser.storage.sync.RustPlacesConnection.init(Connection.kt:23)
E/AndroidRuntime( 5162): 	at mozilla.components.browser.storage.sync.PlacesHistoryStorage$places$2.invoke(PlacesHistoryStorage.kt:31)
E/AndroidRuntime( 5162): 	at mozilla.components.browser.storage.sync.PlacesHistoryStorage$places$2.invoke(PlacesHistoryStorage.kt:26)
E/AndroidRuntime( 5162): 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
E/AndroidRuntime( 5162): 	at mozilla.components.browser.storage.sync.PlacesHistoryStorage.getPlaces$browser_storage_sync_debug(PlacesHistoryStorage.kt)
E/AndroidRuntime( 5162): 	at mozilla.components.browser.storage.sync.PlacesHistoryStorage$recordObservation$2.invokeSuspend(PlacesHistoryStorage.kt:44)
E/AndroidRuntime( 5162): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
E/AndroidRuntime( 5162): 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
E/AndroidRuntime( 5162): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
E/AndroidRuntime( 5162): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
E/AndroidRuntime( 5162): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
```

**Comment by grigoryk** [comment]
This starts to work if instead of using `getDatabasePath` we're relying on `getFilesDir` and asking for a file within that. Perhaps `databases` dir doesn't exist on older API versions, or we can't create it while opening a file within it, or...?

**Comment by grigoryk** [comment]
Patch in #1421.
