### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: InMemoryHistoryStorage.getSuggestions()

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1506]
I was adding the AwesomeBar to the sample browser but with the `InMemoryHistoryStorage` implementation added I get the following exception:

```
E  Process: org.mozilla.samples.browser, PID: 26397
E  java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
E      at mozilla.components.browser.storage.memory.InMemoryHistoryStorage.levenshteinDistance(InMemoryHistoryStorage.kt:112)
E      at mozilla.components.browser.storage.memory.InMemoryHistoryStorage.access$levenshteinDistance(InMemoryHistoryStorage.kt:27)
E      at mozilla.components.browser.storage.memory.InMemoryHistoryStorage$getSuggestions$$inlined$synchronized$lambda$2.invoke(InMemoryHistoryStorage.kt:75
)
E      at mozilla.components.browser.storage.memory.InMemoryHistoryStorage$getSuggestions$$inlined$synchronized$lambda$2.invoke(InMemoryHistoryStorage.kt:27
)
E      at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:174)
E      at kotlin.sequences.FlatteningSequence$iterator$1.next(Sequences.kt:263)
E      at mozilla.components.browser.storage.memory.InMemoryHistoryStorage.getSuggestions(InMemoryHistoryStorage.kt:141)
E      at mozilla.components.feature.awesomebar.provider.HistoryStorageSuggestionProvider.onInputChanged(HistoryStorageSuggestionProvider.kt:27)
E      at mozilla.components.browser.awesomebar.BrowserAwesomeBar$onInputChanged$1$invokeSuspend$$inlined$forEach$lambda$1$1.invokeSuspend(BrowserAwesomeBar
.kt:75)
E      at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
E      at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
E      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
E      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
E      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
E      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
E      at java.lang.Thread.run(Thread.java:818)    
```

For now I'll just add the awesomebar without history.

**Comment by pocmo** [comment]
cc @grigoryk

**Comment by grigoryk** [comment]
Do you know what inputs might have triggered this?

**Comment by pocmo** [comment]
When ignoring all `about` URLs I get the original error back.

`levenshteinDistance` gets called with:

```
levenshteinDistance(
"Internet for people, not profit — Mozilla"
"https://m.huffingtonpost.de/entry/russland-affare-trumps-ex-anwalt-gesteht-luge-uber-brisantes-immobiliengeschaft_de_5bfff959e4b027f1097b49af?r9h&utm_hp_ref=de-homepage)"
```

**Comment by pocmo** [comment]
In my case I have two tabs, one pointing to mozilla and one pointing to the page above. the huffington post article is selected.

**Comment by grigoryk** [comment]
Found the problem - the algorithm wasn't dealing with empty strings correctly. It'd crash when encountering an empty title. Patch incoming.
