### ISSUE TITLE
Crash when pasting emoji in URL bar

### ISSUE THREAD

**Issue by agi90** [mozilla-mobile/android-components#2067]
I get a crash when I try to paste an emoji into the URL bar.

STR

- Load `about:blank`
- Paste emoji after `about:blank` (e.g. "🧶", which on my phone does not have a glyph for BTW)
- Observe crash

I can only reproduce this with some emojis not all.

Phone: Samsung S7
Reference Browser Version: 1.0.1907 (latest at time of writing)

```
 AndroidRuntime: FATAL EXCEPTION: pool-4-thread-3
E AndroidRuntime: Process: org.mozilla.reference.browser, PID: 19670
E AndroidRuntime: org.mozilla.places.PlacesException: Error executing SQL: non-punycode host provided to reverse_host!
E AndroidRuntime:   at org.mozilla.places.RustError.intoException(RustError.kt:57)
E AndroidRuntime:   at org.mozilla.places.PlacesConnection.queryAutocomplete(PlacesConnection.kt:355)
E AndroidRuntime:   at mozilla.components.browser.storage.sync.PlacesHistoryStorage.getSuggestions(PlacesHistoryStorage.kt:86)
E AndroidRuntime:   at mozilla.components.feature.awesomebar.provider.HistoryStorageSuggestionProvider.onInputChanged(HistoryStorageSuggestionProvider.kt:27)
E AndroidRuntime:   at mozilla.components.browser.awesomebar.BrowserAwesomeBar$onInputChanged$1$invokeSuspend$$inlined$forEach$lambda$1$1.invokeSuspend(BrowserAwesomeBar.kt:96)
E AndroidRuntime:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
E AndroidRuntime:   at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
E AndroidRuntime:   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
E AndroidRuntime:   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
E AndroidRuntime:   at java.lang.Thread.run(Thread.java:764)
```

**Comment by jonalmeida** [comment]
The 'ball of yarn' emoji isn't in older versions of Android that don't include some form of EmojiCompat library which is why they aren't visible either.

**Comment by agi90** [comment]
Just verified this is fixed now. Looks like https://github.com/mozilla-mobile/reference-browser/issues/602 did it.
