### ISSUE TITLE
WebRequestError when performing request without connectivity

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#2086]
Fenix: https://github.com/mozilla-mobile/fenix/issues/520

```
 E  Process: org.mozilla.fenix, PID: 8203
 E  org.mozilla.geckoview.WebRequestError: Request failed, error=37, category=5
 E      at org.mozilla.gecko.mozglue.GeckoLoader.nativeRun(Native Method)
 E      at org.mozilla.gecko.GeckoThread.run(GeckoThread.java:81)
```

Happens when the device has no connectivity (e.g. airplane mode) and we perform a request with `GeckoViewFetchClient`.

**Comment by pocmo** [comment]
In Sentry:
* Reference Browser: https://sentry.prod.mozaws.net/operations/reference-browser/issues/5222705
* Fenix: https://sentry.prod.mozaws.net/operations/fenix/issues/5221573
