### ISSUE TITLE
Broken snapshots builds

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#2442]
Snapshot builds are currently not working. See logs in https://tools.taskcluster.net/groups/SC6-9TLfShW9tQFJ1BiGew/tasks/SC6-9TLfShW9tQFJ1BiGew/runs/0/logs/public%2Flogs%2Flive.log

cc @JohanLorenzo @pocmo

**Comment by pocmo** [comment]
```
+ python automation/taskcluster/schedule_snapshot_release.py
Traceback (most recent call last):
  File "automation/taskcluster/schedule_snapshot_release.py", line 93, in <module>
    schedule()
  File "automation/taskcluster/schedule_snapshot_release.py", line 87, in schedule
    decision_task_id, decision_task = make_decision_task(params)
  File "automation/taskcluster/schedule_snapshot_release.py", line 68, in make_decision_task
    rendered = jsone.render(taskcluster_yml, context)
  File "/usr/local/lib/python2.7/dist-packages/jsone/__init__.py", line 18, in render
    rv = renderValue(template, full_context)
  File "/usr/local/lib/python2.7/dist-packages/jsone/render.py", line 345, in renderValue
    return dict(updated())
  File "/usr/local/lib/python2.7/dist-packages/jsone/render.py", line 336, in updated
    v = renderValue(v, context)
  File "/usr/local/lib/python2.7/dist-packages/jsone/render.py", line 323, in renderValue
    return operators[matches[0]](template, context)
  File "/usr/local/lib/python2.7/dist-packages/jsone/render.py", line 158, in let
    subcontext[k] = renderValue(v, context)
  File "/usr/local/lib/python2.7/dist-packages/jsone/render.py", line 323, in renderValue
    return operators[matches[0]](template, context)
  File "/usr/local/lib/python2.7/dist-packages/jsone/render.py", line 138, in ifConstruct
    return renderValue(rv, context)
  File "/usr/local/lib/python2.7/dist-packages/jsone/render.py", line 316, in renderValue
    return interpolate(template, context)
  File "/usr/local/lib/python2.7/dist-packages/jsone/render.py", line 42, in interpolate
    parsed, offset = evaluator.parseUntilTerminator(string, '}')
  File "/usr/local/lib/python2.7/dist-packages/jsone/prattparser.py", line 100, in parseUntilTerminator
    result = pc.parse()
  File "/usr/local/lib/python2.7/dist-packages/jsone/prattparser.py", line 190, in parse
    left = parser.infix_rules[kind](parser, left, token, self)
  File "/usr/local/lib/python2.7/dist-packages/jsone/interpreter.py", line 185, in property_dot
    '{} not found in {}'.format(k, json.dumps(left)))
```
