### ISSUE TITLE
Crash @ org.mozilla.places.PlacesConnectionBusy: Error executing SQL: database is locked

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/android-components#2499]
org.mozilla.places.PlacesConnectionBusy: Error executing SQL: database is locked
    at org.mozilla.places.RustError.intoException(RustError.kt:6)
    at org.mozilla.places.WritablePlacesConnection.noteObservation(PlacesConnection.kt:7)
    at mozilla.components.browser.storage.sync.PlacesHistoryStorage$recordVisit$2.invoke(PlacesHistoryStorage.kt:17)
    at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:2)
    at kotlinx.coroutines.BuildersKt.withContext
    at mozilla.components.browser.storage.sync.PlacesHistoryStorage.recordVisit(PlacesHistoryStorage.kt:1)
    at mozilla.components.feature.session.HistoryDelegate.onVisited(HistoryDelegate.kt:3)
    at mozilla.components.browser.engine.gecko.GeckoEngineSession$createHistoryDelegate$1$onVisited$1.invokeSuspend(GeckoEngineSession.kt:5)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
    at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:13)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:1)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:42)

**Comment by pocmo** [comment]
@grigoryk Is that an error in our layer or something the AS team needs to look into?

**Comment by dholbert** [comment]
FWIW, I hit this a few times a day, when starting Fenix as my default browser when I click a link in another application. (Not sure if that method of launching is important, but it's typically what I've done when I hit this crash.)

**Comment by kbrosnan** [comment]
STR: from dholbert

* Sign into Sync
* Open links from external apps
* Repeat until crash

**Comment by dholbert** [comment]
Also notable: sync is apparently successful sometimes. About 10 minutes after my crash,  from a time when my phone was idle-ish, I see adb logging (for `sync15::sync` / `sync15::sync_multiple`) saying "Sync finished!" and "Sync of history was successful!"  And I do see Fenix saying "Last sync: 0 minutes ago" after this happens.

So I think this only happens when we try to do an opportunistic sync while we are also loading pages and modifying the places DB, or something.

**Comment by grigoryk** [comment]
Relevant A-S issue: https://github.com/mozilla/application-services/issues/829

**Comment by bifleming** [comment]
@pocmo It looks like the a-s work for this was completed awhile ago...is it still bocked?

**Comment by jdragojevic** [comment]
@bifleming @vesta0   - looking in Sentry for Fenix and fenix-nighly - I don't see any recent occurrances of this.  I don't know what may have changed it, but can that be confirmed and possibly reprioritized.

**Comment by bifleming** [comment]
A/S github issue: https://github.com/mozilla/application-services/issues/1230

**Comment by kbrosnan** [comment]
Agreed I don't see this signature in fenix release builds either. Thanks @jdragojevic for the follow up.
