### ISSUE TITLE
GeckoView crash on setSession

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#2935]
FxA sign in crashes right now (also in r-b and Fenix).

```
java.lang.NullPointerException: NullHandle
    at org.mozilla.geckoview.GeckoSession$Compositor.setFixedBottomOffset(Native Method)
    at org.mozilla.geckoview.GeckoDisplay.setVerticalClipping(GeckoDisplay.java:122)
    at org.mozilla.geckoview.GeckoView$Display.setVerticalClipping(GeckoView.java:180)
    at org.mozilla.geckoview.GeckoView$Display.acquire(GeckoView.java:114)
    at org.mozilla.geckoview.GeckoView.setSession(GeckoView.java:390)
    at org.mozilla.geckoview.GeckoView.setSession(GeckoView.java:353)
    at mozilla.components.browser.engine.gecko.GeckoEngineView.render(GeckoEngineView.kt:84)
    at mozilla.components.feature.session.EngineViewPresenter.renderSession$feature_session_release(EngineViewPresenter.kt:51)
    at mozilla.components.feature.session.EngineViewPresenter.onSessionSelected(EngineViewPresenter.kt:47)
    at mozilla.components.browser.session.LegacySessionManager$select$$inlined$synchronized$lambda$1.invoke(LegacySessionManager.kt:459)
    at mozilla.components.browser.session.LegacySessionManager$select$$inlined$synchronized$lambda$1.invoke(LegacySessionManager.kt:20)
    at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:99)
    at mozilla.components.browser.session.LegacySessionManager.notifyObservers(Unknown Source:7)
    at mozilla.components.browser.session.LegacySessionManager.select(LegacySessionManager.kt:459)
    at mozilla.components.browser.session.LegacySessionManager.addInternal(LegacySessionManager.kt:180)
    at mozilla.components.browser.session.LegacySessionManager.addInternal$default(LegacySessionManager.kt:148)
    at mozilla.components.browser.session.LegacySessionManager.add(LegacySessionManager.kt:138)
    at mozilla.components.browser.session.SessionManager.add(SessionManager.kt:79)
    at mozilla.components.browser.session.SessionManager.add$default(SessionManager.kt:77)
    at mozilla.components.feature.tabs.TabsUseCases$AddNewTabUseCase.invoke(TabsUseCases.kt:72)
    at mozilla.components.feature.tabs.TabsUseCases$AddNewTabUseCase.invoke(TabsUseCases.kt:54)

**Comment by cadeyrn** [comment]
Related (other STR, but same exception): https://github.com/mozilla-mobile/fenix/issues/2288

**Comment by csadilek** [comment]
@snorp we're seeing this new crash with the latest GV. Do you have an idea?

**Comment by csadilek** [comment]
Linking issue that introduced `setVerticalClipping`: https://bugzilla.mozilla.org/show_bug.cgi?id=1516048 and https://github.com/mozilla-mobile/android-components/issues/2675.

This problem occurs whenever we're trying to render / switch to a new gecko session on an existing GeckoView.

**Comment by csadilek** [comment]
Filed issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1549576

**Comment by csadilek** [comment]
Fixed by: https://github.com/mozilla-mobile/android-components/pull/2948
