### ISSUE TITLE
App crash when opening settings when logged in to FxA but with no network 

### ISSUE THREAD

**Issue by mhammond** [mozilla-mobile/android-components#3135]
STR:

* Ensure you are logged in an FxAccount in Fenix, then exit Fenix.
* Arrange for no network (eg, airplane mode)
* Start Fenix
* Open Settings

The app crashes. Logcat shows

```
2019-05-27 16:03:09.975 4835-4902/org.mozilla.fenix.debug D/fxaclient_ffi: fxa_ensure_capabilities
2019-05-27 16:03:09.979 4835-4902/org.mozilla.fenix.debug I/viaduct::backend: Using HTTP backend FFI (trusted)
2019-05-27 16:03:10.033 4835-4902/org.mozilla.fenix.debug E/viaduct::backend::ffi: Caught network error (presumably). Type: java.io.IOException, message: "org.mozilla.geckoview.WebRequestError: Request failed, error=0x25, category=0x5"
2019-05-27 16:03:10.033 4835-4902/org.mozilla.fenix.debug W/fxa_client::ffi: Network error: Error(
    
    Network error: Network error: java.io.IOException: "org.mozilla.geckoview.WebRequestError: Request failed, error=0x25, category=0x5")
2019-05-27 16:03:10.180 4835-4835/org.mozilla.fenix.debug I/mozac/CrashReporter: Received crash: UncaughtExceptionCrash(throwable=mozilla.appservices.fxaclient.FxaException$Network: Network error: Network error: java.io.IOException: "org.mozilla.geckoview.WebRequestError: Request failed, error=0x25, category=0x5")
2019-05-27 16:03:10.180 4835-4835/org.mozilla.fenix.debug I/mozac/CrashReporter: Showing prompt
2019-05-27 16:03:10.217 4835-4835/org.mozilla.fenix.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fenix.debug, PID: 4835
    mozilla.appservices.fxaclient.FxaException$Network: Network error: Network error: java.io.IOException: "org.mozilla.geckoview.WebRequestError: Request failed, error=0x25, category=0x5"
        at mozilla.appservices.fxaclient.rust.RustError.intoException(RustError.kt:43)
        at mozilla.appservices.fxaclient.FirefoxAccount.ensureCapabilities(FirefoxAccount.kt:717)
        at mozilla.components.service.fxa.FxaDeviceConstellation$ensureCapabilitiesAsync$1.invokeSuspend(FxaDeviceConstellation.kt:88)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
2019-05-27 16:03:10.228 4835-4835/org.mozilla.fenix.debug I/Process: Sending signal. PID: 4835 SIG: 9
```

See also https://github.com/mozilla/application-services/issues/1096 and https://sentry.prod.mozaws.net/operations/fenix/issues/5810945/?query=is:unresolved%20http%20status, both of which are different sides of the same coin.

**Comment by anandsingh2903** [comment]
I would like to work on this issue.

**Comment by grigoryk** [comment]
This _should_ be fixed by https://github.com/mozilla-mobile/android-components/pull/3093

**Comment by grigoryk** [comment]
... and it is addressed by that PR, as far as i can tell, thanks to all the error handling (STRs no longer reproduce).

**Comment by mhammond** [comment]
Thanks Grisha - I'll file any further issues I find after that lands.
