### ISSUE TITLE
TypeCastException in QrFragment: null cannot be cast to non-null type kotlin.String

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#3221]
Sentry: https://sentry.prod.mozaws.net/operations/fenix/issues/5874872/

```
kotlin.TypeCastException: null cannot be cast to non-null type kotlin.String
    at mozilla.components.feature.qr.QrFragment.openCamera$feature_qr_release(QrFragment.kt:34)
    at mozilla.components.feature.qr.QrFragment$surfaceTextureListener$1.onSurfaceTextureAvailable(QrFragment.kt:1)
    at android.view.TextureView.getHardwareLayer(TextureView.java:493)
    at android.view.View.updateDisplayListIfDirty(View.java:15345)
    at android.view.View.draw(View.java:16142)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
    at android.view.View.draw(View.java:16375)
    at android.view.View.updateDisplayListIfDirty(View.java:15368)
    at android.view.View.draw(View.java:16142)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
    at android.view.View.updateDisplayListIfDirty(View.java:15363)
    at android.view.View.draw(View.java:16142)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
    at android.view.View.updateDisplayListIfDirty(View.java:15363)
    at android.view.View.draw(View.java:16142)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
    at android.view.View.updateDisplayListIfDirty(View.java:15363)
    at android.view.View.draw(View.java:16142)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
    at android.view.View.updateDisplayListIfDirty(View.java:15363)
    at android.view.View.draw(View.java:16142)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
    at android.view.View.updateDisplayListIfDirty(View.java:15363)
    at android.view.View.draw(View.java:16142)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
    at android.view.View.updateDisplayListIfDirty(View.java:15363)
    at android.view.View.draw(View.java:16142)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
    at android.view.View.updateDisplayListIfDirty(View.java:15363)
    at android.view.View.draw(View.java:16142)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
    at android.view.View.updateDisplayListIfDirty(View.java:15363)
    at android.view.View.draw(View.java:16142)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
    at android.view.View.draw(View.java:16375)
    at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2691)
    at android.view.View.updateDisplayListIfDirty(View.java:15368)
    at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
    at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
    at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
    at android.view.ViewRootImpl.draw(ViewRootImpl.java:2708)
    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2504)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2135)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1175)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6163)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
    at android.view.Choreographer.doCallbacks(Choreographer.java:670)
    at android.view.Choreographer.doFrame(Choreographer.java:606)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
    at android.os.Handler.handleCallback(Handler.java:743)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5438)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:772)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:662)
```

**Comment by csadilek** [comment]
This crash only happens on devices that don't have a camera like the Nova Pro ebook reader. We should provide a better exception/error message in this case. Applications should deactivate the QR scanning functionality when there's no camera support.
