### ISSUE TITLE
FxA pairing fails in sample app

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#3250]
```
2019-06-04 13:40:52.049 14468-14571/org.mozilla.samples.fxa E/FirefoxAccount: Error while running: begin oauth pairing flow
    mozilla.appservices.fxaclient.FxaException$Unspecified: Origin mismatch
        at mozilla.appservices.fxaclient.rust.RustError.intoException(RustError.kt:48)
        at mozilla.appservices.fxaclient.FirefoxAccount.beginPairingFlow(FirefoxAccount.kt:525)
        at mozilla.components.service.fxa.FirefoxAccount$beginPairingFlowAsync$1$2.invoke(FirefoxAccount.kt:120)
        at mozilla.components.service.fxa.FirefoxAccount$beginPairingFlowAsync$1$2.invoke(FirefoxAccount.kt:28)
        at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:30)
        at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:56)
        at mozilla.components.service.fxa.FirefoxAccount$beginPairingFlowAsync$1.invokeSuspend(FirefoxAccount.kt:119)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
```

**Comment by vladikoff** [comment]
@vladikoff will fix it
