### ISSUE TITLE
[Tests] Increase stability for `service-glean` unit tests.

### ISSUE THREAD

**Issue by dector** [mozilla-mobile/android-components#3332]
`EventsStorageEngineTest -> getSnapshot() correctly clears the stores`. Issue seems related to multi-threading in coroutines.

<details><summary>Log</summary>

```

SUITE: mozilla.components.service.glean.storages.EventsStorageEngineTest
  TEST: getSnapshot() correctly clears the stores
    [Robolectric] mozilla.components.service.glean.storages.EventsStorageEngineTest.getSnapshot() correctly clears the stores: sdk=28; resources=legacy
    [Robolectric] NOTICE: legacy resources mode is deprecated; see http://robolectric.org/migrating/#migrating-to-40
    I/AssetManager: no overlays.list file found
    I/MonitoringInstr: Instrumentation started!
    I/MonitoringInstr: Setting context classloader to 'org.robolectric.internal.bytecode.SandboxClassLoader@dcf23f6', Original: 'org.robolectric.internal.bytecode.SandboxClassLoader@dcf23f6'
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 1
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 1
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 0
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 0
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 0
    I [glean/Glean] Metrics enabled: true
    I [glean/Glean] Registering pings for mozilla.components.service.glean.GleanMetrics.Pings
    I [glean/MetricsPingScheduler] The 'metrics' collection scheduled for the next calendar day
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 0
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 0
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 1
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 0
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 1
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 1
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 0
    W/SQLiteConnectionPool: A SQLiteConnection object for database ':memory:' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
    W/SQLiteConnectionPool: A SQLiteConnection object for database ':memory:' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
    W/SQLiteConnectionPool: A SQLiteConnection object for database ':memory:' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 0
  FAILURE

java.lang.AssertionError: expected:<1> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at mozilla.components.service.glean.storages.EventsStorageEngineTest.getSnapshot() correctly clears the stores(EventsStorageEngineTest.kt:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:601)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:260)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.GeneratedMethodAccessor97.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
	at sun.reflect.GeneratedMethodAccessor96.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
```

</details>

**Comment by pocmo** [comment]
Is that different than #3258 or #3237? If you have any taskcluster links of failed builds, please post them here! :)

**Comment by dector** [comment]
Yup, I've got new error. Attached log to the issue, thanks. :)

**Comment by pocmo** [comment]
CC @Dexterp37 @mdboom @travis79

**Comment by travis79** [comment]
Squashing these as fast as we can 👍

**Comment by travis79** [comment]
Most of these we are finding popped up after WorkManager dependency was updated to 2.0.x (and it subsequently started running things in tests like its docs say it should)

**Comment by Dexterp37** [comment]
This is no longer relevant, since glean test was moved to the glean repo :) (and the source of the problem was fixed!)
