### ISSUE TITLE
WorkManagerSyncWorker.doWork: KotlinNullPointerException

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#3607]
Just randomly saw that in Reference Browser while reading the log:

```
       WM-WorkerWrapper  E  Work [ id=4d963972-98bb-4405-966f-4dade94ed3d6, tags={ Immediate, mozilla.components.feature.sync.WorkManagerSyncWorker, Common } ] failed because it threw
                             an exception/error
                         E  java.util.concurrent.ExecutionException: kotlin.KotlinNullPointerException
                         E      at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:516)
                         E      at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
                         E      at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:290)
                         E      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                         E      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                         E      at java.lang.Thread.run(Thread.java:919)
                         E  Caused by: kotlin.KotlinNullPointerException
                         E      at mozilla.components.feature.sync.WorkManagerSyncWorker.doWork(WorkManagerSyncDispatcher.kt:223)
                         E      at androidx.work.CoroutineWorker$startWork$1.invokeSuspend(CoroutineWorker.kt:66)
                         E      at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                         E      at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
                         E      at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
                         E      at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
                         E      at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2950)

**Comment by jonalmeida** [comment]
Reference Browser never crashes (any more). 😎
