### ISSUE TITLE
IllegalArgumentExceptionorg: Shortcut must have a non-empty label

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#3782]
```
java.lang.IllegalArgumentException: Shortcut must have a non-empty label
    at androidx.core.content.pm.ShortcutInfoCompat$Builder.build(ShortcutInfoCompat.java:303)
    at mozilla.components.feature.pwa.WebAppShortcutManager.buildBasicShortcut(WebAppShortcutManager.kt:75)
    at mozilla.components.feature.pwa.WebAppShortcutManager.requestPinShortcut(WebAppShortcutManager.kt:34)
    at mozilla.components.feature.pwa.WebAppUseCases$AddToHomescreenUseCase.invoke(WebAppUseCases.kt:39)
    at org.mozilla.reference.browser.browser.ToolbarIntegration$menuItems$2$6$1.invokeSuspend(ToolbarIntegration.kt:92)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:217)
    at android.app.ActivityThread.main(ActivityThread.java:7387)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:500)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:865)
```

Reference Browser: https://github.com/mozilla-mobile/reference-browser/issues/834

**Comment by pocmo** [comment]
CC @NotWoods

**Comment by NotWoods** [comment]
Caused by `session.title` being an empty string. We'll need to add a default label.
