### ISSUE TITLE
Receiving a tab with a backgrounded app throws IllegalStateException

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#3827]
```
2019-07-18 22:20:55.196 org.mozilla.fenix.debug E/AndroidRuntime: FATAL EXCEPTION: Firebase-FirebasePush
    Process: org.mozilla.fenix.debug, PID: 23170
    java.lang.IllegalStateException: You need to call initialize() on your Push instance from Application.onCreate().
        at mozilla.components.concept.push.PushProcessor$Companion.getRequireInstance(PushProcessor.kt:59)
        at mozilla.components.lib.push.firebase.AbstractFirebasePushService.onMessageReceived(AbstractFirebasePushService.kt:46)
        at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:60)
        at com.google.firebase.iid.zzg.run(Unknown Source:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
        at java.lang.Thread.run(Thread.java:764)
```

This is was sort of intentional, but maybe when our instance isn't available we should create it? That would also remove the need to call `install` then.

**Comment by jonalmeida** [comment]
Closing as won't fix. My patch in Fenix had an error that caused this.
