### ISSUE TITLE
GeckoViewFetchClient: IOException: Request failed.

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#3900]
```
org.mozilla.geckoview.WebRequestError: Request failed, error=0x33, category=0x3
    at org.mozilla.gecko.mozglue.GeckoLoader.nativeRun(GeckoLoader.java)
    at org.mozilla.gecko.GeckoThread.run(GeckoThread.java:476)

java.io.IOException: org.mozilla.geckoview.WebRequestError: Request failed, error=0x33, category=0x3
    at mozilla.components.browser.engine.gecko.fetch.GeckoViewFetchClient.fetch(GeckoViewFetchClient.kt:62)
    at mozilla.components.feature.downloads.AbstractFetchDownloadService$performDownload$2.invokeSuspend(AbstractFetchDownloadService.kt:88)
    at mozilla.components.feature.downloads.AbstractFetchDownloadService$performDownload$2.invoke
    at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
    at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:155)
    at kotlinx.coroutines.BuildersKt.withContext
    at mozilla.components.feature.downloads.AbstractFetchDownloadService.performDownload(AbstractFetchDownloadService.kt:77)
    at mozilla.components.feature.downloads.AbstractFetchDownloadService.onStartCommand$feature_downloads_release$suspendImpl(AbstractFetchDownloadService.kt:71)
    at mozilla.components.feature.downloads.AbstractFetchDownloadService.onStartCommand$feature_downloads_release
    at mozilla.components.feature.downloads.CoroutineService$onStartCommand$job$1.invokeSuspend(CoroutineService.kt:46)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
```

From Reference Browser:
https://github.com/mozilla-mobile/reference-browser/issues/847

**Comment by pocmo** [comment]
CC @NotWoods
