### ISSUE TITLE
Intermittent test failure in MetricsPingSchedulerTest

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#3965]
This test has been having intermittent failures in some CI builds:
```
  TEST: startupCheck must immediately collect if the ping is overdue for today
    [Robolectric] mozilla.components.service.glean.scheduler.MetricsPingSchedulerTest.startupCheck must immediately collect if the ping is overdue for today: sdk=28; resources=legacy
    [Robolectric] NOTICE: legacy resources mode is deprecated; see http://robolectric.org/migrating/#migrating-to-40
    E/ROOM: Cannot run invalidation tracker. Is the db closed?
    java.lang.IllegalStateException: Illegal connection pointer 68. Current pointers for thread Thread[arch_disk_io_1,5,main] []
    at org.robolectric.shadows.ShadowSQLiteConnection$Connections.getConnection(ShadowSQLiteConnection.java:367)
    at org.robolectric.shadows.ShadowSQLiteConnection$Connections.prepareStatement(ShadowSQLiteConnection.java:416)
    at org.robolectric.shadows.ShadowSQLiteConnection.nativePrepareStatement(ShadowSQLiteConnection.java:89)
    at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
    at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:903)
    at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:562)
    at android.database.sqlite.SQLiteSession.endTransactionUnchecked(SQLiteSession.java:439)
    at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:401)
    at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:566)
    at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.endTransaction(FrameworkSQLiteDatabase.java:90)
    at androidx.room.InvalidationTracker$1.run(InvalidationTracker.java:337)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
    I/AssetManager: no overlays.list file found
    I/MonitoringInstr: Instrumentation started!
    I/MonitoringInstr: Setting context classloader to 'org.robolectric.internal.bytecode.SandboxClassLoader@7e95f285', Original: 'org.robolectric.internal.bytecode.SandboxClassLoader@7e95f285'
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 1
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 1
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 0
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 0
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 0
    D [glean/MetricsPingScheduler] The 'metrics' ping was last sent on Sun Jul 05 18:36:00 GMT 2015
    I [glean/MetricsPingScheduler] The 'metrics' ping is scheduled for immediate collection, Sat Jul 11 07:00:00 GMT 2015
    I [glean/Dispatchers] Task queued for execution in test mode
  FAILURE
```

TC build logs: https://tools.taskcluster.net/groups/SbEzugB_TE-DFacB-3yLnw/tasks/DntCQRdLRA6ar1GVCLYlNg/runs/0/logs/public%2Flogs%2Flive.log

cc: @travis79

**Comment by travis79** [comment]
We are tracking this particular intermittent test failure in Bugzilla [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1570589).

**Comment by travis79** [comment]
Closing this since we haven't seen this for a while and the [Bugzilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1570589) we have been using to track this has been closed as WONTFIX.
