### ISSUE TITLE
MediaService: Did not call startForeground().

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#4172]
Fenix: https://github.com/mozilla-mobile/fenix/issues/4853

```
RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{df2820b u0 org.mozilla.fenix/mozilla.components.feature.media.service.MediaService}
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1872)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7050)
    at java.lang.reflect.Method.invoke(Method.java)
...
(2 additional frame(s) were not displayed)

Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{df2820b u0 org.mozilla.fenix/mozilla.components.feature.media.service.MediaService}
```

**Comment by pocmo** [comment]
Sentry: https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6158109/

**Comment by pocmo** [comment]
I was able to see this once when playing a video on leparisien.fr

**Comment by pocmo** [comment]
Filtered log:

```
MediaStateMachine  I  Transitioning from MediaState.None to Playing(session=Session(420fff9f-b206-419e-bef9-b0cfb5d7aa8c, http://www.leparisien.fr/vid
                            eo/arnaque-en-croatie-la-villa-etait-un-terrain-vague-20-08-2019-8136603.php), media=[Media(PLAY)])
           MediaService  D  Service created
                         D  Command received
             AudioFocus  D  processAudioFocusResult(1)
      MediaStateMachine  I  Transitioning from Playing(session=Session(420fff9f-b206-419e-bef9-b0cfb5d7aa8c, http://www.leparisien.fr/video/arnaque-en-croat
                            ie-la-villa-etait-un-terrain-vague-20-08-2019-8136603.php), media=[Media(PLAY)]) to Playing(session=Session(420fff9f-b206-419e-b
                            ef9-b0cfb5d7aa8c, http://www.leparisien.fr/video/arnaque-en-croatie-la-villa-etait-un-terrain-vague-20-08-2019-8136603.php), med
                            ia=[Media(PLAY), Media(PLAY)])
           MediaService  D  Command received
             AudioFocus  D  processAudioFocusResult(1)
      MediaStateMachine  I  Transitioning from Playing(session=Session(420fff9f-b206-419e-bef9-b0cfb5d7aa8c, http://www.leparisien.fr/video/arnaque-en-croat
                            ie-la-villa-etait-un-terrain-vague-20-08-2019-8136603.php), media=[Media(WAITING), Media(PAUSE)]) to Playing(session=Session(420
                            fff9f-b206-419e-bef9-b0cfb5d7aa8c, http://www.leparisien.fr/video/arnaque-en-croatie-la-villa-etait-un-terrain-vague-20-08-2019-
                            8136603.php), media=[Media(WAITING)])
           MediaService  D  Command received
             AudioFocus  D  processAudioFocusResult(1)
      MediaStateMachine  I  Transitioning from Playing(session=Session(420fff9f-b206-419e-bef9-b0cfb5d7aa8c, http://www.leparisien.fr/video/arnaque-en-croat
                            ie-la-villa-etait-un-terrain-vague-20-08-2019-8136603.php), media=[Media(PAUSE)]) to Paused(session=Session(420fff9f-b206-419e-b
                            ef9-b0cfb5d7aa8c, http://www.leparisien.fr/video/arnaque-en-croatie-la-villa-etait-un-terrain-vague-20-08-2019-8136603.php), med
                            ia=[Media(PAUSE), Media(PAUSE)])
           MediaService  D  Command received
      MediaStateMachine  I  Transitioning from Paused(session=Session(420fff9f-b206-419e-bef9-b0cfb5d7aa8c, http://www.leparisien.fr/video/arnaque-en-croati
                            e-la-villa-etait-un-terrain-vague-20-08-2019-8136603.php), media=[Media(ENDED), Media(PAUSE)]) to Paused(session=Session(420fff9
                            f-b206-419e-bef9-b0cfb5d7aa8c, http://www.leparisien.fr/video/arnaque-en-croatie-la-villa-etait-un-terrain-vague-20-08-2019-8136
                            603.php), media=[Media(PAUSE)])
           MediaService  D  Command received
      MediaStateMachine  I  Transitioning from Paused(session=Session(420fff9f-b206-419e-bef9-b0cfb5d7aa8c, http://www.leparisien.fr/video/arnaque-en-croati
                            e-la-villa-etait-un-terrain-vague-20-08-2019-8136603.php), media=[Media(PAUSE)]) to Playing(session=Session(420fff9f-b206-419e-b
                            ef9-b0cfb5d7aa8c, http://www.leparisien.fr/video/arnaque-en-croatie-la-villa-etait-un-terrain-vague-20-08-2019-8136603.php), med
                            ia=[Media(PLAY)])
         AndroidRuntime  D  Shutting down VM
                         E  FATAL EXCEPTION: main
                         E  Process: org.mozilla.samples.browser, PID: 10119
                         E  android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{
                            f84ab82 u0 org.mozilla.samples.browser/mozilla.components.feature.media.service.MediaService}
                         E      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1945)
                         E      at android.os.Handler.dispatchMessage(Handler.java:107)
                         E      at android.os.Looper.loop(Looper.java:214)
                         E      at android.app.ActivityThread.main(ActivityThread.java:7356)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by pocmo** [comment]
Now it happened very quickly:

```
MediaStateMachine  I  Transitioning from MediaState.None to Playing(session=Session(8ca60fa8-2cba-41ca-aeb7-ad22c335d9ec, http://www.leparisien.fr/vid
                      eo/rentree-ministerielle-connaissez-vous-vos-ministres-21-08-2019-8136792.php), media=[Media(state=PLAYING,playbackState=PLAY)])
     MediaService  D  Service created
                   D  Command received
       AudioFocus  D  processAudioFocusResult(1)
     MediaService  D  startForeground()

                      Process org.mozilla.samples.browser:media created for service {org.mozilla.samples.browser/org.mozilla.gecko.media.MediaManager
                      }
                      PID: 16408   UID:    GIDs:

MediaStateMachine  I  Transitioning from Playing(session=Session(8ca60fa8-2cba-41ca-aeb7-ad22c335d9ec, http://www.leparisien.fr/video/rentree-minister
                      ielle-connaissez-vous-vos-ministres-21-08-2019-8136792.php), media=[Media(state=PAUSED,playbackState=PAUSE)]) to Paused(session=
                      Session(8ca60fa8-2cba-41ca-aeb7-ad22c335d9ec, http://www.leparisien.fr/video/rentree-ministerielle-connaissez-vous-vos-ministres
                      -21-08-2019-8136792.php), media=[Media(state=PAUSED,playbackState=PAUSE)])
     MediaService  D  Command received
                   D  stopForeground()
MediaStateMachine  I  Transitioning from Paused(session=Session(8ca60fa8-2cba-41ca-aeb7-ad22c335d9ec, http://www.leparisien.fr/video/rentree-ministeri
                      elle-connaissez-vous-vos-ministres-21-08-2019-8136792.php), media=[Media(state=ENDED,playbackState=ENDED)]) to MediaState.None
     MediaService  D  Command received
   AndroidRuntime  D  Shutting down VM
                   E  FATAL EXCEPTION: main
                   E  Process: org.mozilla.samples.browser, PID: 15915
                   E  android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{
                      9a01536 u0 org.mozilla.samples.browser/mozilla.components.feature.media.service.MediaService}
                   E      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1945)
                   E      at android.os.Handler.dispatchMessage(Handler.java:107)
                   E      at android.os.Looper.loop(Looper.java:214)
                   E      at android.app.ActivityThread.main(ActivityThread.java:7356)
                   E      at java.lang.reflect.Method.invoke(Native Method)
                   E      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
                   E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by pocmo** [comment]
Weird, we see:

* Service created
* startForeground()
* stopForeground()
* Crash

Almost as if the `stopForeground()` reverted the ANR timer and we crash as if we never called `startForeground()`.

**Comment by pocmo** [comment]
STR:
* Go to the video site of leparisien.fr
* Play a video
* Refresh page.

Crashes almost reliably if repeated.

**Comment by pocmo** [comment]
```
--------------
PLAY:
--------------

      MediaStateMachine  I  Transitioning from MediaState.None to Playing(session=Session(8ca60fa8-2cba-41ca-aeb7-ad22c335d9ec, http://www.leparisien.fr/video/rent
                            ree-ministerielle-connaissez-vous-vos-ministres-21-08-2019-8136792.php), media=[Media(state=PLAYING,playbackState=PLAY)])
           MediaService  D  Service created
                         D  Command received
             AudioFocus  D  processAudioFocusResult(1)
           MediaService  D  startForeground()

                            Process org.mozilla.samples.browser:media created for service {org.mozilla.samples.browser/org.mozilla.gecko.media.MediaManager}
                            PID: 23962   UID:    GIDs:

      MediaStateMachine  I  Transitioning from Playing(session=Session(8ca60fa8-2cba-41ca-aeb7-ad22c335d9ec, http://www.leparisien.fr/video/rentree-ministerielle-c
                            onnaissez-vous-vos-ministres-21-08-2019-8136792.php), media=[Media(state=PAUSED,playbackState=PAUSE)]) to Paused(session=Session(8ca60f
                            a8-2cba-41ca-aeb7-ad22c335d9ec, http://www.leparisien.fr/video/rentree-ministerielle-connaissez-vous-vos-ministres-21-08-2019-8136792.p
                            hp), media=[Media(state=PAUSED,playbackState=PAUSE)])
           MediaService  D  Command received
                         D  stopForeground()
      MediaStateMachine  I  Transitioning from Paused(session=Session(8ca60fa8-2cba-41ca-aeb7-ad22c335d9ec, http://www.leparisien.fr/video/rentree-ministerielle-co
                            nnaissez-vous-vos-ministres-21-08-2019-8136792.php), media=[Media(state=PLAYING,playbackState=PLAY)]) to Playing(session=Session(8ca60f
                            a8-2cba-41ca-aeb7-ad22c335d9ec, http://www.leparisien.fr/video/rentree-ministerielle-connaissez-vous-vos-ministres-21-08-2019-8136792.p
                            hp), media=[Media(state=PLAYING,playbackState=PLAY)])

--------------
REFRESH!
--------------

                         I  Transitioning from Playing(session=Session(8ca60fa8-2cba-41ca-aeb7-ad22c335d9ec, http://www.leparisien.fr/video/rentree-ministerielle-c
                            onnaissez-vous-vos-ministres-21-08-2019-8136792.php), media=[Media(state=PAUSED,playbackState=PAUSE)]) to Paused(session=Session(8ca60f
                            a8-2cba-41ca-aeb7-ad22c335d9ec, http://www.leparisien.fr/video/rentree-ministerielle-connaissez-vous-vos-ministres-21-08-2019-8136792.p
                            hp), media=[Media(state=PAUSED,playbackState=PAUSE)])
           MediaService  D  Command received
                         D  stopForeground()
      MediaStateMachine  I  Transitioning from Paused(session=Session(8ca60fa8-2cba-41ca-aeb7-ad22c335d9ec, http://www.leparisien.fr/video/rentree-ministerielle-co
                            nnaissez-vous-vos-ministres-21-08-2019-8136792.php), media=[Media(state=PAUSED,playbackState=PAUSE)]) to MediaState.None
           MediaService  D  Command received
         AndroidRuntime  D  Shutting down VM
                         E  FATAL EXCEPTION: main
                         E  Process: org.mozilla.samples.browser, PID: 23641
                         E  android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{c2c9f96
                             u0 org.mozilla.samples.browser/mozilla.components.feature.media.service.MediaService}
                         E      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1945)
                         E      at android.os.Handler.dispatchMessage(Handler.java:107)
                         E      at android.os.Looper.loop(Looper.java:214)
                         E      at android.app.ActivityThread.main(ActivityThread.java:7356)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by pocmo** [comment]
The issue seems to be calling `stopSelf()` without another `startForeground()`... which is weird ... But it's fixed if I call `startForeground()` with some dummy notification.
