### ISSUE TITLE
Crash when seeking through HTML5 video

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#4192]
### Steps to reproduce
1. Go to https://tekeye.uk/html/html5-video-test-page
2. Start a video and seek ahead (may take a few attempts)

### Device information

* Android device: Android 9 (Pixel 2)
* Reference Browser version: `bd91c99` (Since there isn't a nightly, I built a debug version from master 23/08).

```
2019-08-23 08:53:16.921 30412-30577/? E/bt_btif: register_notification_rsp: Avrcp device is not connected, handle: 0x0
2019-08-23 08:53:16.921 30412-30577/? I/chatty: uid=1002(bluetooth) BluetoothAvrcpH identical 4 lines
2019-08-23 08:53:16.921 30412-30577/? E/bt_btif: register_notification_rsp: Avrcp device is not connected, handle: 0x0
2019-08-23 08:53:16.924 18302-18417/org.mozilla.reference.browser.debug:tab D/AudioTrack: stop() called with 132484 frames delivered
2019-08-23 08:53:16.943 18153-18153/org.mozilla.reference.browser.debug I/MediaStateMachine: Transitioning from MediaState.None to Playing(session=Session(5acd5955-0cdc-4ace-9e49-1c960b0c14b4, https://tekeye.uk/html/html5-video-test-page), media=[Media(PLAY)])
2019-08-23 08:53:16.946 18153-18153/org.mozilla.reference.browser.debug I/MediaStateMachine: Transitioning from Playing(session=Session(5acd5955-0cdc-4ace-9e49-1c960b0c14b4, https://tekeye.uk/html/html5-video-test-page), media=[Media(SEEKING)]) to MediaState.None
2019-08-23 08:53:16.948 18153-18153/org.mozilla.reference.browser.debug D/MediaService: Service created
2019-08-23 08:53:16.948 18153-18153/org.mozilla.reference.browser.debug W/MediaSessionCompat: Couldn't find a unique registered media button receiver in the given context.
2019-08-23 08:53:16.950 1179-2201/? D/MediaSessionService: Media button session is changed to org.mozilla.reference.browser.debug/MozacMedia (userId=0)
2019-08-23 08:53:16.951 30412-30412/? I/NewAvrcpMediaPlayerList: onAddressedPlayerChanged: token=org.mozilla.reference.browser.debug
2019-08-23 08:53:16.951 30412-30412/? W/NewAvrcpMediaPlayerList: org.mozilla.reference.browser.debug is already the active player
2019-08-23 08:53:16.953 18153-18153/org.mozilla.reference.browser.debug D/MediaService: Command received
2019-08-23 08:53:16.955 1179-3948/? I/MediaFocusControl: abandonAudioFocus() from uid/pid 10315/18153 clientId=android.media.AudioManager@37cc13fmozilla.components.feature.media.focus.AudioFocus@4b9aa0c
2019-08-23 08:53:16.955 1179-3948/? D/MediaSessionService: Media button session is changed to null
2019-08-23 08:53:16.956 1179-3948/? W/ActivityManager: Bringing down service while still waiting for start foreground: ServiceRecord{fb473fc u0 org.mozilla.reference.browser.debug/mozilla.components.feature.media.service.MediaService}
2019-08-23 08:53:16.957 18153-18153/org.mozilla.reference.browser.debug D/MediaService: Command received
2019-08-23 08:53:16.957 1179-2385/? I/MediaFocusControl: abandonAudioFocus() from uid/pid 10315/18153 clientId=android.media.AudioManager@37cc13fmozilla.components.feature.media.focus.AudioFocus@4b9aa0c
2019-08-23 08:53:16.959 18153-18153/org.mozilla.reference.browser.debug D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
2019-08-23 08:53:16.960 18153-18153/org.mozilla.reference.browser.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.reference.browser.debug, PID: 18153
    android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{fb473fc u0 org.mozilla.reference.browser.debug/mozilla.components.feature.media.service.MediaService}
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1745)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by jonalmeida** [comment]
cc: @pocmo

**Comment by pocmo** [comment]
This looks a lot like the issue fixed by d582fd731c90e6494ce5de6d0cfb2db40931fcd0 (#4172). Do you know what AC version (git hash) that build used?

**Comment by pocmo** [comment]
I tried a bit reproducing this with the latest Fenix Nightly (They are getting build again, yay) and wasn't able to get it to crash yet.

**Comment by jonalmeida** [comment]
> 1.0.1934 (Build #1 GV: 70.0a1-20190819095406)
> :package:: 10.0.0, e341f9373
> :ship:: 0.37.1

After sync-ing I got your changes, and it no longer crashes!

> 1.0.1934 (Build #1 GV: 70.0a1-20190823094538)
> :package:: 10.0.0, 962a749b2
> :ship:: 0.37.1
