### ISSUE TITLE
Telemetry throws exception about "Untagged socket detected"

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#422]
Looks like this is related to "Strict Mode".

There is a discussion at https://github.com/square/okhttp/issues/3537 about this.

Unclear how serious the exception is. It looks like the request is succesfully executed?

This Strict Mode and `TrafficStats` looks interesting though. It sounds like we are able to classify different types of traffic with this, and then ask for reports. This could be useful to get insight in how much traffic telemetry is using. That could be an interesting data point to keep an eye on average bandwidth usage.

```
07-13 15:21:14.382 21840-23054/org.mozilla.focus.coverage D/TelemetryJobService: Performing upload of ping type: core
07-13 15:21:14.539 21840-23054/org.mozilla.focus.coverage E/StrictMode: null
java.lang.Throwable: Untagged socket detected; use TrafficStats.setThreadSocketTag() to track all network usage
    at android.os.StrictMode.onUntaggedSocket(StrictMode.java:2012)
    at com.android.server.NetworkManagementSocketTagger.tag(NetworkManagementSocketTagger.java:78)
    at libcore.io.BlockGuardOs.tagSocket(BlockGuardOs.java:47)
    at libcore.io.BlockGuardOs.socket(BlockGuardOs.java:310)
    at libcore.io.IoBridge.socket(IoBridge.java:667)
    at java.net.PlainSocketImpl.socketCreate(PlainSocketImpl.java:116)
    at java.net.AbstractPlainSocketImpl.create(AbstractPlainSocketImpl.java:98)
    at java.net.Socket.createImpl(Socket.java:484)
    at java.net.Socket.getImpl(Socket.java:547)
    at java.net.Socket.setSoTimeout(Socket.java:1175)
    at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:139)
    at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
    at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
    at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
    at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
    at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
    at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:258)
    at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
    at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(Unknown Source:0)
    at org.mozilla.telemetry.net.HttpURLConnectionTelemetryClient.upload(HttpURLConnectionTelemetryClient.java:97)
    at org.mozilla.telemetry.net.HttpURLConnectionTelemetryClient.uploadPing(HttpURLConnectionTelemetryClient.java:44)
    at org.mozilla.telemetry.schedule.jobscheduler.TelemetryJobService$1.onTelemetryPingLoaded(TelemetryJobService.java:151)
    at org.mozilla.telemetry.storage.FileTelemetryStorage.process(FileTelemetryStorage.java:71)
    at org.mozilla.telemetry.schedule.jobscheduler.TelemetryJobService.performPingUpload(TelemetryJobService.java:147)
    at org.mozilla.telemetry.schedule.jobscheduler.TelemetryJobService.uploadPingsInBackground(TelemetryJobService.java:81)
    at org.mozilla.telemetry.schedule.jobscheduler.TelemetryJobService$UploadPingsTask.doInBackground(TelemetryJobService.java:52)
    at org.mozilla.telemetry.schedule.jobscheduler.TelemetryJobService$UploadPingsTask.doInBackground(TelemetryJobService.java:47)
    at android.os.AsyncTask$2.call(AsyncTask.java:333)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
    at java.lang.Thread.run(Thread.java:764)
07-13 15:21:15.172 21840-23054/org.mozilla.focus.coverage D/HttpURLTelemetryClient: Ping upload: 200
07-13 15:21:15.179 21840-23054/org.mozilla.focus.coverage D/TelemetryJobService: Performing upload of ping type: focus-event
07-13 15:21:15.661 21840-23054/org.mozilla.focus.coverage D/HttpURLTelemetryClient: Ping upload: 200
07-13 15:21:15.667 21840-23054/org.mozilla.focus.coverage D/TelemetryJobService: All uploads performed
```

**Comment by pocmo** [comment]
Yeah, I don't think this is actionable. We just use HttpUrlConnection (which uses okhttp under the hood) and do not have any access to the Sockets. This is one of the reasons why we log strict mode vioalations instead of crashing the app.

**Comment by pocmo** [comment]
The `service-telemetry` is deprecated.
