### ISSUE TITLE
Handle unknown push messages gracefully

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#4264]
With https://github.com/mozilla/application-services/pull/1563 we're no longer getting exceptions from Fxa when messages are delivered to us which cannot be handled, but in the a-c side we still show them as errors when they're just warnings:
```
019-08-29 17:23:40.065 9624-9985/org.mozilla.tv.firefox.debug D/PushObserver: Received new push message for Services
2019-08-29 17:23:40.067 9624-9966/org.mozilla.tv.firefox.debug I/FxaDeviceConstellation: Executing: processing raw events
2019-08-29 17:23:40.098 9624-9966/org.mozilla.tv.firefox.debug E/FxaDeviceConstellation: Error while running: processing raw events
    mozilla.appservices.fxaclient.FxaException$Unspecified: JSON error: invalid type: map, expected unit variant PushPayload::Unknown at line 1 column 64
        at mozilla.appservices.fxaclient.rust.RustError.intoException(RustError.kt:48)
        at mozilla.appservices.fxaclient.FirefoxAccount.handlePushMessage(FirefoxAccount.kt:750)
        at mozilla.components.service.fxa.FxaDeviceConstellation$processRawEventAsync$1$1.invoke(FxaDeviceConstellation.kt:71)
        at mozilla.components.service.fxa.FxaDeviceConstellation$processRawEventAsync$1$1.invoke(FxaDeviceConstellation.kt:33)
        at mozilla.components.service.fxa.UtilsKt$handleFxaExceptions$5.invoke(Utils.kt:64)
        at mozilla.components.service.fxa.UtilsKt$handleFxaExceptions$5.invoke(Utils.kt)
        at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:30)
        at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:56)
        at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:63)
        at mozilla.components.service.fxa.FxaDeviceConstellation$processRawEventAsync$1.invokeSuspend(FxaDeviceConstellation.kt:70)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
```

A longer term fix would be to filter out the 'Device x is now syncing' notifications that get delivered to us when _we_ start syncing.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3597)

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794214

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
