### ISSUE TITLE
QR code pairing causes KotlinNullPointerException on assertion

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#4350]
Pairing with Fenix using QR code scanning fails. Regular sign in with typing (who does that now?!) works.

Linked Fenix issue: ~https://github.com/mozilla-mobile/fenix/issues/5175~ https://github.com/mozilla-mobile/fenix/issues/3580

```
    --------- beginning of crash
2019-09-09 11:57:12.318 org.mozilla.fenix.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fenix.debug, PID: 3712
    kotlin.KotlinNullPointerException
        at mozilla.components.feature.accounts.FirefoxAccountsAuthFeature$interceptor$1.onLoadRequest(FirefoxAccountsAuthFeature.kt:71)
        at org.mozilla.fenix.AppRequestInterceptor.onLoadRequest(AppRequestInterceptor.kt:29)
        at mozilla.components.browser.engine.gecko.GeckoEngineSession$createNavigationDelegate$1.onLoadRequest(GeckoEngineSession.kt:312)
        at org.mozilla.geckoview.GeckoSession$3.handleMessage(GeckoSession.java:565)
        at org.mozilla.geckoview.GeckoSession$3.handleMessage(GeckoSession.java:519)
        at org.mozilla.geckoview.GeckoSessionHandler.handleMessage(GeckoSessionHandler.java:80)
        at org.mozilla.gecko.EventDispatcher$3.run(EventDispatcher.java:373)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by jonalmeida** [comment]
It looks like we're making an assertion on some query param that we're not getting so I guess something changed in FxA? Added the `<qr>` label any way since this doesn't seem to happen with a regular sign-in flow.

**Comment by csadilek** [comment]
Happens quite a bit in Fenix: https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6218513/

**Comment by grigoryk** [comment]
Our Sentry line numbers seem completely irrelevant, but I think this is what's failing:
```val authType = parsedUri.getQueryParameter("action")!!.toAuthType()```

So, seems like we're failing to get the `action` param. Code assumes it'll always be there, but here we're seeing that's not the case.

**Comment by grigoryk** [comment]
So, here's what's happening:
- `action` param is not present in the non-webchannel pairing flow
- `action` param is present in every other flow (webchannel or not)
- code assumes that `action` param is always present

FxA will add the `action` param to this flow in https://github.com/mozilla/application-services/issues/1740

In the meantime, let's ship an `unknown` AuthType to cover our bases here. This is better than making assumptions around what kind of sign-in flow we were in if `action` is missing; that's brittle, and will skew our metrics.
