### ISSUE TITLE
NullPointerException in FxaAccountManager

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#4723]
See Sentry: https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6422375/?environment=fenixNightlyLegacy

Crash is in `postAuthenticated`, but line numbers look off.

**Comment by cpeterso** [comment]
We're seeing about 10-20 instances of this crash from Fenix Nightly in Socorro every day:

https://crash-stats.mozilla.org/signature/?product=FennecAndroid&signature=kotlin.KotlinNullPointerException:%20at%20io.reactivex.plugins.RxJavaPlugins.throwNpe(RxJavaPlugins.java)&version=71.0a1&date=%3C2019-10-14T17:50:59%2B00:00&date=%3E%3D2019-10-07T17:50:59%2B00:00#graphs

Such as https://crash-stats.mozilla.org/report/index/29c6ba88-c8a9-422e-a411-238780191014:

```
kotlin.KotlinNullPointerException
	at io.reactivex.plugins.RxJavaPlugins.throwNpe(RxJavaPlugins.java:1)
	at mozilla.components.service.fxa.manager.FxaAccountManager.postAuthenticated(FxaAccountManager.kt:41)
	at mozilla.components.service.fxa.manager.FxaAccountManager$postAuthenticated$1.invokeSuspend(Unknown Source:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:15)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
```

**Comment by pocmo** [comment]
The following Fenix issue is related and has STR:
https://github.com/mozilla-mobile/fenix/issues/5990

QA ranked this crash as a release blocker.

**Comment by grigoryk** [comment]
Seems like this is a regression from adding a `sessionTokenScope` to Fenix. See https://github.com/mozilla/application-services/issues/1979.

**Comment by grigoryk** [comment]
Going to remove the sessionTokenScope from Fenix for now, since we're not using it just yet. Will re-land once underlying issue is resolved.

**Comment by grigoryk** [comment]
Crashes stopped after removing `sessionTokenScope`. Still unclear _why_ there were crashes though, I didn't investigate beyond finding a "cause". One of the "this won't be null" assumptions in `postAuthenticated` have been violated in this weird case. Very unfortunate that our line numbers are all wrong in crash reports :-(
