### ISSUE TITLE
Sample apps crash because of ``RustLog.enable`` on orientation change

### ISSUE THREAD

**Issue by drigio** [mozilla-mobile/android-components#4859]
### Steps to reproduce :
1. Open any sample app that uses ``RustLog.enable()`` for example samples-firefox-accounts
2. Change the screen orientation.

### Expected Behavior
Screen orientation should change

### Actual Behavior 
App crashes

### Log
```kotlin
2019-10-26 20:08:30.171 18802-18802/org.mozilla.samples.fxa E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.samples.fxa, PID: 18802
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mozilla.samples.fxa/org.mozilla.samples.fxa.MainActivity}: mozilla.appservices.rustlog.LogAdapterCannotEnable: Log adapter may not be enabled: Adapter is already enabled
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
        at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:4824)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4733)
        at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6719)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: mozilla.appservices.rustlog.LogAdapterCannotEnable: Log adapter may not be enabled: Adapter is already enabled
        at mozilla.appservices.rustlog.RustLogAdapter$Companion.enable(RustLogAdapter.kt:52)
        at mozilla.components.support.rustlog.RustLog.enable(RustLog.kt:36)
        at org.mozilla.samples.fxa.MainActivity.onCreate(MainActivity.kt:57)
        at android.app.Activity.performCreate(Activity.java:7144)
        at android.app.Activity.performCreate(Activity.java:7135)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
```

This occurs with any application that uses the ``RustLog.enable()``. 

Checked with ``samples-firefox-accounts`` and ``samples-sync``

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4110)

**Comment by drigio** [comment]
Looked at the code and found out that as ``RustLog.enable()`` is written in ``onCreate()`` , and on orientation change the ``onCreate()`` method is called again which results in ``RustLog.enable()`` to throw the exception ``LogAdapterCannotEnable``.  

A simple ``try...catch`` block inside the ``RustLog.enable()`` defintion would help, but would it be a good practice?

**Comment by pocmo** [comment]
We should call this from the application object instead of the activity.
