### ISSUE TITLE
Intermittent glean test: WorkManager is not initialized properly

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#4929]
```
[task 2019-11-01T03:03:05.742Z] java.lang.IllegalStateException: WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.
[task 2019-11-01T03:03:05.742Z]     at androidx.work.impl.WorkManagerImpl.getInstance(WorkManagerImpl.java:140)
[task 2019-11-01T03:03:05.742Z]     at androidx.work.WorkManager.getInstance(WorkManager.java:180)
[task 2019-11-01T03:03:05.742Z]     at mozilla.telemetry.glean.scheduler.MetricsPingScheduler.schedulePingCollection$glean_core_release(MetricsPingScheduler.kt:118)
[task 2019-11-01T03:03:05.742Z]     at mozilla.telemetry.glean.scheduler.MetricsPingScheduler.schedule(MetricsPingScheduler.kt:244)
[task 2019-11-01T03:03:05.742Z]     at mozilla.telemetry.glean.GleanInternalAPI.initialize(Glean.kt:197)
[task 2019-11-01T03:03:05.742Z]     at mozilla.components.service.glean.Glean.initialize(Glean.kt:41)
[task 2019-11-01T03:03:05.742Z]     at mozilla.components.service.glean.GleanFromJavaTest.testInitGleanWithConfiguration(GleanFromJavaTest.java:33)
[task 2019-11-01T03:03:05.742Z]     at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[task 2019-11-01T03:03:05.742Z]     at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[task 2019-11-01T03:03:05.742Z]     at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[task 2019-11-01T03:03:05.742Z]     at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[task 2019-11-01T03:03:05.742Z]     at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:601)
[task 2019-11-01T03:03:05.742Z]     at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:260)
[task 2019-11-01T03:03:05.742Z]     at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
[task 2019-11-01T03:03:05.742Z]     at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
[task 2019-11-01T03:03:05.742Z]     at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[task 2019-11-01T03:03:05.742Z]     at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[task 2019-11-01T03:03:05.742Z]     at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[task 2019-11-01T03:03:05.742Z]     at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[task 2019-11-01T03:03:05.742Z]     at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[task 2019-11-01T03:03:05.742Z]     at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
[task 2019-11-01T03:03:05.742Z]     at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[task 2019-11-01T03:03:05.742Z]     at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
[task 2019-11-01T03:03:05.742Z]     at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
[task 2019-11-01T03:03:05.742Z]     at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
[task 2019-11-01T03:03:05.742Z]     at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
[task 2019-11-01T03:03:05.742Z]     at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
[task 2019-11-01T03:03:05.742Z]     at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
[task 2019-11-01T03:03:05.742Z]     at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[task 2019-11-01T03:03:05.742Z]     at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
[task 2019-11-01T03:03:05.742Z]     at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
[task 2019-11-01T03:03:05.742Z]     at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
[task 2019-11-01T03:03:05.742Z]     at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
[task 2019-11-01T03:03:05.742Z]     at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
[task 2019-11-01T03:03:05.742Z]     at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[task 2019-11-01T03:03:05.742Z]     at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
[task 2019-11-01T03:03:05.742Z]     at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
[task 2019-11-01T03:03:05.742Z]     at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
[task 2019-11-01T03:03:05.742Z]     at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
[task 2019-11-01T03:03:05.743Z]     at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
[task 2019-11-01T03:03:05.743Z]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[task 2019-11-01T03:03:05.743Z]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[task 2019-11-01T03:03:05.743Z]     at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
[task 2019-11-01T03:03:05.743Z]     at java.lang.Thread.run(Thread.java:748)
```

**Comment by grigoryk** [comment]
Seems like a race condition in tests?

**Comment by jonalmeida** [comment]
cc: @travis79

**Comment by grigoryk** [comment]
Hopefully it's resolved in https://github.com/mozilla-mobile/android-components/pull/4932

I'll keep an eye out on our PRs.

**Comment by travis79** [comment]
This has been fixed for a while and no new complaints, so closing this out.  Happy to reopen if anything new crops up.
