### ISSUE TITLE
Intermittent test failure in DownloadsFeatureTest - onPermissionsResult

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#4938]
Saw this in TC runs for https://github.com/mozilla-mobile/android-components/pull/4937.

Failing test was last touched in #4282. cc @pocmo  

```
[task 2019-11-02T00:26:32.347Z]   TEST: onPermissionsResult will consume download if permissions were not granted
[task 2019-11-02T00:26:32.347Z]     [Robolectric] mozilla.components.feature.downloads.DownloadsFeatureTest.onPermissionsResult will consume download if permissions were not granted: sdk=28; resources=binary
[task 2019-11-02T00:26:32.426Z]     I/MonitoringInstr: Instrumentation started!
[task 2019-11-02T00:26:32.426Z]     I/MonitoringInstr: Setting context classloader to 'org.robolectric.internal.bytecode.SandboxClassLoader@ba107ab', Original: 'org.robolectric.internal.bytecode.SandboxClassLoader@ba107ab'
[task 2019-11-02T00:26:32.426Z]     TabSessionState(id=test-tab, content=ContentState(url=https://www.mozilla.org, private=false, title=, progress=0, loading=false, searchTerms=, securityInfo=SecurityInfoState(secure=false, host=, issuer=), thumbnail=null, icon=null, download=null, hitResult=null, promptRequest=null, findResults=[], windowRequest=null), trackingProtection=TrackingProtectionState(enabled=false, blockedTrackers=[], loadedTrackers=[], ignoredOnTrackingProtection=false), engineState=EngineState(engineSession=null, engineSessionState=null), parentId=null, extensionState={})
[task 2019-11-02T00:26:32.426Z]   FAILURE
[task 2019-11-02T00:26:32.426Z] 
[task 2019-11-02T00:26:32.426Z] java.lang.AssertionError
[task 2019-11-02T00:26:32.426Z] 	at org.junit.Assert.fail(Assert.java:86)
[task 2019-11-02T00:26:32.426Z] 	at org.junit.Assert.assertTrue(Assert.java:41)
[task 2019-11-02T00:26:32.426Z] 	at org.junit.Assert.assertNotNull(Assert.java:712)
[task 2019-11-02T00:26:32.426Z] 	at org.junit.Assert.assertNotNull(Assert.java:722)
[task 2019-11-02T00:26:32.426Z] 	at mozilla.components.feature.downloads.DownloadsFeatureTest.onPermissionsResult will consume download if permissions were not granted(DownloadsFeatureTest.kt:286)
[task 2019-11-02T00:26:32.426Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2019-11-02T00:26:32.426Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2019-11-02T00:26:32.426Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2019-11-02T00:26:32.426Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2019-11-02T00:26:32.426Z] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[task 2019-11-02T00:26:32.426Z] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[task 2019-11-02T00:26:32.426Z] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[task 2019-11-02T00:26:32.426Z] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[task 2019-11-02T00:26:32.426Z] 	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:601)
[task 2019-11-02T00:26:32.426Z] 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
[task 2019-11-02T00:26:32.426Z] 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
[task 2019-11-02T00:26:32.426Z] 	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:260)
[task 2019-11-02T00:26:32.426Z] 	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
[task 2019-11-02T00:26:32.426Z] 	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
[task 2019-11-02T00:26:32.426Z] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[task 2019-11-02T00:26:32.426Z] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[task 2019-11-02T00:26:32.426Z] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[task 2019-11-02T00:26:32.427Z] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[task 2019-11-02T00:26:32.427Z] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[task 2019-11-02T00:26:32.427Z] 	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
[task 2019-11-02T00:26:32.427Z] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[task 2019-11-02T00:26:32.427Z] 	at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:104)
[task 2019-11-02T00:26:32.427Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
[task 2019-11-02T00:26:32.427Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
[task 2019-11-02T00:26:32.427Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
[task 2019-11-02T00:26:32.427Z] 	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
[task 2019-11-02T00:26:32.427Z] 	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
[task 2019-11-02T00:26:32.427Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2019-11-02T00:26:32.427Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2019-11-02T00:26:32.427Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2019-11-02T00:26:32.427Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2019-11-02T00:26:32.427Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
[task 2019-11-02T00:26:32.427Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[task 2019-11-02T00:26:32.427Z] 	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
[task 2019-11-02T00:26:32.427Z] 	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
[task 2019-11-02T00:26:32.427Z] 	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
[task 2019-11-02T00:26:32.427Z] 	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
[task 2019-11-02T00:26:32.427Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2019-11-02T00:26:32.427Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2019-11-02T00:26:32.427Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2019-11-02T00:26:32.427Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2019-11-02T00:26:32.427Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
[task 2019-11-02T00:26:32.427Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[task 2019-11-02T00:26:32.427Z] 	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
[task 2019-11-02T00:26:32.427Z] 	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
[task 2019-11-02T00:26:32.427Z] 	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
[task 2019-11-02T00:26:32.427Z] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
[task 2019-11-02T00:26:32.427Z] 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
[task 2019-11-02T00:26:32.427Z] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[task 2019-11-02T00:26:32.427Z] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[task 2019-11-02T00:26:32.427Z] 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
[task 2019-11-02T00:26:32.427Z] 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by grigoryk** [comment]
Just saw this again in #4989 , but with a slightly different stacktrace:
```

[task 2019-11-06T20:59:47.395Z]   TEST: onPermissionsResult will consume download if permissions were not granted
[task 2019-11-06T20:59:47.395Z]     [Robolectric] mozilla.components.feature.downloads.DownloadsFeatureTest.onPermissionsResult will consume download if permissions were not granted: sdk=28; resources=binary
[task 2019-11-06T20:59:47.479Z]     I/MonitoringInstr: Instrumentation started!
[task 2019-11-06T20:59:47.480Z]     I/MonitoringInstr: Setting context classloader to 'org.robolectric.internal.bytecode.SandboxClassLoader@60297899', Original: 'org.robolectric.internal.bytecode.SandboxClassLoader@60297899'
[task 2019-11-06T20:59:47.480Z]     TabSessionState(id=test-tab, content=ContentState(url=https://www.mozilla.org, private=false, title=, progress=0, loading=false, searchTerms=, securityInfo=SecurityInfoState(secure=false, host=, issuer=), thumbnail=null, icon=null, download=null, hitResult=null, promptRequest=null, findResults=[], windowRequest=null), trackingProtection=TrackingProtectionState(enabled=false, blockedTrackers=[], loadedTrackers=[], ignoredOnTrackingProtection=false), engineState=EngineState(engineSession=null, engineSessionState=null), parentId=null, extensionState={})
[task 2019-11-06T20:59:47.480Z]   FAILURE
[task 2019-11-06T20:59:47.480Z] 
[task 2019-11-06T20:59:47.480Z] java.lang.AssertionError
[task 2019-11-06T20:59:47.480Z] 	at org.junit.Assert.fail(Assert.java:86)
[task 2019-11-06T20:59:47.480Z] 	at org.junit.Assert.assertTrue(Assert.java:41)
[task 2019-11-06T20:59:47.480Z] 	at org.junit.Assert.assertNotNull(Assert.java:712)
[task 2019-11-06T20:59:47.480Z] 	at org.junit.Assert.assertNotNull(Assert.java:722)
[task 2019-11-06T20:59:47.480Z] 	at mozilla.components.feature.downloads.DownloadsFeatureTest.onPermissionsResult will consume download if permissions were not granted(DownloadsFeatureTest.kt:308)
[task 2019-11-06T20:59:47.480Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2019-11-06T20:59:47.480Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2019-11-06T20:59:47.480Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2019-11-06T20:59:47.480Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2019-11-06T20:59:47.480Z] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[task 2019-11-06T20:59:47.480Z] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[task 2019-11-06T20:59:47.480Z] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[task 2019-11-06T20:59:47.480Z] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[task 2019-11-06T20:59:47.480Z] 	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:601)
[task 2019-11-06T20:59:47.480Z] 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
[task 2019-11-06T20:59:47.480Z] 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
[task 2019-11-06T20:59:47.480Z] 	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:260)
[task 2019-11-06T20:59:47.480Z] 	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
[task 2019-11-06T20:59:47.480Z] 	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
[task 2019-11-06T20:59:47.480Z] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[task 2019-11-06T20:59:47.480Z] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[task 2019-11-06T20:59:47.480Z] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[task 2019-11-06T20:59:47.480Z] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[task 2019-11-06T20:59:47.480Z] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[task 2019-11-06T20:59:47.480Z] 	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
[task 2019-11-06T20:59:47.480Z] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[task 2019-11-06T20:59:47.480Z] 	at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:104)
[task 2019-11-06T20:59:47.480Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
[task 2019-11-06T20:59:47.480Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
[task 2019-11-06T20:59:47.480Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
[task 2019-11-06T20:59:47.480Z] 	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
[task 2019-11-06T20:59:47.480Z] 	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
[task 2019-11-06T20:59:47.480Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2019-11-06T20:59:47.480Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2019-11-06T20:59:47.480Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2019-11-06T20:59:47.480Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2019-11-06T20:59:47.480Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
[task 2019-11-06T20:59:47.480Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[task 2019-11-06T20:59:47.480Z] 	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
[task 2019-11-06T20:59:47.480Z] 	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
[task 2019-11-06T20:59:47.480Z] 	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
[task 2019-11-06T20:59:47.480Z] 	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
[task 2019-11-06T20:59:47.480Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2019-11-06T20:59:47.480Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2019-11-06T20:59:47.480Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2019-11-06T20:59:47.480Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2019-11-06T20:59:47.480Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
[task 2019-11-06T20:59:47.480Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[task 2019-11-06T20:59:47.480Z] 	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
[task 2019-11-06T20:59:47.480Z] 	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
[task 2019-11-06T20:59:47.480Z] 	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
[task 2019-11-06T20:59:47.480Z] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
[task 2019-11-06T20:59:47.480Z] 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
[task 2019-11-06T20:59:47.480Z] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[task 2019-11-06T20:59:47.480Z] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[task 2019-11-06T20:59:47.480Z] 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
[task 2019-11-06T20:59:47.480Z] 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by pocmo** [comment]
Just got this in another PR:
* https://firefox-ci-tc.services.mozilla.com/tasks/JAM_Fzm_TmuvCOxwdDc82w/runs/0/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FJAM_Fzm_TmuvCOxwdDc82w%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log
* https://firefoxci.taskcluster-artifacts.net/JAM_Fzm_TmuvCOxwdDc82w/0/public/logs/live_backing.log
