### ISSUE TITLE
AccountManager/sync: deviceSettings not populate on first sync

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#4975]
Got this report from @keianhzo, observed in FxR.

on first sync after a fresh install, they're hitting
```
        at mozilla.components.service.fxa.sync.WorkManagerSyncWorker.doWork(WorkManagerSyncManager.kt:364)
```
This is when worker asserts that `FxaDeviceSettingsCache(context).getCached()!!`.

We populate `FxaDeviceSettingsCache` in the account manager's `postAuthenticated`. Perhaps there's a race/misalignment between when that runs and when sync worker first runs?

Full stacktrace:

```
2019-11-05 01:51:23.527 18225-18255/org.mozilla.vrbrowser.dev E/WM-WorkerWrapper: Work [ id=5a8726b9-58ca-4150-979b-5e5b648a4f88, tags={ Common, mozilla.components.service.fxa.sync.WorkManagerSyncWorker, Immediate } ] failed because it threw an exception/error
    java.util.concurrent.ExecutionException: kotlin.KotlinNullPointerException
        at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:516)
        at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
        at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:284)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: kotlin.KotlinNullPointerException
        at mozilla.components.service.fxa.sync.WorkManagerSyncWorker.doWork(WorkManagerSyncManager.kt:364)
        at androidx.work.CoroutineWorker$startWork$1.invokeSuspend(CoroutineWorker.kt:68)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
2019-11-05 01:51:23.528 18225-18255/org.mozilla.vrbrowser.dev I/WM-WorkerWrapper: Worker result FAILURE for Work [ id=5a8726b9-58ca-4150-979b-5e5b648a4f88, tags={ Common, mozilla.components.service.fxa.sync.WorkManagerSyncWorker, Immediate } ]
2019-11-05 01:51:23.554 18225-18255/org.mozilla.vrbrowser.dev E/WM-WorkerWrapper: Work [ id=90f18868-3912-4baa-8a93-d30646f7160e, tags={ Common, mozilla.components.service.fxa.sync.WorkManagerSyncWorker, Debounce } ] failed because it threw an exception/error
    java.util.concurrent.ExecutionException: kotlin.KotlinNullPointerException
        at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:516)
        at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
        at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:284)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: kotlin.KotlinNullPointerException
        at mozilla.components.service.fxa.sync.WorkManagerSyncWorker.doWork(WorkManagerSyncManager.kt:364)
        at androidx.work.CoroutineWorker$startWork$1.invokeSuspend(CoroutineWorker.kt:68)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
2019-11-05 01:53:24.452 21452-21479/org.mozilla.vrbrowser.dev I/WM-WorkerWrapper: Worker result FAILURE for Work [ id=85e5926c-b44b-4258-9282-5750f745ab75, tags={ Common, mozilla.components.service.fxa.sync.WorkManagerSyncWorker, Debounce } ]
2019-11-05 01:53:44.743 21452-21478/org.mozilla.vrbrowser.dev I/WM-WorkerWrapper: Worker result SUCCESS for Work [ id=217c896f-5175-4320-9417-32bb9a8cf71f, tags={ mozac_service_glean_ping_upload_worker, mozilla.telemetry.glean.scheduler.PingUploadWorker } ]
2019-11-05 01:53:56.752 21452-21479/org.mozilla.vrbrowser.dev I/WM-WorkerWrapper: Worker result SUCCESS for Work [ id=6ec5498b-a7fa-42eb-b5bb-fd89863bf4d9, tags={ Common, mozilla.components.service.fxa.sync.WorkManagerSyncWorker, Immediate } ]
2019-11-05 01:53:57.366 21452-21478/org.mozilla.vrbrowser.dev I/WM-WorkerWrapper: Worker result SUCCESS for Work [ id=747438d5-0d48-4d0f-ac08-e020f19b6cc0, tags={ mozac_service_glean_ping_upload_worker, mozilla.telemetry.glean.scheduler.PingUploadWorker } ]
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4293)

**Comment by jonalmeida** [comment]
Closing as won't fix; this crash/error no longer shows up in our crash reporters.
