### ISSUE TITLE
Fennec migration: Fenix crashes at sync

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/android-components#5044]
## Preconditions:
Have Firefox Release installed and logged in.
## Steps to reproduce
1. Replace Fennec with Fenix using a build from https://github.com/mozilla-mobile/fenix/wiki/Fennec-Migration;
2. Launch Fenix;
3. Repeat Step 1 and Step 2 on a different device;
4. Observe the behavior of the first device.
### Expected behavior
Fenix is usable on both devices.
### Actual behavior
Fenix crashes on the first device after the second device is connected.
### Notes:
[logcat-sync.txt](https://github.com/mozilla-mobile/android-components/files/3841041/logcat-sync.txt)

### Device information

* Android device: Google Pixel 2 (Android 9), Google Pixel 3 (Android Q).
* Fenix version: Nightly 191109 GV 71

**Comment by grigoryk** [comment]
Same with https://github.com/mozilla-mobile/android-components/issues/5041, could you please attach unfiltered logcat output which starts sometime before you attempt to sync? Logs you have attached now are not related to Fenix.

**Comment by ebalazs-sv** [comment]
@grigoryk Hi! Here is the debug, no filters logcat from Google Pixel 2 (Android 9):
[synccrash.txt](https://github.com/mozilla-mobile/android-components/files/3845612/synccrash.txt)

**Comment by grigoryk** [comment]
Thank you!
That's the same stacktrace as in https://github.com/mozilla-mobile/android-components/issues/5041#issuecomment-554092492. Let's use this bug to fix that stacktrace, since it actually relates to `sync` in a way.

Happens after sync runs:
```
2019-11-14 10:54:07.279 17781-17941/? E/AndroidRuntime: FATAL EXCEPTION: Firebase-FirebasePush
    Process: org.mozilla.firefox, PID: 17781
    java.lang.IllegalStateException: You need to call initialize() on your Push instance from Application.onCreate().
        at mozilla.components.concept.push.PushProcessor$Companion.getRequireInstance(PushProcessor.kt:1)
        at org.mozilla.fenix.components.FirebasePush.onMessageReceived(FirebasePush.kt:9)
        at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:175)
        at com.google.firebase.iid.zzg.run(Unknown Source:5)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:2)
        at java.lang.Thread.run(Thread.java:764)
2019-11-14 10:54:07.280 17781-17941/? I/mozac/CrashReporter: Received crash: UncaughtExceptionCrash(throwable=java.lang.IllegalStateException: You need to call initialize() on your Push instance from Application.onCreate()., breadcrumbs=[Breadcrumb(message=Changing to fragment homeFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Thu Nov 14 10:53:58 GMT+02:00 2019)])
```

**Comment by grigoryk** [comment]
https://github.com/mozilla-mobile/fenix/issues/6898 with the right firebase case, this should go away (cc @jonalmeida )

**Comment by ebalazs-sv** [comment]
Verified as fixed on Fennec Migration Nightly build 1 with Samsung Galaxy S8 (Android 9) - ARM64, Xiaomi Mi Pad 2 (Android 5.1) - x86, OnePlus 6T (Android 9.0) - ARM. 
I will move this to Done. Thanks!
