### ISSUE TITLE
FileUriExposedExceptionorg.mozilla.fenix.components.BackgroundServices$deviceEventObserver

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#5054]
What appears to have happened is that a user sent themselves a tab opened on `file:///`, it arrived in Fenix, and application crashed while intent wrapping that URI was being processed.

Since opening `file:///` urls sent from desktop to mobile is _very_ unlikely to work, we can just log an error and drop this tab, instead of trying to process it.

I wonder what Fennec did in such cases.

https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/6425705/
```
android.os.FileUriExposedException: file:///C:/Users/some/path/to/file.pdf exposed beyond app through Intent.getData()
    at android.os.StrictMode.onFileUriExposed(StrictMode.java:1978)
    at android.net.Uri.checkFileUriExposed(Uri.java:2371)
    at android.content.Intent.prepareToLeaveProcess(Intent.java:10247)
    at android.content.Intent.prepareToLeaveProcess(Intent.java:10201)
    at android.app.PendingIntent.getActivity(PendingIntent.java:347)
    at android.app.PendingIntent.getActivity(PendingIntent.java:309)
    at org.mozilla.fenix.components.BackgroundServices$deviceEventObserver$1.onEvents(BackgroundServices.kt:20)
    at -$$LambdaGroup$ks$zttBDHRXg1MtKquX7vb2sFPFho4.invoke(com.android.tools.r8.jetbrains.kotlin-style lambda group:2)
    at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:4)
    at mozilla.components.service.fxa.manager.FxaAccountManager$DeviceEventsIntegration.onEvents(FxaAccountManager.kt:2)
    at -$$LambdaGroup$ks$zttBDHRXg1MtKquX7vb2sFPFho4.invoke(com.android.tools.r8.jetbrains.kotlin-style lambda group:7)
    at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:4)
    at mozilla.components.service.fxa.FxaDeviceConstellation.notifyObservers
    at mozilla.components.service.fxa.FxaDeviceConstellation$processEvents$1.invokeSuspend(FxaDeviceConstellation.kt:3)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
    at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:15)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6718)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4379)

**Comment by jonalmeida** [comment]
Closing as won't fix; we don't see these crashes any more.
