### ISSUE TITLE
Sample browser: UnsupportedOperationException: Web notification support is not available in this engine

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#5106]
I get this error in sample browser (using GV beta) in the logs.

```
2019-11-20 11:21:06.364 27745-27745/org.mozilla.fennec_sebastiankaspari E/WebNotificationFeature: failed to register for web notification delegate
    java.lang.UnsupportedOperationException: Web notification support is not available in this engine
        at mozilla.components.concept.engine.Engine$DefaultImpls.registerWebNotificationDelegate(Engine.kt:155)
        at mozilla.components.browser.engine.gecko.GeckoEngine.registerWebNotificationDelegate(GeckoEngine.kt:45)
        at mozilla.components.feature.webnotifications.WebNotificationFeature.<init>(WebNotificationFeature.kt:59)
        at org.mozilla.samples.browser.DefaultComponents$sessionManager$2.invoke(DefaultComponents.kt:138)
        at org.mozilla.samples.browser.DefaultComponents$sessionManager$2.invoke(DefaultComponents.kt:65)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.mozilla.samples.browser.DefaultComponents.getSessionManager(Unknown Source:8)
        at org.mozilla.samples.browser.DefaultComponents$migrator$2.invoke(DefaultComponents.kt:73)
        at org.mozilla.samples.browser.DefaultComponents$migrator$2.invoke(DefaultComponents.kt:65)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.mozilla.samples.browser.DefaultComponents.getMigrator(Unknown Source:7)
        at org.mozilla.samples.browser.SampleApplication.onCreate(SampleApplication.kt:53)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

In our engine we throw but in the feature we catch and log. If we catch anyways then do we need to throw at all? Seeing this exception on every app start is definitely distracting when debugging other errors. :)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4427)

**Comment by csadilek** [comment]
This doesn't happen anymore. Closing.
