### ISSUE TITLE
[Crash] IllegalStateException: GeckoResult is complete (in onLoadRequest)

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#5127]
Saw this new crash: https://sentry.prod.mozaws.net/operations/fenix-nightly/?environment=fenixNightly&query=is%3Aunresolved+result+is+already+complete

Happens in `EngineObserver.onLoadRequest`. Looks like it was introduced by https://github.com/mozilla-mobile/android-components/issues/4950, which last changed `onLoadRequest` in `EngineObserver` and `GeckoEngineSession`.

/cc @rocketsroger (Happy to help look into it)

```
java.lang.IllegalStateException: result is already complete
    at org.mozilla.geckoview.GeckoResult.complete(GeckoResult.java:7)
    at -$$LambdaGroup$ks$o9doJfz7AB6U70DTkcSBdVdRCWg.invoke(com.android.tools.r8.jetbrains.kotlin-style lambda group:22)
    at mozilla.components.browser.session.Session$$special$$inlined$vetoable$1.beforeChange(Delegates.kt:9)
    at kotlin.properties.ObservableProperty.setValue(ObservableProperty.kt:2)
    at mozilla.components.browser.session.engine.EngineObserver.onLoadRequest(EngineObserver.kt:6)
    at -$$LambdaGroup$ks$FroDpmAIczInMwqVPB4tDIsP_m0.invoke(com.android.tools.r8.jetbrains.kotlin-style lambda group:6)
    at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:4)
    at mozilla.components.concept.engine.EngineSession.notifyObservers
    at mozilla.components.browser.engine.gecko.GeckoEngineSession$createNavigationDelegate$1.onLoadRequest(GeckoEngineSession.kt:15)
    at org.mozilla.geckoview.GeckoSession$3.handleMessage(GeckoSession.java:41)
    at org.mozilla.geckoview.GeckoSession$3.handleMessage(GeckoSession.java:1)
    at org.mozilla.geckoview.GeckoSessionHandler.handleMessage(GeckoSessionHandler.java:2)
    at org.mozilla.gecko.EventDispatcher$3.run(EventDispatcher.java:1)
    at android.os.Handler.handleCallback(Handler.java:808)
    at android.os.Handler.dispatchMessage(Handler.java:101)
    at android.os.Looper.loop(Looper.java:166)
    at android.app.ActivityThread.main(ActivityThread.java:7523)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

**Comment by rocketsroger** [comment]
I'll look into this.

**Comment by rocketsroger** [comment]
https://github.com/mozilla-mobile/android-components/issues/5243 will move `AppLinksFeature` out of the observer mechanism.  Keeping this open to confirm this is fixed after merging https://github.com/mozilla-mobile/android-components/issues/5243

**Comment by rocketsroger** [comment]
Fixed by https://github.com/mozilla-mobile/fenix/issues/7156
