### ISSUE TITLE
Crash in java.util.NoSuchElementException: at mozilla.components.feature.push.AutoPushFeature$onMessageReceived$1.invokeSuspend(AutoPushFeature.kt:27)

### ISSUE THREAD

**Issue by mozillamarcia** [mozilla-mobile/android-components#5134]
Seen while looking at Fenix nightly crash stats. #4 overall: https://bit.ly/2XANCKm

```
java.util.NoSuchElementException: Array contains no element matching the predicate.
	at mozilla.components.feature.push.AutoPushFeature$onMessageReceived$1.invokeSuspend(AutoPushFeature.kt:27)
	at mozilla.components.feature.push.AutoPushFeature$onMessageReceived$1.invoke(Unknown Source:10)
	at mozilla.components.feature.push.AutoPushFeatureKt$launchAndTry$1.invokeSuspend(AutoPushFeature.kt:5)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:15)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
```

**Comment by jonalmeida** [comment]
There's a strong relation between this and https://github.com/mozilla-mobile/fenix/issues/6663

**Comment by jonalmeida** [comment]
This should go away when we have better support for multiple scoped UUIDs.

**Comment by ebalazs-sv** [comment]
Verified as fixed.
There are no more crashes with this signature in [Fenix crash stats](https://crash-stats.mozilla.org/search/?signature=~java.util.NoSuchElementException%3A%20at%20mozilla.components.feature.push.AutoPushFeature%24onMessageReceived%241.invokeSuspend%28AutoPushFeature.kt%3A27%29&date=%3E%3D2019-12-04T12%3A42%3A00.000Z&date=%3C2019-12-16T12%3A42%3A00.000Z&_facets=signature&page=1&_sort=-date&_columns=date&_columns=signature&_columns=product&_columns=version&_columns=build_id&_columns=platform#facet-signature).
I will mark this as Done.
