### ISSUE TITLE
Intermittent test failure in SessionStorageTest

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#5166]
```
[task 2019-11-26T20:19:34.893Z]   TEST: AutoSave - periodically in foreground
[task 2019-11-26T20:19:34.893Z]     [Robolectric] mozilla.components.browser.session.storage.SessionStorageTest.AutoSave - periodically in foreground: sdk=28; resources=binary
[task 2019-11-26T20:19:34.893Z]     I/MonitoringInstr: Instrumentation started!
[task 2019-11-26T20:19:34.893Z]     I/MonitoringInstr: Setting context classloader to 'org.robolectric.internal.bytecode.SandboxClassLoader@6f75c79', Original: 'org.robolectric.internal.bytecode.SandboxClassLoader@6f75c79'
[task 2019-11-26T20:19:35.293Z]   FAILURE
```

Logs: https://firefoxci.taskcluster-artifacts.net/GyGUdRbJSKyt7sTcJ4zNQw/0/public/logs/live_backing.log

**Comment by pocmo** [comment]
```
[task 2019-11-26T20:19:35.293Z] java.lang.IllegalStateException: LifecycleOwner of this LifecycleRegistry is alreadygarbage collected. It is too late to change lifecycle state.
[task 2019-11-26T20:19:35.293Z] 	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:327)
[task 2019-11-26T20:19:35.293Z] 	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:145)
[task 2019-11-26T20:19:35.293Z] 	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:131)
[task 2019-11-26T20:19:35.293Z] 	at mozilla.components.browser.session.storage.SessionStorageTest.AutoSave - periodically in foreground(SessionStorageTest.kt:391)
```
