### ISSUE TITLE
Test failure in build-feature-push - subscribe calls Rust API

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#5203]
Saw this in https://github.com/mozilla-mobile/android-components/pull/5131
cc @jonalmeida 
```
[task 2019-11-29T20:10:21.377Z]   TEST: subscribe calls Rust API
[task 2019-11-29T20:10:21.377Z]   FAILURE
[task 2019-11-29T20:10:21.377Z] 
[task 2019-11-29T20:10:21.377Z] org.mockito.exceptions.misusing.InvalidUseOfMatchersException: 
[task 2019-11-29T20:10:21.377Z] Invalid use of argument matchers!
[task 2019-11-29T20:10:21.378Z] 3 matchers expected, 2 recorded:
[task 2019-11-29T20:10:21.378Z] -> at mozilla.components.feature.push.RustPushConnectionTest.subscribe calls Rust API(RustPushConnectionTest.kt:68)
[task 2019-11-29T20:10:21.378Z] -> at mozilla.components.feature.push.RustPushConnectionTest.subscribe calls Rust API(RustPushConnectionTest.kt:68)
[task 2019-11-29T20:10:21.378Z] 
[task 2019-11-29T20:10:21.378Z] This exception may occur if matchers are combined with raw values:
[task 2019-11-29T20:10:21.378Z]     //incorrect:
[task 2019-11-29T20:10:21.378Z]     someMethod(anyObject(), "raw String");
[task 2019-11-29T20:10:21.378Z] When using matchers, all arguments have to be provided by matchers.
[task 2019-11-29T20:10:21.378Z] For example:
[task 2019-11-29T20:10:21.379Z]     //correct:
[task 2019-11-29T20:10:21.379Z]     someMethod(anyObject(), eq("String by matcher"));
[task 2019-11-29T20:10:21.379Z] 
[task 2019-11-29T20:10:21.379Z] For more info see javadoc for Matchers class.
[task 2019-11-29T20:10:21.379Z] 
[task 2019-11-29T20:10:21.379Z] 	at mozilla.appservices.push.PushAPI$DefaultImpls.subscribe$default(PushManager.kt:346)
[task 2019-11-29T20:10:21.379Z] 	at mozilla.components.feature.push.RustPushConnectionTest.subscribe calls Rust API(RustPushConnectionTest.kt:68)
[task 2019-11-29T20:10:21.379Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2019-11-29T20:10:21.379Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2019-11-29T20:10:21.379Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2019-11-29T20:10:21.379Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2019-11-29T20:10:21.379Z] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[task 2019-11-29T20:10:21.379Z] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[task 2019-11-29T20:10:21.380Z] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[task 2019-11-29T20:10:21.380Z] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[task 2019-11-29T20:10:21.380Z] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
[task 2019-11-29T20:10:21.380Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
[task 2019-11-29T20:10:21.380Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
[task 2019-11-29T20:10:21.380Z] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[task 2019-11-29T20:10:21.381Z] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[task 2019-11-29T20:10:21.381Z] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[task 2019-11-29T20:10:21.381Z] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[task 2019-11-29T20:10:21.381Z] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[task 2019-11-29T20:10:21.382Z] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[task 2019-11-29T20:10:21.382Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
[task 2019-11-29T20:10:21.382Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
[task 2019-11-29T20:10:21.382Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
[task 2019-11-29T20:10:21.382Z] 	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
[task 2019-11-29T20:10:21.382Z] 	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
```

**Comment by jonalmeida** [comment]
Oh wait no, this is the other part of the as upgrade with the push API changes.

**Comment by jonalmeida** [comment]
This was an API change, not an intermittent failure. The linked PR fixed it.
