### ISSUE TITLE
Intermittent test failure service-experiments - test even distribution

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#5204]
Saw this in #5131.

```
[task 2019-11-29T23:15:55.614Z]   TEST: test even distribution
[task 2019-11-29T23:15:55.614Z]     [Robolectric] mozilla.components.service.experiments.ExperimentEvaluatorTest.test even distribution: sdk=28; resources=binary
[task 2019-11-29T23:15:55.614Z]     I/MonitoringInstr: Instrumentation started!
[task 2019-11-29T23:15:55.614Z]     I/MonitoringInstr: Setting context classloader to 'org.robolectric.internal.bytecode.SandboxClassLoader@5aa1c7b4', Original: 'org.robolectric.internal.bytecode.SandboxClassLoader@5aa1c7b4'
[task 2019-11-29T23:15:56.514Z]   FAILURE

[task 2019-11-29T23:15:56.514Z] java.lang.AssertionError
[task 2019-11-29T23:15:56.514Z] 	at org.junit.Assert.fail(Assert.java:86)
[task 2019-11-29T23:15:56.514Z] 	at org.junit.Assert.assertTrue(Assert.java:41)
[task 2019-11-29T23:15:56.514Z] 	at org.junit.Assert.assertTrue(Assert.java:52)
[task 2019-11-29T23:15:56.514Z] 	at mozilla.components.service.experiments.ExperimentEvaluatorTest.test even distribution(ExperimentEvaluatorTest.kt:766)
[task 2019-11-29T23:15:56.514Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2019-11-29T23:15:56.514Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2019-11-29T23:15:56.514Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2019-11-29T23:15:56.514Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2019-11-29T23:15:56.514Z] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[task 2019-11-29T23:15:56.514Z] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[task 2019-11-29T23:15:56.514Z] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[task 2019-11-29T23:15:56.514Z] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[task 2019-11-29T23:15:56.514Z] 	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:601)
[task 2019-11-29T23:15:56.514Z] 	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:260)
[task 2019-11-29T23:15:56.514Z] 	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
[task 2019-11-29T23:15:56.514Z] 	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
[task 2019-11-29T23:15:56.514Z] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[task 2019-11-29T23:15:56.514Z] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[task 2019-11-29T23:15:56.514Z] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[task 2019-11-29T23:15:56.514Z] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[task 2019-11-29T23:15:56.514Z] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[task 2019-11-29T23:15:56.514Z] 	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
[task 2019-11-29T23:15:56.514Z] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[task 2019-11-29T23:15:56.514Z] 	at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:104)
[task 2019-11-29T23:15:56.514Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
[task 2019-11-29T23:15:56.514Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
[task 2019-11-29T23:15:56.514Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
[task 2019-11-29T23:15:56.514Z] 	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
[task 2019-11-29T23:15:56.514Z] 	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
[task 2019-11-29T23:15:56.514Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2019-11-29T23:15:56.514Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2019-11-29T23:15:56.514Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2019-11-29T23:15:56.514Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2019-11-29T23:15:56.514Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
[task 2019-11-29T23:15:56.514Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[task 2019-11-29T23:15:56.514Z] 	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
[task 2019-11-29T23:15:56.514Z] 	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
[task 2019-11-29T23:15:56.514Z] 	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
[task 2019-11-29T23:15:56.514Z] 	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
[task 2019-11-29T23:15:56.514Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2019-11-29T23:15:56.514Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2019-11-29T23:15:56.514Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2019-11-29T23:15:56.514Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2019-11-29T23:15:56.514Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
[task 2019-11-29T23:15:56.514Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[task 2019-11-29T23:15:56.514Z] 	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
[task 2019-11-29T23:15:56.514Z] 	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
[task 2019-11-29T23:15:56.514Z] 	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
[task 2019-11-29T23:15:56.514Z] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
[task 2019-11-29T23:15:56.514Z] 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
[task 2019-11-29T23:15:56.514Z] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[task 2019-11-29T23:15:56.514Z] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[task 2019-11-29T23:15:56.514Z] 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
[task 2019-11-29T23:15:56.515Z] 	at java.lang.Thread.run(Thread.java:748)]
```

**Comment by grigoryk** [comment]
cc @georgf

**Comment by travis79** [comment]
> cc @georgf

Georg is still afk.

cc @mythmon
