### ISSUE TITLE
NetworkOnMainThread when reporting crash from notification (RB)

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#5215]
In Reference Browser whenever I click the "report" button in the crash notification then it immediately crashes again. I think I saw NetworkOnMainThread in the logs, but I couldn't really read them on my phone.

**Comment by pocmo** [comment]
Just go this for Fenix too after reporting a crash from the notification ("report" action):

```
                         E  java.lang.RuntimeException: Unable to start service mozilla.components.lib.crash.service.SendCrashReportService@899fae9 with Intent { flg=0x10000000 cmp=org.mozilla.fennec_aurora/mozilla.components.lib.crash.service.SendCrashReportService bnds=[22,691][213,823] (has extras) }: android.os.N
                            etworkOnMainThreadException
                         E      at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4105)
                         E      at android.app.ActivityThread.access$1800(ActivityThread.java:219)
                         E      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
                         E      at android.os.Handler.dispatchMessage(Handler.java:107)
                         E      at android.os.Looper.loop(Looper.java:214)
                         E      at android.app.ActivityThread.main(ActivityThread.java:7356)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
                         E  Caused by: android.os.NetworkOnMainThreadException
                         E      at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1565)
                         E      at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:115)
                         E      at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
                         E      at java.net.InetAddress.getAllByName(InetAddress.java:1152)
                         E      at com.android.okhttp.Dns$1.lookup(Dns.java:41)
                         E      at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:178)
                         E      at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:144)
                         E      at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:86)
                         E      at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:176)
                         E      at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
                         E      at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
                         E      at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
                         E      at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
                         E      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
                         E      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
                         E      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
                         E      at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
                         E      at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
                         E      at mozilla.components.lib.crash.service.MozillaSocorroService.sendReport$lib_crash_release(MozillaSocorroService.kt:10)
                         E      at mozilla.components.lib.crash.service.MozillaSocorroService.report(MozillaSocorroService.kt:2)
                         E      at mozilla.components.lib.crash.CrashReporter.submitReport(CrashReporter.kt:4)
                         E      at mozilla.components.lib.crash.service.SendCrashReportService.onStartCommand(SendCrashReportService.kt:23)
                         E      at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4087)
                         E      ... 8 more
```
