### ISSUE TITLE
Sample browser crashing due to FATAL EXCEPTION: IconThread

### ISSUE THREAD

**Issue by psymoon** [mozilla-mobile/android-components#5260]
```
2019-12-08 16:30:55.911 11827-11924/org.mozilla.samples.browser E/AndroidRuntime: FATAL EXCEPTION: IconThread
    Process: org.mozilla.samples.browser, PID: 11827
    java.lang.IllegalArgumentException: Could not process image.
        at org.mozilla.gecko.mozglue.GeckoLoader.nativeRun(Native Method)
        at org.mozilla.gecko.GeckoThread.run(GeckoThread.java:476)
```

Seems to be happening on `geckoNightlyDebug`

**Comment by psymoon** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1602565

**Comment by psymoon** [comment]
@csadilek and I both verify the new gecko nightly update fixed this bug.
