### ISSUE TITLE
Fennec migration: Beta/Nighty migration build crashes after start

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/android-components#5276]
## Preconditions:
Have Firefox Beta/Nightly installed and logged in.
## Steps to reproduce
1. Replace Fennec Beta/Nightly with Fenix using a Beta/Nightly build from https://github.com/mozilla-mobile/fenix/wiki/Fennec-Migration;
2. Launch Fenix.
### Expected behavior
Fenix opens.
### Actual behavior
Fenix crashes.
### Notes:
[crash.txt](https://github.com/mozilla-mobile/android-components/files/3945075/crash.txt)

### Device information

* Android device: Samsung Galaxy S8 (Android 9) - ARM64; Motorola Nexus 6 (Android 7.1.1); Xiaomi Mi Pad 2 (Android 5.1).
* Fenix version: Beta 12/10 GV 71; Nightly 191210 GV 72

**Comment by ebalazs-sv** [comment]
Each time Fenix crashes, the opened tabs are added one more time in the Open tabs list.

**Comment by ebalazs-sv** [comment]
I had tested this on Beta and Nightly migration builds from 01/08 with Google Pixel 3 (Android Q), Samsung Galaxy S8 (Android 9), Huawei Honor 8 (Android 7.0) and this is still reproducible with the following signature:

`    --------- beginning of crash
2020-01-08 12:21:24.598 15905-15905/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.firefox_beta, PID: 15905
    java.lang.ExceptionInInitializerError
        at kotlinx.coroutines.EventLoopKt.settings$default(EventLoop.kt:1)
        at org.mozilla.fenix.FenixApplication.setupInMainProcessOnly(FenixApplication.kt:5)
        at org.mozilla.fenix.MigratingFenixApplication.setupInMainProcessOnly(MigratingFenixApplication.kt:13)
        at org.mozilla.fenix.FenixApplication.onCreate(FenixApplication.kt:4)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalStateException: Unknown build type: fennecBeta
        at org.mozilla.fenix.Config.<clinit>(Config.kt:3)
        at kotlinx.coroutines.EventLoopKt.settings$default(EventLoop.kt:1) 
        at org.mozilla.fenix.FenixApplication.setupInMainProcessOnly(FenixApplication.kt:5) 
        at org.mozilla.fenix.MigratingFenixApplication.setupInMainProcessOnly(MigratingFenixApplication.kt:13) 
        at org.mozilla.fenix.FenixApplication.onCreate(FenixApplication.kt:4) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:219) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) `

**Comment by pocmo** [comment]
Fenix introduced a release variant config and ignored the fennec beta and nightly flavors. I"m going to fix that.

**Comment by pocmo** [comment]
With the next upcoming build that should hopefully be fixed.

**Comment by ebalazs-sv** [comment]
@pocmo I had tested this on Release, Beta, Nightly migration builds from 01/10 with Samsung Galaxy S8 (Android 9), OnePlus 5T (Android 9), Huawei Honor 8 (Android 7.0), Xiaomi Mi4i (Android 5.0.2) and the app still crashes only when logged in. The crash happens before the account is migrated. 
`    --------- beginning of crash
2020-01-10 11:35:21.913 13979-14268/? E/AndroidRuntime: FATAL EXCEPTION: Firebase-FirebasePush
    Process: org.mozilla.firefox_beta, PID: 13979
    java.lang.IllegalStateException: You need to call PushProcessor.install() on your Push instance from Application.onCreate().
        at mozilla.components.concept.push.PushProcessor$Companion.getRequireInstance(PushProcessor.kt:1)
        at org.mozilla.fenix.components.FirebasePush.onMessageReceived(FirebasePush.kt:8)
        at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:178)
        at com.google.firebase.iid.zzg.run(Unknown Source:5)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:2)
        at java.lang.Thread.run(Thread.java:764)`

[logcat](https://github.com/mozilla-mobile/android-components/files/4044917/startcrash.txt)

**Comment by pocmo** [comment]
This looks like a different crash. I'll move this to a separate bug.

**Comment by pocmo** [comment]
https://github.com/mozilla-mobile/android-components/issues/5586

**Comment by ebalazs-sv** [comment]
Verified as fixed on Fennec Migration Nightly build 1 with Samsung Galaxy S8 (Android 9) - ARM64, Xiaomi Mi Pad 2 (Android 5.1) - x86, OnePlus 6T (Android 9.0) - ARM. Fenix does not crash after the migration.
I will move this to Done. Thanks!
