### ISSUE TITLE
Fennec Nightly Upgrade: IllegalStateException : Not allowed to start service Intent

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#5329]
Crash when upgrading Fennec Nightly with a Fenix build.

```
E  FATAL EXCEPTION: main
E  Process: org.mozilla.fennec_aurora, PID: 29582
E  java.lang.RuntimeException: Unable to create application org.mozilla.fenix.MigratingFenixApplication: java.lang.IllegalStateException
: Not allowed to start service Intent { cmp=org.mozilla.fennec_aurora/org.mozilla.fenix.MigrationService }: app is in background uid
UidRecord{cbc9e67 u0a91 TRNB idle procs:1 seq(0,0,0)}
E      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5876)
E      at android.app.ActivityThread.access$1100(ActivityThread.java:199)
E      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
E      at android.os.Handler.dispatchMessage(Handler.java:106)
E      at android.os.Looper.loop(Looper.java:193)
E      at android.app.ActivityThread.main(ActivityThread.java:6669)
E      at java.lang.reflect.Method.invoke(Native Method)
E      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E  Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.mozilla.fennec_aurora/org.mozilla.fenix.Mig
rationService }: app is in background uid UidRecord{cbc9e67 u0a91 TRNB idle procs:1 seq(0,0,0)}
E      at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1577)
E      at android.app.ContextImpl.startService(ContextImpl.java:1532)
E      at android.content.ContextWrapper.startService(ContextWrapper.java:664)
E      at org.mozilla.fenix.MigratingFenixApplication.setupInMainProcessOnly(MigratingFenixApplication.kt:17)
E      at org.mozilla.fenix.FenixApplication.onCreate(FenixApplication.kt:4)
E      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
E      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
E      ... 8 more
```

**Comment by pocmo** [comment]
This only happens together with the widget after https://github.com/mozilla-mobile/fenix/pull/7202 lands. When the app is updated and the widget is on the home screen (and at least while looking at the home screen), Android will restart the application process for the widget. This will cause the migration to start happening while the app is in the background and Android will deny running this service.

**Comment by ebalazs-sv** [comment]
Hi! This is reproducible with today's Release, Beta, Nightly migration builds 12/19 with Pixel 2 (Android 9):

```
2019-12-19 11:51:31.530 23978-23978/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.firefox_beta, PID: 23978
    java.lang.RuntimeException: Unable to create application org.mozilla.fenix.MigratingFenixApplication: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.mozilla.firefox_beta/org.mozilla.fenix.MigrationService }: app is in background uid UidRecord{3f0efd3 u0a442 TRNB bg:+10m51s413ms idle procs:3 seq(0,0,0)}
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5925)
        at android.app.ActivityThread.access$1100(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.mozilla.firefox_beta/org.mozilla.fenix.MigrationService }: app is in background uid UidRecord{3f0efd3 u0a442 TRNB bg:+10m51s413ms idle procs:3 seq(0,0,0)}
        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1577)
        at android.app.ContextImpl.startService(ContextImpl.java:1532)
        at android.content.ContextWrapper.startService(ContextWrapper.java:664)
        at org.mozilla.fenix.MigratingFenixApplication.setupInMainProcessOnly(MigratingFenixApplication.kt:17)
        at org.mozilla.fenix.FenixApplication.onCreate(FenixApplication.kt:4)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5920)
        at android.app.ActivityThread.access$1100(ActivityThread.java:200) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6718) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)  
```

Not reproducible on Huawei Honor 8 (Android 7.0), Google Pixel 3 (Android Q).

**Comment by ebalazs-sv** [comment]
Verified as fixed on Release migration build 1/3 GV 72 with

- Google Pixel 3 (Android Q);
- Samsung Galaxy Note 8 (Android 9);
- Nexus 6P (Android 8.1.0).

When the app is updated and the widget is on the home screen it doesn't crash.  I will mark this as Done.
