### ISSUE TITLE
Migration crash loop: LoginsStorageException: The logins tables are not empty

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#5346]
I accidentally updated Firefox Nightly on my phone to Fenix. Now I am in a migration crash loop. Whenever I start the app the migration starts and then after some seconds the app crashes.

```
         AndroidRuntime  E  FATAL EXCEPTION: main
                         E  Process: org.mozilla.fennec_aurora, PID: 13350
                         E  mozilla.appservices.logins.LoginsStorageException: The logins tables are not empty
                         E      at mozilla.appservices.logins.rust.RustError.intoException(RustError.kt:4)
                         E      at mozilla.appservices.logins.DatabaseLoginsStorage.importLogins(DatabaseLoginsStorage.kt:12)
                         E      at mozilla.components.service.sync.logins.AsyncLoginsStorageAdapter$importLoginsAsync$1.invokeSuspend(AsyncLoginsStorage
                            .kt:6)
                         E      at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
                         E      at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
                         E      at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
                         E      at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:15)
```

**Comment by pocmo** [comment]
https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/issues/6865643/

**Comment by ebalazs-sv** [comment]
Hi! I need to have access to Sentry to verify this issue. @kbrosnan Could you please help with that? Thanks!

**Comment by kbrosnan** [comment]
Sentry only makes sense for verification of issues that are in general release. There are only a handful of people running the migration code.

**Comment by ebalazs-sv** [comment]
st3fan confirmed that we can move this to Done. Thanks!
