### ISSUE TITLE
mozilla.appservices.syncmanager.UnexpectedError: Handle is invalid: Tried to use a null handle

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#5383]
Just saw this in my device log:

```
E  Work [ id=dd0561e0-a6d7-4410-8fbb-c2333d7f7e1e, tags={ mozilla.components.service.fxa.sync.WorkManagerSyncWorker, Debounce, Common } ] failed because it threw an exception/error
E  java.util.concurrent.ExecutionException: mozilla.appservices.syncmanager.UnexpectedError: Handle is invalid: Tried to use a null handle (this object has probably been closed)
E      at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:4)
E      at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:48)
E      at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:1)
E      at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:1)
E      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E      at java.lang.Thread.run(Thread.java:919)
E  Caused by: mozilla.appservices.syncmanager.UnexpectedError: Handle is invalid: Tried to use a null handle (this object has probably been closed)
E      at mozilla.appservices.syncmanager.RustError.intoException(RustError.kt:4)
E      at mozilla.appservices.syncmanager.SyncManager.setLogins(SyncManager.kt:4)
E      at mozilla.components.service.fxa.sync.WorkManagerSyncWorker.doSync(WorkManagerSyncManager.kt:10)
E      at mozilla.components.service.fxa.sync.WorkManagerSyncWorker$doWork$2.invokeSuspend(WorkManagerSyncManager.kt:2)
E      at mozilla.components.service.fxa.sync.WorkManagerSyncWorker$doWork$2.invoke(Unknown Source:10)
E      at mozilla.components.service.sync.logins.SyncableLoginsStore.unlocked(AsyncLoginsStorage.kt:6)
E      at mozilla.components.service.sync.logins.SyncableLoginsStore$unlocked$1.invokeSuspend(Unknown Source:12)
E      at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
E      at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
E      at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
E      at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:15)
I  Worker result FAILURE for Work [ id=dd0561e0-a6d7-4410-8fbb-c2333d7f7e1e, tags={ mozilla.components.service.fxa.sync.WorkManagerSyncWorker, Debounce, Common } ]
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4648)

**Comment by csadilek** [comment]
We're not seeing this anymore, closing for now.
