### ISSUE TITLE
AbstractMethodError: at GeckoEngineSession.createNavigationDelegate.onLoadRequest

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#5402]
Crash report: [[link]](https://crash-stats.mozilla.com/signature/?product=ReferenceBrowser&version=73.0a1&signature=java.lang.AbstractMethodError%3A%20at%20mozilla.components.browser.engine.gecko.GeckoEngineSession%24createNavigationDelegate%241%24onLoadRequest%241.invoke%28GeckoEngineSession.kt%3A391%29&date=%3E%3D2019-12-16T21%3A31%3A00.000Z&date=%3C2019-12-23T21%3A31%3A00.000Z&_columns=date&_columns=product&_columns=version&_columns=build_id&_columns=platform&_columns=reason&_columns=address&_columns=install_time&_columns=startup_crash&_sort=-date&page=1#summary)

Seeing many of these crashes.

```
java.lang.AbstractMethodError
	at mozilla.components.browser.engine.gecko.GeckoEngineSession$createNavigationDelegate$1$onLoadRequest$1.invoke(GeckoEngineSession.kt:391)
	at mozilla.components.browser.engine.gecko.GeckoEngineSession$createNavigationDelegate$1$onLoadRequest$1.invoke(GeckoEngineSession.kt:329)
	at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:137)
	at mozilla.components.concept.engine.EngineSession.notifyObservers(Unknown Source:7)
	at mozilla.components.browser.engine.gecko.GeckoEngineSession$createNavigationDelegate$1.onLoadRequest(GeckoEngineSession.kt:387)
	at org.mozilla.geckoview.GeckoSession$3.handleMessage(GeckoSession.java:560)
	at org.mozilla.geckoview.GeckoSession$3.handleMessage(GeckoSession.java:499)
	at org.mozilla.geckoview.GeckoSessionHandler.handleMessage(GeckoSessionHandler.java:90)
	at org.mozilla.gecko.EventDispatcher$3.run(EventDispatcher.java:373)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

**Comment by jonalmeida** [comment]
cc: @rocketsroger in case you have any info into what this cause could be.

**Comment by jonalmeida** [comment]
Closed in error. 😄

**Comment by rocketsroger** [comment]
I seen this before when there's a cache issue in the build.  Locally when I see it usually clear cache fixes it.  Looks like these crashes stopped on Dec 22nd.

**Comment by jonalmeida** [comment]
Hmm interesting, @gabrielluong saw the crash today on a fresh install of r-b, but I guess you're right. The maven-metadata.xml bug is at it again!

Thanks for the info Roger!

**Comment by jonalmeida** [comment]
^ Actually meant to close it this time.
