### ISSUE TITLE
feature-downloads tests fail with OutOfMemoryError

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#5419]
Tests is feature-downloads fail locally for me.

I was able to reproduce this with `./gradlew :feature-downloads:testDebug`.

<details>
<summary>Stack trace</summary>

```
Exception in thread "DefaultDispatcher-worker-2 @coroutine#7" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at net.bytebuddy.description.type.TypeDescription$Generic$AnnotationReader$Dispatcher$ForJava8CapableVm.resolveParameterType(TypeDescription.java:2708)
        at net.bytebuddy.description.type.TypeDescription$Generic$LazyProjection$OfMethodParameter.getAnnotationReader(TypeDescription.java:6636)
        at net.bytebuddy.description.type.TypeDescription$Generic$LazyProjection$OfMethodParameter.resolve(TypeDescription.java:6623)
        at net.bytebuddy.description.type.TypeDescription$Generic$LazyProjection.accept(TypeDescription.java:6106)
        at net.bytebuddy.description.method.ParameterDescription$TypeSubstituting.getType(ParameterDescription.java:1057)
        at net.bytebuddy.description.method.ParameterList$AbstractBase.asTypeList(ParameterList.java:109)
        at net.bytebuddy.description.method.MethodDescription$AbstractBase.asTypeToken(MethodDescription.java:837)
        at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default$Key$Store.asGraph(MethodGraph.java:1170)
        at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.compile(MethodGraph.java:577)
        at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$AbstractBase.compile(MethodGraph.java:465)
        at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isOverridden(MockMethodAdvice.java:134)
        at java.io.InputStream.read(InputStream.java:101)
        at mozilla.components.feature.downloads.AbstractFetchDownloadService.copyInChunks$feature_downloads_debug(AbstractFetchDownloadService.kt:358)
        at mozilla.components.feature.downloads.AbstractFetchDownloadService$performDownload$1$1.invoke(AbstractFetchDownloadService.kt:333)
        at mozilla.components.feature.downloads.AbstractFetchDownloadService$performDownload$1$1.invoke(AbstractFetchDownloadService.kt:68)
        at mozilla.components.feature.downloads.AbstractFetchDownloadService.useFileStreamLegacy(AbstractFetchDownloadService.kt:450)
        at mozilla.components.feature.downloads.AbstractFetchDownloadService.useFileStream$feature_downloads_debug(AbstractFetchDownloadService.kt:401)
        at mozilla.components.feature.downloads.AbstractFetchDownloadService$performDownload$1.invoke(AbstractFetchDownloadService.kt:332)
        at mozilla.components.feature.downloads.AbstractFetchDownloadService$performDownload$1.invoke(AbstractFetchDownloadService.kt:68)
        at mozilla.components.concept.fetch.Response$Body.useStream(Response.kt:79)
        at mozilla.components.feature.downloads.AbstractFetchDownloadService.performDownload$feature_downloads_debug(AbstractFetchDownloadService.kt:328)
        at mozilla.components.feature.downloads.AbstractFetchDownloadService.startDownloadJob$feature_downloads_debug(AbstractFetchDownloadService.kt:282)
        at mozilla.components.feature.downloads.AbstractFetchDownloadService$broadcastReceiver$2$1$onReceive$3.invokeSuspend(AbstractFetchDownloadService.kt:123)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
Exception in thread "DefaultDispatcher-worker-2 @coroutine#7" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at net.bytebuddy.description.type.TypeDescription$Generic$AnnotationReader$Dispatcher$ForJava8CapableVm.resolveParameterType(TypeDescription.java:2708)
        at net.bytebuddy.description.type.TypeDescription$Generic$LazyProjection$OfMethodParameter.getAnnotationReader(TypeDescription.java:6636)
        at net.bytebuddy.description.type.TypeDescription$Generic$LazyProjection$OfMethodParameter.resolve(TypeDescription.java:6623)
        at net.bytebuddy.description.type.TypeDescription$Generic$LazyProjection.accept(TypeDescription.java:6106)
        at net.bytebuddy.description.method.ParameterDescription$TypeSubstituting.getType(ParameterDescription.java:1057)
        at net.bytebuddy.description.method.ParameterList$AbstractBase.asTypeList(ParameterList.java:109)
        at net.bytebuddy.description.method.MethodDescription$AbstractBase.asTypeToken(MethodDescription.java:837)
        at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default$Key$Store.asGraph(MethodGraph.java:1170)
        at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.compile(MethodGraph.java:577)
        at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$AbstractBase.compile(MethodGraph.java:465)
        at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isOverridden(MockMethodAdvice.java:134)
        at java.io.InputStream.read(InputStream.java:101)
        at mozilla.components.feature.downloads.AbstractFetchDownloadService.copyInChunks$feature_downloads_debug(AbstractFetchDownloadService.kt:358)
Exception in thread "Thread-22" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "Thread-36" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "Thread-45" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "Thread-12" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "DefaultDispatcher-worker-2" kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for DispatchedContinuation[LimitingDispatcher@52cf9a38[dispatcher = DefaultDispatcher], Continuation at mozilla.components.feature.downloads.AbstractFetchDownloadService$broadcastReceiver$2$1$onReceive$3.invokeSuspend(AbstractFetchDownloadService.kt)@389b0059]. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
        at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:93)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:64)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.lang.StringBuilder.toString(StringBuilder.java:407)
        at java.lang.StackTraceElement.toString(StackTraceElement.java:173)
        at java.lang.String.valueOf(String.java:2994)
        at java.lang.StringBuilder.append(StringBuilder.java:131)
        at java.lang.Throwable.printStackTrace(Throwable.java:658)
        at java.lang.Throwable.printStackTrace(Throwable.java:643)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1061)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
        at kotlinx.coroutines.CoroutineExceptionHandlerImplKt.handleCoroutineExceptionImpl(CoroutineExceptionHandlerImpl.kt:39)
        at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:33)
        at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Builders.common.kt:182)
        at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:228)
        at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:902)
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:859)
        at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:824)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        ... 4 more
Exception in thread "DefaultDispatcher-worker-2" kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for DispatchedContinuation[LimitingDispatcher@52cf9a38[dispatcher = DefaultDispatcher], Continuation at mozilla.components.feature.downloads.AbstractFetchDownloadService$broadcastReceiver$2$1$onReceive$3.invokeSuspend(AbstractFetchDownloadService.kt)@389b0059]. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
        at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:93)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:64)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.lang.StringBuilder.toString(StringBuilder.java:407)
        at java.lang.StackTraceElement.toString(StackTraceElement.java:173)
        at java.lang.String.valueOf(String.java:2994)
        at java.lang.StringBuilder.append(StringBuilder.java:131)
        at java.lang.Throwable.printStackTrace(Throwable.java:658)
        at java.lang.Throwable.printStackTrace(Throwable.java:643)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1061)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
        at kotlinx.coroutines.CoroutineExceptionHandlerImplKt.handleCoroutineExceptionImpl(CoroutineExceptionHandlerImpl.kt:39)
        at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:33)
        at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Builders.common.kt:182)
        at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:228)
        at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:902)
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:859)
        at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:824)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        ... 4 more

```

</details>

This was seen happening in https://github.com/mozilla-mobile/android-components/pull/5285.

cc: @sblatz

**Comment by jonalmeida** [comment]
Opened https://github.com/mozilla-mobile/android-components/pull/5427 to revert the PR since all our builds are failing on that intermittent test failure and is blocking snapshot builds.

**Comment by sblatz** [comment]
https://github.com/mozilla-mobile/fenix/issues/7443 this looks to be what's happening! I didn't catch it in Sample Browser because the `onDownloadStopped` doesn't create a notification in Sample Browser 😄

**Comment by jonalmeida** [comment]
We can close this since the test failures were resolved.
