### ISSUE TITLE
Update to Kotlin 1.2.60

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#547]
https://blog.jetbrains.com/kotlin/2018/08/kotlin-1-2-60-is-out/

**Comment by pocmo** [comment]
```
java.lang.IllegalStateException: runBlocking is not allowed in Android main looper thread
	at kotlinx.coroutines.experimental.android.MainLooperChecker.checkRunBlocking(HandlerContext.kt:124)
	at kotlinx.coroutines.experimental.BuildersKt__BuildersKt.runBlocking(Builders.kt:42)
	at kotlinx.coroutines.experimental.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.experimental.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:41)
	at kotlinx.coroutines.experimental.BuildersKt.runBlocking$default(Unknown Source)
	at mozilla.components.browser.domains.CustomDomainsTest.testCustomListIsEmptyByDefault(CustomDomainsTest.kt:29)
```
