### ISSUE TITLE
Intermittent test failure in CrashReporterActivityTest

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#5508]
<details>

<summary>Test failure log</summary>

```
[task 2020-01-08T16:08:30.660Z]   TEST: Pressing restart button sends report
[task 2020-01-08T16:08:30.660Z]     [Robolectric] mozilla.components.lib.crash.prompt.CrashReporterActivityTest.Pressing restart button sends report: sdk=28; resources=binary
[task 2020-01-08T16:08:30.760Z]     I/MonitoringInstr: Instrumentation started!
[task 2020-01-08T16:08:30.760Z]     I/MonitoringInstr: Setting context classloader to 'org.robolectric.internal.bytecode.SandboxClassLoader@60952a16', Original: 'org.robolectric.internal.bytecode.SandboxClassLoader@60952a16'
[task 2020-01-08T16:08:30.760Z]     D/LifecycleMonitor: Lifecycle status change: mozilla.components.lib.crash.prompt.CrashReporterActivity@261ea2c2 in: PRE_ON_CREATE
[task 2020-01-08T16:08:30.760Z]     D/LifecycleMonitor: running callback: androidx.test.core.app.ActivityScenario$1@59edb17
[task 2020-01-08T16:08:30.760Z]     D/LifecycleMonitor: callback completes: androidx.test.core.app.ActivityScenario$1@59edb17
[task 2020-01-08T16:08:30.960Z]     D/LifecycleMonitor: Lifecycle status change: mozilla.components.lib.crash.prompt.CrashReporterActivity@261ea2c2 in: CREATED
[task 2020-01-08T16:08:30.960Z]     D/LifecycleMonitor: running callback: androidx.test.core.app.ActivityScenario$1@59edb17
[task 2020-01-08T16:08:30.960Z]     D/LifecycleMonitor: callback completes: androidx.test.core.app.ActivityScenario$1@59edb17
[task 2020-01-08T16:08:30.960Z]     D/LifecycleMonitor: Lifecycle status change: mozilla.components.lib.crash.prompt.CrashReporterActivity@261ea2c2 in: STARTED
[task 2020-01-08T16:08:30.960Z]     D/LifecycleMonitor: running callback: androidx.test.core.app.ActivityScenario$1@59edb17
[task 2020-01-08T16:08:30.960Z]     D/LifecycleMonitor: callback completes: androidx.test.core.app.ActivityScenario$1@59edb17
[task 2020-01-08T16:08:30.960Z]     D/LifecycleMonitor: Lifecycle status change: mozilla.components.lib.crash.prompt.CrashReporterActivity@261ea2c2 in: RESUMED
[task 2020-01-08T16:08:30.960Z]     D/LifecycleMonitor: running callback: androidx.test.core.app.ActivityScenario$1@59edb17
[task 2020-01-08T16:08:30.960Z]     D/LifecycleMonitor: callback completes: androidx.test.core.app.ActivityScenario$1@59edb17
[task 2020-01-08T16:08:31.060Z]     I [mozac/CrashReporter] Crash report submitted to 1 services
[task 2020-01-08T16:08:31.060Z]   FAILURE
[task 2020-01-08T16:08:31.060Z] 
[task 2020-01-08T16:08:31.060Z] Wanted but not invoked:
[task 2020-01-08T16:08:31.060Z] service.report(
[task 2020-01-08T16:08:31.060Z]     UncaughtExceptionCrash(throwable=java.lang.RuntimeException: Hello World, breadcrumbs=[])
[task 2020-01-08T16:08:31.060Z] );
[task 2020-01-08T16:08:31.060Z] -> at mozilla.components.lib.crash.prompt.CrashReporterActivityTest$Pressing restart button sends report$1.invokeSuspend(CrashReporterActivityTest.kt:90)
[task 2020-01-08T16:08:31.060Z] Actually, there were zero interactions with this mock.
[task 2020-01-08T16:08:31.060Z] 
[task 2020-01-08T16:08:31.060Z] 	at mozilla.components.lib.crash.prompt.CrashReporterActivityTest$Pressing restart button sends report$1.invokeSuspend(CrashReporterActivityTest.kt:90)
[task 2020-01-08T16:08:31.060Z] 	at mozilla.components.lib.crash.prompt.CrashReporterActivityTest$Pressing restart button sends report$1.invoke(CrashReporterActivityTest.kt)
[task 2020-01-08T16:08:31.060Z] 	at kotlinx.coroutines.test.TestBuildersKt$runBlockingTest$deferred$1.invokeSuspend(TestBuilders.kt:50)
[task 2020-01-08T16:08:31.060Z] 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[task 2020-01-08T16:08:31.060Z] 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
[task 2020-01-08T16:08:31.060Z] 	at kotlinx.coroutines.test.TestCoroutineDispatcher.dispatch(TestCoroutineDispatcher.kt:50)
[task 2020-01-08T16:08:31.060Z] 	at kotlinx.coroutines.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:271)
[task 2020-01-08T16:08:31.060Z] 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
[task 2020-01-08T16:08:31.060Z] 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
[task 2020-01-08T16:08:31.060Z] 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158)
[task 2020-01-08T16:08:31.060Z] 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.async(Builders.common.kt:89)
[task 2020-01-08T16:08:31.060Z] 	at kotlinx.coroutines.BuildersKt.async(Unknown Source)
[task 2020-01-08T16:08:31.060Z] 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.async$default(Builders.common.kt:82)
[task 2020-01-08T16:08:31.060Z] 	at kotlinx.coroutines.BuildersKt.async$default(Unknown Source)
[task 2020-01-08T16:08:31.060Z] 	at kotlinx.coroutines.test.TestBuildersKt.runBlockingTest(TestBuilders.kt:49)
[task 2020-01-08T16:08:31.060Z] 	at kotlinx.coroutines.test.TestBuildersKt.runBlockingTest$default(TestBuilders.kt:45)
[task 2020-01-08T16:08:31.060Z] 	at mozilla.components.lib.crash.prompt.CrashReporterActivityTest.Pressing restart button sends report(CrashReporterActivityTest.kt:72)
[task 2020-01-08T16:08:31.060Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2020-01-08T16:08:31.060Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2020-01-08T16:08:31.060Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2020-01-08T16:08:31.060Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2020-01-08T16:08:31.060Z] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[task 2020-01-08T16:08:31.060Z] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[task 2020-01-08T16:08:31.060Z] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[task 2020-01-08T16:08:31.060Z] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[task 2020-01-08T16:08:31.060Z] 	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:601)
[task 2020-01-08T16:08:31.060Z] 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
[task 2020-01-08T16:08:31.060Z] 	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:260)
[task 2020-01-08T16:08:31.060Z] 	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
[task 2020-01-08T16:08:31.060Z] 	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
[task 2020-01-08T16:08:31.060Z] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[task 2020-01-08T16:08:31.060Z] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[task 2020-01-08T16:08:31.060Z] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[task 2020-01-08T16:08:31.060Z] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[task 2020-01-08T16:08:31.060Z] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[task 2020-01-08T16:08:31.060Z] 	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
[task 2020-01-08T16:08:31.060Z] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[task 2020-01-08T16:08:31.060Z] 	at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:104)
[task 2020-01-08T16:08:31.060Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
[task 2020-01-08T16:08:31.060Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
[task 2020-01-08T16:08:31.060Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
[task 2020-01-08T16:08:31.060Z] 	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
[task 2020-01-08T16:08:31.060Z] 	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
[task 2020-01-08T16:08:31.060Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2020-01-08T16:08:31.060Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2020-01-08T16:08:31.060Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2020-01-08T16:08:31.060Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2020-01-08T16:08:31.060Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
[task 2020-01-08T16:08:31.060Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[task 2020-01-08T16:08:31.060Z] 	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
[task 2020-01-08T16:08:31.060Z] 	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
[task 2020-01-08T16:08:31.060Z] 	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
[task 2020-01-08T16:08:31.060Z] 	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
[task 2020-01-08T16:08:31.060Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2020-01-08T16:08:31.060Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2020-01-08T16:08:31.060Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2020-01-08T16:08:31.060Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2020-01-08T16:08:31.060Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
[task 2020-01-08T16:08:31.060Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[task 2020-01-08T16:08:31.060Z] 	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
[task 2020-01-08T16:08:31.060Z] 	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
[task 2020-01-08T16:08:31.060Z] 	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
[task 2020-01-08T16:08:31.060Z] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
[task 2020-01-08T16:08:31.060Z] 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
[task 2020-01-08T16:08:31.060Z] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[task 2020-01-08T16:08:31.060Z] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[task 2020-01-08T16:08:31.060Z] 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
[task 2020-01-08T16:08:31.060Z] 	at java.lang.Thread.run(Thread.java:748)
```

</details>

[Full CI logs.](https://firefoxci.taskcluster-artifacts.net/b32XZJBNQPyFFtl5u7dV7w/0/public/logs/live_backing.log)

**Comment by jonalmeida** [comment]
It seems like another random test is failing in the same unit test class:
```
[task 2020-01-08T17:34:46.652Z]   TEST: CrashReporter will submit report immediately for non native crash and with setup Prompt-ONLY_NATIVE_CRASH
[task 2020-01-08T17:34:46.652Z]     [Robolectric] mozilla.components.lib.crash.CrashReporterTest.CrashReporter will submit report immediately for non native crash and with setup Prompt-ONLY_NATIVE_CRASH: sdk=28; resources=binary
[task 2020-01-08T17:34:46.652Z]     I/MonitoringInstr: Instrumentation started!
[task 2020-01-08T17:34:46.652Z]     I/MonitoringInstr: Setting context classloader to 'org.robolectric.internal.bytecode.SandboxClassLoader@2a2c08f5', Original: 'org.robolectric.internal.bytecode.SandboxClassLoader@2a2c08f5'
[task 2020-01-08T17:34:46.652Z]     I [mozac/CrashReporter] Received crash: Mock for UncaughtExceptionCrash, hashCode: 1696081769
[task 2020-01-08T17:34:46.652Z]     I [mozac/CrashReporter] Immediately submitting crash report
[task 2020-01-08T17:34:46.652Z]     I [mozac/CrashReporter] Crash report submitted to 1 services
[task 2020-01-08T17:34:46.752Z]   FAILURE
```

Build: https://github.com/mozilla-mobile/android-components/runs/379833236
Logs: https://firefoxci.taskcluster-artifacts.net/T0lOryFrSSqGIFAif_ctLQ/0/public/logs/live_backing.log
