### ISSUE TITLE
Fennec migration: page shortcuts don't work after migration on some devices

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/android-components#5608]
STR:
1. From fennec, add a few page shortcuts on the homescreen.
2. Migrate to Fenix.
3. Tap the shortcuts to open them in Fenix.

Expected results:
Shortcuts open in Fenix.

Actual results:
Shortcuts don't open.  I get an "App isn't installed" error.

Build: 1/16 Nightly migration build
Devices: HTC Desire 820 (Android 6.0.1), Huawei Honor 8 (Android 7.0)
Not reproducing on: 
Samsung Galaxy S8 (Android 9), OnePlus 6T (Android 9), Pixel XL (Android Q)

**Comment by pocmo** [comment]
Can you provide us a log from those devices from around the time where you are pressing the launcher icon? Hopefully the launcher will give us some hints.

**Comment by pocmo** [comment]
CC @Mugurell

**Comment by sv-ohorvath** [comment]
`01-16 17:37:33.712 1265-3561/? I/ActivityManager: START u0 {act=org.mozilla.gecko.BOOKMARK dat=https: flg=0x10000000 cmp=org.mozilla.fennec_aurora/org.mozilla.gecko.BrowserApp bnds=[540,50][720,306]} from uid 2897 pid 2874 on display 0
01-16 17:37:33.712 1265-3561/? W/ActivityManager: Permission Denial: starting Intent { act=org.mozilla.gecko.BOOKMARK dat=https: flg=0x10000000 cmp=org.mozilla.fennec_aurora/org.mozilla.gecko.BrowserApp bnds=[540,50][720,306] } from ProcessRecord{17a685d 2874:com.htc.launcher/2897} (pid=2874, uid=2897) not exported from uid 10131
01-16 17:37:33.722 2874-2874/? E/Launcher: Launcher does not have the permission to launch Intent { act=org.mozilla.gecko.BOOKMARK dat=https: flg=0x10000000 cmp=org.mozilla.fennec_aurora/org.mozilla.gecko.BrowserApp bnds=[540,50][720,306] }. Make sure to create a MAIN intent-filter for the corresponding activity or use the exported attribute for this activity.
01-16 17:37:33.722 2874-2874/? E/Launcher: Exception: 
    java.lang.SecurityException: Permission Denial: starting Intent { act=org.mozilla.gecko.BOOKMARK dat=https: flg=0x10000000 cmp=org.mozilla.fennec_aurora/org.mozilla.gecko.BrowserApp bnds=[540,50][720,306] } from ProcessRecord{17a685d 2874:com.htc.launcher/2897} (pid=2874, uid=2897) not exported from uid 10131
        at android.os.Parcel.readException(Parcel.java:1629)
        at android.os.Parcel.readException(Parcel.java:1582)
        at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2695)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1624)
        at android.app.Activity.startActivityForResult(Activity.java:3940)
        at android.app.Activity.startActivityForResult(Activity.java:3901)
        at com.htc.launcher.Launcher.startActivityForResultSafely(Unknown Source)
        at com.htc.launcher.Launcher.startActivityForResult(Unknown Source)
        at android.app.Activity.startActivity(Activity.java:4224)
        at com.htc.launcher.util.UtilitiesLauncher.startShortcutIntentSafely(Unknown Source)
        at com.htc.launcher.util.UtilitiesLauncher.startActivitySafely(Unknown Source)
        at com.htc.launcher.Launcher.startActivity(Unknown Source)
        at com.htc.launcher.Launcher.startActivitySafely(Unknown Source)
        at com.htc.launcher.Launcher.onClick(Unknown Source)
        at android.view.View.performClick(View.java:5232)
        at android.view.View$PerformClick.run(View.java:21289)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:168)
        at android.app.ActivityThread.main(ActivityThread.java:5885)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
01-16 17:37:33.722 2874-2874/? I/ContextualWidget: click item=ShortcutInfo(title=W*a intent=Intent { act=org.mozilla.gecko.BOOKMARK dat= flg=0x10000000 cmp=org.mozilla.fennec_aurora/org.mozilla.gecko.BrowserApp bnds=[540,50][720,306] } id=212 type=1 container=-100 appsContainer=<ALLAPPS> screen=1 cellX=3 cellY=0 cellZ=0 spanX=1 spanY=1 isGesture=false dropPos=null user=UserHandle{0} count=0 restored=0)`

**Comment by jonalmeida** [comment]
@Mugurell note that we changed the `targetAcitivity` from `HomeActivity` to IntentReceiverActivity` for invoking the UI if that's something that might be causing the security exception.

**Comment by pocmo** [comment]
Fixed with the next build.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Fennec Nightly migration build 2, 01/17with Huawei Honor 8 (Android 7.0), HTC Desire 820 (Android 6.0.1).
I will move this to Done. thanks!
