### ISSUE TITLE
FxA throws errors on push messages it can't handle

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#5662]
When `FirefoxAccount` receives a message it can't handle, we throw the error below. 

This can be noisy since gv and a-s are now both consumers of push and will both receives messages that can be intended for the other.
```
2020-01-21 13:40:26.117 32199-32395/org.mozilla.reference.browser.debug E/FxaDeviceConstellation: Error while running: processing raw events
    mozilla.appservices.fxaclient.FxaException$Unspecified: JSON error: expected value at line 1 column 1
        at mozilla.appservices.fxaclient.rust.RustError.intoException(RustError.kt:48)
        at mozilla.appservices.fxaclient.FirefoxAccount.handlePushMessage(FirefoxAccount.kt:895)
        at mozilla.components.service.fxa.FxaDeviceConstellation$processRawEventAsync$1$1.invoke(FxaDeviceConstellation.kt:69)
        at mozilla.components.service.fxa.FxaDeviceConstellation$processRawEventAsync$1$1.invoke(FxaDeviceConstellation.kt:33)
        at mozilla.components.service.fxa.UtilsKt$handleFxaExceptions$7.invokeSuspend(Utils.kt:68)
        at mozilla.components.service.fxa.UtilsKt$handleFxaExceptions$7.invoke(Unknown Source:10)
        at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:28)
        at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:60)
        at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:67)
        at mozilla.components.service.fxa.FxaDeviceConstellation$processRawEventAsync$1.invokeSuspend(FxaDeviceConstellation.kt:68)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
```

**Comment by jonalmeida** [comment]
Closing as invalid since we're filtering out non-FxA push messages so we no longer need to worry about this. See [here](https://github.com/mozilla/application-services/issues/2710#issuecomment-591675471) for details.
