### ISSUE TITLE
NotImplementedError: Octet length not supported: -108

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#5692]
https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/issues/7135764/

```
NotImplementedError: Octet length not supported: -108
    at mozilla.components.support.migration.FennecLoginsMigration.getEncodingLengthOffset(FennecLoginsMigration.kt:1)
    at mozilla.components.support.migration.FennecLoginsMigration.access$derDecodeLoginEntry(FennecLoginsMigration.kt:2)
    at mozilla.components.support.migration.FennecLoginsMigration$getLogins$$inlined$use$lambda$1.invoke(FennecLoginsMigration.kt:8)
    at mozilla.components.support.migration.FennecLoginsMigration.collectExceptionsIntoASet$support_migration_release(FennecLoginsMigration.kt:1)
    at mozilla.components.support.migration.FennecLoginsMigration.getLogins$support_migration_release(FennecLoginsMigration.kt:7)
...
(8 additional frame(s) were not displayed)

Octet length not supported: -108
```

**Comment by grigoryk** [comment]
Well, this is a little unexpected. Length of -108 is clearly wrong. Most likely `ByteArray.getEncodingLength` is doing something wrong while obtaining this length.

**Comment by pocmo** [comment]
Sentry issue: [FENIX-FENNEC-NIGHTLY-2Z](https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/issues/7184149/)

**Comment by ebalazs-sv** [comment]
pocmo confirmed that is not to be tested manually so moving this to Done. Thanks!
