### ISSUE TITLE
feature-sitepermissions: InvalidParameterException: not a valid permission.

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#5723]
This is a top crash in Fenix Nightly that we somehow missed.

https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6684300/

InvalidParameterException: Generic(id=4, desc=Gecko permission type = 4) is not a valid permission.

```
java.security.InvalidParameterException: Generic(id=4, desc=Gecko permission type = 4) is not a valid permission.
    at mozilla.components.feature.sitepermissions.SitePermissionsFeature.toSitePermissions(SitePermissionsFeature.kt:10)
    at mozilla.components.feature.sitepermissions.SitePermissionsFeature.toSitePermissions$default(SitePermissionsFeature.kt:7)
    at mozilla.components.feature.sitepermissions.SitePermissionsFeature$storeSitePermissions$1.invokeSuspend(SitePermissionsFeature.kt:11)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:15)
```

**Comment by Amejia481** [comment]
Closed in favor of https://github.com/mozilla-mobile/fenix/issues/8411
