### ISSUE TITLE
LoginsStorageException: Using DatabaseLoginsStorage without unlocking first

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#5740]
https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/issues/7164100/

```
LoginsStorageException: Using DatabaseLoginsStorage without unlocking first
    at mozilla.appservices.logins.DatabaseLoginsStorage.checkUnlocked(DatabaseLoginsStorage.kt:2)
    at mozilla.appservices.logins.DatabaseLoginsStorage.access$checkUnlocked(DatabaseLoginsStorage.kt:1)
    at mozilla.appservices.logins.DatabaseLoginsStorage.ensureValid(DatabaseLoginsStorage.kt:5)
    at mozilla.components.service.sync.logins.AsyncLoginsStorageAdapter$ensureValid$1.invokeSuspend(AsyncLoginsStorage.kt:4)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
...
(3 additional frame(s) were not displayed)

Using DatabaseLoginsStorage without unlocking first
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4830)

**Comment by Sparky93** [comment]
Hello, I'd like to work on this.

**Comment by pocmo** [comment]
We decided to move this off the migration board since that is an unrelated to the migration.

**Comment by jonalmeida** [comment]
I don't see this exception showing up in our crash reporter any more. Closing as won't fix.
