### ISSUE TITLE
PushManager.unsubscribe: PushError: Error -  General Error: "No subscriptions created yet."

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#5750]
https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/issues/7173199/

```
PushError: Error(

General Error: "No subscriptions created yet.")
    at mozilla.appservices.push.RustError.intoException(RustError.kt:4)
    at mozilla.appservices.push.PushManager.unsubscribe(PushManager.kt:9)
    at mozilla.components.feature.push.RustPushConnection.unsubscribe(Connection.kt:3)
    at mozilla.components.feature.push.AutoPushFeature$unsubscribeForType$1$1.invokeSuspend(AutoPushFeature.kt:5)
    at mozilla.components.feature.push.AutoPushFeature$unsubscribeForType$1$1.invoke(AutoPushFeature.kt)
...
(6 additional frame(s) were not displayed)

Error(

General Error: "No subscriptions created yet.")
```

**Comment by pocmo** [comment]
We haven't seen this again. Closing.

CC @grigoryk @jonalmeida

**Comment by ebalazs-sv** [comment]
This was not to be manually verified as discussed with pocmo and also this error was not seen 10 days ago, as mentioned in the previous comment.
Due to that I will move it to Done. Thanks!
