### ISSUE TITLE
LoginMigrationException: Rust import unexpectedly threw: mozilla.appservices.logins.LoginsStorageException: The logins tab...

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#5765]
https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/issues/6926652/

```
LoginMigrationException: Rust import unexpectedly threw: mozilla.appservices.logins.LoginsStorageException: The logins tables are not empty
    at mozilla.components.support.migration.FennecLoginsMigration.migrate$support_migration_release(FennecLoginsMigration.kt:23)
    at mozilla.components.support.migration.FennecLoginsMigration$migrate$1.invokeSuspend
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:14)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
...
(2 additional frame(s) were not displayed)

[INFO] Rust import unexpectedly threw: mozilla.appservices.logins.LoginsStorageException: The logins tables are not empty
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4840)

**Comment by pocmo** [comment]
This has happened in the past when we crashes during the migration without saving the state - and so we retried the migration on the next app start. However that was fixed. We haven't seen that for a while and now this crash is back... maybe a regression?

**Comment by Sparky93** [comment]
I haven't manage to reproduce this crash no matter how much I tried, at best I can get is a speculative fix.
