### ISSUE TITLE
FennecMigratorException$MigrateBookmarksException: mozilla.appservices.places.PlacesException: Error executing SQL: Conversion error from type Text ...

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#5843]
https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/issues/6963672/

```
PlacesException: Error executing SQL: Conversion error from type Text at index: 4, invalid utf-8 sequence of 1 bytes from index 28
    at mozilla.appservices.places.RustError.intoException(RustError.kt:4)
    at mozilla.appservices.places.PlacesApi.importBookmarksFromFennec(PlacesConnection.kt:11)
    at mozilla.components.browser.storage.sync.RustPlacesConnection.importBookmarksFromFennec(Connection.kt:2)
    at mozilla.components.support.migration.FennecMigrator$runMigrationsAsync$1.invokeSuspend(FennecMigrator.kt:74)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
...
(5 additional frame(s) were not displayed)

FennecMigratorException$MigrateBookmarksException: mozilla.appservices.places.PlacesException: Error executing SQL: Conversion error from type Text at index: 4, invalid utf-8 sequence of 1 bytes from index 28
    at mozilla.components.support.migration.FennecMigrator$runMigrationsAsync$1.invokeSuspend(FennecMigrator.kt:93)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
    at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
...
(2 additional frame(s) were not displayed)

[INFO] mozilla.appservices.places.PlacesException: Error executing SQL: Conversion error from type Text at index: 4, invalid utf-8 sequence of 1 bytes from index 28
```

**Comment by pocmo** [comment]
This is part of the list of #5938.
