### ISSUE TITLE
ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW cat=[mozilla.components.pwa.c...

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#5866]
https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/issues/7183008/

```
ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW cat=[mozilla.components.pwa.category.SHORTCUT] dat= pkg=org.mozilla.fennec_aurora (has extras) }
    at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2014)
    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1675)
    at android.app.Activity.startActivityForResult(Activity.java:4586)
    at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:6)
    at android.app.Activity.startActivityForResult(Activity.java:4544)
...
(17 additional frame(s) were not displayed)

No Activity found to handle Intent { act=android.intent.action.VIEW cat=[mozilla.components.pwa.category.SHORTCUT] dat= pkg=org.mozilla.fennec_aurora (has extras) }
```

**Comment by pocmo** [comment]
Sentry issue: [FENIX-FENNEC-BETA-1S](https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/issues/7658852/)
