### ISSUE TITLE
IllegalStateException: addonProgressOverlay must not be null

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#5867]
https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/issues/7242708/

```
IllegalStateException: addonProgressOverlay must not be null
    at androidx.transition.CanvasUtils.checkExpressionValueIsNotNull(CanvasUtils.java:1)
    at org.mozilla.fenix.addons.AddonsManagementFragment$onPositiveButtonClicked$1.invoke(AddonsManagementFragment.kt:2)
    at -$$LambdaGroup$js$QAi8y9-3MWhFtmfr5gRz9lkO2II.onClick(java-style lambda group:240)
    at android.view.View.performClick(View.java:6312)
    at android.view.View$PerformClick.run(View.java:24811)
...
(7 additional frame(s) were not displayed)

addonProgressOverlay must not be null
```

**Comment by pocmo** [comment]
Saw this happening for a migration build. Not sure if this is already tracked.

**Comment by csadilek** [comment]
This was fixed in Fenix:
