### ISSUE TITLE
IllegalStateException: Expected a string but was NULL

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#5868]
https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/issues/7235232/

```
IllegalStateException: Expected a string but was NULL
    at android.util.JsonReader.nextString(JsonReader.java:408)
    at mozilla.components.support.migration.session.StreamingSessionStoreParser.parseWindows(StreamingSessionStoreParser.kt:28)
    at mozilla.components.support.migration.session.StreamingSessionStoreParser.parse$support_migration_release(StreamingSessionStoreParser.kt:7)
    at mozilla.components.support.migration.FennecSessionMigration.migrate(FennecSessionMigration.kt:12)
    at mozilla.components.support.migration.FennecMigrator.migrateOpenTabs(FennecMigrator.kt:14)
...
(6 additional frame(s) were not displayed)

[INFO] Expected a string but was NULL
```

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly migration build 9, 02/14 with Huawei P9 Lite (Android 7) and when migrating tabs without title the app does not crash.
I will move this to Done. Thanks!
