### ISSUE TITLE
Fennec migration: Crash when removing uBlock Mobile add-on

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/android-components#5940]
STR:
1. Install uBlock Mobile and another add-on (like Ghostery) on Fennec.
2. Install the migration build #9 (from 2/14).
3. Go to Settings>Addons>Not supported list. 
4. Delete the uBlock Mobile add-on.

Expected results:
Add-on removed

Actual results:
App crashes. 
* I didn't find another add-on to reproduce this crash, but this combo 1/2 will do the trick.

Device: Pixel (Android 10), Honor 8 (Android 7.0)
Build: Migration build 9, from 2/14. 

`2020-02-14 15:13:00.205 27387-27387/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fennec_aurora, PID: 27387
    java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionUnsupportedAddonsAdapter$UnsupportedAddonViewHolder{bdd847b position=1 id=-1, oldPos=1, pLpos:-1 scrap [attachedScrap] tmpDetached no parent} androidx.recyclerview.widget.RecyclerView{254826b VFED.V... .F....ID 0,359-1080,1554 #7f090413 app:id/unsupported_add_ons_list}, adapter:mozilla.components.feature.addons.ui.UnsupportedAddonsAdapter@77a51c8, layout:androidx.recyclerview.widget.LinearLayoutManager@caff261, context:org.mozilla.fenix.HomeActivity@c9aa684
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:70)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:1)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:8)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:12)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:125)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:40)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:7)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:2)
        at android.view.View.layout(View.java:17684)
        at android.view.ViewGroup.layout(ViewGroup.java:5631)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1762)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1606)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1515)
        at android.view.View.layout(View.java:17684)
        at android.view.ViewGroup.layout(ViewGroup.java:5631)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:17684)
        at android.view.ViewGroup.layout(ViewGroup.java:5631)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1762)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1606)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1515)
        at android.view.View.layout(View.java:17684)
        at android.view.ViewGroup.layout(ViewGroup.java:5631)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:17684)
        at android.view.ViewGroup.layout(ViewGroup.java:5631)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1762)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1606)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1515)
        at android.view.View.layout(View.java:17684)
        at android.view.ViewGroup.layout(ViewGroup.java:5631)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:17684)
        at android.view.ViewGroup.layout(ViewGroup.java:5631)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1762)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1606)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1515)
        at android.view.View.layout(View.java:17684)
        at android.view.ViewGroup.layout(ViewGroup.java:5631)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:774)
        at android.view.View.layout(View.java:17684)
        at android.view.ViewGroup.layout(ViewGroup.java:5631)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2511)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2226)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1364)
2020-02-14 15:13:00.205 27387-27387/? E/AndroidRuntime:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6757)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:923)
        at android.view.Choreographer.doCallbacks(Choreographer.java:735)
        at android.view.Choreographer.doFrame(Choreographer.java:667)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:909)
        at android.os.Handler.handleCallback(Handler.java:755)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6524)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
2020-02-14 15:13:00.207 973-9409/? E/ReportTools: This is not beta user build`

**Comment by pocmo** [comment]
Sentry issue: [FENIX-FENNEC-NIGHTLY-86](https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/issues/7279016/)
