### ISSUE TITLE
java.lang.IllegalStateException: remove_add_on must not be null

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#5977]
Crash in Fenix. Sentry: https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/7300121/

Let's investigate here though and fix everywhere.

```
java.lang.IllegalStateException: remove_add_on must not be null
    at -$$LambdaGroup$ks$3dk2TV2PDS17-TeNsA6Slr1xVgA.invoke(com.android.tools.r8.jetbrains.kotlin-style lambda group:25)
    at -$$LambdaGroup$ks$O1hItAye9K862nmb-1vtC5PRRfE.invoke(com.android.tools.r8.jetbrains.kotlin-style lambda group:34)
    at -$$LambdaGroup$js$8vC4ZcgGL9QCmG3TDOYl97vbFvI.onValue(java-style lambda group:37)
    at org.mozilla.geckoview.GeckoResult.lambda$thenInternal$2$GeckoResult(GeckoResult.java:2)
    at org.mozilla.geckoview.-$$Lambda$GeckoResult$gwCgOUK_EYQn2g6GolfZvo6A_WE.run
    at org.mozilla.geckoview.GeckoResult.lambda$dispatchLocked$3(GeckoResult.java:2)
    at org.mozilla.geckoview.-$$Lambda$GeckoResult$PehjG2jgyDa_p37vZrKrSi2I94s.run
    at android.os.Handler.handleCallback(Handler.java:808)
    at android.os.Handler.dispatchMessage(Handler.java:101)
    at android.os.Looper.loop(Looper.java:166)
    at android.app.ActivityThread.main(ActivityThread.java:7529)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

org.mozilla.geckoview.UncaughtException: java.lang.IllegalStateException: remove_add_on must not be null
    at org.mozilla.geckoview.GeckoResult.dispatchLocked(GeckoResult.java:4)
    at org.mozilla.geckoview.GeckoResult.completeExceptionally(GeckoResult.java:4)
    at org.mozilla.geckoview.GeckoResult.lambda$thenInternal$2$GeckoResult(GeckoResult.java:10)
    at org.mozilla.geckoview.-$$Lambda$GeckoResult$gwCgOUK_EYQn2g6GolfZvo6A_WE.run
    at org.mozilla.geckoview.GeckoResult.lambda$dispatchLocked$3(GeckoResult.java:2)
    at org.mozilla.geckoview.-$$Lambda$GeckoResult$PehjG2jgyDa_p37vZrKrSi2I94s.run
    at android.os.Handler.handleCallback(Handler.java:808)
    at android.os.Handler.dispatchMessage(Handler.java:101)
    at android.os.Looper.loop(Looper.java:166)
    at android.app.ActivityThread.main(ActivityThread.java:7529)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

**Comment by csadilek** [comment]
Closing in favour of: https://github.com/mozilla-mobile/fenix/issues/8570
