### ISSUE TITLE
UpdateWebExtension crashes when called and no update available

### ISSUE THREAD

**Issue by psymoon** [mozilla-mobile/android-components#6006]
STR:
- Fresh install
- Go to Add-ons in menu
- Install uBlock

```
32607-32607/org.mozilla.samples.browser E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.samples.browser, PID: 32607
    org.mozilla.geckoview.GeckoResult$UncaughtException: kotlin.KotlinNullPointerException
        at org.mozilla.geckoview.GeckoResult.dispatchLocked(GeckoResult.java:639)
        at org.mozilla.geckoview.GeckoResult.completeExceptionally(GeckoResult.java:782)
        at org.mozilla.geckoview.GeckoResult.lambda$thenInternal$2$GeckoResult(GeckoResult.java:465)
        at org.mozilla.geckoview.-$$Lambda$GeckoResult$gwCgOUK_EYQn2g6GolfZvo6A_WE.run(Unknown Source:8)
        at org.mozilla.geckoview.GeckoResult.lambda$dispatchLocked$3(GeckoResult.java:653)
        at org.mozilla.geckoview.-$$Lambda$GeckoResult$PehjG2jgyDa_p37vZrKrSi2I94s.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: kotlin.KotlinNullPointerException
        at mozilla.components.browser.engine.gecko.GeckoEngine$updateWebExtension$1.onValue(GeckoEngine.kt:242)
        at mozilla.components.browser.engine.gecko.GeckoEngine$updateWebExtension$1.onValue(GeckoEngine.kt:55)
        at org.mozilla.geckoview.GeckoResult.lambda$thenInternal$2$GeckoResult(GeckoResult.java:451)
        at org.mozilla.geckoview.-$$Lambda$GeckoResult$gwCgOUK_EYQn2g6GolfZvo6A_WE.run(Unknown Source:8) 
        at org.mozilla.geckoview.GeckoResult.lambda$dispatchLocked$3(GeckoResult.java:653) 
        at org.mozilla.geckoview.-$$Lambda$GeckoResult$PehjG2jgyDa_p37vZrKrSi2I94s.run(Unknown Source:2) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by Amejia481** [comment]
It looks like geckoview is not passing us the `extension` when the complete the update.

``` 
Caused by: kotlin.KotlinNullPointerException
        at mozilla.components.browser.engine.gecko.GeckoEngine$updateWebExtension$1.onValue(GeckoEngine.kt:242)
```
  
https://github.com/mozilla-mobile/android-components/blob/28fb30197a41a9687d3481c5f247edd2d65742ff/components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt#L242

**Comment by Amejia481** [comment]
Not sure what could be wrong here, maybe we can log some additional information like the ext id to have more context around the crash. @csadilek  Do you any idea why this could happen?

**Comment by Amejia481** [comment]
Right now [AMO shows ](https://addons.mozilla.org/en-CA/firefox/addon/ublock-origin/)the last update of UBlock was `1.24.4` 18 days ago, but their repository they say the have a pending update for [Firefox 1.25.0 from yesterday](https://github.com/gorhill/uBlock/releases)


![image](https://user-images.githubusercontent.com/773158/74958911-b0f2d600-53d7-11ea-8b5c-516a30621667.png)

![image](https://user-images.githubusercontent.com/773158/74959156-16df5d80-53d8-11ea-861f-ca362eaab964.png)

**Comment by csadilek** [comment]
@Amejia481 yes, that's a bug on our side, actually. `If no update is available, null will be returned.` So, if we get null back it means there was no update and we shouldn't do anything :).

**Comment by csadilek** [comment]
Fixed by https://github.com/mozilla-mobile/android-components/pull/6014
