### ISSUE TITLE
Crash in [@ java.io.IOException: at org.mozilla.geckoview.GeckoInputStream.read(GeckoInputStream.java)]

### ISSUE THREAD

**Issue by fluffyemily** [mozilla-mobile/android-components#6009]
Reraised after being determined not to be a GeckoView bug in [1616561](https://bugzilla.mozilla.org/show_bug.cgi?id=1616561)

This bug is for crash report [bp-b416b923-ffaa-41db-8ccd-15ee40200219](https://crash-stats.mozilla.org/report/index/b416b923-ffaa-41db-8ccd-15ee40200219).

Java stack trace:

java.io.IOException
	at org.mozilla.geckoview.GeckoInputStream.read(GeckoInputStream.java:11)
	at org.mozilla.geckoview.GeckoInputStream.read(GeckoInputStream.java:6)
	at androidx.transition.CanvasUtils.copyTo$default(CanvasUtils.java:4)
	at androidx.transition.CanvasUtils.readBytes(CanvasUtils.java:2)
	at mozilla.components.browser.icons.loader.HttpIconLoaderKt$toIconLoaderResult$1.invoke(HttpIconLoader.kt:1)
	at mozilla.components.concept.fetch.Response$Body.useStream(Response.kt:1)
	at mozilla.components.browser.icons.loader.HttpIconLoader.load(HttpIconLoader.kt:21)
	at mozilla.components.browser.icons.BrowserIcons$loadIcon$1.invokeSuspend(BrowserIcons.kt:23)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

**Comment by unicorn-io** [comment]
can i try this out?

**Comment by pocmo** [comment]
This was fixed in e69868699184643947923f0e850f6bc5858f4f9d.
