### ISSUE TITLE
Gecko hang on tap of address bar in Fenix immediately after cold start

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/android-components#6010]
Master build: ae294c3fd8a7ef13ecf164ee214f25b25e8ee13f
GeckoNightlyDebug
Device: Pixel 2 (Android 10)

Immediately after cold start launch, tap the address bar. You'll get the not responding hang popup.

```Kotlin
2020-02-20 15:13:05.643 5861-5913/org.mozilla.fenix.debug I/WM-WorkerWrapper: Worker result RETRY for Work [ id=b3c29cf6-2684-4875-8ab7-69248abed24b, tags={ mozilla.telemetry.glean.scheduler.PingUploadWorker, mozac_service_glean_ping_upload_worker } ]
2020-02-20 15:13:05.720 5861-5926/org.mozilla.fenix.debug D/App: Could not fetch region from location service
    java.net.SocketTimeoutException
        at mozilla.components.browser.engine.gecko.fetch.GeckoViewFetchClient.fetch(GeckoViewFetchClient.kt:60)
        at mozilla.components.service.location.MozillaLocationServiceKt.fetchRegion(MozillaLocationService.kt:139)
        at mozilla.components.service.location.MozillaLocationServiceKt.access$fetchRegion(MozillaLocationService.kt:1)
        at mozilla.components.service.location.MozillaLocationService$fetchRegion$2.invokeSuspend(MozillaLocationService.kt:70)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)```

**Comment by boek** [comment]
dup of #5989
