### ISSUE TITLE
Fennec migration: Fenix crashed when going to accounts.firefox.com

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/android-components#6044]
## Preconditions:
Logged in on Fennec.
## Steps to reproduce
1. Replace Fennec with Fenix ;
2. Type accounts.firefox.com in a new tab;
3. Tap the "Sign in" button;
4. Observe the behavior;
### Expected behavior
The account page is displayed.
### Actual behavior
Fenix crashes.
### Notes:
[Video](https://drive.google.com/file/d/1gfzBFBgSTukYfTr3GfZvcICb4i6IGUoj/view)
[shortlogcat.txt](https://github.com/mozilla-mobile/android-components/files/4245146/shortlogcat.txt)
[nofilterlogcat.txt](https://github.com/mozilla-mobile/android-components/files/4245148/nofilterlogcat.txt)
Not reproducible on Google Pixel 3 (Android Q), Xiaomi Mi Pad 2 (Android 5.1), Samsung Galaxy Note9 (Android 9).
On Nightly migration build 9, 02/14, the page freezes and opens after a while. 

### Device information

* Android device: LG G7 fit (Android 8.1), Samsung Galaxy S5 - (Android 6.0.1);
* Fenix version: Beta migration build 1, 02/24.

**Comment by pocmo** [comment]
```
2020-02-24 16:44:56.719 19601-19601/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.firefox_beta, PID: 19601
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:448)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810) 
     Caused by: mozilla.appservices.logins.LoginsStorageException: Using DatabaseLoginsStorage without unlocking first
        at mozilla.appservices.logins.DatabaseLoginsStorage.checkUnlocked(DatabaseLoginsStorage.kt:2)
        at mozilla.appservices.logins.DatabaseLoginsStorage.access$checkUnlocked(DatabaseLoginsStorage.kt:1)
        at mozilla.appservices.logins.DatabaseLoginsStorage.getByBaseDomain(DatabaseLoginsStorage.kt:4)
        at mozilla.components.service.sync.logins.AsyncLoginsStorageAdapter$getByBaseDomain$1.invokeSuspend(AsyncLoginsStorage.kt:4)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:15)
2020-02-24 16:44:56.725 19601-19601/? I/mozac/CrashReporter: Received crash: UncaughtExceptionCrash(throwable=java.lang.RuntimeException: 
```

**Comment by st3fan** [comment]
May be the same as https://github.com/mozilla-mobile/fenix/issues/7344

**Comment by grigoryk** [comment]
`accounts.firefox.com` feels like a red-herring, looking at that crash log.

**Comment by st3fan** [comment]
@grigoryk yeah check https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/7099367 it happens during random browsing too.

My guess is that it is more related to login forms than accounts.firefox.com specifically?

**Comment by grigoryk** [comment]
Yeah, login forms need to query login storage, and if sync is running (for example) it may crash due to https://github.com/mozilla-mobile/android-components/issues/5715. This should be resolved once I finish my PR for #5715.

**Comment by st3fan** [comment]
Moved this to In Progress but maybe we should just close it as it is a dupe?

**Comment by grigoryk** [comment]
Yeah, closing as a dupe.

**Comment by ebalazs-sv** [comment]
This was closed as a Duplicate, so I will move it to Done. Thanks!
