### ISSUE TITLE
Create a migration for SitePermissionsDatabase to introduce autoplay fields

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#6075]
Related stack-trace 

```
java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number.
    at androidx.room.RoomOpenHelper.onOpen(RoomOpenHelper.java:10)
    at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onOpen(FrameworkSQLiteOpenHelper.java:4)
    at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:411)
    at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:298)
    at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:2)
    at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:1)
    at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:1)
    at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:1)
    at mozilla.components.feature.sitepermissions.db.SitePermissionsDao_Impl.getSitePermissionsBy(SitePermissionsDao_Impl.java:4)
    at mozilla.components.feature.sitepermissions.SitePermissionsStorage.findSitePermissionsBy(SitePermissionsStorage.kt:3)
    at mozilla.components.feature.sitepermissions.SitePermissionsFeature$onContentPermissionRequested$permissionFromStorage$1.invokeSuspend(SitePermissionsFeature.kt:7)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:15)
```

**Comment by liuche** [comment]
How frequent is this crash, and can we uplift it into the AC release that is going out with Fenix 4.0? I believe it missed the 34.0.0 release.

**Comment by Amejia481** [comment]
It happens every time an user goes to any page that requires permissions like notification,mic, cam ... etc.

**Comment by pocmo** [comment]
I'll get this into 34.0.1 today!
