### ISSUE TITLE
Fenix nightly crashes with "Room cannot verify the data integrity"

### ISSUE THREAD

**Issue by eeejay** [mozilla-mobile/android-components#6089]
When I load washingtonpost.com, and many other sites Fenix crashes with this stacktrace:
```
02-26 08:53:59.317  9516  9516 E AndroidRuntime: FATAL EXCEPTION: main
02-26 08:53:59.317  9516  9516 E AndroidRuntime: Process: org.mozilla.fenix.nightly, PID: 9516
02-26 08:53:59.317  9516  9516 E AndroidRuntime: java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number.
02-26 08:53:59.317  9516  9516 E AndroidRuntime: 	at androidx.room.RoomOpenHelper.onOpen(RoomOpenHelper.java:10)
02-26 08:53:59.317  9516  9516 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onOpen(FrameworkSQLiteOpenHelper.java:4)
02-26 08:53:59.317  9516  9516 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:428)
02-26 08:53:59.317  9516  9516 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:317)
02-26 08:53:59.317  9516  9516 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:2)
02-26 08:53:59.317  9516  9516 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:1)
02-26 08:53:59.317  9516  9516 E AndroidRuntime: 	at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:1)
02-26 08:53:59.317  9516  9516 E AndroidRuntime: 	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:1)
02-26 08:53:59.317  9516  9516 E AndroidRuntime: 	at mozilla.components.feature.sitepermissions.db.SitePermissionsDao_Impl.getSitePermissionsBy(SitePermissionsDao_Impl.java:4)
02-26 08:53:59.317  9516  9516 E AndroidRuntime: 	at mozilla.components.feature.sitepermissions.SitePermissionsStorage.findSitePermissionsBy(SitePermissionsStorage.kt:3)
02-26 08:53:59.317  9516  9516 E AndroidRuntime: 	at mozilla.components.feature.sitepermissions.SitePermissionsFeature$onContentPermissionRequested$permissionFromStorage$1.invokeSuspend(SitePermissionsFeature.kt:7)
02-26 08:53:59.317  9516  9516 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
02-26 08:53:59.317  9516  9516 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
02-26 08:53:59.317  9516  9516 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
02-26 08:53:59.317  9516  9516 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:15)
```

**Comment by eeejay** [comment]
Nightly 200225 18:01 (Build #20561806)
34.0.0, ac78e22f1
GV: 75.0a1-20200223093951

**Comment by eeejay** [comment]
Dup of #6075 sorry!
