### ISSUE TITLE
Sample Browser crashing intermittently

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#6212]
Took me down a 🐰 🕳, but this is just because we're calling [onTrimMemory](https://github.com/mozilla-mobile/android-components/blob/master/samples/browser/src/main/java/org/mozilla/samples/browser/SampleApplication.kt#L81) for both the main and :tab processes which causes an additional Gecko runtime to be created, and ultimately leads to the child process killing its parent:

```
2020-03-09 17:54:22.947 12129-12175/org.mozilla.samples.browser:tab D/GeckoThread: State changed to JNI_READY
2020-03-09 17:54:22.992 12129-12175/org.mozilla.samples.browser:tab I/Process: Sending signal. PID: 11683 SIG: 9
2020-03-09 17:54:23.050 12129-12175/org.mozilla.samples.browser:tab I/fennec: XRE_main returned 1
2020-03-09 17:54:23.050 12129-12175/org.mozilla.samples.browser:tab D/GeckoThread: State changed to EXITED
2020-03-09 17:54:23.050 12129-12129/org.mozilla.samples.browser:tab D/AndroidRuntime: Shutting down VM
2020-03-09 17:54:23.051 12129-12129/org.mozilla.samples.browser:tab E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.samples.browser:tab, PID: 12129
    java.lang.RuntimeException: GeckoRuntime is shutting down
        at mozilla.components.browser.engine.gecko.GeckoEngine$2.onShutdown(GeckoEngine.kt:98)
        at org.mozilla.geckoview.GeckoRuntime$1.handleMessage(GeckoRuntime.java:255)
        at org.mozilla.gecko.EventDispatcher$3.run(EventDispatcher.java:356)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by pocmo** [comment]
Oh, damn, I recently saw that check in Fenix and didn't think of sample browser.
