### ISSUE TITLE
GeckoRuntime shuts down when the app is background

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#6258]
### STR
1. Open a page in the sample browser with GV beta (master as 6e1631e4f).
2. Switch to another memory intensive app like another browser.
3. Observe the eventual system dialog 'Sample Browser keeps stopping'.

```
2020-03-13 11:35:52.997 1395-2230/? E/InputDispatcher: channel '1c0cb5e org.mozilla.samples.browser/org.mozilla.samples.browser.BrowserActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2020-03-13 11:35:52.998 9755-9755/org.mozilla.samples.browser E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.samples.browser:socket, PID: 9755
    java.lang.RuntimeException: GeckoRuntime is shutting down
        at mozilla.components.browser.engine.gecko.GeckoEngine$2.onShutdown(GeckoEngine.kt:95)
        at org.mozilla.geckoview.GeckoRuntime$1.handleMessage(GeckoRuntime.java:254)
        at org.mozilla.gecko.EventDispatcher$3.run(EventDispatcher.java:356)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by jonalmeida** [comment]
Probably a duplicate of https://github.com/mozilla-mobile/android-components/issues/6212. I'm going to rebase and test this again.

**Comment by jonalmeida** [comment]
It works!
