### ISSUE TITLE
IllegalStateException: No camera found on device

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#6414]
https://sentry.prod.mozaws.net/operations/firefox-beta/issues/7662742/

```
IllegalStateException: No camera found on device
    at mozilla.components.feature.qr.QrFragment.openCamera$feature_qr_release(QrFragment.kt:9)
    at mozilla.components.feature.qr.QrFragment$surfaceTextureListener$1.onSurfaceTextureAvailable(QrFragment.kt:1)
    at android.view.TextureView.getHardwareLayer(TextureView.java:390)
    at android.view.TextureView.draw(TextureView.java:339)
    at android.view.View.updateDisplayListIfDirty(View.java:16189)
...
(64 additional frame(s) were not displayed)

No camera found on device
```

**Comment by pocmo** [comment]
Not sure if this is Fenix specific or an issue in our component.

**Comment by pocmo** [comment]
Sentry issue: [FENIX-FENNEC-BETA-2G](https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/issues/7665281/)

**Comment by Amejia481** [comment]
Looks like the device doesn't have a camera 😄 
I think X96Max_Plus2  is a TV BOX 📺

**Comment by csadilek** [comment]
We have a `hasCamera` function that Fenix is using to decide whether or not to hide QR scanner functionality. It seems this part doesn't work and the functionality is available in this case.

**Comment by csadilek** [comment]
This has been fixed by: https://github.com/mozilla-mobile/android-components/pull/7912
