### ISSUE TITLE
InternalPanic: called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#6416]
https://sentry.prod.mozaws.net/operations/firefox-beta/issues/7661881/

```
InternalPanic: called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"
    at mozilla.appservices.places.RustError.intoException(RustError.kt:14)
    at mozilla.appservices.places.PlacesWriterConnection.noteObservation(PlacesConnection.kt:12)
    at mozilla.components.browser.storage.sync.PlacesHistoryStorage$recordObservation$2.invokeSuspend(PlacesHistoryStorage.kt:11)
    at mozilla.components.browser.storage.sync.PlacesHistoryStorage$recordObservation$2.invoke(PlacesHistoryStorage.kt)
    at kotlin.jvm.internal.Intrinsics.startUndispatchedOrReturn(Intrinsics.java:2)
...
(7 additional frame(s) were not displayed)

called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"
```

**Comment by thomcc** [comment]
Once an operation panics in a-s every subsequent operation will panic with this error, so on it's own it's hard to know what the issue is.
