### ISSUE TITLE
SecurityException: Permission Denial: starting Intent { act=android.intent.action.VIEW cat=[android.intent.category....

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#6417]
https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/issues/7661607/

```
RemoteException: Remote stack trace:
	at com.android.server.wm.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1184)
	at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:896)
	at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:651)
	at com.android.server.wm.HwActivityStarter.startActivity(HwActivityStarter.java:266)
	at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:1519)

SecurityException: Permission Denial: starting Intent { act=android.intent.action.VIEW cat=[android.intent.category.BROWSABLE] dat=https://id1.cloud.huawei.com/... flg=0x10000000 pkg=com.huawei.hwid cmp=com.huawei.hwid/com.huawei.hms.approuter.AppRouterActivity } from ProcessRecord{cb65308 7163:org.mozilla.firefox_beta/u0a283} (pid=7163, uid=10283) not exported from uid 10063
    at android.os.Parcel.createException(Parcel.java:2071)
    at android.os.Parcel.readException(Parcel.java:2039)
    at android.os.Parcel.readException(Parcel.java:1987)
    at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:3888)
    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1731)
...
(20 additional frame(s) were not displayed)

Permission Denial: starting Intent { act=android.intent.action.VIEW cat=[android.intent.category.BROWSABLE] dat=https://id1.cloud.huawei.com/... flg=0x10000000 pkg=[...] } from ProcessRecord{cb65308 7163:org.mozilla.firefox_beta/u0a283} (pid=7163, uid=10283) not exported from uid 10063
```

**Comment by pocmo** [comment]
@rocketsroger Looks like we offer and try to launch activities that are not `exported` via the app links feature.

**Comment by rocketsroger** [comment]
Looks like this is a bug on the app side, not on our side.  The Huawei app has intent filter set to handle the intent but does not have the activity set to `android:exported="true"`.  

There's nothing we can do from our end.  Closing
