### ISSUE TITLE
(Push) Communication Server Error: "Could not fetch endpoint: Backend error: Missing HTTP status")

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#6418]
https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/issues/7661872/

```
CommunicationServerError: Error(

Communication Server Error: "Could not fetch endpoint: Backend error: Missing HTTP status")
    at mozilla.appservices.push.RustError.intoException(RustError.kt:12)
    at mozilla.appservices.push.PushManager.subscribe(PushManager.kt:13)
    at mozilla.appservices.push.PushAPI$DefaultImpls.subscribe$default(PushManager.kt:1)
    at mozilla.components.feature.push.RustPushConnection.updateToken(Connection.kt:21)
    at mozilla.components.feature.push.AutoPushFeature$onNewToken$1.invokeSuspend(AutoPushFeature.kt:14)
...
(7 additional frame(s) were not displayed)

PushError$Rust: Error(

Communication Server Error: "Could not fetch endpoint: Backend error: Missing HTTP status")
    at mozilla.components.feature.push.AutoPushFeature$launchAndTry$2.invoke(AutoPushFeature.kt:3)
    at mozilla.components.feature.push.AutoPushFeatureKt$launchAndTry$1.invokeSuspend(AutoPushFeature.kt:17)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:19)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
...
(2 additional frame(s) were not displayed)

[INFO] Error(

Communication Server Error: "Could not fetch endpoint: Backend error: Missing HTTP status")
```

**Comment by pocmo** [comment]
@jonalmeida Another push related one from the beta migration build. Is that something we need to handle?

**Comment by jonalmeida** [comment]
These are info level reports we were intentionally sending to the crash reporter. There's nothing for us to do here. I have a patch that will stop logging most of the noisy reports (https://github.com/mozilla-mobile/android-components/pull/6397).

**Comment by jonalmeida** [comment]
We can close this now since we no longer report this communication errors.
