### ISSUE TITLE
FennecMigratorException$MigratePinnedSitesException: mozilla.appservices.places.PlacesException: A connection of this type is already open

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#6436]
https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/issues/7660253/

```
PlacesException: A connection of this type is already open
    at mozilla.appservices.places.RustError.intoException(RustError.kt:4)
    at mozilla.appservices.places.PlacesApi.importPinnedSitesFromFennec(PlacesConnection.kt:13)
    at mozilla.components.browser.storage.sync.RustPlacesConnection.readPinnedSitesFromFennec(Connection.kt:2)
    at mozilla.components.support.migration.FennecMigrator$runMigrationsAsync$1.invokeSuspend(FennecMigrator.kt:184)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
...
(4 additional frame(s) were not displayed)

FennecMigratorException$MigratePinnedSitesException: mozilla.appservices.places.PlacesException: A connection of this type is already open
    at mozilla.components.support.migration.FennecMigrator$runMigrationsAsync$1.invokeSuspend(FennecMigrator.kt:213)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:19)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
...
(1 additional frame(s) were not displayed)

[INFO] mozilla.appservices.places.PlacesException: A connection of this type is already open
```

**Comment by st3fan** [comment]
@grigoryk is this something we should address?

**Comment by grigoryk** [comment]
@st3fan the linked sentry issue is a collection of random problems - unsupported db versions, malformed db files, "guid cannot contain itself" and "foreign key constraint violation" bookmark merge snafus, etc.

I didn't actually see `A connection of this type is already open` in the list of recently observed issue, unless sentry decided to group those differently now.

Overall volume for these is both constant and low (a few a day). I don't get a sense that addressing any single issue here will help meaningfully. We already made a call not to expand support for lower db versions, and a-s [ruled out good chunk of these issues as non-actionable](https://github.com/mozilla/application-services/issues/2660) (due to a combination of low volume and high effort).

So, I don't think there's anything to do here at this point.

**Comment by st3fan** [comment]
Closing this.
