### ISSUE TITLE
LoginMigrationException: getLogins unexpectedly threw: mozilla.components.support.migration.LoginMigrationException: Unsup...

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#6438]
https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/issues/7660255/

```
LoginMigrationException: getLogins unexpectedly threw: mozilla.components.support.migration.LoginMigrationException: Unsupported signons.sqlite DB version: 5
    at mozilla.components.support.migration.FennecLoginsMigration.migrate$support_migration_release(FennecLoginsMigration.kt:24)
    at mozilla.components.support.migration.FennecMigrator.migrateLogins(FennecMigrator.kt:21)
    at mozilla.components.support.migration.FennecMigrator$runMigrationsAsync$1.invokeSuspend(FennecMigrator.kt:133)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:19)
...
(3 additional frame(s) were not displayed)

[INFO] getLogins unexpectedly threw: mozilla.components.support.migration.LoginMigrationException: Unsupported signons.sqlite DB version: 5
```

**Comment by grigoryk** [comment]
`Unsupported signons.sqlite DB version: 5`

**Comment by grigoryk** [comment]
Other grouped exceptions:
```
[INFO] Failed to check MP: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 1294): Could not open database
#################################################################
Error Code : 1294 (SQLITE_CANTOPEN_ENOENT)
Caused By : Specified directory or database file does not exist.
	(unknown error (code 1294): Could not open database)
#################################################################
```
