### ISSUE TITLE
LoginMigrationException: Rust import unexpectedly threw: mozilla.appservices.logins.LoginsStorageException: The logins tab...

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#6439]
https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/issues/7674367/

```
LoginMigrationException: Rust import unexpectedly threw: mozilla.appservices.logins.LoginsStorageException: The logins tables are not empty
    at mozilla.components.support.migration.FennecLoginsMigration.migrate$support_migration_release(FennecLoginsMigration.kt:23)
    at mozilla.components.support.migration.FennecLoginsMigration$migrate$1.invokeSuspend
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
...
(2 additional frame(s) were not displayed)

[INFO] Rust import unexpectedly threw: mozilla.appservices.logins.LoginsStorageException: The logins tables are not empty
```

**Comment by grigoryk** [comment]
`The logins tables are not empty`
