### ISSUE TITLE
RuntimeException: Cannot confirm/dismiss a Prompt twice.

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#6445]
https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/issues/7684260/

```
RuntimeException: Cannot confirm/dismiss a Prompt twice.
    at org.mozilla.geckoview.GeckoSession$PromptDelegate$BasePrompt.dismiss(GeckoSession.java:4)
    at -$$LambdaGroup$ks$Q-VzEnrllbTUf3w0kjdx_oIrO1o.invoke(com.android.tools.r8.jetbrains.kotlin-style lambda group:99)
    at mozilla.components.feature.prompts.file.FilePicker$onActivityResult$1.invoke(FilePicker.kt:6)
    at kotlin.jvm.internal.Intrinsics.consumePromptFrom(Intrinsics.java:8)
    at kotlin.jvm.internal.Intrinsics.consumePromptFrom$default(Intrinsics.java:1)
...
(17 additional frame(s) were not displayed)

RuntimeException: Failure delivering result ResultInfo{who=null, request=400329, result=0, data=null} to activity {org.mozilla.firefox_beta/org.mozilla.fenix.HomeActivity}: java.lang.RuntimeException: Cannot confirm/dismiss a Prompt twice.
    at android.app.ActivityThread.deliverResults(ActivityThread.java:5041)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:5084)
    at android.app.ActivityThread.-wrap20
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2053)
    at android.os.Handler.dispatchMessage(Handler.java:108)
...
(5 additional frame(s) were not displayed)

Failure delivering result ResultInfo{who=null, request=400329, result=0, data=null} to activity {org.mozilla.firefox_beta/org.mozilla.fenix.HomeActivity}: java.lang.RuntimeException: Cannot confirm/dismiss a Prompt twice.
```

**Comment by liuche** [comment]
Linking this into Sentry, as I go through 4.3 crashes (and sentry is marking this one as "new").

**Comment by kbrosnan** [comment]
bz-1648121

GV team said in triage that they think that AC should just catch this exception and log it if needed.

**Comment by pocmo** [comment]
In Fenix 79:
https://sentry.prod.mozaws.net/share/issue/a40e2f26e84241e8b6b612495c58d680/

**Comment by Amejia481** [comment]
I think this issue was already fixed by https://github.com/mozilla-mobile/android-components/commit/166e0b12a11d9366c82580e0a0517c94b8585e1f on ac `51.0.0` on [nightly we haven't seen the issue after](https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/8713857/events/) ac 51. @pocmo  should we uplift the patch?

**Comment by Amejia481** [comment]
Already uplifted on [v48.0.15](https://github.com/mozilla-mobile/android-components/commits/v48.0.15)

**Comment by Amejia481** [comment]
We are seeing new events, looks like https://github.com/mozilla-mobile/android-components/issues/6445#issuecomment-669330716 didn't addressed the issue.

**Comment by Amejia481** [comment]
I noticed it's the same exception but this one is happening in different part on the `SharePrompt`, the above one was happening on `FilePicker`. I openend https://github.com/mozilla-mobile/android-components/issues/8240 to address the new issue.



```
java.lang.RuntimeException: Cannot confirm/dismiss a Prompt twice.
    at org.mozilla.geckoview.GeckoSession$PromptDelegate$BasePrompt.dismiss(GeckoSession.java:4)
    at org.mozilla.geckoview.GeckoSession$PromptDelegate$SharePrompt.dismiss(GeckoSession.java:2)
    at mozilla.components.browser.engine.gecko.prompt.-$$LambdaGroup$ks$8u4bVLX0p_V5ID86K2iFOrsJPms.invoke(com.android.tools.r8.jetbrains.kotlin-style lambda group:7)
    at org.mozilla.fenix.share.ShareFragment.dismiss(ShareFragment.kt:8)
    at androidx.navigation.fragment.DialogFragmentNavigator.popBackStack(DialogFragmentNavigator.java:7)
    at androidx.navigation.NavController.popBackStackInternal(NavController.java:15)
    at androidx.navigation.NavController.popBackStack(NavController.java:3)
    at androidx.navigation.NavController.popBackStack(NavController.java:2)
    at androidx.navigation.fragment.DialogFragmentNavigator$1.onStateChanged(DialogFragmentNavigator.java:4)
    at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:3)
    at androidx.lifecycle.LifecycleRegistry.backwardPass(LifecycleRegistry.java:10)
    at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:5)
    at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:5)
    at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:2)
    at androidx.fragment.app.Fragment.performStop(Fragment.java:4)
    at androidx.fragment.app.FragmentStateManager.stop(FragmentStateManager.java:3)
    at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:31)
    at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:4)
    at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:26)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:51)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:10)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:4)
    at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:1)
    at android.os.Handler.handleCallback(Handler.java:789)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6944)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```
