### ISSUE TITLE
IllegalStateException: Fragment already added: SimpleRedirectDialogFragment{22dbcbf} (c9095191-a44a-4113-9048-18c76441eb...

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#6461]
https://sentry.prod.mozaws.net/operations/firefox-beta/issues/7696958/

```
IllegalStateException: Fragment already added: SimpleRedirectDialogFragment{22dbcbf} (c9095191-a44a-4113-9048-18c76441ebde) SHOULD_OPEN_APP_LINK_PROMPT_DIALOG}
    at androidx.fragment.app.FragmentStore.addFragment(FragmentStore.java:7)
    at androidx.fragment.app.FragmentManager.addFragment(FragmentManager.java:4)
    at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:24)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:51)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:10)
...
(9 additional frame(s) were not displayed)

Fragment already added: SimpleRedirectDialogFragment{22dbcbf} (c9095191-a44a-4113-9048-18c76441ebde) SHOULD_OPEN_APP_LINK_PROMPT_DIALOG}
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5438)

**Comment by csadilek** [comment]
Not seeing this crash anymore in Sentry. Closing.
