### ISSUE TITLE
[Bug] NoScript crashes after global enable and quick tap on settings

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/android-components#6477]
## Prerequisites
Have NoScript installed.

## Steps to reproduce
1.Repeatedly disable/enable Search by Image and quickly tap the Settings button.

### Expected behavior
The Settings are properly displayed.

### Actual behavior
Crash

### Device information
* Android device: OnePlus A3 (Android 6.0.1)

* Fenix version: Custom Nightly(Build #20861010) 38.0.20200325130041, c580c2293
GV: 76.0a1-20200324093140 AS: 0.55.0

### Notes
❗️ Similar signature a the one encountered in #6447 
►Video
![20200401-092754](https://user-images.githubusercontent.com/51314259/78106324-db36ab00-73fb-11ea-97fe-28957df48a69.gif)

►Log
```kotlin
--------- beginning of crash
04-01 09:26:05.828 18622-18622/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fenix.nightly, PID: 18622
    kotlin.TypeCastException: null cannot be cast to non-null type kotlin.String
        at -$$LambdaGroup$js$yYMvyZVuCIBAx87qTqj6O0z70jU.onClick(java-style lambda group:27)
        at android.view.View.performClick(View.java:5233)
        at android.view.View$PerformClick.run(View.java:21209)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:152)
        at android.app.ActivityThread.main(ActivityThread.java:5507)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
04-01 09:26:05.829 18622-18622/? D/AppTracker: App Event: crash

```

**Comment by csadilek** [comment]
Duping to #6447 and adjusting title as this can happen for every add-on. Work in progress and continues in https://github.com/mozilla-mobile/android-components/issues/6447
