### ISSUE TITLE
UnsupportedAddonsAdapter: NoSuchElementException: Key en-US is missing in the map.

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#6498]
https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/issues/7726065/

```
NoSuchElementException: Key en-US is missing in the map.
    at kotlin.collections.ArraysKt___ArraysKt.getValue(_Arrays.kt:3)
    at kotlin.jvm.internal.Intrinsics.translate(Intrinsics.java:2)
    at mozilla.components.feature.addons.ui.UnsupportedAddonsAdapter.onBindViewHolder(UnsupportedAddonsAdapter.kt:7)
    at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:1)
    at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6)
...
(63 additional frame(s) were not displayed)

Key en-US is missing in the map.
```

**Comment by Amejia481** [comment]
It looks like there is an unsupported add-on, that doesn't have translations for the locale the user is using and neither have translations for our fallback locale "en-US"

**Comment by Amejia481** [comment]
Closing in favor of  https://github.com/mozilla-mobile/android-components/issues/6496
