### ISSUE TITLE
SessionStorage.restore(): OutOfMemoryError: Failed to allocate a 74701520 byte allocation with 25165824 free bytes and 53MB until OOM, max al...

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#6534]
https://sentry.prod.mozaws.net/operations/firefox-beta/issues/7758020/

```
OutOfMemoryError: Failed to allocate a 74701520 byte allocation with 25165824 free bytes and 53MB until OOM, max allowed footprint 237520064, growth limit 268435456
    at java.lang.StringFactory.newStringFromChars(StringFactory.java:267)
    at java.lang.StringBuffer.toString(StringBuffer.java:671)
    at java.io.StringWriter.toString(StringWriter.java:210)
    at kotlin.io.FilesKt__FileReadWriteKt.readText(FileReadWrite.kt:5)
    at kotlin.jvm.internal.Intrinsics.readSnapshot(Intrinsics.java:2)
...
(6 additional frame(s) were not displayed)

Failed to allocate a 74701520 byte allocation with 25165824 free bytes and 53MB until OOM, max allowed footprint 237520064, growth limit 268435456
```

**Comment by pocmo** [comment]
Happened for a Fennec beta migration build.

We saw a similar issue in the past when migrating sessions. We do seem to have some users with a ton of tabs open. We should parse sessions from a stream, like we do during the migration nowadays.

**Comment by pocmo** [comment]
We parse streams now.
