### ISSUE TITLE
promots: IllegalStateException: cursor.getString(nameIndex) must not be null

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#6536]
https://sentry.prod.mozaws.net/operations/firefox-beta/issues/7756991/

```
IllegalStateException: cursor.getString(nameIndex) must not be null
    at mozilla.components.feature.prompts.file.FilePicker.onActivityResult(FilePicker.kt:1)
    at mozilla.components.feature.prompts.PromptFeature.onActivityResult(PromptFeature.kt:1)
    at org.mozilla.fenix.browser.BaseBrowserFragment$onActivityResult$1.invoke(BaseBrowserFragment.kt:2)
    at mozilla.components.support.base.feature.ViewBoundFeatureWrapper.withFeature(ViewBoundFeatureWrapper.kt:1)
    at org.mozilla.fenix.browser.BaseBrowserFragment.onActivityResult(BaseBrowserFragment.kt:1)
...
(12 additional frame(s) were not displayed)

RuntimeException: Failure delivering result ResultInfo{who=null, request=203721, result=-1, data=Intent { dat=content://media/external/file/179544 typ=application/pdf flg=0x3 }} to activity {org.mozilla.firefox_beta/org.mozilla.fenix.HomeActivity}: java.lang.IllegalStateException: cursor.getString(nameIndex) must not be null
    at android.app.ActivityThread.deliverResults(ActivityThread.java:4564)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:4608)
    at android.app.ActivityThread.-wrap19
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1832)
    at android.os.Handler.dispatchMessage(Handler.java:106)
...
(5 additional frame(s) were not displayed)

Failure delivering result ResultInfo{who=null, request=203721, result=-1, data=Intent { dat=content://media/external/file/179544 typ=application/pdf flg=0x3 }} to activity {org.mozilla.firefox_beta/org.mozilla.fenix.HomeActivity}: java.lang.IllegalStateException: cursor.getString(nameIndex) must not be null
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5519)

**Comment by jonalmeida** [comment]
Closing as won't fix; crash doesn't show up any more and the last reports were from AC 54.
