### ISSUE TITLE
(addonsManagementFragment) TypeCastException: null cannot be cast to non-null type kotlin.String

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#6537]
https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/issues/7761373/

```
TypeCastException: null cannot be cast to non-null type kotlin.String
    at -$$LambdaGroup$js$yYMvyZVuCIBAx87qTqj6O0z70jU.onClick(java-style lambda group:27)
    at android.view.View.performClick(View.java:6734)
    at android.view.View.performClickInternal(View.java:6697)
    at android.view.View.access$3400(View.java:804)
    at android.view.View$PerformClick.run(View.java:26370)
...
(7 additional frame(s) were not displayed)

null cannot be cast to non-null type kotlin.String
```

**Comment by pocmo** [comment]
From the bug it is not completely clear where this is happening. But the last breadcrumb is `addonsManagementFragment` ... so I assume it may be related to our web extension code.

**Comment by Amejia481** [comment]
I think this could be marked as dup of https://github.com/mozilla-mobile/fenix/issues/9647
