### ISSUE TITLE
AddonManagerException: org.json.JSONException: Unterminated string at character [..]

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#6543]
https://sentry.prod.mozaws.net/operations/firefox-beta/issues/7754016/

```
JSONException: Unterminated string at character 38311 of {"page_size":25,"page_count":1,"count":1,"next":null,"previous":null,"results":[{"addon":{"id":607454,"authors":[{"id":11423598,"name":"Raymond Hill","url":"https://addons.mozilla.org/ar/firefox/user/11423598/","username":"gorhill","picture_url":null}],"average_daily_users":5927899,"categories":{"android":["security-privacy"],"firefox":["privacy-security"]},"contributions_url":"","created":"2015-04-25T07:26:22Z","current_version":{"id":4977457,"compatibility":{"firefox":{"min":"55.0","max":"*"},"android":{"min":"55.0","max":"*"}},"edit_url":"https://addons.mozilla.org/ar/developers/addon/ublock-origin/versions/4977457","files":[{"id":3521827,"created":"2020-03-07T13:24:22Z","hash":"sha256:997aac00064665641298047534c9392492ef09f0cbf177b6a30d4fa288081579","is_restart_required":false,"is_webextension":true,"is_mozilla_signed_extension":false,"platform":"all","size":2645595,"status":"public","url":"https://addons.mozilla.org/firefox/downloads/file/3521827/ublock_origin-1.25.2-an+fx.xpi?src=","permissions":["dns","menus","privacy","storage","tabs","unlimitedStorage","webNavigation","webRequest","webRequestBlocking","<all_urls>","http://*/*","https://*/*","file://*/*"]}],"is_strict_compatibility_enabled":false,"license":{"id":6,"is_custom":false,"name":{"ca":"Llicència GPL (General Public License) de GNU, version 3.0","cs":"GNU General Public License, verze 3.0","de":"GNU General Public License, Version 3.0","el":"GNU General Public License, έκδοση 3.0","en-US":"GNU General Public License, version 3.0","es":"Licencia pública GNU, versión 3.0","eu":"GNU General Public License, 3.0 bertsioa","fa":"مجوز عمومی کلی گنو، نسخهٔ ۳٫۰","ga-IE":"GNU General Public License, leagan 3.0","id":"GNU General Public License, versi 3.0","it":"Licenza GNU General Public License, versione 3.0","ja":"GNU General Public License バージョン 3.0","nl":"GNU General Public License, versie 3.0","pl":"General Public Licence, wersja 3.0","pt-PT":"GNU General Public License, versão 3.0","ru":"GNU General Public License, версия 3.0","sk":"GNU General Public License, verzia 3.0","sq":"Leje e Përgjithshme Publike GNU, version 3.0","uk":"GNU General Public License, версія 3.0","vi":"Giấy phép Công cộng GNU, phiên bản 3.0","zh-CN":"GNU 通用公共授权，版本 3.0","zh-TW":"GNU General Public License，版本 3.0"},"url":"http://www.gnu.org/licenses/gpl-3.0.html"},"release_notes":{"en-US":"See <a href=\"https://outgoing.prod.mozaws.net/v1/97fc44a938a39d8a3b4029072b26a2b7094223786bf3004322727696ba9c0e67/https%3A//github.com/gorhill/uBlock/releases/tag/1.25.2\" rel=\"nofollow\">release notes</a>.\n\n<b>Closed as fixed:</b>\n\n<ul><li><a href=\"https://outgoing.prod.mozaws.net/v1/726ca7bca8f5bb5b2d8ffd4eead53361817a12fb13922d6216e05227691120b3/https%3A//github.com/gorhill/uBlock/pull/3770\" rel=\"nofollow\">In Element Zapper, support Mac keyboards’ Delete key</a> (pull request from @roryokane)</li><li><a href=\"https://outgoing.prod.mozaws.net/v1/8817f9b70dcf93bd42d27c4b193a7204f8e443628b98a221ad084ee9655a460c/https%3A//github.com/uBlockOrigin/uBlock-issues/issues/900\" rel=\"nofollow\">Uncaught (in promise) ReferenceError: WebAssembly is not defined</a></li><li><a href=\"https://outgoing.prod.mozaws.net/v1/c34981d47335e60b6c8219288b674db78f767e6a5fe1c9a1bbbfed97d92a1238/https%3A//github.com/uBlockOrigin/uBlock-issues/issues/899\" rel=\"nofollow\">Accessing localStorage delays startup</a></li><li><a href=\"https://outgoing.prod.mozaws.net/v1/35062af62bcfded82dce44dd580419e60171bd7153a6b03c2d5675ba15bcbf19/https%3A//github.com/uBlockOrigin/uBlock-issues/issues/879\" rel=\"nofollow\">Need to whitelist Microsoft Edge internal page</a></li></ul>\n<b>Notable commits with no entry in issue tracker:</b>\n\n<ul><li><a href=\"https://outgoing.prod.mozaws.net/v1/458a98e112f68479807841f48f003d46d67e3c7ddf4cfeb52f6536ec49a0ded9/https%3A//github.com/gorhill/uBlock/commit/034c915f3be1257ed5de638a456e7c95932c553d\" rel=\"nofollow\">Allow re-entrance in abort-current-inline-script</a></li><li><a href=\"https://outgoing.prod.mozaws.net/v1/9721c53234293bf9a9bb3a2a0...
    at org.json.JSONTokener.syntaxError(JSONTokener.java:460)
    at org.json.JSONTokener.nextString(JSONTokener.java:234)
    at org.json.JSONTokener.nextValue(JSONTokener.java:111)
    at org.json.JSONTokener.readObject(JSONTokener.java:394)
    at org.json.JSONTokener.nextValue(JSONTokener.java:104)
...
(20 additional frame(s) were not displayed)

AddonManagerException: org.json.JSONException: Unterminated string at character 38311 of {"page_size":25,"page_count":1,"count":1,"next":null,"previous":null,"results":[{"addon":{"id":607454,"authors":[{"id":11423598,"name":"Raymond Hill","url":"https://addons.mozilla.org/ar/firefox/user/11423598/","username":"gorhill","picture_url":null}],"average_daily_users":5927899,"categories":{"android":["security-privacy"],"firefox":["privacy-security"]},"contributions_url":"","created":"2015-04-25T07:26:22Z","current_version":{"id":4977457,"compatibility":{"firefox":{"min":"55.0","max":"*"},"android":{"min":"55.0","max":"*"}},"edit_url":"https://addons.mozilla.org/ar/developers/addon/ublock-origin/versions/4977457","files":[{"id":3521827,"created":"2020-03-07T13:24:22Z","hash":"sha256:997aac00064665641298047534c9392492ef09f0cbf177b6a30d4fa288081579","is_restart_required":false,"is_webextension":true,"is_mozilla_signed_extension":false,"platform":"all","size":2645595,"status":"public","url":"https://addons.mozilla.org/firefox/downloads/file/3521827/ublock_origin-1.25.2-an+fx.xpi?src=","permissions":["dns","menus","privacy","storage","tabs","unlimitedStorage","webNavigation","webRequest","webRequestBlocking","<all_urls>","http://*/*","https://*/*","file://*/*"]}],"is_strict_compatibility_enabled":false,"license":{"id":6,"is_custom":false,"name":{"ca":"Llicència GPL (General Public License) de GNU, version 3.0","cs":"GNU General Public License, verze 3.0","de":"GNU General Public License, Version 3.0","el":"GNU General Public License, έκδοση 3.0","en-US":"GNU General Public License, version 3.0","es":"Licencia pública GNU, versión 3.0","eu":"GNU General Public License, 3.0 bertsioa","fa":"مجوز عمومی کلی گنو، نسخهٔ ۳٫۰","ga-IE":"GNU General Public License, leagan 3.0","id":"GNU General Public License, versi 3.0","it":"Licenza GNU General Public License, versione 3.0","ja":"GNU General Public License バージョン 3.0","nl":"GNU General Public License, versie 3.0","pl":"General Public Licence, wersja 3.0","pt-PT":"GNU General Public License, versão 3.0","ru":"GNU General Public License, версия 3.0","sk":"GNU General Public License, verzia 3.0","sq":"Leje e Përgjithshme Publike GNU, version 3.0","uk":"GNU General Public License, версія 3.0","vi":"Giấy phép Công cộng GNU, phiên bản 3.0","zh-CN":"GNU 通用公共授权，版本 3.0","zh-TW":"GNU General Public License，版本 3.0"},"url":"http://www.gnu.org/licenses/gpl-3.0.html"},"release_notes":{"en-US":"See <a href=\"https://outgoing.prod.mozaws.net/v1/97fc44a938a39d8a3b4029072b26a2b7094223786bf3004322727696ba9c0e67/https%3A//github.com/gorhill/uBlock/releases/tag/1.25.2\" rel=\"nofollow\">release notes</a>.\n\n<b>Closed as fixed:</b>\n\n<ul><li><a href=\"https://outgoing.prod.mozaws.net/v1/726ca7bca8f5bb5b2d8ffd4eead53361817a12fb13922d6216e05227691120b3/https%3A//github.com/gorhill/uBlock/pull/3770\" rel=\"nofollow\">In Element Zapper, support Mac keyboards’ Delete key</a> (pull request from @roryokane)</li><li><a href=\"https://outgoing.prod.mozaws.net/v1/8817f9b70dcf93bd42d27c4b193a7204f8e443628b98a221ad084ee9655a460c/https%3A//github.com/uBlockOrigin/uBlock-issues/issues/900\" rel=\"nofollow\">Uncaught (in promise) ReferenceError: WebAssembly is not defined</a></li><li><a href=\"https://outgoing.prod.mozaws.net/v1/c34981d47335e60b6c8219288b674db78f767e6a5fe1c9a1bbbfed97d92a1238/https%3A//github.com/uBlockOrigin/uBlock-issues/issues/899\" rel=\"nofollow\">Accessing localStorage delays startup</a></li><li><a href=\"https://outgoing.prod.mozaws.net/v1/35062af62bcfded82dce44dd580419e60171bd7153a6b03c2d5675ba15bcbf19/https%3A//github.com/uBlockOrigin/uBlock-issues/issues/879\" rel=\"nofollow\">Need to whitelist Microsoft Edge internal page</a></li></ul>\n<b>Notable commits with no entry in issue tracker:</b>\n\n<ul><li><a href=\"https://outgoing.prod.mozaws.net/v1/458a98e112f68479807841f48f003d46d67e3c7ddf4cfeb52f6536ec49a0ded9/https%3A//github.com/gorhill/uBlock/commit/034c915f3be1257ed5de638a456e7c95932c553d\" rel=\"nofollow\">Allow re-entrance in abort-current-inline-script</a></li><li><a href=\"https://outgoing.prod.mozaws.net/v1/9...
    at mozilla.components.feature.addons.AddonManager.getAddons(AddonManager.kt:57)
    at mozilla.components.feature.addons.AddonManager.getAddons$default(AddonManager.kt:1)
    at mozilla.components.feature.addons.migration.SupportedAddonsWorker.doWork(SupportedAddonsChecker.kt:7)
    at androidx.work.CoroutineWorker$startWork$1.invokeSuspend(CoroutineWorker.kt:5)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
...
(3 additional frame(s) were not displayed)

[INFO] org.json.JSONException: Unterminated string at character 38311 of {"page_size":25,"page_count":1,"count":1,"next":null,"previous":null,"results":[{"addon":{"id":607454,"authors":[{"id":11423598,"name":"Raymond Hill","url":"https://addons.mozilla.org/ar/firefox/user/11423598/","username":"gorhill","picture_url":null}],"average_daily_users":5927899,"categories":{"android":["security-privacy"],"firefox":["privacy-security"]},"contributions_url":"","created":"2015-04-25T07:26:22Z","current_version":{"id":4977457,"compatibility":{"firefox":{"min":"55.0","max":"*"},"android":{"min":"55.0","max":"*"}},"edit_url":"https://addons.mozilla.org/ar/developers/addon/ublock-origin/versions/4977457","files":[{"id":3521827,"created":"2020-03-07T13:24:22Z","hash":"sha256:997aac00064665641298047534c9392492ef09f0cbf177b6a30d4fa288081579","is_restart_required":false,"is_webextension":true,"is_mozilla_signed_extension":false,"platform":"all","size":2645595,"status":"public","url":"https://addons.m...
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5527)

**Comment by csadilek** [comment]
Fixed by https://github.com/mozilla-mobile/android-components/issues/8147.
