### ISSUE TITLE
LoginsStorageException: Protobuf decode error: failed to decode Protobuf message: invalid wire type value: 6

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#6560]
https://sentry.prod.mozaws.net/operations/firefox-beta/issues/7771891/

```
LoginsStorageException: Protobuf decode error: failed to decode Protobuf message: invalid wire type value: 6
    at mozilla.appservices.logins.rust.RustError.intoException(RustError.kt:4)
    at mozilla.appservices.logins.DatabaseLoginsStorage.ensureValid(DatabaseLoginsStorage.kt:20)
    at mozilla.components.service.sync.logins.SyncableLoginsStorage$ensureValid$2.invokeSuspend(SyncableLoginsStorage.kt:3)
    at mozilla.components.service.sync.logins.SyncableLoginsStorage$ensureValid$2.invoke(SyncableLoginsStorage.kt)
    at kotlin.jvm.internal.Intrinsics.startUndispatchedOrReturn(Intrinsics.java:2)
...
(6 additional frame(s) were not displayed)

Protobuf decode error: failed to decode Protobuf message: invalid wire type value: 6
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5550)

**Comment by ekager** [comment]
We are updating AS and some of this logic in #6298 so maybe that will help but haven't seen this type of error before.
cc @grigoryk

**Comment by jonalmeida** [comment]
This crash no longer happens (we don't even use protobuf anymore!); closing as won't fix.
