### ISSUE TITLE
PlacesBookmarksStorage: UrlParseFailed: Error parsing URL: invalid domain character

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#6588]
https://sentry.prod.mozaws.net/operations/firefox-beta/issues/7799970/

```
UrlParseFailed: Error parsing URL: invalid domain character
    at mozilla.appservices.places.RustError.intoException(RustError.kt:13)
    at mozilla.appservices.places.PlacesReaderConnection.searchBookmarks(PlacesConnection.kt:16)
    at mozilla.components.browser.storage.sync.PlacesBookmarksStorage$searchBookmarks$2.invokeSuspend(PlacesBookmarksStorage.kt:3)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:19)
...
(2 additional frame(s) were not displayed)

Error parsing URL: invalid domain character
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5586)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795147

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
