### ISSUE TITLE
TopSiteStorage: SQLiteDatabaseLockedException: database is locked (code 5 SQLITE_BUSY): , while compiling: PRAGMA journal_mode

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#6589]
https://sentry.prod.mozaws.net/operations/firefox-beta/issues/7799994/

```
SQLiteDatabaseLockedException: database is locked (code 5 SQLITE_BUSY): , while compiling: PRAGMA journal_mode
    at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
    at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:909)
    at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:654)
    at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:339)
    at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:304)
...
(22 additional frame(s) were not displayed)

database is locked (code 5 SQLITE_BUSY): , while compiling: PRAGMA journal_mode
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5587)

**Comment by csadilek** [comment]
Last version I am seeing these is 99. Closing.
