### ISSUE TITLE
IllegalStateException - You need to call PushProcessor.install() on your Push instance from Application.onCreate()

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#6590]
> https://sentry.prod.mozaws.net/operations/firefox-beta/issues/7791258

This looks like a message that we print. Did code get moved around to get things off the startup path? There are very few of these in 4.2.1 Fennec Beta - so maybe it is just very unfortunate timing?

```
java.lang.IllegalStateException: You need to call PushProcessor.install() on your Push instance from Application.onCreate().
    at mozilla.components.concept.push.PushProcessor$Companion.getRequireInstance(PushProcessor.kt:1)
    at mozilla.components.lib.push.firebase.AbstractFirebasePushService.onNewToken(AbstractFirebasePushService.kt:1)
    at org.mozilla.fenix.components.FirebasePushService.onNewToken(FirebasePushService.kt:1)
    at com.google.firebase.messaging.FirebaseMessagingService.zzd
    at com.google.firebase.iid.zzc.run
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at com.google.android.gms.common.util.concurrent.zza.run
    at java.lang.Thread.run(Thread.java:818)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5589)

**Comment by rvandermeulen** [comment]
This is currently the #7 overall topcrash in Fenix 95.2.0 according to Socorro:
https://crash-stats.mozilla.org/signature/?product=Fenix&signature=java.lang.IllegalStateException%3A%20at%20mozilla.components.lib.push.firebase.AbstractFirebasePushService.onMessageReceived%28AbstractFirebasePushService.kt%3A13%29

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795146

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
