### ISSUE TITLE
ClassCastException: mozilla.components.concept.storage.Login cannot be cast to java.lang.Boolean

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#6591]
> https://sentry.prod.mozaws.net/operations/firefox-beta/issues/7795881

Low frequency on the 4.2.1 Fennec Migration build, but probably worth an investigation? Feels like a _this should never happen_ kind of exception.

```
java.lang.ClassCastException: mozilla.components.concept.storage.Login cannot be cast to java.lang.Boolean
    at mozilla.components.feature.prompts.PromptFeature.onConfirm(PromptFeature.kt:16)
    at mozilla.components.feature.prompts.dialog.LoginDialogFragment.access$onPositiveClickAction(LoginDialogFragment.kt:10)
    at -$$LambdaGroup$js$ShXO7hRzPdt_LOzUGJeIMrgdRBc.onClick(java-style lambda group:3)
    at android.view.View.performClick(View.java:6308)
    at android.view.View$PerformClick.run(View.java:24949)
    at android.os.Handler.handleCallback(Handler.java:790)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6548)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
```

**Comment by pocmo** [comment]
Related to (or the same as) #6576
