### ISSUE TITLE
HttpIconLoader: OutOfMemoryError: Failed to allocate a 268435472 byte allocation with 25165824 free bytes and 121MB until OOM, max ...

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#6638]
https://sentry.prod.mozaws.net/operations/firefox-beta/issues/7846101/

```
OutOfMemoryError: Failed to allocate a 268435472 byte allocation with 25165824 free bytes and 121MB until OOM, max allowed footprint 166064880, growth limit 268435456
    at java.util.Arrays.copyOf(Arrays.java:3164)
    at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
    at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
    at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
    at androidx.transition.CanvasUtils.copyTo$default(CanvasUtils.java:3)
...
(10 additional frame(s) were not displayed)

Failed to allocate a 268435472 byte allocation with 25165824 free bytes and 121MB until OOM, max allowed footprint 166064880, growth limit 268435456
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5635)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795145

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
