### ISSUE TITLE
IllegalArgumentException - Comparison method violates its general contract!

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#6640]
> https://sentry.prod.mozaws.net/operations/firefox-beta/issues/7849936

Low frequency but maybe something we can avoid?

```
java.lang.IllegalArgumentException: Comparison method violates its general contract!
    at java.util.TimSort.mergeHi(TimSort.java:899)
    at java.util.TimSort.mergeAt(TimSort.java:516)
    at java.util.TimSort.mergeForceCollapse(TimSort.java:457)
    at java.util.TimSort.sort(TimSort.java:254)
    at java.util.Arrays.sort(Arrays.java:1498)
    at java.util.ArrayList.sort(ArrayList.java:1470)
    at java.util.Collections.sort(Collections.java:201)
    at androidx.transition.CanvasUtils.sortWith(CanvasUtils.java:1)
    at mozilla.components.browser.icons.BrowserIcons$loadIcon$1.invokeSuspend(BrowserIcons.kt:19)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5638)

**Comment by kbrosnan** [comment]
Still happening https://sentry.io/organizations/mozilla/issues/?project=6375561&project=6295546&project=6295551&query=is%3Aunresolved+Comparison+method+violates+its+general+contract%21&statsPeriod=14d

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793157

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
