### ISSUE TITLE
IllegalStateException: it.origins must not be null

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#6641]
> https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/issues/7847098

This appeared on Migrated Fennec Beta. A few reports but all for a single device it seems.

```
java.lang.IllegalStateException: it.origins must not be null
    at mozilla.components.browser.engine.gecko.webextension.GeckoWebExtension.getMetadata(GeckoWebExtension.kt:10)
    at mozilla.components.support.webextensions.WebExtensionSupport.toState(WebExtensionSupport.kt:4)
    at mozilla.components.support.webextensions.WebExtensionSupport.registerInstalledExtension(WebExtensionSupport.kt:4)
    at mozilla.components.support.webextensions.WebExtensionSupport.access$registerInstalledExtension(WebExtensionSupport.kt:1)
    at -$$LambdaGroup$ks$LeLeCGfMVtNYZ7WsvHRaCO5Fr9g.invoke(com.android.tools.r8.jetbrains.kotlin-style lambda group:27)
    at mozilla.components.browser.engine.gecko.GeckoEngine$listInstalledWebExtensions$1.onValue(GeckoEngine.kt:16)
    at org.mozilla.geckoview.GeckoResult.lambda$thenInternal$2$GeckoResult(GeckoResult.java:2)
    at org.mozilla.geckoview.-$$Lambda$GeckoResult$gwCgOUK_EYQn2g6GolfZvo6A_WE.run(lambda)
    at org.mozilla.geckoview.GeckoResult.lambda$dispatchLocked$3(GeckoResult.java:2)
    at org.mozilla.geckoview.-$$Lambda$GeckoResult$PehjG2jgyDa_p37vZrKrSi2I94s.run(lambda)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:145)
    at android.app.ActivityThread.main(ActivityThread.java:6134)
    at java.lang.reflect.Method.invoke(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

org.mozilla.geckoview.UncaughtException: java.lang.IllegalStateException: it.origins must not be null
    at org.mozilla.geckoview.GeckoResult.dispatchLocked(GeckoResult.java:4)
    at org.mozilla.geckoview.GeckoResult.completeExceptionally(GeckoResult.java:4)
    at org.mozilla.geckoview.GeckoResult.lambda$thenInternal$2$GeckoResult(GeckoResult.java:10)
    at org.mozilla.geckoview.-$$Lambda$GeckoResult$gwCgOUK_EYQn2g6GolfZvo6A_WE.run(lambda)
    at org.mozilla.geckoview.GeckoResult.lambda$dispatchLocked$3(GeckoResult.java:2)
    at org.mozilla.geckoview.-$$Lambda$GeckoResult$PehjG2jgyDa_p37vZrKrSi2I94s.run(lambda)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:145)
    at android.app.ActivityThread.main(ActivityThread.java:6134)
    at java.lang.reflect.Method.invoke(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

**Comment by csadilek** [comment]
Hm, GeckoView has `origins` documented as `@NonNull`. This may be related to a specific extension. Will investigate...

**Comment by csadilek** [comment]
GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1629957
