### ISSUE TITLE
IncompatibleClassChangeError: Couldn't find androidx.lifecycle.OnLifecycleEvent.value

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#6642]
> https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/issues/7840581

I put a Push label on this crash but I don't think it is actually Push related. I think that is just the place where we run into this.

I did notice that the reports are for Android 5.0 - maybe `androidx.lifecycle.LifecycleRegistry.addObserver` has an issue there? Or maybe it is supposed to throw exceptions in case of errors? 

```
java.lang.IncompatibleClassChangeError: Couldn't find androidx.lifecycle.OnLifecycleEvent.value
    at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:659)
    at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:641)
    at libcore.reflect.AnnotationAccess.getDeclaredAnnotation(AnnotationAccess.java:170)
    at java.lang.reflect.Method.getAnnotation(Method.java:301)
    at androidx.lifecycle.ClassesInfoCache.createInfo(ClassesInfoCache.java:13)
    at androidx.lifecycle.ClassesInfoCache.hasLifecycleMethods(ClassesInfoCache.java:6)
    at androidx.lifecycle.Lifecycling.resolveObserverCallbackType(Lifecycling.java:6)
    at androidx.lifecycle.Lifecycling.getObserverConstructorType(Lifecycling.java:3)
    at androidx.lifecycle.Lifecycling.lifecycleEventObserver(Lifecycling.java:7)
    at androidx.lifecycle.LifecycleRegistry$ObserverWithState.<init>(LifecycleRegistry.java:2)
    at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:2)
    at mozilla.components.support.base.observer.ObserverRegistry.register(ObserverRegistry.kt:11)
    at mozilla.components.feature.accounts.push.FxaPushSupportFeature.<init>(FxaPushSupportFeature.kt:12)
    at org.mozilla.fenix.components.BackgroundServices.<init>(BackgroundServices.kt:44)
    at org.mozilla.fenix.components.Components$backgroundServices$2.invoke(Components.kt:12)
```

**Comment by jonalmeida** [comment]
This might be a multi-dex issue since the classes are not found. We might have to add a proguard rule instead?

**Comment by Shabinder** [comment]
`-keep class androidx.lifecycle.** {*;}`
I guess this progaurd rule would suffice, however haven't tested this yet.

**Comment by Hasnat-Ehmad** [comment]
[Shabinder](https://github.com/Shabinder) answer works.
 Thanks
