### ISSUE TITLE
CursorWindowAllocationException: Cursor window allocation of 2048 kb failed

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#6671]
> https://sentry.prod.mozaws.net/operations/firefox-beta/issues/7879795

Unclear what is happening here, but 2KB is not a lot to request and the device doesn't seem to be in a low memory situation.

```
android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. # Open Cursors=1 (# cursors opened by this proc=1)
    at android.database.CursorWindow.<init>(CursorWindow.java:108)
    at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
    at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:138)
    at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
    at mozilla.components.feature.top.sites.db.TopSiteDao_Impl$3.call(TopSiteDao_Impl.java:11)
    at androidx.room.RoomTrackingLiveData$1.run(RoomTrackingLiveData.java:5)
    at androidx.room.TransactionExecutor$1.run(TransactionExecutor.java:1)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
    at java.lang.Thread.run(Thread.java:764)

java.lang.RuntimeException: Exception while computing database live data.
    at androidx.room.RoomTrackingLiveData$1.run(RoomTrackingLiveData.java:6)
    at androidx.room.TransactionExecutor$1.run(TransactionExecutor.java:1)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
    at java.lang.Thread.run(Thread.java:764)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5676)

**Comment by kbrosnan** [comment]
These reports show OOM behavior see bz-760394 for previous investigations for Fennec. The main thing we can do here is track down leaks and stop them from happening.
