### ISSUE TITLE
RuntimeException: Unexpected icon value: null

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#6673]
> https://sentry.prod.mozaws.net/operations/firefox-beta/issues/7843009

```
java.lang.RuntimeException: Unexpected icon value: null
    at org.mozilla.geckoview.WebExtension$Icon.getIconValue(WebExtension.java:13)
    at org.mozilla.geckoview.WebExtension$Icon.<init>(WebExtension.java:8)
    at org.mozilla.geckoview.WebExtension$MetaData.<init>(WebExtension.java:48)
    at org.mozilla.geckoview.WebExtension.<init>(WebExtension.java:8)
    at org.mozilla.geckoview.WebExtensionController$2.sendSuccess(WebExtensionController.java:5)
    at org.mozilla.gecko.EventDispatcher$JavaCallbackDelegate$1.run(EventDispatcher.java:2)
    at android.os.Handler.handleCallback(Handler.java:761)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:156)
    at android.app.ActivityThread.main(ActivityThread.java:6517)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5679)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796312

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
