### ISSUE TITLE
OutOfMemoryError from GeckoEngineView.captureThumbnail

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#6675]
> https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/issues/7893158

Normally we ignore OOMEs but this one caught my attention. Screenshots on high resolution devices can use a lot of memory. Should we have a fallback scenario, where we estimate how much this would take and if there is not enough free memory available, use a placeholder image instead?

In this case the bitmap request was 7.2MB while only 2.4MB was available. Maybe a generic image is better than crashing?

```
java.lang.OutOfMemoryError: Failed to allocate a 7257612 byte allocation with 2417144 free bytes and 2MB until OOM
    at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
    at android.graphics.Bitmap.nativeCreate(Bitmap.java)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:975)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:946)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:913)
    at org.mozilla.geckoview.GeckoDisplay$ScreenshotBuilder.capture(GeckoDisplay.java:21)
    at org.mozilla.geckoview.GeckoDisplay.capturePixels(GeckoDisplay.java:1)
    at org.mozilla.geckoview.GeckoView$Display.capturePixels(GeckoView.java:3)
    at org.mozilla.geckoview.GeckoView.capturePixels(GeckoView.java:1)
    at mozilla.components.browser.engine.gecko.GeckoEngineView.captureThumbnail(GeckoEngineView.kt:3)
    at org.mozilla.fenix.browser.BrowserAnimator$captureEngineViewAndDrawStatically$$inlined$let$lambda$1.invokeSuspend(BrowserAnimator.kt:9)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
    at kotlinx.coroutines.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:18)
    at kotlin.jvm.internal.Intrinsics.startCoroutineCancellable(Intrinsics.java:1)
    at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:15)
    at kotlin.jvm.internal.Intrinsics.launch(Intrinsics.java:6)
    at kotlin.jvm.internal.Intrinsics.launch$default(Intrinsics.java:2)
    at org.mozilla.fenix.browser.BrowserAnimator.captureEngineViewAndDrawStatically(BrowserAnimator.kt:2)
    at org.mozilla.fenix.components.toolbar.BrowserToolbarView$$special$$inlined$with$lambda$1.invoke(BrowserToolbarView.kt:7)
    at -$$LambdaGroup$js$rSoSXqyxpjwo3DM2X62KxPNCfB8.onClick(java-style lambda group:257)
    at android.view.View.performClick(View.java:5697)
    at android.widget.TextView.performClick(TextView.java:10826)
    at android.view.View$PerformClick.run(View.java:22526)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:158)
    at android.app.ActivityThread.main(ActivityThread.java:7224)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by jonalmeida** [comment]
This is something that's important for tabs tray. Adding it to that board as well.

**Comment by jonalmeida** [comment]
These crashes started and stopped in AC 37.0.0 and we're on 48.0.0 in Fenix. A lot has changed in thumbnails since then so I'm going to close this for now.
