### ISSUE TITLE
IllegalStateException from QrFeature.removeQrFragment

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#6678]
> https://sentry.prod.mozaws.net/operations/firefox-beta/issues/7881442

```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
    at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:6)
    at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:14)
    at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:1)
    at mozilla.components.feature.qr.QrFeature.removeQrFragment$feature_qr_release(QrFeature.kt:4)
    at mozilla.components.feature.qr.QrFeature$scanCompleteListener$1.onScanComplete(QrFeature.kt:1)
    at -$$LambdaGroup$js$B8PecC72Gd5rnZ7z3D0x_TttToo.run(java-style lambda group:18)
    at android.os.Handler.handleCallback(Handler.java:815)
    at android.os.Handler.dispatchMessage(Handler.java:104)
    at android.os.Looper.loop(Looper.java:194)
    at android.app.ActivityThread.main(ActivityThread.java:5651)
    at java.lang.reflect.Method.invoke(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
```

**Comment by kbrosnan** [comment]
@Mugurell is this resolved by https://github.com/mozilla-mobile/fenix/issues/13037?

**Comment by Mugurell** [comment]
> @Mugurell is this resolved by [mozilla-mobile/fenix#13037](https://github.com/mozilla-mobile/fenix/issues/13037)?

No, seems like a different issues that happens after users have actually scanned the qr code and want to go back.
Tried to search for new occurrences but it seems like it isn't an issue anymore?

**Comment by Mugurell** [comment]
The patch for this has been merged.
Should really not happen anymore but let's keep an eye on Sentry to be sure.

**Comment by Mugurell** [comment]
The above beta issue listing seems to not be available anymore.
Saw no new occurrences of this on Nightly in the last 14 days - https://sentry.prod.mozaws.net/operations/firefox-nightly/?query=is%3Aunresolved+java.lang.IllegalStateException%3A+Can+not+perform+this+action+after+onSaveInstanceState&statsPeriod=14d
@kbrosnan do you think this can be closed as fixed?

**Comment by mcarare** [comment]
This crash does not seem to have any occurrences anymore, I am closing this as such.
