### ISSUE TITLE
RuntimeException: Cannot confirm/dismiss a Prompt twice

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#6679]
> https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/issues/7881330

Unclear if this is an AC or GV issue.

```
java.lang.RuntimeException: Cannot confirm/dismiss a Prompt twice.
    at org.mozilla.geckoview.GeckoSession$PromptDelegate$BasePrompt.confirm(GeckoSession.java:5)
    at org.mozilla.geckoview.GeckoSession$PromptDelegate$FilePrompt.confirm(GeckoSession.java:10)
    at org.mozilla.geckoview.GeckoSession$PromptDelegate$FilePrompt.confirm(GeckoSession.java:1)
    at mozilla.components.browser.engine.gecko.prompt.GeckoPromptDelegate$onFilePrompt$onSelectSingle$1.invoke(GeckoPromptDelegate.kt:2)
    at mozilla.components.feature.prompts.file.FilePicker.handleFilePickerIntentResult$feature_prompts_release(FilePicker.kt:9)
    at mozilla.components.feature.prompts.file.FilePicker$onActivityResult$1.invoke(FilePicker.kt:4)
    at kotlin.jvm.internal.Intrinsics.consumePromptFrom(Intrinsics.java:8)
    at kotlin.jvm.internal.Intrinsics.consumePromptFrom$default(Intrinsics.java:1)
    at mozilla.components.feature.prompts.file.FilePicker.onActivityResult(FilePicker.kt:1)
    at mozilla.components.feature.prompts.PromptFeature.onActivityResult(PromptFeature.kt:1)
    at org.mozilla.fenix.browser.BaseBrowserFragment$onActivityResult$1.invoke(BaseBrowserFragment.kt:2)
    at mozilla.components.support.base.feature.ViewBoundFeatureWrapper.withFeature(ViewBoundFeatureWrapper.kt:1)
    at org.mozilla.fenix.browser.BaseBrowserFragment.onActivityResult(BaseBrowserFragment.kt:1)
    at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:8)
    at android.app.Activity.dispatchActivityResult(Activity.java:6500)
    at android.app.ActivityThread.deliverResults(ActivityThread.java:3936)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:3983)
    at android.app.ActivityThread.-wrap16(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1548)
    at android.os.Handler.dispatchMessage(Handler.java:111)
    at android.os.Looper.loop(Looper.java:207)
    at android.app.ActivityThread.main(ActivityThread.java:5765)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```

**Comment by liuche** [comment]
Dupe to #6445
