### ISSUE TITLE
IllegalStateException: Compositor must be ready before pixels can be captured

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#6680]
> https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/issues/7876670

There are quite a few of these now in Migrated Fennec Beta. I don't think I've seen this before.

```
java.lang.IllegalStateException: Compositor must be ready before pixels can be captured
    at org.mozilla.geckoview.GeckoDisplay$ScreenshotBuilder.capture(GeckoDisplay.java:24)
    at org.mozilla.geckoview.GeckoDisplay.capturePixels(GeckoDisplay.java:1)
    at org.mozilla.geckoview.GeckoView$Display.capturePixels(GeckoView.java:3)
    at org.mozilla.geckoview.GeckoView.capturePixels(GeckoView.java:1)
    at mozilla.components.browser.engine.gecko.GeckoEngineView.captureThumbnail(GeckoEngineView.kt:3)
    at org.mozilla.fenix.browser.BrowserAnimator$captureEngineViewAndDrawStatically$$inlined$let$lambda$1.invokeSuspend(BrowserAnimator.kt:9)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
    at kotlinx.coroutines.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:18)
    at kotlin.jvm.internal.Intrinsics.startCoroutineCancellable(Intrinsics.java:1)
    at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:15)
    at kotlin.jvm.internal.Intrinsics.launch(Intrinsics.java:6)
    at kotlin.jvm.internal.Intrinsics.launch$default(Intrinsics.java:2)
    at org.mozilla.fenix.browser.BrowserAnimator.captureEngineViewAndDrawStatically(BrowserAnimator.kt:2)
    at org.mozilla.fenix.components.toolbar.BrowserToolbarView$$special$$inlined$with$lambda$1.invoke(BrowserToolbarView.kt:7)
    at -$$LambdaGroup$js$rSoSXqyxpjwo3DM2X62KxPNCfB8.onClick(java-style lambda group:257)
    at android.view.View.performClick(View.java:5697)
    at android.widget.TextView.performClick(TextView.java:10826)
    at android.view.View$PerformClick.run(View.java:22526)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:158)
    at android.app.ActivityThread.main(ActivityThread.java:7224)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by kbrosnan** [comment]
Snorp suggested catching the exception. This has really spiked with the beta release. Looks like @csadilek has made some changes in this area. Would you have a look or redirect?

BZ-1644998
https://crash-stats.mozilla.org/signature/?product=Fenix&signature=java.lang.IllegalStateException%3A%20at%20org.mozilla.geckoview.GeckoDisplay%24ScreenshotBuilder.capture%28GeckoDisplay.java%29

**Comment by csadilek** [comment]
This was first fixed back in November. GeckoView advised to wait for `firstContenfulPaint` which we implemented for: https://github.com/mozilla-mobile/android-components/issues/5189

This seems to not be good enough anymore? I don't think catching `IllegalStateException`s is ideal. Will reach out to James, to discuss.

**Comment by csadilek** [comment]
Talked to James. Unfortunately, there's no reliably way to determine if the compositor is ready or not. So, short-term, we can really only add a catch-all. Ideally, the GeckoResult should resolve in an error, as opposed to the (async) method throwing an exception. With this in place everything would have already worked correctly, as we return null in case of an error result.

New GV bug filed: https://bugzilla.mozilla.org/show_bug.cgi?id=1645114

**Comment by kbrosnan** [comment]
Sentry issue: [FENIX-FENNEC-BETA-X8](https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/issues/8053505/?referrer=github_plugin)
