### ISSUE TITLE
PlacesException (Query returned no rows) via PlacesHistoryStorage$deleteEverything

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#6711]
> https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/issues/7923939

Maybe this is a normal situation (no rows) returned as an error?

```
mozilla.appservices.places.PlacesException: Error executing SQL: Query returned no rows
    at mozilla.appservices.places.RustError.intoException(RustError.kt:4)
    at mozilla.appservices.places.PlacesWriterConnection.deleteEverything(PlacesConnection.kt:11)
    at mozilla.components.browser.storage.sync.PlacesHistoryStorage$deleteEverything$2.invokeSuspend(PlacesHistoryStorage.kt:3)
    at mozilla.components.browser.storage.sync.PlacesHistoryStorage$deleteEverything$2.invoke
    at kotlin.jvm.internal.Intrinsics.startUndispatchedOrReturn(Intrinsics.java:2)
    at kotlin.jvm.internal.Intrinsics.withContext(Intrinsics.java:9)
    at mozilla.components.browser.storage.sync.PlacesHistoryStorage.deleteEverything(PlacesHistoryStorage.kt:1)
    at org.mozilla.fenix.settings.deletebrowsingdata.DefaultDeleteBrowsingDataController.deleteHistoryAndDOMStorages(DeleteBrowsingDataController.kt:4)
    at org.mozilla.fenix.settings.deletebrowsingdata.DefaultDeleteBrowsingDataController$deleteHistoryAndDOMStorages$1.invokeSuspend
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:19)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:14)
```

**Comment by kbrosnan** [comment]
Not seeing any instances of crash in Gecko 78 or 79.
