### ISSUE TITLE
Crash KotlinNullPointerExceptionmozilla.components.feature.downloads.AbstractFetchDownloadService

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#6797]
Related Fenix issue https://github.com/mozilla-mobile/fenix/issues/7303

```
kotlin.KotlinNullPointerException: null
    at mozilla.components.feature.downloads.AbstractFetchDownloadService.useFileStreamScopedStorage(AbstractFetchDownloadService.kt:18)
    at mozilla.components.feature.downloads.AbstractFetchDownloadService.useFileStream$feature_downloads_release(AbstractFetchDownloadService.kt:8)
    at mozilla.components.feature.downloads.AbstractFetchDownloadService$performDownload$1.invoke(AbstractFetchDownloadService.kt:20)
    at mozilla.components.concept.fetch.Response$Body.useStream(Response.kt:1)
    at mozilla.components.feature.downloads.AbstractFetchDownloadService.performDownload$feature_downloads_release(AbstractFetchDownloadService.kt:19)
    at mozilla.components.feature.downloads.AbstractFetchDownloadService.startDownloadJob$feature_downloads_release(AbstractFetchDownloadService.kt:3)
    at mozilla.components.feature.downloads.AbstractFetchDownloadService$onStartCommand$1.invokeSuspend(AbstractFetchDownloadService.kt:5)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:19)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:14)
```

**Comment by Amejia481** [comment]
I think it could be related to the below ‼️  expressions.

[First](https://github.com/gabrielluong/android-components/blob/281a63fda4e9163efb97bc8a50fa51a75d68d0fb/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt#L375) : `copyInChunks(downloadJobs[download.id]!!, inStream, outStream)`

[Second](https://github.com/gabrielluong/android-components/blob/281a63fda4e9163efb97bc8a50fa51a75d68d0fb/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt#L378) : ` verifyDownload(downloadJobs[download.id]!!)`

**Comment by Amejia481** [comment]
We could avoid the ‼️ expressions by using `currentDownloadJobState`, as it should hold the same value as `downloadJobs[download.id]`, but I'm not sure how we got in that state, it looks like `downloadJobs` could be modified by another thread, we have to keep investigating.

```kotlin
    internal fun performDownload(download: DownloadState) {
        val currentDownloadJobState = downloadJobs[download.id] ?: return
        val isResumingDownload = currentDownloadJobState.currentBytesCopied > 0L
        val headers = MutableHeaders()

        if (isResumingDownload) {
            headers.append(RANGE, "bytes=${currentDownloadJobState.currentBytesCopied}-")
        }

        val request = Request(download.url, headers = headers)
        val response = httpClient.fetch(request)

        // If we are resuming a download and the response does not contain a CONTENT_RANGE
        // we cannot be sure that the request will properly be handled
        if (response.status != PARTIAL_CONTENT_STATUS && response.status != OK_STATUS ||
            (isResumingDownload && !response.headers.contains(CONTENT_RANGE))) {
            // We experienced a problem trying to fetch the file, send a failure notification
            currentDownloadJobState.currentBytesCopied = 0
            setDownloadJobStatus(currentDownloadJobState, DownloadJobStatus.FAILED)
            return
        }

        response.body.useStream { inStream ->
            val newDownloadState = download.withResponse(response.headers, inStream)
            currentDownloadJobState.state = newDownloadState

            useFileStream(newDownloadState, isResumingDownload) { outStream ->
                copyInChunks(currentDownloadJobState, inStream, outStream)
            }

            verifyDownload(currentDownloadJobState)
        }
    }
```
