### ISSUE TITLE
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#6920]
I saw a ton of those in a Fenix log. Seems to be coming from AS. Not sure if we need to do something here. The Android system has been closing down non API SDK usage over the last versions. So it may be possible that this will turn into a crash at some point.

```
            StrictMode  D  StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Lsun/misc/Unsafe;->putLong(Ljava
                            /lang/Object;JJ)V
                         D      at android.os.StrictMode.lambda$static$1(StrictMode.java:411)
                         D      at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
                         D      at java.lang.Class.getDeclaredMethodInternal(Native Method)
                         D      at java.lang.Class.getPublicMethodRecursive(Class.java:2079)
                         D      at java.lang.Class.getMethod(Class.java:2066)
                         D      at java.lang.Class.getMethod(Class.java:1693)
                         D      at com.google.protobuf.UnsafeUtil.supportsUnsafeArrayOperations(UnsafeUtil.java:349)
                         D      at com.google.protobuf.UnsafeUtil.<clinit>(UnsafeUtil.java:52)
                         D      at com.google.protobuf.UnsafeUtil.getUnsafe(UnsafeUtil.java:291)
                         D      at com.google.protobuf.MessageSchema.<clinit>(MessageSchema.java:101)
                         D      at com.google.protobuf.MessageSchema.newSchema(MessageSchema.java:220)
                         D      at com.google.protobuf.ManifestSchemaFactory.newSchema(ManifestSchemaFactory.java:77)
                         D      at com.google.protobuf.ManifestSchemaFactory.createSchema(ManifestSchemaFactory.java:71)
                         D      at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:93)
                         D      at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:107)
                         D      at com.google.protobuf.GeneratedMessageLite.parsePartialFrom(GeneratedMessageLite.java:1531)
                         D      at com.google.protobuf.GeneratedMessageLite.parseFrom(GeneratedMessageLite.java:1695)
                         D      at com.google.protobuf.GeneratedMessageLite.parseFrom(GeneratedMessageLite.java:1688)
                         D      at mozilla.appservices.places.MsgTypes$SearchResultList.parseFrom(MsgTypes.java:6095)
                         D      at mozilla.appservices.places.PlacesReaderConnection.queryAutocomplete(PlacesConnection.kt:271)
                         D      at mozilla.components.browser.storage.sync.PlacesHistoryStorage.getSuggestions(PlacesHistoryStorage.kt:
                            102)
                         D      at mozilla.components.feature.awesomebar.provider.HistoryStorageSuggestionProvider.onInputChanged(Histo
                            ryStorageSuggestionProvider.kt:48)
                         D      at mozilla.components.browser.awesomebar.BrowserAwesomeBar$onInputChanged$1.invokeSuspend(BrowserAwesom
                            eBar.kt:144)
                         D      at mozilla.components.browser.awesomebar.BrowserAwesomeBar$onInputChanged$1.invoke(Unknown Source:10)
                         D      at mozilla.components.browser.awesomebar.BrowserAwesomeBar$queryProvidersForSuggestions$1$invokeSuspend
                            $$inlined$forEach$lambda$1$1.invokeSuspend(BrowserAwesomeBar.kt:157)
                         D      at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                         D      at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
                         D      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                         D      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                         D      at java.lang.Thread.run(Thread.java:923)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5907)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795364

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
