### ISSUE TITLE
Crash IllegalArgumentException: Unsupported URI scheme when downloading icon

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/android-components#7142]
Originally reported here: https://github.com/mozilla-mobile/fenix/issues/10880

## Steps to reproduce
Visit https://www.gruppoapi.com/ricerca-stazioni-servizio

> 2020-05-27 20:00:14.677 9383-9590/org.mozilla.fenix.debug D/HttpIconLoader: IllegalArgumentException while trying to download icon resource https://www.gruppoapi.com/ricerca-stazioni-servizio/images/logo-gruppoapi-shared.png
    
    java.lang.IllegalArgumentException: Unsupported URI scheme
        at org.mozilla.geckoview.GeckoWebExecutor.fetch(GeckoWebExecutor.java:128)
        at mozilla.components.browser.engine.gecko.fetch.GeckoViewFetchClient.fetch(GeckoViewFetchClient.kt:64)
        at mozilla.components.browser.icons.loader.HttpIconLoader.load(HttpIconLoader.kt:54)
        at mozilla.components.browser.icons.BrowserIconsKt.load(BrowserIcons.kt:276)
        at mozilla.components.browser.icons.BrowserIconsKt.access$load(BrowserIcons.kt:1)
        at mozilla.components.browser.icons.BrowserIcons.loadIconInternal(BrowserIcons.kt:127)
        at mozilla.components.browser.icons.BrowserIcons.access$loadIconInternal(BrowserIcons.kt:77)
        at mozilla.components.browser.icons.BrowserIcons$loadIcon$1.invokeSuspend(BrowserIcons.kt:110)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

I confirmed catching the `IllegalArgumentException` in `HttpIconLoader` fixes this, which we should probably do because crashing on fetching icons seems silly, but I thought this was interesting to bring up before catching it because it's unclear to me why this website would be an `Unsupported URI scheme`.

**Comment by Amejia481** [comment]
The url contains breaking line "https://www.gruppoapi.com/ricerca-stazioni-servizio/images/logo-gruppoapi-shared.png\n" character causing  https://dxr.mozilla.org/mozilla-central/source/mobile/android/geckoview/src/main/java/org/mozilla/geckoview/GeckoWebExecutor.java#127 to break

**Comment by Amejia481** [comment]
Sentry crash https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/8443650/?query=is%3Aunresolved
