### ISSUE TITLE
PlacesHistoryStorage crash in Sample Browser

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#7244]
This seems to be a regression. Sample browser is crashing quite frequently now when moving from background to foreground or loading a new page.

```
 java.lang.IllegalStateException: must call init first
        at mozilla.components.browser.storage.sync.RustPlacesConnection.writer(Connection.kt:95)
        at mozilla.components.browser.storage.sync.PlacesHistoryStorage$recordObservation$2.invokeSuspend(PlacesHistoryStorage.kt:63)
        at mozilla.components.browser.storage.sync.PlacesHistoryStorage$recordObservation$2.invoke(Unknown Source:10)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:154)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
        at mozilla.components.browser.storage.sync.PlacesHistoryStorage.recordObservation$suspendImpl(PlacesHistoryStorage.kt:59)
        at mozilla.components.browser.storage.sync.PlacesHistoryStorage.recordObservation(Unknown Source:0)
        at mozilla.components.feature.session.HistoryDelegate.onTitleChanged(HistoryDelegate.kt:28)
        at mozilla.components.browser.engine.gecko.GeckoEngineSession$createContentDelegate$1$onTitleChange$$inlined$let$lambda$1.invokeSuspend(GeckoEngineSession.kt:700)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by csadilek** [comment]
Different trace for `onDestroy`:

```
    java.lang.RuntimeException: Unable to destroy activity {org.mozilla.samples.browser/org.mozilla.samples.browser.BrowserActivity}: java.lang.IllegalStateException: must call init first
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4941)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4970)
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalStateException: must call init first
        at mozilla.components.browser.storage.sync.RustPlacesConnection.close(Connection.kt:127)
        at mozilla.components.browser.storage.sync.PlacesStorage.cleanup(PlacesStorage.kt:64)
        at org.mozilla.samples.browser.BrowserActivity.onDestroy(BrowserActivity.kt:60)
        at android.app.Activity.performDestroy(Activity.java:8071)
```

**Comment by grigoryk** [comment]
Ran out of time today, will come back to this on Monday. Seems like doing what Fenix does (and hitting the storage `init` code sometime right after startup) should fix this, but that also shouldn't be necessary...
E.g. looking at the code, we appear to call `init` before any interaction with the APIs. But from the stacktraces, that's clearly not the case - so something's broken here, in a way that we're not hitting this in Fenix.

**Comment by csadilek** [comment]
@grigoryk I think I found a real problem here in our lib:

The first problem (see first stack) is caused by a thread-safety issue accessing `api` when requesting the `writer`: https://github.com/mozilla-mobile/android-components/blob/master/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/Connection.kt#L94

`onTitleChange` in the Engine triggers the first initialization of the `RustPlacesConnection` in Sample Browser. This should be good enough and work. However, it runs on a different IO thread than `recordObservation` and its `writer`. Unlike `reader` and `init`, `writer` isn't synchronized and may run before `init` is complete.

The second problem is that we call `cleanup` in `BrowserActivity.onDestroy` and we simply might have never needed the storage before.
