### ISSUE TITLE
Certain actions with afterChange() followed by syncDispatch() take from 200ms - 800ms

### ISSUE THREAD

**Issue by MarcLeclair** [mozilla-mobile/android-components#7295]
I've noticed that some actions block the Java Main Thread when navigating to a new webpage. I've noticed it in the following build:

- locally with `geckoBetaFenixBeta` builds as shown in this profile: https://share.firefox.dev/2Y47G8D and https://share.firefox.dev/2zZ3KOu  . In this one,  `UpdateBackNavigationStateAction` takes up to 500ms at times.

- From the playstore, I noticed it with the `Nightly for Developers` build  as shown in these profiles: 
   G5 plus: https://share.firefox.dev/373tsgR
   Pixel 4: https://share.firefox.dev/3dE1Np8
  However, in this scenario, it's actually the `UpdateTitleAction` that seems to take a long time to finish.

It is worth to note that I tried it on `Firefox for Android` channel too on the play store and didn't see this behavior happening.  (profile for reference) (https://share.firefox.dev/2MAwxLY

I'm not sure if there's anything to do about this, but it seems as if a simple update action shouldn't take this long on our Main Thread.

**Comment by csadilek** [comment]
> locally with `geckoBetaFenixBeta` builds as

Just clarifying that this happens on master only, also with`geckoBetaFenixBeta` build from master, but not on the latest published beta build. That means it's a pretty recent regression. @pocmo pointed to the new `ThumbnailsMiddleware` which seems to run IO operations on the main thread?

**Comment by pocmo** [comment]
Locally I enabled `StrictMode` on the store thread and that was also the first thing it caught:

```
D  StrictMode policy violation: android.os.strictmode.DiskReadViolation
D      at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1589)
D      at libcore.io.BlockGuardOs.access(BlockGuardOs.java:71)
D      at libcore.io.ForwardingOs.access(ForwardingOs.java:72)
D      at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:7351)
D      at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:281)
D      at java.io.File.exists(File.java:815)
D      at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:677)
D      at android.app.ContextImpl.ensurePrivateCacheDirExists(ContextImpl.java:673)
D      at android.app.ContextImpl.getCacheDir(ContextImpl.java:784)
D      at android.content.ContextWrapper.getCacheDir(ContextWrapper.java:292)
D      at mozilla.components.browser.thumbnails.utils.ThumbnailDiskCache.getThumbnailCacheDirectory(ThumbnailDiskCache.kt:78)
D      at mozilla.components.browser.thumbnails.utils.ThumbnailDiskCache.getThumbnailCache(ThumbnailDiskCache.kt:87)
D      at mozilla.components.browser.thumbnails.utils.ThumbnailDiskCache.putThumbnailBitmap$browser_thumbnails_debug(ThumbnailDiskCache.k
t:63)
D      at mozilla.components.browser.thumbnails.storage.ThumbnailStorage.saveThumbnail(ThumbnailStorage.kt:85)
D      at mozilla.components.browser.thumbnails.ThumbnailsMiddleware.invoke(ThumbnailsMiddleware.kt:30)
D      at mozilla.components.browser.thumbnails.ThumbnailsMiddleware.invoke(ThumbnailsMiddleware.kt:18)
D      at mozilla.components.lib.state.internal.ReducerChainBuilder$build$$inlined$forEach$lambda$1.invoke(ReducerChainBuilder.kt:53)
```
