### ISSUE TITLE
push::crypto - base64 failed for target:salt; InvalidByte(0, 34)

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#7316]
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/8679281/events/41d07fef0f7f441aa0f9f21552f402eb/

```
...
    at $Proxy5.push_decrypt
    at mozilla.appservices.push.PushManager.decrypt(PushManager.kt:5)
    at mozilla.components.feature.push.RustPushConnection.decryptMessage(Connection.kt:5)
    at mozilla.components.feature.push.AutoPushFeature$onMessageReceived$$inlined$ifInitialized$lambda$1.invokeSuspend(AutoPushFeature.kt:12)
    at mozilla.components.feature.push.AutoPushFeature$onMessageReceived$$inlined$ifInitialized$lambda$1.invoke
    at mozilla.components.feature.push.ext.CoroutineScopeKt$launchAndTry$2.invokeSuspend(CoroutineScope.kt:5)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:919)
```

**Comment by jonalmeida** [comment]
This is being tracked in https://github.com/mozilla/application-services/issues/3365.

**Comment by jonalmeida** [comment]
The errors have now been resolved on the autopush side.
