### ISSUE TITLE
IllegalArgumentException:  invalid value for param: totalBytes

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#7401]
https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/issues/8642501/?referrer=github_plugin

```
IllegalArgumentException:  invalid value for param: totalBytes
    at android.app.DownloadManager.addCompletedDownload(DownloadManager.java:1388)
    at android.app.DownloadManager.addCompletedDownload(DownloadManager.java:1366)
    at mozilla.components.feature.downloads.AbstractFetchDownloadService.addToDownloadSystemDatabaseCompat$feature_downloads_release(AbstractFetchDownloadService.kt:17)
    at mozilla.components.feature.downloads.AbstractFetchDownloadService.updateDownloadNotification$feature_downloads_release(AbstractFetchDownloadService.kt:5)
    at mozilla.components.feature.downloads.AbstractFetchDownloadService.access$updateDownloadNotification(AbstractFetchDownloadService.kt:5)
...
(14 additional frame(s) were not displayed)

 invalid value for param: totalBytes
```

**Comment by Amejia481** [comment]
It looks like this happens when we pass an negative file size to `addCompletedDownload`, with some luck it could be fixed when https://github.com/mozilla-mobile/android-components/pull/7400 lands on Fenix, let's keep an eye open to see if the crashes continue increasing after the patch.

[Source](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/app/DownloadManager.java;l=1501?q=DownloadManager)

```java
    public long addCompletedDownload(String title, String description,
            boolean isMediaScannerScannable, String mimeType, String path, long length,
            boolean showNotification, boolean allowWrite, Uri uri, Uri referer) {
        // make sure the input args are non-null/non-zero
        validateArgumentIsNonEmpty("title", title);
        validateArgumentIsNonEmpty("description", description);
        validateArgumentIsNonEmpty("path", path);
        validateArgumentIsNonEmpty("mimeType", mimeType);
        if (length < 0) {
            throw new IllegalArgumentException(" invalid value for param: totalBytes");
        }

```

**Comment by Amejia481** [comment]
It's been a while since the last report, I think is OK to close it. Please feel free to reopen if it seen again
