### ISSUE TITLE
DownloadDialogFragment: DiskReadViolation

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#7403]
Just got this in Focus. Looks like `DownloadDialogFragment` indirectly does File I/O on the main thread.

```
D  StrictMode policy violation; ~duration=75 ms: android.os.strictmode.DiskReadViolation
D      at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1589)
D      at libcore.io.BlockGuardOs.access(BlockGuardOs.java:71)
D      at libcore.io.ForwardingOs.access(ForwardingOs.java:72)
D      at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:7351)
D      at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:281)
D      at java.io.File.exists(File.java:815)
D      at mozilla.components.support.utils.DownloadUtils.uniqueFileName(DownloadUtils.kt:83)
D      at mozilla.components.support.utils.DownloadUtils.guessFileName(DownloadUtils.kt:65)
D      at mozilla.components.feature.downloads.DownloadDialogFragment.setDownload(DownloadDialogFragment.kt:36)
D      at mozilla.components.feature.downloads.DownloadsFeature.showDialog(DownloadsFeature.kt:183)
D      at mozilla.components.feature.downloads.DownloadsFeature.processDownload(DownloadsFeature.kt:128)
D      at mozilla.components.feature.downloads.DownloadsFeature.access$processDownload(DownloadsFeature.kt:56)
D      at mozilla.components.feature.downloads.DownloadsFeature$onPermissionsResult$1.invoke(DownloadsFeature.kt:164)
D      at mozilla.components.feature.downloads.DownloadsFeature$onPermissionsResult$1.invoke(DownloadsFeature.kt:56)
D      at mozilla.components.feature.downloads.DownloadsFeature.withActiveDownload(DownloadsFeature.kt:211)
D      at mozilla.components.feature.downloads.DownloadsFeature.onPermissionsResult(DownloadsFeature.kt:162)
D      at org.mozilla.focus.fragment.BrowserFragment.onRequestPermissionsResult(BrowserFragment.kt:608)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6403)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1792944

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
