### ISSUE TITLE
Settings may cause WebView method call on wrong thread

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/android-components#742]
I encountered a crash on Fire TV with a stack trace that seems to point to components.  I have only seen this once, but I'll comment here if I get any more reproduction information.

From home, fresh install:
- Clicked tile
- Waited to load
- Backed out to home
- Clicked tile
- Crashed

```
    java.lang.Throwable: A WebView method was called on thread 'Chrome_FileThread'. All WebView methods must be called on the same thread. (Expected Looper Looper (main, tid 1) {2cb5e88} called on null, FYI main Looper is Looper (main, tid 1) {2cb5e88})
        at android.webkit.WebView.checkThread(WebView.java:2350)
        at android.webkit.WebView.getSettings(WebView.java:1943)
        at mozilla.components.browser.engine.system.SystemEngineSession.initSettings$engine_system_release(SystemEngineSession.kt:161)
        at mozilla.components.browser.engine.system.SystemEngineSession.getSettings(SystemEngineSession.kt:156)
        at mozilla.components.browser.engine.system.SystemEngineView$createWebViewClient$1.shouldInterceptRequest(SystemEngineView.kt:145)
        at com.amazon.webview.awvclients.AmazonWebViewClient.shouldInterceptRequest(AmazonWebViewClient.java:226)
        at com.android.webview.chromium.WebViewContentsClientAdapter.shouldInterceptRequest(WebViewContentsClientAdapter.java:322)
        at com.android.webview.chromium.WebViewExtAmazonContentsClientAdapter.shouldInterceptRequest(WebViewExtAmazonContentsClientAdapter.java:18)
        at org.chromium.android_webview.AwContents$BackgroundThreadClientImpl.shouldInterceptRequest(AwContents.java:497)
        at org.chromium.android_webview.AwContentsBackgroundThreadClient.shouldInterceptRequestFromNative(AwContentsBackgroundThreadClient.java:38)
2018-09-10 14:53:05.975 28896-28953/? E/cr_Cloud9JNICrash: java.lang.RuntimeException: java.lang.Throwable: A WebView method was called on thread 'Chrome_FileThread'. All WebView methods must be called on the same thread. (Expected Looper Looper (main, tid 1) {2cb5e88} called on null, FYI main Looper is Looper (main, tid 1) {2cb5e88})
        at android.webkit.WebView.checkThread(WebView.java:2360)
        at android.webkit.WebView.getSettings(WebView.java:1943)
        at mozilla.components.browser.engine.system.SystemEngineSession.initSettings$engine_system_release(SystemEngineSession.kt:161)
        at mozilla.components.browser.engine.system.SystemEngineSession.getSettings(SystemEngineSession.kt:156)
        at mozilla.components.browser.engine.system.SystemEngineView$createWebViewClient$1.shouldInterceptRequest(SystemEngineView.kt:145)
        at com.amazon.webview.awvclients.AmazonWebViewClient.shouldInterceptRequest(AmazonWebViewClient.java:226)
        at com.android.webview.chromium.WebViewContentsClientAdapter.shouldInterceptRequest(WebViewContentsClientAdapter.java:322)
        at com.android.webview.chromium.WebViewExtAmazonContentsClientAdapter.shouldInterceptRequest(WebViewExtAmazonContentsClientAdapter.java:18)
        at org.chromium.android_webview.AwContents$BackgroundThreadClientImpl.shouldInterceptRequest(AwContents.java:497)
        at org.chromium.android_webview.AwContentsBackgroundThreadClient.shouldInterceptRequestFromNative(AwContentsBackgroundThreadClient.java:38)
     Caused by: java.lang.Throwable: A WebView method was called on thread 'Chrome_FileThread'. All WebView methods must be called on the same thread. (Expected Looper Looper (main, tid 1) {2cb5e88} called on null, FYI main Looper is Looper (main, tid 1) {2cb5e88})
        at android.webkit.WebView.checkThread(WebView.java:2350)
        at android.webkit.WebView.getSettings(WebView.java:1943) 
        at mozilla.components.browser.engine.system.SystemEngineSession.initSettings$engine_system_release(SystemEngineSession.kt:161) 
        at mozilla.components.browser.engine.system.SystemEngineSession.getSettings(SystemEngineSession.kt:156) 
        at mozilla.components.browser.engine.system.SystemEngineView$createWebViewClient$1.shouldInterceptRequest(SystemEngineView.kt:145) 
        at com.amazon.webview.awvclients.AmazonWebViewClient.shouldInterceptRequest(AmazonWebViewClient.java:226) 
        at com.android.webview.chromium.WebViewContentsClientAdapter.shouldInterceptRequest(WebViewContentsClientAdapter.java:322) 
        at com.android.webview.chromium.WebViewExtAmazonContentsClientAdapter.shouldInterceptRequest(WebViewExtAmazonContentsClientAdapter.java:18) 
        at org.chromium.android_webview.AwContents$BackgroundThreadClientImpl.shouldInterceptRequest(AwContents.java:497) 
        at org.chromium.android_webview.AwContentsBackgroundThreadClient.shouldInterceptRequestFromNative(AwContentsBackgroundThreadClient.java:38) 
```

**Comment by csadilek** [comment]
I think I understand what's happening here. The thread on which `shouldIntereceptRequest` is called doesn't see that latest updated session (which is updated and initialized in `SystemEngineView.render`). Therefore the view's settings are getting initialized lazily and on the wrong thread: https://github.com/mozilla-mobile/android-components/blob/master/components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineSession.kt#L165

@Baron-Severin I will look into this and try to fix it this Sprint. Let me know if you have any more details.
