### ISSUE TITLE
RemoteTabProviderException: failed to decide Protobuf message

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#7426]
34247b71-83dd-4ab8-9c2d-65cdd6e3e259
mozilla.appservices.remotetabs.RemoteTabProviderException: Protobuf decode error: failed to decode Protobuf message: invalid tag value: 0
 * Sentry: https://sentry.prod.mozaws.net/operations/fenix-nightly/?query=17356c25bd8f4740aac2a348736206e2
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-39e50735-cca3-426b-ba73-fb56b0200617
----
```
mozilla.appservices.remotetabs.RemoteTabProviderException: Protobuf decode error: failed to decode Protobuf message: invalid tag value: 0
	at mozilla.appservices.remotetabs.rust.RustError.intoException(RustError.kt:4)
	at mozilla.appservices.remotetabs.RemoteTabsProvider.setLocalTabs(RemoteTabsProvider.kt:14)
	at mozilla.components.browser.storage.sync.RemoteTabsStorage$store$2.invokeSuspend(RemoteTabsStorage.kt:16)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
```

**Comment by kbrosnan** [comment]
Sentry issue: [FENIX-FENNEC-NIGHTLY-2DJ](https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/issues/8617877/?referrer=github_plugin)

**Comment by kbrosnan** [comment]
Sentry issue: [FENIX-FENNEC-BETA-2FC](https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/issues/8942570/?referrer=github_plugin)

**Comment by pocmo** [comment]
@vladikoff Can this still happen now that you  switched to JSON instead of protocol buffers?

**Comment by vladikoff** [comment]
cc @rfk @eoger

**Comment by eoger** [comment]
Not for Synced Tabs no.

**Comment by pocmo** [comment]
Alright, closing! :)
