### ISSUE TITLE
SitePermissionsFeature: InvalidParameterException: not a valid permission

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#7428]
Had cases of this in the past: https://github.com/mozilla-mobile/android-components/issues/5723

Today's Fenix Nightly (Nightly 200617 06:00):
```
java.security.InvalidParameterException: Generic(id=6, desc=Gecko permission type = 6) is not a valid permission.
    at mozilla.components.feature.sitepermissions.SitePermissionsFeature.toSitePermissions(SitePermissionsFeature.kt:14)
    at mozilla.components.feature.sitepermissions.SitePermissionsFeature.toSitePermissions$default(SitePermissionsFeature.kt:2)
    at mozilla.components.feature.sitepermissions.SitePermissionsFeature$storeSitePermissions$1.invokeSuspend(SitePermissionsFeature.kt:5)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6424)

**Comment by csadilek** [comment]
Not seeing this crash anymore. Closing.
