### ISSUE TITLE
ExceptionInInitializerError: Caused by: java.lang.UnsatisfiedLinkError: Unable to load library 'glean_ffi':

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#7511]
```
    FATAL EXCEPTION: GleanAPIPool
Process: org.mozilla.samples.browser, PID: 6717
java.lang.ExceptionInInitializerError
	at mozilla.telemetry.glean.GleanInternalAPI$initialize$1.invokeSuspend(Glean.kt:151)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.IllegalStateException: Glean functionality not available
	at mozilla.telemetry.glean.rust.LibGleanFFI$Companion$INSTANCE$1.invoke(LibGleanFFI.kt:79)
	at mozilla.telemetry.glean.rust.LibGleanFFI$Companion$INSTANCE$1.invoke(LibGleanFFI.kt:67)
	at java.lang.reflect.Proxy.invoke(Proxy.java:397)
	at $Proxy2.glean_new_ping_type(Unknown Source)
	at mozilla.telemetry.glean.private.PingType.<init>(PingType.kt:54)
	at mozilla.telemetry.glean.GleanMetrics.Pings.<clinit>(Pings.kt:52)
	... 10 more
Caused by: java.lang.UnsatisfiedLinkError: Unable to load library 'glean_ffi':
dlopen failed: cannot locate symbol "stderr" referenced by "libglean_ffi.so"...
dlopen failed: cannot locate symbol "stderr" referenced by "libglean_ffi.so"...
dlopen failed: cannot locate symbol "stderr" referenced by "libglean_ffi.so"...
Native library (android-x86/libglean_ffi.so) not found in resource path (.)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:302)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:455)
	at com.sun.jna.Library$Handler.<init>(Library.java:179)
	at com.sun.jna.Native.load(Native.java:596)
	at com.sun.jna.Native.load(Native.java:570)
	at mozilla.telemetry.glean.rust.LibGleanFFI$Companion.<clinit>(LibGleanFFI.kt:71)
	at mozilla.telemetry.glean.rust.LibGleanFFI.<clinit>(LibGleanFFI.kt)
	... 12 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "stderr" referenced by "libglean_ffi.so"...
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)
		... 18 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "stderr" referenced by "libglean_ffi.so"...
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:204)
		... 18 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "stderr" referenced by "libglean_ffi.so"...
		at java.lang.Runtime.loadLibrary(Runtime.java:371)
		at java.lang.System.loadLibrary(System.java:989)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:218)
		... 18 more
	Suppressed: java.io.IOException: Native library (android-x86/libglean_ffi.so) not found in resource path (.)
		at com.sun.jna.Native.extractFromResourcePath(Native.java:1089)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:276)
		... 18 more
```

**Comment by pocmo** [comment]
Happened on Firebase:
https://treeherder.mozilla.org/#/jobs?repo=android-components&group_state=expanded&resultStatus=testfailed%2Cbusted%2Cexception%2Cusercancel%2Crunnable&revision=3ee940a24c3d733b8b4530ada67baccfc14d4bfb

**Comment by pocmo** [comment]
Passed on `Pixel 2, API Level 28`, but failed on `Nexus 6, Virtual, API Level 21` (I think the "virtual" here means that this is an x86 emulator).

**Comment by mdboom** [comment]
I'm a bit stumped, but we did recently change our Android builds from being built on CircleCI to directly on Taskcluster, and I wonder if there is some environmental difference there.  @badboy is probably the most expert on that.

We could probably revert https://github.com/mozilla-mobile/android-components/pull/7505 in the meantime without too much difficulty if this is blocking other work.
