### ISSUE TITLE
Releasing session to switch from custom tab to browser does not work anymore

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#7647]
Fenix issue: https://github.com/mozilla-mobile/fenix/issues/12311

This looks like it is a regression from the refactoring to use `BrowserStore` in the `SessionFeature`.

**Comment by pocmo** [comment]
After adding a similar switch action to sample browser I can reproduce it there too:

```
         AndroidRuntime  E  FATAL EXCEPTION: main
                         E  Process: org.mozilla.samples.browser, PID: 515
                         E  java.lang.IllegalStateException: SET SESSION: Current activity: BrowserActivity Other activity: ExternalAppBrowserActivity
                         E      at mozilla.components.browser.engine.gecko.GeckoEngineView.render(GeckoEngineView.kt:124)
                         E      at mozilla.components.feature.session.engine.EngineViewPresenter.onEngineSession(EngineViewPresenter.kt:53)
                         E      at mozilla.components.feature.session.engine.EngineViewPresenter.access$onEngineSession(EngineViewPresenter.kt:22)
                         E      at mozilla.components.feature.session.engine.EngineViewPresenter$start$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:137)
                         E      at mozilla.components.support.ktx.kotlinx.coroutines.flow.FlowKt$ifChanged$$inlined$filter$1$2.emit(Collect.kt:147)
                         E      at mozilla.components.feature.session.engine.EngineViewPresenter$start$1$invokeSuspend$$inlined$map$2$2.emit(Collect.kt:139)
                         E      at mozilla.components.feature.session.engine.EngineViewPresenter$start$1$invokeSuspend$$inlined$map$1$2.emit(Collect.kt:139)
                         E      at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:59)
                         E      at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:11)
                         E      at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                         E      at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
                         E      at android.os.Handler.handleCallback(Handler.java:907)
                         E      at android.os.Handler.dispatchMessage(Handler.java:99)
                         E      at android.os.Looper.loop(Looper.java:216)
                         E      at android.app.ActivityThread.main(ActivityThread.java:7464)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)
                         E  Caused by: java.lang.IllegalStateException: Display already acquired
                         E      at org.mozilla.geckoview.GeckoSession.acquireDisplay(GeckoSession.java:2398)
                         E      at org.mozilla.geckoview.GeckoView.setSession(GeckoView.java:441)
                         E      at mozilla.components.browser.engine.gecko.GeckoEngineView.render(GeckoEngineView.kt:115)
                         E      ... 17 more
```

This almost looks like we didn't actually release the session? Or maybe too late?

**Comment by pocmo** [comment]
What's happening in the store is that we are removing the `TabSessionState` and adding a `CustomTabSessionState`. Since that new state has the same ID as before the `SessionFeature` will find it and render it again. Since that happens asynchronously just reordering the calls may not be enough. 🤔

**Comment by pocmo** [comment]
Patch landed in AC and also in Fenix.
