### ISSUE TITLE
Crash in [@ android.app.RemoteServiceException: at android.app.ActivityThread$H.handleMessage(ActivityThread.java)]

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/android-components#7764]
This bug is for crash report bp-83f69f06-43ad-4fea-b7f6-372bf0200707.

Java stack trace:
```
android.app.RemoteServiceException
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1894)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7156)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```

Similar to  #7468

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6718)

**Comment by kbrosnan** [comment]
Tracking also at bz-1651221

**Comment by ebalazs-sv** [comment]
This issue is reproducible on RC 80.1.2 from 9/1 with Motorola Moto G6 (Android 8).
android.app.RemoteServiceException: Bad notification for startForeground: java.util.ConcurrentModificationException
Crash report: https://crash-stats.mozilla.org/report/index/3bc60816-2dea-4f3a-8235-da7630200901

**Comment by kbrosnan** [comment]
@ebalazs-sv what steps were you doing when this crash was encountered?

**Comment by ebalazs-sv** [comment]
I do not have the steps to reproduce this issue. The app crashed while testing it and I did reproduce it only once when tapping on the download notification.

**Comment by csadilek** [comment]
Duping to https://github.com/mozilla-mobile/android-components/issues/9983.
