### ISSUE TITLE
LoginMigrationException: The logins tables are not empty

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#7877]
https://sentry.prod.mozaws.net/share/issue/999fc594a0d84e709d8d52ca15bcf1f4/

```
mozilla.components.support.migration.LoginMigrationException: Rust import unexpectedly threw: mozilla.appservices.logins.LoginsStorageException: The logins tables are not empty
    at mozilla.components.support.migration.FennecLoginsMigration.migrate$support_migration_release(FennecLoginsMigration.kt:22)
    at mozilla.components.support.migration.FennecLoginsMigration$migrate$1.invokeSuspend
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:20)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
    at java.lang.Thread.run(Thread.java:784)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6828)

**Comment by pocmo** [comment]
We saw this in Beta too. Happened only once in release yet. So not something we need to address yet. But let's keep an eye on it.
