### ISSUE TITLE
FNX3-22864 ⁃ GeckoWebExtension.getMetadata: it.version must not be null

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#7878]
https://sentry.prod.mozaws.net/share/issue/21da19915c3645588f02f3d18f772978/

```
java.lang.IllegalStateException: it.version must not be null
    at kotlin.jvm.internal.ArrayIteratorKt.checkExpressionValueIsNotNull(ArrayIterator.kt:1)
    at mozilla.components.browser.engine.gecko.webextension.GeckoWebExtension.getMetadata(GeckoWebExtension.kt:7)
    at androidx.core.app.AppOpsManagerCompat.isUnsupported(AppOpsManagerCompat.java:1)
    at mozilla.components.feature.addons.AddonManager.updateAddon(AddonManager.kt:2)
    at mozilla.components.feature.addons.update.AddonUpdaterWorker.doWork(AddonUpdater.kt:10)
    at androidx.work.CoroutineWorker$startWork$1.invokeSuspend(CoroutineWorker.kt:5)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
    at android.os.Handler.handleCallback(Handler.java:907)
    at android.os.Handler.dispatchMessage(Handler.java:105)
    at android.os.Looper.loop(Looper.java:216)
    at android.app.ActivityThread.main(ActivityThread.java:7625)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FNX3-22864)

**Comment by csadilek** [comment]
We recently worked around a similar case: `@NonNull` field `origin` in GV actually returning null for an extension. However, in the case of `version`, we shouldn't land a workaround. Filed in GV: https://bugzilla.mozilla.org/show_bug.cgi?id=1655755

This is reported as `info` as we fail to update the add-on.

**Comment by csadilek** [comment]
The most likely cause of this is an ID collision of an installed add-on and an add-on we register dynamically on startup. The only one we have that could cause this is webcompat. Let's revert the following commit on the 48 branch only and see if the problem goes away: https://github.com/mozilla-mobile/android-components/pull/7360/ (We haven't seen it during Nightly and earlier beta migrations before this fix).

This commit fixed the add-on ID of webcompat, now possibly colliding with the installed one in Fennec, which we'd disable anyway during migration, but fail to because of the collision when we query GV.

The revert is NOT needed on newer branches, because we switched to `installBuiltIn` which should not have the problem according to the add-ons team.

**Comment by csadilek** [comment]
Alright, this doesn't happen anymore in 79.0.2. So the workaround above fixed this. Closing.
