### ISSUE TITLE
AddonsManagerAdapter: Key zh-CN is missing in the map.

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#7879]
https://sentry.prod.mozaws.net/share/issue/835b3160fa0a4208a222fd163612c392/

```
java.util.NoSuchElementException: Key zh-CN is missing in the map.
    at kotlin.collections.GroupingKt.getValue
    at mozilla.components.feature.addons.ui.AddonsManagerAdapterKt.translate(AddonsManagerAdapter.kt:2)
    at org.mozilla.fenix.addons.AddonDetailsView.bind(AddonDetailsView.kt:2)
    at org.mozilla.fenix.addons.AddonDetailsFragment.onViewCreated(AddonDetailsFragment.kt:5)
    at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:21)
    at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:25)
    at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:5)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:53)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:11)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:4)
    at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:1)
    at android.os.Handler.handleCallback(Handler.java:900)
    at android.os.Handler.dispatchMessage(Handler.java:103)
    at android.os.Looper.loop(Looper.java:219)
    at android.app.ActivityThread.main(ActivityThread.java:8347)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
```

**Comment by lindongbin** [comment]
https://crash-stats.mozilla.org/report/index/b45a638b-32f1-45b6-ba23-dd7e10200730

79.0.0 (Build #2015753875)
AC: 48.0.8, f8d50ada8
GV: 79.0-20200720193547
AS: 61.0.10

**Comment by Amejia481** [comment]
Similar to https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/9384625/activity/?query=is%3Aunresolved

**Comment by kbrosnan** [comment]
https://crash-stats.mozilla.org/signature/?product=Fenix&signature=java.util.NoSuchElementException%3A%20at%20kotlin.collections.GroupingKt.getValue%28Unknown%20Source%3A5%29
