### ISSUE TITLE
IllegalArgumentException: Bitmap is not valid

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#7880]
```
java.lang.IllegalArgumentException: Bitmap is not valid
    at androidx.palette.graphics.Palette$Builder.<init>(Palette.java:17)
    at androidx.palette.graphics.Palette.from(Palette.java:1)
    at mozilla.components.browser.icons.processor.ColorProcessor.process(ColorProcessor.kt:3)
    at mozilla.components.browser.icons.BrowserIcons.access$loadIconInternal(BrowserIcons.kt:29)
    at mozilla.components.browser.icons.BrowserIcons$loadIcon$1.invokeSuspend(BrowserIcons.kt:3)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:764)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6835)

**Comment by pocmo** [comment]
https://sentry.prod.mozaws.net/share/issue/593096a935d4487388e60a5704afba5d/

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793156

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
