### ISSUE TITLE
Unsupported URI scheme

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#7888]
```
java.lang.IllegalArgumentException: Unsupported URI scheme
    at org.mozilla.geckoview.GeckoWebExecutor.fetch(GeckoWebExecutor.java:12)
    at mozilla.components.browser.engine.gecko.fetch.GeckoViewFetchClient.fetch(GeckoViewFetchClient.kt:45)
    at mozilla.components.browser.icons.loader.HttpIconLoader.load(HttpIconLoader.kt:13)
    at mozilla.components.browser.icons.BrowserIcons.access$loadIconInternal(BrowserIcons.kt:13)
    at mozilla.components.browser.icons.BrowserIcons$loadIcon$1.invokeSuspend(BrowserIcons.kt:3)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)
```

Looks like we should check the icon URLs first.

**Comment by pocmo** [comment]
https://sentry.prod.mozaws.net/share/issue/142e1c8f44f342b8a2512b72676807cb/

**Comment by Amejia481** [comment]
I think we already have a check, maybe the condition is not getting met https://github.com/mozilla-mobile/android-components/blob/facd6048b28236a825ec42b4a851991e8393e73f/components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/fetch/GeckoViewFetchClient.kt#L43

**Comment by pocmo** [comment]
I guess there can be literally `anything://hello.world` in the markup and we'd pass that to GeckoView.

**Comment by Amejia481** [comment]
👍

**Comment by Amejia481** [comment]
@pocmo I'm bit confused as we are validating that the scheme should `http` or `https` on [shouldDownload](https://github.com/mozilla-mobile/android-components/blob/9c5ceec059ff102a8028d21ce2c2c203ead4fc8f/components/browser/icons/src/main/java/mozilla/components/browser/icons/loader/HttpIconLoader.kt#L36)

[Source](https://github.com/mozilla-mobile/android-components/blob/9c5ceec059ff102a8028d21ce2c2c203ead4fc8f/components/browser/icons/src/main/java/mozilla/components/browser/icons/loader/HttpIconLoader.kt#L70)

```kotlin
    private fun shouldDownload(resource: IconRequest.Resource): Boolean {
        return resource.url.toUri().isHttpOrHttps && !failureCache.hasFailedRecently(resource.url)
    }
```
