### ISSUE TITLE
crash at mozilla.appservices.fxaclient.rust.RustError.intoException(RustError.kt:5) 

### ISSUE THREAD

**Issue by keianhzo** [mozilla-mobile/android-components#7889]
I originally posted this in [AS](https://github.com/MozillaReality/FirefoxReality/issues/new?assignees=&labels=&template=bug_report.md&title=) but it seems that this should be caught by AC. This is our top crasher in FxR v11 with AC v44:
```
mozilla.appservices.fxaclient.FxaException$Network
	at mozilla.appservices.fxaclient.rust.RustError.intoException(RustError.kt:5)
	at mozilla.appservices.fxaclient.FirefoxAccount.getTokenServerEndpointURL(FirefoxAccount.kt:9)
	at mozilla.components.service.fxa.manager.FxaAccountManager.maybeUpdateSyncAuthInfoCache(FxaAccountManager.kt:17)
	at mozilla.components.service.fxa.manager.FxaAccountManager$maybeUpdateSyncAuthInfoCache$1.invokeSuspend(FxaAccountManager.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
```

Not sure if it might by fixed in more recent versions as we don't really know how to reproduce it.

**Comment by grigoryk** [comment]
Thanks, I'll address this as part of #7856.

**Comment by grigoryk** [comment]
Similar in nature to https://github.com/mozilla-mobile/android-components/issues/7536 (we're not handling network failures properly).

**Comment by keianhzo** [comment]
Thanks @grigoryk!

**Comment by grigoryk** [comment]
The larger PR which fixes this will probably land by then, although I'm not 100% certain. It will also be a pretty substantial change, not sure you'd want to take it mostly untested in the wild.

I'll consider pushing out a smaller fix just for this that will be safe to include by Aug 10th.
