### ISSUE TITLE
IllegalMonitorStateException: unlock of unowned monitor on object of type '(raw)' on thread 

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#7916]
Sentry: https://sentry.prod.mozaws.net/operations/firefox/issues/9261958/

```
java.lang.IllegalMonitorStateException: unlock of unowned monitor on object of type '(raw)' on thread 'Thread[27,tid=4511,Runnable,Thread*=0xb8df38f0,peer=0x1da04740,"pool-11-thread-1"]'
    at mozilla.appservices.push.PushManager.<init>(PushManager.kt:10)
    at mozilla.components.feature.push.RustPushConnection.updateToken(Connection.kt:15)
    at mozilla.components.feature.push.AutoPushFeature$$special$$inlined$let$lambda$1.invokeSuspend(AutoPushFeature.kt:6)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:818)

mozilla.components.concept.push.PushError$Rust: unlock of unowned monitor on object of type '(raw)' on thread 'Thread[27,tid=4511,Runnable,Thread*=0xb8df38f0,peer=0x1da04740,"pool-11-thread-1"]'
    at mozilla.components.feature.push.AutoPushFeature$$special$$inlined$exceptionHandler$1.handleException(CoroutineExceptionHandler.kt:5)
    at androidx.core.app.AppOpsManagerCompat.handleCoroutineException(AppOpsManagerCompat.java:2)
    at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Builders.common.kt:1)
    at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:13)
    at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:16)
    at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:11)
    at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:2)
    at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:1)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:11)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:818)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6869)

**Comment by jonalmeida** [comment]
What is common amongst all the devices that crashed are that they are Android 5.0 x86 architectures.

**Comment by jonalmeida** [comment]
I've filed https://github.com/mozilla/application-services/issues/3446 because I'm not sure what to do here.

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796618

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
