### ISSUE TITLE
java.io.FileNotFoundException: /storage/emulated/0/Download/NewPipe_v0.19.8.apk (No such file or directory)

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#7921]
Related issue https://github.com/mozilla-mobile/fenix/issues/12297#issuecomment-666030428

```
07-29 20:39:17.333  8021  8079 D AbstractFetchDownloadService: Fetching download
07-29 20:39:17.350  8021  8079 E AbstractFetchDownloadService: Unable to complete download marked as FAILED
07-29 20:39:17.350  8021  8079 E AbstractFetchDownloadService: java.io.FileNotFoundException: /storage/emulated/0/Download/NewPipe_v0.19.8.apk (No such file or directory)
07-29 20:39:17.350  8021  8079 E AbstractFetchDownloadService: 	at java.io.FileOutputStream.open0(Native Method)
07-29 20:39:17.350  8021  8079 E AbstractFetchDownloadService: 	at java.io.FileOutputStream.open(FileOutputStream.java:308)
07-29 20:39:17.350  8021  8079 E AbstractFetchDownloadService: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:238)
07-29 20:39:17.350  8021  8079 E AbstractFetchDownloadService: 	at mozilla.components.feature.downloads.AbstractFetchDownloadService.useFileStream$feature_downloads_release(AbstractFetchDownloadService.kt:28)
07-29 20:39:17.350  8021  8079 E AbstractFetchDownloadService: 	at mozilla.components.feature.downloads.AbstractFetchDownloadService$performDownload$1.invoke(AbstractFetchDownloadService.kt:15)
07-29 20:39:17.350  8021  8079 E AbstractFetchDownloadService: 	at mozilla.components.concept.fetch.Response$Body.useStream(Response.kt:1)
07-29 20:39:17.350  8021  8079 E AbstractFetchDownloadService: 	at mozilla.components.feature.downloads.AbstractFetchDownloadService.performDownload$feature_downloads_release(AbstractFetchDownloadService.kt:12)
07-29 20:39:17.350  8021  8079 E AbstractFetchDownloadService: 	at mozilla.components.feature.downloads.AbstractFetchDownloadService.startDownloadJob$feature_downloads_release(AbstractFetchDownloadService.kt:2)
07-29 20:39:17.350  8021  8079 E AbstractFetchDownloadService: 	at mozilla.components.feature.downloads.AbstractFetchDownloadService$onStartCommand$1.invokeSuspend(AbstractFetchDownloadService.kt:3)
07-29 20:39:17.350  8021  8079 E AbstractFetchDownloadService: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
07-29 20:39:17.350  8021  8079 E AbstractFetchDownloadService: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
07-29 20:39:17.350  8021  8079 E AbstractFetchDownloadService: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
07-29 20:39:17.350  8021  8079 E AbstractFetchDownloadService: 	at 
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6871)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1792940

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
