### ISSUE TITLE
GleanCrashReporterService: Handling IOException

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#7989]
We got the following crash on Sentry:

```
android.system.ErrnoException: write failed: ENOSPC (No space left on device)
    at libcore.io.Posix.writeBytes(Posix.java)
    at libcore.io.Posix.write(Posix.java:258)
    at libcore.io.BlockGuardOs.write(BlockGuardOs.java:313)
    at libcore.io.IoBridge.write(IoBridge.java:537)
    at java.io.FileOutputStream.write(FileOutputStream.java:186)
    at java.io.OutputStream.write(OutputStream.java:82)
    at mozilla.components.lib.crash.service.GleanCrashReporterService.recordCrash$lib_crash_release(GleanCrashReporterService.kt:9)
```

While there's not much we can do when the device is out of memory, we should not crash with an `IOException` when reading/writing files in `GleanCrashReporterService`. Taking a quick peek it seems like we do not catch any yet.

**Comment by pocmo** [comment]
https://sentry.prod.mozaws.net/share/issue/50e13942ef8f4f64b673b75749965265/

**Comment by pocmo** [comment]
CC @travis79
