### ISSUE TITLE
PlacesException: Error executing SQL: database or disk is full

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#8003]
Not much we can do if the disk is full. But I guess we should try to handle this more gracefully and at least not crash. Unsure whether we can handle this on our side or whether we need a more fine-grained exception since it looks like we only see `PlacesException` on our side?

```
mozilla.appservices.places.PlacesException: Error executing SQL: database or disk is full
    at mozilla.appservices.places.RustError.intoException(RustError.kt:4)
    at mozilla.appservices.places.PlacesWriterConnection.noteObservation(PlacesConnection.kt:12)
    at mozilla.components.browser.storage.sync.PlacesHistoryStorage$recordObservation$2.invokeSuspend(PlacesHistoryStorage.kt:10)
    at mozilla.components.browser.storage.sync.PlacesHistoryStorage$recordObservation$2.invoke(PlacesHistoryStorage.kt)
    at androidx.core.app.AppOpsManagerCompat.startUndispatchedOrReturn(AppOpsManagerCompat.java:2)
    at kotlinx.coroutines.AwaitKt.withContext(Await.kt:9)
    at mozilla.components.browser.storage.sync.PlacesHistoryStorage.recordObservation(PlacesHistoryStorage.kt:1)
    at mozilla.components.feature.session.HistoryDelegate.onTitleChanged(HistoryDelegate.kt:6)
    at mozilla.components.browser.engine.gecko.GeckoEngineSession$createContentDelegate$1$onTitleChange$$inlined$let$lambda$1.invokeSuspend(GeckoEngineSession.kt:5)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
```

https://sentry.prod.mozaws.net/share/issue/ef5ee9b96a7849efa2d4bfac83164e66/

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6939)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796415

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
