### ISSUE TITLE
PlacesConnectionBusy: Error executing SQL: database is locked

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#8011]
Seeing this during `onTitleChange` history delegate calls: https://sentry.prod.mozaws.net/operations/fenix-fennec/issues/9256648/?query=release%3Aorg.mozilla.firefox-79.0.2%20lastSeen%3A-3d%20level%3Afatal

```
mozilla.appservices.places.PlacesConnectionBusy: Error executing SQL: database is locked
    at mozilla.appservices.places.RustError.intoException(RustError.kt:12)
    at mozilla.appservices.places.PlacesWriterConnection.noteObservation(PlacesConnection.kt:12)
    at mozilla.components.browser.storage.sync.PlacesHistoryStorage$recordObservation$2.invokeSuspend(PlacesHistoryStorage.kt:10)
    at mozilla.components.browser.storage.sync.PlacesHistoryStorage$recordObservation$2.invoke
    at androidx.core.app.AppOpsManagerCompat.startUndispatchedOrReturn(AppOpsManagerCompat.java:2)
    at kotlinx.coroutines.AwaitKt.withContext(Await.kt:9)
    at mozilla.components.browser.storage.sync.PlacesHistoryStorage.recordObservation(PlacesHistoryStorage.kt:1)
    at mozilla.components.feature.session.HistoryDelegate.onTitleChanged(HistoryDelegate.kt:6)
    at mozilla.components.browser.engine.gecko.GeckoEngineSession$createContentDelegate$1$onTitleChange$$inlined$let$lambda$1.invokeSuspend(GeckoEngineSession.kt:5)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
```

Not sure about the `a-s` label yet, hopefully it's not needed. Perhaps there's a sync running in the background? Either way, we shouldn't crash in these situations, even if that means dropping a title change.

**Comment by grigoryk** [comment]
Similarly for https://sentry.prod.mozaws.net/operations/fenix-fennec/issues/9261993/?query=release%3Aorg.mozilla.firefox-79.0.2%20lastSeen%3A-3d%20level%3Afatal - "disk is full" encountered during onTitleChange results in a crash currently. Lots of things will fail to work in this scenario, but let's not crash at least.

**Comment by grigoryk** [comment]
I think ignoring certain types of failures encountered during `onTitleChange` would be appropriate here. We can log them as `infos` to keep track of volume.

**Comment by grigoryk** [comment]
Another cause: `Error executing SQL: UNIQUE constraint failed: moz_places.guid`
