### ISSUE TITLE
[Bug] Intermittent loadSearchEngineList successfully loads after saving

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/android-components#8124]
Log: https://treeherder.mozilla.org/logviewer.html#?job_id=313039544&repo=android-components

```
[task 2020-08-14T17:20:01.539Z]   TEST: loadSearchEngineList successfully loads after saving
[task 2020-08-14T17:20:01.539Z]     [Robolectric] mozilla.components.feature.search.storage.SearchEngineStorageTest.loadSearchEngineList successfully loads after saving: sdk=28; resources=binary
[task 2020-08-14T17:20:01.539Z]     I/MonitoringInstr: Instrumentation started!
[task 2020-08-14T17:20:01.539Z]     I/MonitoringInstr: Setting context classloader to 'org.robolectric.internal.bytecode.SandboxClassLoader@419ae2fa', Original: 'org.robolectric.internal.bytecode.SandboxClassLoader@419ae2fa'
[task 2020-08-14T17:20:01.539Z]   FAILURE
[task 2020-08-14T17:20:01.539Z] 
[task 2020-08-14T17:20:01.541Z] org.junit.ComparisonFailure: expected:<id[1]> but was:<id[2]>
[task 2020-08-14T17:20:01.541Z] 	at org.junit.Assert.assertEquals(Assert.java:115)
[task 2020-08-14T17:20:01.541Z] 	at org.junit.Assert.assertEquals(Assert.java:144)
[task 2020-08-14T17:20:01.541Z] 	at mozilla.components.feature.search.storage.SearchEngineStorageTest$loadSearchEngineList successfully loads after saving$1.invokeSuspend(SearchEngineStorageTest.kt:77)
[task 2020-08-14T17:20:01.541Z] 	at mozilla.components.feature.search.storage.SearchEngineStorageTest$loadSearchEngineList successfully loads after saving$1.invoke(SearchEngineStorageTest.kt)
[task 2020-08-14T17:20:01.541Z] 	at kotlinx.coroutines.test.TestBuildersKt$runBlockingTest$deferred$1.invokeSuspend(TestBuilders.kt:50)
[task 2020-08-14T17:20:01.541Z] 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[task 2020-08-14T17:20:01.541Z] 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
[task 2020-08-14T17:20:01.541Z] 	at kotlinx.coroutines.test.TestCoroutineDispatcher.dispatch(TestCoroutineDispatcher.kt:50)
[task 2020-08-14T17:20:01.541Z] 	at kotlinx.coroutines.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:288)
[task 2020-08-14T17:20:01.541Z] 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
[task 2020-08-14T17:20:01.541Z] 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
[task 2020-08-14T17:20:01.541Z] 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158)
[task 2020-08-14T17:20:01.541Z] 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.async(Builders.common.kt:89)
[task 2020-08-14T17:20:01.541Z] 	at kotlinx.coroutines.BuildersKt.async(Unknown Source)
[task 2020-08-14T17:20:01.541Z] 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.async$default(Builders.common.kt:82)
[task 2020-08-14T17:20:01.541Z] 	at kotlinx.coroutines.BuildersKt.async$default(Unknown Source)
[task 2020-08-14T17:20:01.541Z] 	at kotlinx.coroutines.test.TestBuildersKt.runBlockingTest(TestBuilders.kt:49)
[task 2020-08-14T17:20:01.541Z] 	at kotlinx.coroutines.test.TestBuildersKt.runBlockingTest$default(TestBuilders.kt:45)
[task 2020-08-14T17:20:01.541Z] 	at mozilla.components.feature.search.storage.SearchEngineStorageTest.loadSearchEngineList successfully loads after saving(SearchEngineStorageTest.kt:55)
[task 2020-08-14T17:20:01.541Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2020-08-14T17:20:01.541Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2020-08-14T17:20:01.541Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2020-08-14T17:20:01.541Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2020-08-14T17:20:01.541Z] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[task 2020-08-14T17:20:01.541Z] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[task 2020-08-14T17:20:01.541Z] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[task 2020-08-14T17:20:01.541Z] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[task 2020-08-14T17:20:01.541Z] 	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:601)
[task 2020-08-14T17:20:01.541Z] 	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:260)
[task 2020-08-14T17:20:01.541Z] 	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
[task 2020-08-14T17:20:01.541Z] 	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
[task 2020-08-14T17:20:01.541Z] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[task 2020-08-14T17:20:01.541Z] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[task 2020-08-14T17:20:01.541Z] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[task 2020-08-14T17:20:01.541Z] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[task 2020-08-14T17:20:01.541Z] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[task 2020-08-14T17:20:01.541Z] 	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
[task 2020-08-14T17:20:01.541Z] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[task 2020-08-14T17:20:01.541Z] 	at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:104)
[task 2020-08-14T17:20:01.541Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
[task 2020-08-14T17:20:01.541Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
[task 2020-08-14T17:20:01.541Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
[task 2020-08-14T17:20:01.541Z] 	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
[task 2020-08-14T17:20:01.541Z] 	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
[task 2020-08-14T17:20:01.541Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2020-08-14T17:20:01.541Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2020-08-14T17:20:01.541Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2020-08-14T17:20:01.541Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2020-08-14T17:20:01.541Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
[task 2020-08-14T17:20:01.541Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[task 2020-08-14T17:20:01.541Z] 	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
[task 2020-08-14T17:20:01.541Z] 	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
[task 2020-08-14T17:20:01.541Z] 	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
[task 2020-08-14T17:20:01.541Z] 	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
[task 2020-08-14T17:20:01.541Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2020-08-14T17:20:01.541Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2020-08-14T17:20:01.541Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2020-08-14T17:20:01.541Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2020-08-14T17:20:01.541Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
[task 2020-08-14T17:20:01.541Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[task 2020-08-14T17:20:01.541Z] 	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
[task 2020-08-14T17:20:01.541Z] 	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
[task 2020-08-14T17:20:01.541Z] 	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
[task 2020-08-14T17:20:01.541Z] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
[task 2020-08-14T17:20:01.541Z] 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
[task 2020-08-14T17:20:01.541Z] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[task 2020-08-14T17:20:01.541Z] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[task 2020-08-14T17:20:01.541Z] 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
[task 2020-08-14T17:20:01.541Z] 	at java.lang.Thread.run(Thread.java:748)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7029)

**Comment by jonalmeida** [comment]
I've seen a few failures from this test as well from GeckoView upgrade PRs.

**Comment by jonalmeida** [comment]
Going to pick this up today because it leads to many unnecessary CI re-runs already.

**Comment by jonalmeida** [comment]
I ran the unit tests on Android Studio in loop a few thousand times without seeing failures. However, when I put up [a PR](https://github.com/mozilla-mobile/android-components/pull/8441), to re-enable the test, CI immediately failed.

I'm unsure what to do next to investigate why a unit test fails on CI alone.

Taking this out of the sprint for now.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796453

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
