### ISSUE TITLE
IllegalStateException: Fragment already added: SimpleRedirectDialogFragment (SHOULD_OPEN_APP_LINK_PROMPT_DIALOG)

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#8169]
This is similar to the crash we had for the download fragment, but app links and low volume:

```
java.lang.IllegalStateException: Fragment already added: SimpleRedirectDialogFragment{65faa78} (b29aa62f-8d58-4e3f-9f09-70ab965f46c7) SHOULD_OPEN_APP_LINK_PROMPT_DIALOG}
    at androidx.fragment.app.FragmentStore.addFragment(FragmentStore.java:7)
    at androidx.fragment.app.FragmentManager.addFragment(FragmentManager.java:4)
    at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:24)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:51)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:10)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:4)
    at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:1)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.TinnoLoop(Looper.java:150)
    at android.os.Looper.loop(Looper.java:208)
    at android.app.ActivityThread.main(ActivityThread.java:6175)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by csadilek** [comment]
Sentry: https://sentry.prod.mozaws.net/operations/fenix-fennec/issues/9367623/

/cc @rocketsroger

**Comment by rocketsroger** [comment]
> Sentry: https://sentry.prod.mozaws.net/operations/fenix-fennec/issues/9367623/
> 
> /cc @rocketsroger

Thanks, I'll take a look

**Comment by rocketsroger** [comment]
> is the issue resolved?

Yes, AFAIK this had been resolved.
