### ISSUE TITLE
ArithmeticException: divide by zero in Download notification

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#8190]
Sentry: https://sentry.prod.mozaws.net/operations/fenix-fennec/issues/9300646/?query=is%3Aunresolved%20divide

```
java.lang.ArithmeticException: divide by zero
    at androidx.core.app.AppOpsManagerCompat.getProgress(AppOpsManagerCompat.java:3)
    at mozilla.components.feature.downloads.DownloadNotification.createDownloadGroupNotification$feature_downloads_release(DownloadNotification.kt:18)
    at mozilla.components.feature.downloads.AbstractFetchDownloadService.updateNotificationGroup$feature_downloads_release(AbstractFetchDownloadService.kt:3)
    at mozilla.components.feature.downloads.AbstractFetchDownloadService.updateForegroundNotificationIfNeeded$feature_downloads_release(AbstractFetchDownloadService.kt:11)
    at mozilla.components.feature.downloads.AbstractFetchDownloadService.access$updateDownloadNotification(AbstractFetchDownloadService.kt:4)
    at mozilla.components.feature.downloads.AbstractFetchDownloadService$onStartCommand$2.invokeSuspend(AbstractFetchDownloadService.kt:7)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.AwaitKt.resume(Await.kt:11)
    at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:18)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:5)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:2)
    at kotlinx.coroutines.android.HandlerContext$scheduleResumeAfterDelay$$inlined$Runnable$1.run(Runnable.kt:1)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:226)
    at android.app.ActivityThread.main(ActivityThread.java:7212)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:956)
```

**Comment by Amejia481** [comment]
Closed by https://github.com/mozilla-mobile/android-components/pull/8191
