### ISSUE TITLE
Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#8258]
https://sentry.prod.mozaws.net/operations/firefox/issues/9378636/?query=is%3Aunresolved

```

java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
    at androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java:8)
    at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:2)
    at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:3)
    at androidx.fragment.app.DialogFragment.showNow(DialogFragment.java:5)
    at mozilla.components.feature.downloads.DownloadsFeature.showDialog$feature_downloads_release(DownloadsFeature.kt:5)
    at mozilla.components.feature.downloads.DownloadsFeature.access$processDownload(DownloadsFeature.kt:8)
    at mozilla.components.feature.downloads.DownloadsFeature$start$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:3)
    at mozilla.components.support.ktx.kotlinx.coroutines.flow.FlowKt$ifChanged$$inlined$filter$1$2.emit(Collect.kt:7)
    at mozilla.components.feature.downloads.DownloadsFeature$start$1$invokeSuspend$$inlined$mapNotNull$1$2.emit(Collect.kt:4)
    at kotlinx.coroutines.flow.FlowKt.emitAllImpl$FlowKt__ChannelsKt
    at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
    at android.os.Handler.handleCallback(Handler.java:790)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6558)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)
```

**Comment by Amejia481** [comment]
Fixed by https://github.com/Amejia481/android-components/commit/b345d02b5396d41fe37c5ff6fdb8adc281024a35
