### ISSUE TITLE
Attempt to invoke virtual method 'int android.widget.SimpleMonthView.getMonthHeight()' on a null object reference

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#8260]
https://sentry.prod.mozaws.net/operations/firefox/issues/9296840/?query=is%3Aunresolved

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.widget.SimpleMonthView.getMonthHeight()' on a null object reference
    at android.widget.DayPickerView.onLayout(DayPickerView.java:230)
    at android.view.View.layout(View.java:20948)
    at android.view.ViewGroup.layout(ViewGroup.java:6279)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
    at android.view.View.layout(View.java:20948)
    at android.view.ViewGroup.layout(ViewGroup.java:6279)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
    at android.widget.ScrollView.onLayout(ScrollView.java:1595)
    at android.view.View.layout(View.java:20948)
    at android.view.ViewGroup.layout(ViewGroup.java:6279)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1842)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1686)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1595)
    at android.view.View.layout(View.java:20948)
    at android.view.ViewGroup.layout(ViewGroup.java:6279)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
    at android.view.View.layout(View.java:20948)
    at android.view.ViewGroup.layout(ViewGroup.java:6279)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
    at android.view.View.layout(View.java:20948)
    at android.view.ViewGroup.layout(ViewGroup.java:6279)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
    at android.view.View.layout(View.java:20948)
    at android.view.ViewGroup.layout(ViewGroup.java:6279)
    at com.android.internal.widget.AlertDialogLayout.setChildFrame(AlertDialogLayout.java:365)
    at com.android.internal.widget.AlertDialogLayout.onLayout(AlertDialogLayout.java:358)
    at android.view.View.layout(View.java:20948)
    at android.view.ViewGroup.layout(ViewGroup.java:6279)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
    at android.view.View.layout(View.java:20948)
    at android.view.ViewGroup.layout(ViewGroup.java:6279)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
    at android.view.View.layout(View.java:20948)
    at android.view.ViewGroup.layout(ViewGroup.java:6279)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
    at com.android.internal.policy.DecorView.onLayout(DecorView.java:902)
    at android.view.View.layout(View.java:20948)
    at android.view.ViewGroup.layout(ViewGroup.java:6279)
    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3037)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2545)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1636)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7946)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
    at android.view.Choreographer.doCallbacks(Choreographer.java:893)
    at android.view.Choreographer.doFrame(Choreographer.java:812)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
    at android.os.Handler.handleCallback(Handler.java:907)
    at android.os.Handler.dispatchMessage(Handler.java:105)
    at android.os.Looper.loop(Looper.java:216)
    at android.app.ActivityThread.main(ActivityThread.java:7625)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7149)

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796638

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
