### ISSUE TITLE
History is recorded for invalid URLs causing sentry reports

### ISSUE THREAD

**Issue by mhammond** [mozilla-mobile/android-components#8277]
Visit, say, `http://1234.56.78.91` - the page will obviously not load, but there will be an attempt to record history for it.

The exception is caught by [`handlePlacesException()`](https://github.com/mozilla-mobile/android-components/blob/4d7378d41494280eba52657eaa70b46ac9f443aa/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesStorage.kt#L78) - which records the exception with the crash reporter, causing sentry reports such as [this one](https://sentry.prod.mozaws.net/operations/firefox/issues/9318285)

There doesn't appear to be any impact on Fenix other than the logcat noise and the sentry report.

logcat shows:

```
2020-08-28 10:40:37.063 9517-9550/org.mozilla.fenix.debug W/PlacesHistoryStorage: Ignoring url exception while running recordObservation
    mozilla.appservices.places.UrlParseFailed: Error parsing URL: invalid IPv4 address
        at mozilla.appservices.places.RustError.intoException(RustError.kt:44)
        at mozilla.appservices.places.PlacesWriterConnection.noteObservation(PlacesConnection.kt:1355)
        at mozilla.components.browser.storage.sync.PlacesHistoryStorage$recordObservation$2.invokeSuspend(PlacesHistoryStorage.kt:64)
        at mozilla.components.browser.storage.sync.PlacesHistoryStorage$recordObservation$2.invoke(Unknown Source:10)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:154)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
        at mozilla.components.browser.storage.sync.PlacesHistoryStorage.recordObservation$suspendImpl(PlacesHistoryStorage.kt:60)
        at mozilla.components.browser.storage.sync.PlacesHistoryStorage.recordObservation(Unknown Source:0)
        at mozilla.components.feature.session.HistoryDelegate.onTitleChanged(HistoryDelegate.kt:28)
        at mozilla.components.browser.engine.gecko.GeckoEngineSession$createContentDelegate$1$onTitleChange$$inlined$let$lambda$1.invokeSuspend(GeckoEngineSession.kt:705)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7167)

**Comment by pocmo** [comment]
Looks like we are trying to save from the `onTitleChanged()` callback here (maybe that's the error page?).

**Comment by grigoryk** [comment]
Not always from `onTitleChange`. Here's a general `noteObservation` call failing with the same error:
```
mozilla.components.support.rustlog.RustErrorException: places::ffi - URL parse error: invalid IPv4 address
    at mozilla.components.support.rustlog.CrashReporterOnLog.invoke(RustLog.kt:9)
    at mozilla.appservices.rustlog.RawLogCallbackImpl.invoke(RustLogAdapter.kt:3)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:11)
    at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:1)
    at com.sun.jna.Native.invokeVoid(Native.java)
    at com.sun.jna.Function.invoke(Function.java:98)
    at com.sun.jna.Function.invoke(Function.java:22)
    at com.sun.jna.Library$Handler.invoke(Library.java:31)
    at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
    at $Proxy6.places_note_observation
    at mozilla.appservices.places.PlacesWriterConnection.noteObservation(PlacesConnection.kt:8)
    at mozilla.components.browser.storage.sync.PlacesHistoryStorage$recordObservation$2.invokeSuspend(PlacesHistoryStorage.kt:9)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:919)
```
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/9580485/?query=is%3Aunresolved%20RustErrorException

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796414

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
