### ISSUE TITLE
UNIQUE constraint failed: downloads.id (code 1555 SQLITE_CONSTRAINT_PRIMARYKEY)

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#8301]
```
e2f60089-2746-4e47-8d20-41193d42b383
android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: downloads.id (code 1555 SQLITE_CONSTRAINT_PRIMARYKEY)
----
android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: downloads.id (code 1555 SQLITE_CONSTRAINT_PRIMARYKEY)
at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:879)
at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:88)
at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeInsert(FrameworkSQLiteStatement.java:1)
at androidx.room.EntityInsertionAdapter.insertAndReturnId(EntityInsertionAdapter.java:3)
at mozilla.components.feature.downloads.db.DownloadDao_Impl$5.call(DownloadDao_Impl.java:2)
at androidx.room.CoroutinesRoom$Companion$execute$2.invokeSuspend(CoroutinesRoom.kt:3)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
at androidx.room.TransactionExecutor$1.run(TransactionExecutor.java:1)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:919)
```

**Comment by Amejia481** [comment]
No new events are showing in sentry
