### ISSUE TITLE
java.io.IOException: Stream closed (BrowserIcons)

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#8372]
Sentry https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/9495778/?query=is%3Aunresolved

```
java.io.IOException: Stream closed
    at java.io.BufferedWriter.ensureOpen(BufferedWriter.java:116)
    at java.io.BufferedWriter.write(BufferedWriter.java:221)
    at java.io.Writer.write(Writer.java:157)
    at java.io.Writer.append(Writer.java:227)
    at com.jakewharton.disklrucache.DiskLruCache.get(DiskLruCache.java:11)
    at mozilla.components.browser.icons.utils.IconDiskCache.getResources(IconDiskCache.kt:3)
    at mozilla.components.browser.icons.preparer.DiskIconPreparer.prepare(DiskIconPreparer.kt:2)
    at mozilla.components.browser.icons.BrowserIconsKt.access$prepare(BrowserIcons.kt:2)
    at mozilla.components.browser.icons.BrowserIcons.access$loadIconInternal(BrowserIcons.kt:5)
    at mozilla.components.browser.icons.BrowserIcons$loadIcon$1.invokeSuspend(BrowserIcons.kt:3)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    at java.lang.Thread.run(Thread.java:761)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7231)

**Comment by kbrosnan** [comment]
Still happens https://sentry.io/organizations/mozilla/issues/?project=6375561&project=6295546&project=6295551&query=Stream+closed&statsPeriod=14d

very rare crash

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793155

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
