### ISSUE TITLE
java.lang.IllegalArgumentException: Bitmap is not valid (BrowserIcons)

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#8373]
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/8934863/?query=is%3Aunresolved
```

java.lang.IllegalArgumentException: Bitmap is not valid
    at androidx.palette.graphics.Palette$Builder.<init>(Palette.java:17)
    at androidx.palette.graphics.Palette.from(Palette.java:1)
    at mozilla.components.browser.icons.processor.ColorProcessor.process(ColorProcessor.kt:3)
    at mozilla.components.browser.icons.BrowserIcons.access$loadIconInternal(BrowserIcons.kt:29)
    at mozilla.components.browser.icons.BrowserIcons$loadIcon$1.invokeSuspend(BrowserIcons.kt:3)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
    at java.lang.Thread.run(Thread.java:764)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7233)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793154

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
