### ISSUE TITLE
UninitializedPropertyAccessException from BrowserToolbarBottomBehavior.tryToScrollVertically

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#8405]
> https://sentry.prod.mozaws.net/operations/firefox/issues/9283204

```
kotlin.UninitializedPropertyAccessException: lateinit property browserToolbar has not been initialized
    at kotlin.jvm.internal.ArrayIteratorKt.throwUninitializedPropertyAccessException(ArrayIterator.kt:2)
    at mozilla.components.browser.toolbar.behavior.BrowserToolbarBottomBehavior.tryToScrollVertically$browser_toolbar_release(BrowserToolbarBottomBehavior.kt:7)
    at mozilla.components.browser.toolbar.behavior.BrowserToolbarBottomBehavior$createGestureDetector$1.invoke(BrowserToolbarBottomBehavior.kt:3)
    at mozilla.components.browser.toolbar.behavior.BrowserGestureDetector$gestureDetector$2$1.invoke(BrowserGestureDetector.kt:6)
    at mozilla.components.browser.toolbar.behavior.BrowserGestureDetector$CustomScrollDetectorListener.onScroll(BrowserGestureDetector.kt:1)
    at android.view.GestureDetector.onTouchEvent(GestureDetector.java:624)
    at mozilla.components.browser.toolbar.behavior.BrowserGestureDetector.handleTouchEvent$browser_toolbar_release(BrowserGestureDetector.kt:7)
    at mozilla.components.browser.toolbar.behavior.BrowserToolbarBottomBehavior.onInterceptTouchEvent(BrowserToolbarBottomBehavior.kt:2)
    at mozilla.components.browser.toolbar.behavior.BrowserToolbarBottomBehavior.onInterceptTouchEvent(BrowserToolbarBottomBehavior.kt:1)
    at androidx.coordinatorlayout.widget.CoordinatorLayout.performIntercept(CoordinatorLayout.java:13)
    at androidx.coordinatorlayout.widget.CoordinatorLayout.onInterceptTouchEvent(CoordinatorLayout.java:3)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2522)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2981)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2668)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2981)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2668)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2981)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2668)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2981)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2668)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2981)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2668)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2981)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2668)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2981)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2668)
    at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:555)
    at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1894)
    at android.app.Activity.dispatchTouchEvent(Activity.java:3508)
    at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:1)
    at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:508)
    at android.view.View.dispatchPointerEvent(View.java:12082)
    at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5463)
    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5247)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4737)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4790)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4756)
    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4887)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4764)
    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4944)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4737)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4790)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4756)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4764)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4737)
    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7363)
    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7337)
    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7295)
    at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7514)
    at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:193)
    at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
    at android.os.MessageQueue.next(MessageQueue.java:379)
    at android.os.Looper.loop(Looper.java:144)
    at android.app.ActivityThread.main(ActivityThread.java:7555)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
```

**Comment by st3fan** [comment]
@Mugurell this is a pretty high frequency crash - would you mind exploring this one?

**Comment by Mugurell** [comment]
This seems to be the same as https://github.com/mozilla-mobile/android-components/issues/8305
@st3fan Do we know if it's still happening in latest Nightlies? My sentry-fu skills don't want to help here..

**Comment by liuche** [comment]
I don't see this as a large crasher in Nightly at all, here is the story of two versions of this crash in Nightly:

https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/9492919/?query=is%3Aunresolved%20uninitialized
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/8969900/?query=is%3Aunresolved%20uninitialized

**Comment by kbrosnan** [comment]
Not seeing much on Nightly about 150 crashes in the last 7 days. https://crash-stats.mozilla.org/search/?java_stack_trace=~kotlin.UninitializedPropertyAccessException&build_id=%3E%3D20200902095359&product=Fenix&version=0.0a1&_facets=signature&_sort=-date&_columns=date&_columns=signature&_columns=product&_columns=version&_columns=build_id&_columns=platform#facet-signature

**Comment by liuche** [comment]
OKay I think we should close this then, and I'll resolve the crashes in Sentry so they show up again if they're still broken.
