### ISSUE TITLE
PromptFeature onConsume cast failed with class PromptRequest$Alert

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#8463]
Stable
https://sentry.prod.mozaws.net/operations/firefox/issues/9620907/?query=is%3Aunresolved

Beta
https://sentry.prod.mozaws.net/operations/firefox-beta/issues/9532024/?query=is%3Aunresolved

```
java.lang.ClassCastException: mozilla.components.concept.storage.Login cannot be cast to java.lang.Boolean
    at mozilla.components.feature.prompts.PromptFeature$onConfirm$1.invoke(PromptFeature.kt:6)
    at androidx.core.app.AppOpsManagerCompat.consumePromptFrom(AppOpsManagerCompat.java:5)
    at mozilla.components.feature.prompts.PromptFeature.onConfirm(PromptFeature.kt:1)
    at mozilla.components.feature.prompts.dialog.SaveLoginDialogFragment.access$onPositiveClickAction(SaveLoginDialogFragment.kt:10)
    at mozilla.components.feature.prompts.dialog.SaveLoginDialogFragment$onViewCreated$1.onClick(SaveLoginDialogFragment.kt:1)
    at android.view.View.performClick(View.java:6652)
    at android.view.View.performClickInternal(View.java:6624)
    at android.view.View.access$3100(View.java:787)
    at android.view.View$PerformClick.run(View.java:26213)
    at android.os.Handler.handleCallback(Handler.java:891)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:207)
    at android.app.ActivityThread.main(ActivityThread.java:7470)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

java.lang.IllegalArgumentException: PromptFeature onConsume cast failed with class mozilla.components.concept.engine.prompt.PromptRequest$Alert
    at mozilla.components.feature.prompts.PromptFeature$onConfirm$1.invoke(PromptFeature.kt:38)
    at androidx.core.app.AppOpsManagerCompat.consumePromptFrom(AppOpsManagerCompat.java:5)
    at mozilla.components.feature.prompts.PromptFeature.onConfirm(PromptFeature.kt:1)
    at mozilla.components.feature.prompts.dialog.SaveLoginDialogFragment.access$onPositiveClickAction(SaveLoginDialogFragment.kt:10)
    at mozilla.components.feature.prompts.dialog.SaveLoginDialogFragment$onViewCreated$1.onClick(SaveLoginDialogFragment.kt:1)
    at android.view.View.performClick(View.java:6652)
    at android.view.View.performClickInternal(View.java:6624)
    at android.view.View.access$3100(View.java:787)
    at android.view.View$PerformClick.run(View.java:26213)
    at android.os.Handler.handleCallback(Handler.java:891)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:207)
    at android.app.ActivityThread.main(ActivityThread.java:7470)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
```

**Comment by Amejia481** [comment]
Low volume.

**Comment by Amejia481** [comment]
cc @ekager

**Comment by ekager** [comment]
Looks same as https://github.com/mozilla-mobile/android-components/issues/6591 and possibly #6576

**Comment by Amejia481** [comment]
👍  
Thanks we can close this :)
