### ISSUE TITLE
RuntimeExceptionandroid.app.ActivityThread in deliverResults fatalFailure delivering result

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#8477]
https://sentry.prod.mozaws.net/operations/firefox/issues/9455045/?query=is%3Aunresolved%20Failure%20delivering%20result%20ResultInfo

```
Failure delivering result ResultInfo{who=null, request=203721, result=-1, data=Intent { dat=content://com.estrongs.files/storage/emulated/0/CamScanner/PDF/CamScanner 09-13-2020 18.27.21(3).pdf }} to activity {org.mozilla.firefox/org.mozilla.fenix.HomeActivity}: java.lang.SecurityException: Permission Denial: opening provider com.estrongs.android.pop.app.FileContentProvider from ProcessRecord{4679539 20147:org.mozilla.firefox/u0a147} (pid=20147, uid=10147) that is not exported from UID 10123


java.lang.SecurityException: Permission Denial: opening provider com.estrongs.android.pop.app.FileContentProvider from ProcessRecord{4679539 20147:org.mozilla.firefox/u0a147} (pid=20147, uid=10147) that is not exported from UID 10123
    at android.os.Parcel.readException(Parcel.java:2013)
    at android.os.Parcel.readException(Parcel.java:1959)
    at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:4784)
    at android.app.ActivityThread.acquireProvider(ActivityThread.java:5866)
    at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2530)
    at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1780)
    at android.content.ContentResolver.query(ContentResolver.java:738)
    at android.content.ContentResolver.query(ContentResolver.java:704)
    at android.content.ContentResolver.query(ContentResolver.java:662)
    at mozilla.components.browser.engine.gecko.prompt.GeckoPromptDelegate.toFileUri(GeckoPromptDelegate.kt:6)
    at mozilla.components.browser.engine.gecko.prompt.GeckoPromptDelegate.access$toFileUri(GeckoPromptDelegate.kt:1)
    at mozilla.components.browser.engine.gecko.prompt.GeckoPromptDelegate$onFilePrompt$onSelectSingle$1.invoke(GeckoPromptDelegate.kt:3)
    at mozilla.components.feature.prompts.file.FilePicker.handleFilePickerIntentResult$feature_prompts_release(FilePicker.kt:16)
    at mozilla.components.feature.prompts.file.FilePicker$onActivityResult$1.invoke(FilePicker.kt:5)
    at androidx.core.app.AppOpsManagerCompat.consumePromptFrom(AppOpsManagerCompat.java:5)
    at mozilla.components.feature.prompts.file.FilePicker.onActivityResult(FilePicker.kt:2)
    at mozilla.components.feature.prompts.PromptFeature.onActivityResult(PromptFeature.kt:1)
    at org.mozilla.fenix.browser.BaseBrowserFragment$onActivityResult$1.invoke(BaseBrowserFragment.kt:3)
    at mozilla.components.support.base.feature.ViewBoundFeatureWrapper.withFeature(ViewBoundFeatureWrapper.kt:1)
    at org.mozilla.fenix.browser.BaseBrowserFragment.onActivityResult(BaseBrowserFragment.kt:1)
    at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:7)
    at android.app.Activity.dispatchActivityResult(Activity.java:7276)
    at android.app.ActivityThread.deliverResults(ActivityThread.java:4292)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:4340)
    at android.app.ActivityThread.-wrap19
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6543)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)

java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=203721, result=-1, data=Intent { dat=content://com.estrongs.files/storage/emulated/0/CamScanner/PDF/CamScanner 09-13-2020 18.27.21(3).pdf }} to activity {org.mozilla.firefox/org.mozilla.fenix.HomeActivity}: java.lang.SecurityException: Permission Denial: opening provider com.estrongs.android.pop.app.FileContentProvider from ProcessRecord{4679539 20147:org.mozilla.firefox/u0a147} (pid=20147, uid=10147) that is not exported from UID 10123
    at android.app.ActivityThread.deliverResults(ActivityThread.java:4296)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:4340)
    at android.app.ActivityThread.-wrap19
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6543)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7346)

**Comment by Amejia481** [comment]
Low volume.

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796640

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
