### ISSUE TITLE
IOExceptionlibcore.io.IoBridge in write fatalwrite failed: ENOSPC (No space left on device)

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#8479]
https://sentry.prod.mozaws.net/operations/firefox-beta/issues/8983622/?query=is%3Aunresolved

```
android.system.ErrnoException: write failed: ENOSPC (No space left on device)
    at libcore.io.Posix.writeBytes(Posix.java)
    at libcore.io.Posix.write(Posix.java:271)
    at libcore.io.BlockGuardOs.write(BlockGuardOs.java:313)
    at libcore.io.IoBridge.write(IoBridge.java:493)
    at java.io.FileOutputStream.write(FileOutputStream.java:186)
    at java.io.OutputStream.write(OutputStream.java:82)
    at mozilla.components.lib.crash.service.GleanCrashReporterService.recordCrash$lib_crash_release(GleanCrashReporterService.kt:9)
    at mozilla.components.lib.crash.service.GleanCrashReporterService.record(GleanCrashReporterService.kt:1)
    at mozilla.components.lib.crash.CrashReporter$submitCrashTelemetry$2.invokeSuspend(CrashReporter.kt:9)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)

java.io.IOException: write failed: ENOSPC (No space left on device)
    at libcore.io.IoBridge.write(IoBridge.java:498)
    at java.io.FileOutputStream.write(FileOutputStream.java:186)
    at java.io.OutputStream.write(OutputStream.java:82)
    at mozilla.components.lib.crash.service.GleanCrashReporterService.recordCrash$lib_crash_release(GleanCrashReporterService.kt:9)
    at mozilla.components.lib.crash.service.GleanCrashReporterService.record(GleanCrashReporterService.kt:1)
    at mozilla.components.lib.crash.CrashReporter$submitCrashTelemetry$2.invokeSuspend(CrashReporter.kt:9)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7349)

**Comment by csadilek** [comment]
Not seeing crashes with this signature anymore. Let's close and re-open in case this does still happen.
