### ISSUE TITLE
Crash in [@ mozilla.appservices.fxaclient.FxaException$Network: at mozilla.appservices.fxaclient.rust.RustError.intoException(RustError.kt:5)]

### ISSUE THREAD

**Issue by mstange** [mozilla-mobile/android-components#8492]
In the last day, [the rate of crashes with this signature](https://crash-stats.mozilla.org/signature/?product=Fenix&version=0.0a1&signature=mozilla.appservices.fxaclient.FxaException%24Network%3A%20at%20mozilla.appservices.fxaclient.rust.RustError.intoException%28RustError.kt%3A5%29&date=%3E%3D2020-03-24T18%3A42%3A00.000Z&date=%3C2020-09-24T18%3A42%3A00.000Z&_columns=date&_columns=product&_columns=version&_columns=build_id&_columns=platform&_columns=reason&_columns=address&_columns=install_time&_columns=startup_crash&_sort=-build_id&_sort=-date&page=1#graphs) has gone up considerably. Maybe a regression from #7856? @grigoryk 

It sounds similar to #7536 which was about not handling network failures, if I understand things correctly.

Crash report: https://crash-stats.mozilla.org/report/index/92c220aa-3be3-4c80-b071-af3e30200924

Java stack trace:
```
mozilla.appservices.fxaclient.FxaException$Network
	at mozilla.appservices.fxaclient.rust.RustError.intoException(RustError.kt:5)
	at mozilla.appservices.fxaclient.FirefoxAccount.getTokenServerEndpointURL(FirefoxAccount.kt:9)
	at mozilla.components.service.fxa.FirefoxAccount.getTokenServerEndpointURL(FirefoxAccount.kt:1)
	at mozilla.components.service.fxa.manager.FxaAccountManager.maybeUpdateSyncAuthInfoCache(FxaAccountManager.kt:13)
	at mozilla.components.service.fxa.manager.FxaAccountManager$maybeUpdateSyncAuthInfoCache$1.invokeSuspend(Unknown Source:11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
```

**Comment by grigoryk** [comment]
Given timing, most likely a regression from #7856. Here's a Sentry report with a bit more detail, showing the same spike: https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/8905012/?query=is%3Aunresolved

```
mozilla.appservices.fxaclient.Network: Network error: [no-sentry] Network error: Java error: "fetch error: org.mozilla.geckoview.WebRequestError: Request failed, error=0x25, category=0x5"
    at mozilla.appservices.fxaclient.rust.RustError.intoException(RustError.kt:5)
    at mozilla.appservices.fxaclient.FirefoxAccount.getTokenServerEndpointURL(FirefoxAccount.kt:9)
    at mozilla.components.service.fxa.FirefoxAccount.getTokenServerEndpointURL(FirefoxAccount.kt:1)
    at mozilla.components.service.fxa.manager.FxaAccountManager.maybeUpdateSyncAuthInfoCache(FxaAccountManager.kt:13)
    at mozilla.components.service.fxa.manager.FxaAccountManager$maybeUpdateSyncAuthInfoCache$1.invokeSuspend
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:919)
```

**Comment by grigoryk** [comment]
We're not handling network failures within `getTokenServerEndpointURL`, which could happen if `remote config` needs to be populated within the fxaclient (on startup?).

It's not obvious to me why this is spiking now, as far as I can tell prior to #7856 we were just as vulnerable to this, and I don't think behaviour of getTokenServerEndpointURL changed recently within appservices either.

Either way, patch incoming to handle these failures gracefully.

**Comment by mstange** [comment]
Looks like it worked! [The graph went back down.](https://crash-stats.mozilla.org/signature/?product=Fenix&version=0.0a1&signature=mozilla.appservices.fxaclient.FxaException%24Network%3A%20at%20mozilla.appservices.fxaclient.rust.RustError.intoException%28RustError.kt%3A5%29&date=%3E%3D2020-09-15T20%3A18%3A00.000Z&date=%3C2020-09-29T20%3A18%3A00.000Z#graphs)

**Comment by grigoryk** [comment]
Excellent!
