### ISSUE TITLE
IllegalArgumentException: Unknown URL content://downloads/my_downloads

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#8567]
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/8827103/?query=is%3Aunresolved

```
java.lang.IllegalArgumentException: Unknown URL content://downloads/my_downloads
    at android.content.ContentResolver.insert(ContentResolver.java:1280)
    at android.app.DownloadManager.addCompletedDownload(DownloadManager.java:1753)
    at android.app.DownloadManager.addCompletedDownload(DownloadManager.java:1718)
    at mozilla.components.feature.downloads.AbstractFetchDownloadService.addToDownloadSystemDatabaseCompat$feature_downloads_release(AbstractFetchDownloadService.kt:18)
    at mozilla.components.feature.downloads.AbstractFetchDownloadService.updateDownloadNotification$feature_downloads_release(AbstractFetchDownloadService.kt:5)
    at mozilla.components.feature.downloads.AbstractFetchDownloadService.access$updateDownloadNotification(AbstractFetchDownloadService.kt:5)
    at mozilla.components.feature.downloads.AbstractFetchDownloadService$onStartCommand$2.invokeSuspend(AbstractFetchDownloadService.kt:7)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.AwaitKt.resume(Await.kt:11)
    at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:18)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:5)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:2)
    at kotlinx.coroutines.android.HandlerContext$scheduleResumeAfterDelay$$inlined$Runnable$1.run(Runnable.kt:1)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:7325)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by Amejia481** [comment]
Low volume

**Comment by kbrosnan** [comment]
https://crash-stats.mozilla.org/signature/?product=Fenix&signature=java.lang.IllegalArgumentException%253A%20at%20android.content.ContentResolver.insert(ContentResolver.java)

<html><body>


Product | Version | Count | Percentage | Installations (approx)
-- | -- | -- | -- | --
Fenix | 97.1.0 | 277 | 24.4% | 24
Fenix | 96.3.0 | 154 | 13.5% | 32
Fenix | 96.3.1 | 101 | 8.9% | 37


</body>
</html>

Looks like a few very crashy users on a Xiaomi Redmi 6A.

**Comment by rvandermeulen** [comment]
Volume is high enough to take this to the #4 overall top crash for Fenix 97 at the moment.
