### ISSUE TITLE
Crash in [@ java.security.UnrecoverableKeyException: at android.security.keystore.AndroidKeyStoreProvider.getKeyCharacteristics(AndroidKeyStoreProvider.java)]

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/android-components#8581]
Crash report: https://crash-stats.mozilla.org/report/index/edc047a1-5245-4301-97b2-8b2b70201001

Java stack trace:
```
java.security.UnrecoverableKeyException
	at android.security.keystore.AndroidKeyStoreProvider.getKeyCharacteristics(AndroidKeyStoreProvider.java:234)
	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyFromKeystore(AndroidKeyStoreProvider.java:356)
	at android.security.keystore.AndroidKeyStoreSpi.engineGetKey(AndroidKeyStoreSpi.java:101)
	at java.security.KeyStore.getKey(KeyStore.java:1062)
	at mozilla.components.lib.dataprotect.KeyStoreWrapper.getKeyFor(Keystore.kt:4)
	at mozilla.components.lib.dataprotect.Keystore.getKey(Keystore.kt:1)
	at mozilla.components.lib.dataprotect.Keystore.available(Keystore.kt:1)
	at mozilla.components.lib.dataprotect.Keystore.&lt;init&gt;(Keystore.kt:4)
	at mozilla.components.lib.dataprotect.SecurePreferencesImpl23$keystore$2.invoke(SecureAbove22Preferences.kt:1)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:6)
	at mozilla.components.lib.dataprotect.SecurePreferencesImpl23.getKeystore(Unknown Source:2)
	at mozilla.components.lib.dataprotect.SecurePreferencesImpl23.getString(SecureAbove22Preferences.kt:1)
	at mozilla.components.lib.dataprotect.SecureAbove22Preferences.getString(SecureAbove22Preferences.kt:1)
	at mozilla.components.service.fxa.SecureAbove22AccountStorage.read(AccountStorage.kt:1)
	at mozilla.components.service.fxa.manager.FxaAccountManager.internalStateSideEffects(FxaAccountManager.kt:95)
	at mozilla.components.service.fxa.manager.FxaAccountManager.stateActions(FxaAccountManager.kt:33)
	at mozilla.components.service.fxa.manager.FxaAccountManager$processQueue$2.invokeSuspend(FxaAccountManager.kt:41)
	at mozilla.components.service.fxa.manager.FxaAccountManager$processQueue$2.invoke(Unknown Source:10)
	at androidx.core.app.AppOpsManagerCompat.startUndispatchedOrReturn(AppOpsManagerCompat.java:2)
	at kotlinx.coroutines.AwaitKt.withContext(Await.kt:9)
	at mozilla.components.service.fxa.manager.FxaAccountManager.processQueue(FxaAccountManager.kt:1)
	at mozilla.components.service.fxa.manager.FxaAccountManager$start$2.invokeSuspend(FxaAccountManager.kt:6)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7431)

**Comment by jonalmeida** [comment]
cc: @grigoryk @ekager 

This came up at AC triage and were looking for some context.

**Comment by ekager** [comment]
Historically, these APIs are fairly fragile and hardware dependent.

Looks like we can try updating to the newest security library to possibly fix some concurrency issues

https://stackoverflow.com/a/62764642

**Comment by willmeet** [comment]
do you lost your keystore of your android app ? 

Then the simple solution >
http://www.technologymanias.com/2020/10/missing-or-lost-keystore-of-your.html

**Comment by jonalmeida** [comment]
These crashes no longer appear in our crash reporter; closing.
