### ISSUE TITLE
java.lang.IllegalArgumentException Invalid file path:

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#8613]
```
java.lang.IllegalArgumentException: Invalid file path: /storage/emulated/0/Download/Re-opening-guidelines-for-Harris-Ranch-Hospitality-Division-Draft-9.11.2....pdf
    at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
    at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
    at android.content.ContentProviderProxy.insert(ContentProviderNative.java:481)
    at android.content.ContentResolver.insert(ContentResolver.java:1835)
    at android.app.DownloadManager.addCompletedDownload(DownloadManager.java:2170)
    at android.app.DownloadManager.addCompletedDownload(DownloadManager.java:2079)
    at mozilla.components.feature.downloads.AbstractFetchDownloadService.addCompletedDownload$feature_downloads_release(AbstractFetchDownloadService.kt:6)
    at mozilla.components.feature.downloads.AbstractFetchDownloadService.addToDownloadSystemDatabaseCompat$feature_downloads_release(AbstractFetchDownloadService.kt:12)
    at mozilla.components.feature.downloads.AbstractFetchDownloadService.updateDownloadNotification$feature_downloads_release(AbstractFetchDownloadService.kt:5)
    at mozilla.components.feature.downloads.AbstractFetchDownloadService.access$updateDownloadNotification(AbstractFetchDownloadService.kt:5)
    at mozilla.components.feature.downloads.AbstractFetchDownloadService$onStartCommand$2.invokeSuspend(AbstractFetchDownloadService.kt:7)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.AwaitKt.resume(Await.kt:11)
    at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:18)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:5)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:2)
    at kotlinx.coroutines.android.HandlerContext$scheduleResumeAfterDelay$$inlined$Runnable$1.run(Runnable.kt:1)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:237)
    at android.app.ActivityThread.main(ActivityThread.java:8154)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by Amejia481** [comment]
Low volumen

**Comment by Amejia481** [comment]
We haven't seen new entries on sentry
