### ISSUE TITLE
java.net.URISyntaxException: Expected scheme-specific part at index

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#863]
Looks like we're not catching a possible exception thrown by `URI`:

https://github.com/mozilla-mobile/android-components/blob/14fdb2d78a009bc0dc782cb28898a6f5d3128c23/components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineView.kt#L131

Some thoughts:
- We're trying to use `android.net.Uri` everywhere based on previous discussions: https://github.com/mozilla-mobile/android-components/issues/648 - maybe this should be Uri?
- ^ I wonder if we should have static analysis to ensure we're only using `Uri` and not using `URI` or `URL` or whatever else
- Reminder to add a regression test! :)

This is an issue in firefox-tv v3.0.

```
     Caused by: java.net.URISyntaxException: Expected scheme-specific part at index 4: fgh:
        at java.net.URI$Parser.fail(URI.java:2855)
        at java.net.URI$Parser.failExpecting(URI.java:2861)
        at java.net.URI$Parser.parse(URI.java:3064)
        at java.net.URI.<init>(URI.java:589)
        at mozilla.components.browser.engine.system.SystemEngineView$createWebViewClient$1$onPageFinished$$inlined$let$lambda$1.invoke(SystemEngineView.kt:130)
        at mozilla.components.browser.engine.system.SystemEngineView$createWebViewClient$1$onPageFinished$$inlined$let$lambda$1.invoke(SystemEngineView.kt:113)
        at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:106)
        at mozilla.components.concept.engine.EngineSession.notifyObservers(EngineSession.kt)
        at mozilla.components.browser.engine.system.SystemEngineSession.internalNotifyObservers$engine_system_release(SystemEngineSession.kt:278)
        at mozilla.components.browser.engine.system.SystemEngineView$createWebViewClient$1.onPageFinished(SystemEngineView.kt:127)
        at com.amazon.webview.awvclients.AmazonWebViewClient.onPageFinished(AmazonWebViewClient.java:95)
        at com.android.webview.chromium.WebViewContentsClientAdapter.onPageFinished(WebViewContentsClientAdapter.java:546)
        at com.android.webview.chromium.WebViewExtAmazonContentsClientAdapter.onPageFinished(WebViewExtAmazonContentsClientAdapter.java:18)
        at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:201)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
```

**Comment by mcomella** [comment]
Tracking in TV: https://github.com/mozilla-mobile/firefox-tv/issues/1195

**Comment by csadilek** [comment]
Just a note: To reproduce this, one would have to navigate trigger a security change as well e.g.

- Navigate to `https://mozilla.org`
- Navigate to `fgh:`

This will crash the app.
