### ISSUE TITLE
RustErrorException: logins::ffi - Not a database / invalid key error

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/android-components#8649]
https://sentry.prod.mozaws.net/operations/firefox-beta/issues/9738954/?referrer=github_plugin

```
RustErrorException: logins::ffi - Not a database / invalid key error
    at mozilla.components.support.rustlog.CrashReporterOnLog.invoke(RustLog.kt:11)
    at mozilla.appservices.rustlog.RawLogCallbackImpl.invoke(RustLogAdapter.kt:3)
    at java.lang.reflect.Method.invoke(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:11)
...
(23 additional frame(s) were not displayed)

[INFO] logins::ffi - Not a database / invalid key error
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7483)

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796645

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
