### ISSUE TITLE
PWA -> Private Custom tab -> PWA renetry Crash in [@ java.lang.IllegalStateException: at mozilla.components.browser.engine.gecko.GeckoEngineView.render(GeckoEngineView.kt:18)]

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/android-components#8660]
Crash report: https://crash-stats.mozilla.org/report/index/529d53d2-22b8-4b8d-b5a7-0a3240201009

Java stack trace:
```
java.lang.IllegalStateException
	at mozilla.components.browser.engine.gecko.GeckoEngineView.render(GeckoEngineView.kt:18)
	at mozilla.components.feature.session.engine.EngineViewPresenter.onTabToRender(EngineViewPresenter.kt:9)
	at mozilla.components.feature.session.engine.EngineViewPresenter.access$onTabToRender(EngineViewPresenter.kt:1)
	at mozilla.components.feature.session.engine.EngineViewPresenter$start$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:2)
	at mozilla.components.support.ktx.kotlinx.coroutines.flow.FlowKt$ifAnyChanged$$inlined$filter$1$2.emit(Collect.kt:15)
	at mozilla.components.feature.session.engine.EngineViewPresenter$start$1$invokeSuspend$$inlined$map$1$2.emit(Collect.kt:3)
	at kotlinx.coroutines.flow.FlowKt.emitAllImpl$FlowKt__ChannelsKt(Unknown Source:11)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by kbrosnan** [comment]
Str: 
* Have Fenix set to open external links in a private tab
* Install the Twitter PWA
* Click a link in a tweet
* This should open in a private tab
* Tap home
* Tap the Twitter PWA again

**Comment by csadilek** [comment]
Our fix doesn't seem to work in Nightly, which is strange. We tested and verified in a debug build. Back to the drawing board.
