### ISSUE TITLE
Intermittent test failure: Updates region on init

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/android-components#8669]
Log: https://treeherder.mozilla.org/logviewer.html#?job_id=318267531&repo=android-components

```
[task 2020-10-10T14:35:40.518Z] SUITE: mozilla.components.feature.search.region.RegionMiddlewareTest
[task 2020-10-10T14:35:40.518Z]   TEST: Updates region on init
[task 2020-10-10T14:35:40.518Z]   SUCCESS
[task 2020-10-10T14:35:40.518Z] 
[task 2020-10-10T14:35:40.518Z]   TEST: Dispatches cached home region and update later
[task 2020-10-10T14:35:40.618Z]   FAILURE
[task 2020-10-10T14:35:40.618Z] 
[task 2020-10-10T14:35:40.618Z] org.junit.ComparisonFailure: expected:<[DE]> but was:<[FR]>
[task 2020-10-10T14:35:40.618Z] 	at org.junit.Assert.assertEquals(Assert.java:115)
[task 2020-10-10T14:35:40.618Z] 	at org.junit.Assert.assertEquals(Assert.java:144)
[task 2020-10-10T14:35:40.618Z] 	at mozilla.components.feature.search.region.RegionMiddlewareTest.Dispatches cached home region and update later(RegionMiddlewareTest.kt:132)
[task 2020-10-10T14:35:40.619Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2020-10-10T14:35:40.619Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2020-10-10T14:35:40.619Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2020-10-10T14:35:40.619Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2020-10-10T14:35:40.619Z] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[task 2020-10-10T14:35:40.619Z] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[task 2020-10-10T14:35:40.619Z] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[task 2020-10-10T14:35:40.619Z] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[task 2020-10-10T14:35:40.619Z] 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
[task 2020-10-10T14:35:40.619Z] 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
[task 2020-10-10T14:35:40.620Z] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
[task 2020-10-10T14:35:40.620Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
[task 2020-10-10T14:35:40.620Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
[task 2020-10-10T14:35:40.620Z] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[task 2020-10-10T14:35:40.620Z] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[task 2020-10-10T14:35:40.620Z] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[task 2020-10-10T14:35:40.620Z] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[task 2020-10-10T14:35:40.620Z] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[task 2020-10-10T14:35:40.621Z] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[task 2020-10-10T14:35:40.621Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
[task 2020-10-10T14:35:40.621Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
[task 2020-10-10T14:35:40.621Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
[task 2020-10-10T14:35:40.622Z] 	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
[task 2020-10-10T14:35:40.622Z] 	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
[task 2020-10-10T14:35:40.622Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2020-10-10T14:35:40.622Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2020-10-10T14:35:40.622Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2020-10-10T14:35:40.622Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2020-10-10T14:35:40.622Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
[task 2020-10-10T14:35:40.622Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[task 2020-10-10T14:35:40.622Z] 	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
[task 2020-10-10T14:35:40.622Z] 	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
[task 2020-10-10T14:35:40.622Z] 	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
[task 2020-10-10T14:35:40.622Z] 	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
[task 2020-10-10T14:35:40.622Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2020-10-10T14:35:40.622Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2020-10-10T14:35:40.622Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2020-10-10T14:35:40.622Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2020-10-10T14:35:40.622Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
[task 2020-10-10T14:35:40.622Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[task 2020-10-10T14:35:40.622Z] 	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
[task 2020-10-10T14:35:40.622Z] 	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
[task 2020-10-10T14:35:40.622Z] 	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
[task 2020-10-10T14:35:40.622Z] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
[task 2020-10-10T14:35:40.622Z] 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
[task 2020-10-10T14:35:40.622Z] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[task 2020-10-10T14:35:40.622Z] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[task 2020-10-10T14:35:40.622Z] 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
[task 2020-10-10T14:35:40.622Z] 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jonalmeida** [comment]
cc: @pocmo

**Comment by pocmo** [comment]
Have run into this a couple of times myself. I'll move this into the current sprint and work on this today.
