### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.Map.size()' on a null object reference

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#8715]
```
java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.Map.size()' on a null object reference

     FATAL EXCEPTION: main
Process: org.mozilla.samples.browser, PID: 6199
java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.Map.size()' on a null object reference
	at org.mozilla.geckoview.GeckoSession$Loader.additionalHeaders(GeckoSession.java:1646)
	at org.mozilla.geckoview.GeckoSession.loadUri(GeckoSession.java:1870)
	at mozilla.components.browser.engine.gecko.GeckoEngineSession.loadUrl(GeckoEngineSession.kt:149)
	at mozilla.components.concept.engine.EngineSession.loadUrl$default(EngineSession.kt:546)
	at mozilla.components.browser.session.engine.middleware.LinkingMiddleware$performLoadOnMainThread$1.invokeSuspend(LinkingMiddleware.kt:82)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5221)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

Looks like the new API doesn't handle `null` values.

**Comment by pocmo** [comment]
https://console.firebase.google.com/project/moz-android-components-230120/testlab/histories/bh.9f526cd30412cc12/matrices/7562499020072772908/executions/bs.4353a10d54e156c8

**Comment by pocmo** [comment]
https://treeherder.mozilla.org/#/jobs?repo=android-components&group_state=expanded&resultStatus=testfailed%2Cbusted%2Cexception%2Cusercancel%2Crunnable&revision=5cd371eebc9e2dfef8cc45472dd52a72b5a36558

**Comment by pocmo** [comment]
Alternatively we may just switch to the new API: #8710
