### ISSUE TITLE
IndexOutOfBoundsException: setSpan (-1 ... 9) starts before 0

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/android-components#8754]
https://sentry.prod.mozaws.net/operations/firefox-beta/issues/9776127/?referrer=github_plugin

```
IndexOutOfBoundsException: setSpan (-1 ... 9) starts before 0
    at android.text.SpannableStringInternal.checkRange(SpannableStringInternal.java:496)
    at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:196)
    at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:183)
    at android.text.SpannableString.setSpan(SpannableString.java:60)
    at androidx.core.app.AppOpsManagerCompat.addUnderline(AppOpsManagerCompat.java:4)
...
(16 additional frame(s) were not displayed)

setSpan (-1 ... 9) starts before 0
```

**Comment by kbrosnan** [comment]
This is the top crash on 82.0 B5/B6/RC1 https://crash-stats.mozilla.org/signature/?product=Fenix&signature=java.lang.IndexOutOfBoundsException%3A%20at%20android.text.SpannableStringInternal.checkRange%28SpannableStringInternal.java%29

**Comment by kbrosnan** [comment]
This is almost certainly the `No account <u>Create one</u> to sync Firefox between devices

https://github.com/mozilla-mobile/fenix/commit/c1bf66618e17cd739f999221d9cd16ebf01955ec
