### ISSUE TITLE
Crash in [@ kotlin.UninitializedPropertyAccessException: at mozilla.components.browser.toolbar.behavior.BrowserToolbarBottomBehavior.tryToScrollVertically$browser_toolbar_release(BrowserToolbarBottomBehavior.kt:7)]

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/android-components#8884]
### This is a regression in 83

* https://crash-stats.mozilla.org/signature/?product=Fenix&signature=kotlin.UninitializedPropertyAccessException%3A%20at%20mozilla.components.browser.toolbar.behavior.BrowserToolbarBottomBehavior.tryToScrollVertically%24browser_toolbar_release(BrowserToolbarBottomBehavior.kt%3A7)
* https://sentry.prod.mozaws.net/operations/firefox-beta/issues/9871138/
* https://sentry.prod.mozaws.net/operations/firefox-beta/?query=is%3Aunresolved+BrowserToolbarBottomBehavior
* https://sentry.prod.mozaws.net/operations/firefox-nightly/?query=is%3Aunresolved+BrowserToolbarBottomBehavior

Java stack trace:
```
kotlin.UninitializedPropertyAccessException
	at mozilla.components.browser.toolbar.behavior.BrowserToolbarBottomBehavior.tryToScrollVertically$browser_toolbar_release(BrowserToolbarBottomBehavior.kt:7)
	at mozilla.components.browser.toolbar.behavior.BrowserToolbarBottomBehavior$createGestureDetector$1.invoke(BrowserToolbarBottomBehavior.kt:3)
	at mozilla.components.browser.toolbar.behavior.BrowserGestureDetector$gestureDetector$1.invoke(BrowserGestureDetector.kt:5)
	at mozilla.components.browser.toolbar.behavior.BrowserGestureDetector$CustomScrollDetectorListener.onScroll(BrowserGestureDetector.kt:1)
	at android.view.GestureDetector.onTouchEvent(GestureDetector.java:612)
	at mozilla.components.browser.toolbar.behavior.BrowserGestureDetector.handleTouchEvent$browser_toolbar_release(BrowserGestureDetector.kt:4)
	at mozilla.components.browser.toolbar.behavior.BrowserToolbarBottomBehavior.onInterceptTouchEvent(BrowserToolbarBottomBehavior.kt:3)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.performIntercept(CoordinatorLayout.java:20)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onInterceptTouchEvent(CoordinatorLayout.java:3)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2573)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3034)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3034)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3034)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3034)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3034)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3034)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3034)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3034)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3034)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:441)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1850)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3413)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:1)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:399)
	at android.view.View.dispatchPointerEvent(View.java:12832)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5667)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5193)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4673)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4726)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4692)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4832)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4700)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4889)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4673)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4726)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4692)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4700)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4673)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7697)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7666)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7599)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7800)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:187)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:178)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7771)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7823)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1004)
	at android.view.Choreographer.doCallbacks(Choreographer.java:816)
	at android.view.Choreographer.doFrame(Choreographer.java:745)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:990)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6898)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by kbrosnan** [comment]
Mostly Huawei devices

**Comment by pocmo** [comment]
CC @Mugurell

**Comment by Mugurell** [comment]
This should be resolved by https://github.com/mozilla-mobile/android-components/commit/e0d106e217e18a4ac4b96e29182162ce212b552b which I see is included in AC 65.
