### ISSUE TITLE
Intermittent test failure with LazyComponent in support-base 

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#8911]
This happened during a l10n translation update [PR](https://github.com/mozilla-mobile/android-components/pull/8908#event-3964909671).

Logs: https://firefox-ci-tc.services.mozilla.com/tasks/SQflMOC3SimRXBgzteiDqA/runs/0/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FSQflMOC3SimRXBgzteiDqA%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log

```
[task 2020-11-06T00:16:16.255Z]   TEST: WHEN multiple threads try to initialize the same lazy component THEN only one component is initialized
[task 2020-11-06T00:16:16.255Z]     D [LazyComponent] Initialized lazyComponent #1: java.lang.Integer
[task 2020-11-06T00:16:16.354Z]   FAILURE
[task 2020-11-06T00:16:16.354Z] 
[task 2020-11-06T00:16:16.354Z] java.lang.AssertionError: expected:<1> but was:<0>
[task 2020-11-06T00:16:16.354Z] 	at org.junit.Assert.fail(Assert.java:88)
[task 2020-11-06T00:16:16.355Z] 	at org.junit.Assert.failNotEquals(Assert.java:834)
[task 2020-11-06T00:16:16.355Z] 	at org.junit.Assert.assertEquals(Assert.java:118)
[task 2020-11-06T00:16:16.355Z] 	at org.junit.Assert.assertEquals(Assert.java:144)
[task 2020-11-06T00:16:16.355Z] 	at mozilla.components.support.base.utils.LazyComponentTest.WHEN multiple threads try to initialize the same lazy component THEN only one component is initialized(LazyComponentTest.kt:66)
[task 2020-11-06T00:16:16.355Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2020-11-06T00:16:16.355Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2020-11-06T00:16:16.355Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2020-11-06T00:16:16.355Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2020-11-06T00:16:16.355Z] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[task 2020-11-06T00:16:16.355Z] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[task 2020-11-06T00:16:16.355Z] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[task 2020-11-06T00:16:16.355Z] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[task 2020-11-06T00:16:16.355Z] 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
[task 2020-11-06T00:16:16.355Z] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
[task 2020-11-06T00:16:16.355Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
[task 2020-11-06T00:16:16.355Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
[task 2020-11-06T00:16:16.355Z] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[task 2020-11-06T00:16:16.355Z] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[task 2020-11-06T00:16:16.355Z] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[task 2020-11-06T00:16:16.355Z] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[task 2020-11-06T00:16:16.355Z] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[task 2020-11-06T00:16:16.355Z] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[task 2020-11-06T00:16:16.355Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
[task 2020-11-06T00:16:16.355Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
[task 2020-11-06T00:16:16.355Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
[task 2020-11-06T00:16:16.355Z] 	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
[task 2020-11-06T00:16:16.355Z] 	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
[task 2020-11-06T00:16:16.355Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2020-11-06T00:16:16.355Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2020-11-06T00:16:16.355Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2020-11-06T00:16:16.355Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2020-11-06T00:16:16.355Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
[task 2020-11-06T00:16:16.355Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[task 2020-11-06T00:16:16.355Z] 	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
[task 2020-11-06T00:16:16.355Z] 	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)

```

cc: @mcomella

**Comment by mcomella** [comment]
I forgot to await.

**Comment by mcomella** [comment]
I opened https://github.com/mozilla-mobile/android-components/pull/8922
