### ISSUE TITLE
Crash in [@ java.lang.NumberFormatException: at java.lang.Integer.parseInt(Integer.java)]

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/android-components#8926]
Crash report: https://crash-stats.mozilla.org/report/index/aa423ddf-4a5d-4818-90d3-157dc0201107

Java stack trace:
```
java.lang.NumberFormatException: For input string: "undefined"
	at java.lang.Integer.parseInt(Integer.java:615)
	at java.lang.Integer.valueOf(Integer.java:801)
	at org.mozilla.geckoview.MediaSession$Metadata.fromBundle(MediaSession.java:16)
	at org.mozilla.geckoview.MediaSession$Handler.handleMessage(MediaSession.java:9)
	at org.mozilla.geckoview.MediaSession$Handler.handleMessage(MediaSession.java:1)
	at org.mozilla.geckoview.GeckoSessionHandler.handleMessage(GeckoSessionHandler.java:2)
	at org.mozilla.gecko.EventDispatcher$2.run(EventDispatcher.java:1)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7682)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7694)

**Comment by kbrosnan** [comment]
Nightly on Android is crashing consistently whenever I try to play the live stream on cnn.com

**Comment by csadilek** [comment]
I can't find this signature anymore. Closing.
