### ISSUE TITLE
Glean sample app crashing on Firebase

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#8950]
The nimbus component landed today and since then the glean sample app started failing on Firebase with a crash:

```
org.mozilla.experiments.nimbus.ErrorException$ResponseError: Error in network response: {"code":404,"errno":111,"error":"Not Found","details":{"id":"nimbus-mobile-experiments","resource_name":"collection"}}

     FATAL EXCEPTION: pool-3-thread-1
Process: org.mozilla.samples.glean.debug, PID: 16932
org.mozilla.experiments.nimbus.ErrorException$ResponseError: Error in network response: {"code":404,"errno":111,"error":"Not Found","details":{"id":"nimbus-mobile-experiments","resource_name":"collection"}}
	at org.mozilla.experiments.nimbus.Error.intoException(nimbus.kt:625)
	at org.mozilla.experiments.nimbus.NimbusClient.getActiveExperiments(nimbus.kt:998)
	at mozilla.components.service.nimbus.Nimbus$init$1.invokeSuspend(Nimbus.kt:147)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
```

**Comment by travis79** [comment]
Yep, I know what the problem is.  Give me 5 minutes to get a PR up.  Sorry for the noise :)
