### ISSUE TITLE
Intermittent test failures in task test-ui-glean 

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#8955]
I've seen this happen on two PRs so far where the Firebase UI tests crash:

```
[task 2020-11-11T14:39:12.101Z] ┌─────────┬──────────────────────┬─────────────────────────┬─────────────────────┐
[task 2020-11-11T14:39:12.101Z] │ OUTCOME │      MATRIX ID       │     TEST AXIS VALUE     │    TEST DETAILS     │
[task 2020-11-11T14:39:12.102Z] ├─────────┼──────────────────────┼─────────────────────────┼─────────────────────┤
[task 2020-11-11T14:39:12.102Z] │ failure │ matrix-1t4yejsxjp73m │ blueline-28-en-portrait │ Application crashed │
[task 2020-11-11T14:39:12.102Z] │ failure │ matrix-1t4yejsxjp73m │ Nexus6-21-en-portrait   │ Application crashed │
[task 2020-11-11T14:39:12.102Z] └─────────┴──────────────────────┴─────────────────────────┴─────────────────────┘
[task 2020-11-11T14:39:12.102Z] More details are available at:
[task 2020-11-11T14:39:12.103Z] https://console.firebase.google.com/project/moz-android-components-230120/testlab/histories/bh.acacddb44ee28c64/matrices/6267623565082952208
```

The crash logs on Firebase:

```
org.mozilla.experiments.nimbus.ErrorException$ResponseError: Error in network response: {"code":404,"errno":111,"error":"Not Found","details":{"id":"nimbus-mobile-experiments","resource_name":"collection"}}

     FATAL EXCEPTION: pool-3-thread-1
Process: org.mozilla.samples.glean.debug, PID: 16331
org.mozilla.experiments.nimbus.ErrorException$ResponseError: Error in network response: {"code":404,"errno":111,"error":"Not Found","details":{"id":"nimbus-mobile-experiments","resource_name":"collection"}}
	at org.mozilla.experiments.nimbus.Error.intoException(nimbus.kt:625)
	at org.mozilla.experiments.nimbus.NimbusClient.getActiveExperiments(nimbus.kt:998)
	at mozilla.components.service.nimbus.Nimbus$init$1.invokeSuspend(Nimbus.kt:147)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
```

Looks like we're trying to make network calls to a remote server in the test? 🤔 

Reference links:
 - https://github.com/mozilla-mobile/android-components/pull/8945 - [TC logs](https://firefox-ci-tc.services.mozilla.com/tasks/WWedT28lQA6vDSDmUhL0ag)
 - https://github.com/mozilla-mobile/android-components/pull/8948 - [TC logs](https://firefox-ci-tc.services.mozilla.com/tasks/akZJ6Uc4Sv-JtCMK5DxwNg)

cc: @travis79

**Comment by jonalmeida** [comment]
Ah, looks like this was already addressed and the PRs I was looking at were failing before this merged.

Duplicate of https://github.com/mozilla-mobile/android-components/issues/8950.
