### ISSUE TITLE
Sample Browser crashes when entering ://

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#897]
Pretty sure this is related to our URL parsing, similar to #760, but filing this since that issue is closed.

STR:
1. Enter in the toolbar `://`.

Expected:
- A search with the default search engine using `://`.

Actual:
- We crash.

Currently, Fennec and Focus[1] handle this without crashing. Although Focus displays an 'Invalid Address' error page.

Crash log:
```
2018-09-27 16:30:22.775 22584-22603/org.mozilla.samples.browser D/GeckoViewModule: dispatch GeckoView:LoadUri, data={"uri":"http://://","flags":0}
2018-09-27 16:30:22.776 22584-22603/org.mozilla.samples.browser D/GeckoViewNavigation: onEvent: event=GeckoView:LoadUri, data={"uri":"http://://","flags":0}
2018-09-27 16:30:22.782 22584-22584/org.mozilla.samples.browser W/IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
2018-09-27 16:30:22.787 22650-22666/org.mozilla.samples.browser:tab D/GeckoViewNavigation[C]: handleLoadError: uri=null uri2=null error=2152398858
2018-09-27 16:30:22.789 22584-22584/org.mozilla.samples.browser W/IInputConnectionWrapper: getSelectedText on inactive InputConnection
2018-09-27 16:30:22.790 22584-22584/org.mozilla.samples.browser W/IInputConnectionWrapper: getTextAfterCursor on inactive InputConnection
2018-09-27 16:30:22.791 22584-22603/org.mozilla.samples.browser D/GeckoIdleService: Setting timer a day from now
2018-09-27 16:30:22.792 1840-1840/? I/LatinIme: onDeactivate()
2018-09-27 16:30:22.792 22584-22584/org.mozilla.samples.browser D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
2018-09-27 16:30:22.793 22584-22584/org.mozilla.samples.browser E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.samples.browser, PID: 22584
    java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter uri
        at mozilla.components.browser.engine.gecko.GeckoEngineSession$createNavigationDelegate$1.onLoadError(Unknown Source:43)
        at org.mozilla.geckoview.GeckoSession$2.handleMessage(GeckoSession.java:348)
        at org.mozilla.geckoview.GeckoSession$2.handleMessage(GeckoSession.java:172)
        at org.mozilla.geckoview.GeckoSessionHandler.handleMessage(GeckoSessionHandler.java:79)
        at org.mozilla.gecko.EventDispatcher$2.run(EventDispatcher.java:344)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

1: Focus version - 8.0 (Build #322690835 :lizard: 62.0.2.20180921002357)

**Comment by jonalmeida** [comment]
This is no longer an issue with using `WebURLFinder`! 🎉
