### ISSUE TITLE
Crash in [@ java.lang.NullPointerException: at org.mozilla.fenix.components.toolbar.DefaultToolbarIntegration.<init>(ToolbarIntegration.kt:16)] on Kindle devices

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/android-components#9072]
Crash report: https://crash-stats.mozilla.org/report/index/da2d9181-dbf8-489b-b934-27cca0201130

Java stack trace:
```
java.lang.NullPointerException
	at org.mozilla.fenix.components.toolbar.DefaultToolbarIntegration.<init>(ToolbarIntegration.kt:16)
	at org.mozilla.fenix.components.toolbar.BrowserToolbarView.<init>(BrowserToolbarView.kt:88)
	at org.mozilla.fenix.browser.BaseBrowserFragment.initializeUI$app_nightly(BaseBrowserFragment.kt:54)
	at org.mozilla.fenix.browser.BrowserFragment.initializeUI$app_nightly(BrowserFragment.kt:3)
	at org.mozilla.fenix.browser.BaseBrowserFragment.onViewCreated(BaseBrowserFragment.kt:1)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:21)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:25)
	at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:5)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:53)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:11)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:12)
	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:1)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6740)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by kbrosnan** [comment]
This only happens on Kindle devices.

**Comment by csadilek** [comment]
Same as https://github.com/mozilla-mobile/fenix/issues/16775. @kbrosnan Let's just keep the Fenix one, as the crash is in `fenix.components.toolbar.BrowserToolbarView`?
