### ISSUE TITLE
Crash in [@ kotlin.UninitializedPropertyAccessException: at mozilla.components.browser.toolbar.behavior.BrowserToolbarBottomBehavior.tryToScrollVertically$browser_toolbar_release(BrowserToolbarBottomBehavior.kt:7)]

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/android-components#9083]
Crash report: https://crash-stats.mozilla.org/report/index/97f51592-714f-4223-810b-acea20201201

Java stack trace:
```
kotlin.UninitializedPropertyAccessException
	at mozilla.components.browser.toolbar.behavior.BrowserToolbarBottomBehavior.tryToScrollVertically$browser_toolbar_release(BrowserToolbarBottomBehavior.kt:7)
	at mozilla.components.browser.toolbar.behavior.BrowserToolbarBottomBehavior$createGestureDetector$1.invoke(BrowserToolbarBottomBehavior.kt:3)
	at mozilla.components.browser.toolbar.behavior.BrowserGestureDetector$gestureDetector$1.invoke(BrowserGestureDetector.kt:5)
	at mozilla.components.browser.toolbar.behavior.BrowserGestureDetector$CustomScrollDetectorListener.onScroll(BrowserGestureDetector.kt:1)
	at android.view.GestureDetector.onTouchEvent(GestureDetector.java:611)
	at mozilla.components.browser.toolbar.behavior.BrowserGestureDetector.handleTouchEvent$browser_toolbar_release(BrowserGestureDetector.kt:4)
	at mozilla.components.browser.toolbar.behavior.BrowserToolbarBottomBehavior.onInterceptTouchEvent(BrowserToolbarBottomBehavior.kt:3)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.performIntercept(CoordinatorLayout.java:20)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onInterceptTouchEvent(CoordinatorLayout.java:3)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2515)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:549)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1953)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3559)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:1)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:502)
	at android.view.View.dispatchPointerEvent(View.java:12027)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5304)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5093)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4588)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4641)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4607)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4734)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4615)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4791)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4588)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4641)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4607)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4615)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4588)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7195)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7169)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7130)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7351)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:181)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7274)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7379)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:981)
	at android.view.Choreographer.doCallbacks(Choreographer.java:790)
	at android.view.Choreographer.doFrame(Choreographer.java:715)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:967)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7529)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```
Devices are mostly Chinese HUAWEI, ZTE and Xiaomi Android API versions 26, 27, 28

**Comment by kbrosnan** [comment]
Dupe of #8884
