### ISSUE TITLE
Crash in BrowserStateSerializer: IllegalArgumentException: Unknown session key: source

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#9292]
Fallout from the feature-collections refactoring and crashing in Nightly. Looks like we forgot to handle `source`?

```
java.lang.IllegalArgumentException: Unknown session key: source
    at mozilla.components.browser.session.storage.BrowserStateSerializerKt.access$tab(BrowserStateSerializer.kt:21)
    at mozilla.components.feature.tab.collections.adapter.TabAdapter.restore(TabAdapter.kt:7)
    at org.mozilla.fenix.home.sessioncontrol.DefaultSessionControlController.handleCollectionOpenTabClicked(SessionControlController.kt:8)
    at org.mozilla.fenix.home.sessioncontrol.SessionControlInteractor.onCollectionOpenTabClicked(SessionControlInteractor.kt:1)
    at org.mozilla.fenix.home.sessioncontrol.viewholders.-$$LambdaGroup$js$CmLMMZGdtRGl-qY2EQsQLG5w5hQ.onClick(java-style lambda group:1)
```

https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/10288164/
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/10295333/

**Comment by csadilek** [comment]
We stopped persisting and restoring session source a while ago in https://github.com/mozilla-mobile/android-components/issues/6651. We have old collections around though and need to tolerate session source being in the JSON. Our new `BrowserStateSerializer` doesn't tolerate it though. Let's fix that.
