### ISSUE TITLE
org.mozilla.geckoview.GeckoSession$SessionState.fromString(GeckoSession.java:1): org.json.JSONException: at org.json.JSON.typeMismatch(JSON.java)

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#9332]
https://crash-stats.mozilla.org/report/index/4aa0464f-6618-498d-bc01-9d9cc0210106#tab-details

```
org.json.JSONException
	at org.json.JSON.typeMismatch(JSON.java:112)
	at org.json.JSONObject.<init>(JSONObject.java:168)
	at org.json.JSONObject.<init>(JSONObject.java:181)
	at org.mozilla.geckoview.GeckoSession$SessionState.fromString(GeckoSession.java:1)
	at mozilla.components.browser.session.storage.serialize.BrowserStateReaderKt.tab(BrowserStateReader.kt:69)
	at mozilla.components.browser.session.storage.serialize.BrowserStateReaderKt.access$browsingSession(BrowserStateReader.kt:11)
	at mozilla.components.browser.session.storage.serialize.BrowserStateReader.read(BrowserStateReader.kt:3)
	at mozilla.components.browser.session.storage.SessionStorage.restore(SessionStorage.kt:3)
	at mozilla.components.feature.tabs.TabsUseCases$RestoreUseCase$invoke$2.invokeSuspend(TabsUseCases.kt:5)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7960)

**Comment by pocmo** [comment]
This looks like a regression from the session store refactoring that landed yesterday.

What's odd is that it is coming out of GeckoView when restoring the SessionState. At this point I am not really sure if the restore is really broken or whether this has happened before too and was just hidden since we caught all `JSONException` previously. If this is to be expected then we may just catch `JSONException` again. In the long term this probably should be handled inside `GeckoSession.SessionState` if it is expected.

**Comment by pocmo** [comment]
Looking into the code I think this is something that was always possible, but since we use `org.json` ourselves and caught `JSONException` we never saw this coming out of GeckoView.

`GeckoSession.SessionState.toString()` can in some situations return `null`:
https://searchfox.org/mozilla-central/source/mobile/android/geckoview/src/main/java/org/mozilla/geckoview/GeckoSession.java#2509-2524

However `GeckoSession.SessionState.fromString()` always expects `JSONObject`:
https://searchfox.org/mozilla-central/source/mobile/android/geckoview/src/main/java/org/mozilla/geckoview/GeckoSession.java#2504-2506

So I think we should:
* Catch `JSONException` to work around the startup crash that our users are seeing
* File a GeckoView bug so that this can get fixed in `GeckoView`. `fromString()` should handle `null` values. In general we probably should never see a `JSONException` coming out of `GeckoView`.

**Comment by pocmo** [comment]
Filed GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1685486

**Comment by csadilek** [comment]
Handled in https://github.com/mozilla-mobile/android-components/pull/9333 and fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1685486
