### ISSUE TITLE
Failed download from custom tab

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#9340]
I'm trying to download one of the APKs listed on 

https://firefox-ci-tc.services.mozilla.com/tasks/FBfhXazcQh-AXbH2CYL28Q#artifacts

I'm opening the above link from the native Slack app. The initial page renders fine in the custom tab. But when I tap on one of the APK links,  I get a bank page and a progress indicator that sits at about 25%. This does not seem to time-out.

When I copy/past the above link directly into Fenix (not a custom tab), the downloads work.

I'm on Fenix 84.1.2 Release.

```
01-06 10:40:56.021  1430  1793 I ActivityTaskManager: START u0 {act=android.intent.action.VIEW cat=[mozilla.components.pwa.category.SHORTCUT] dat=https://firefox-ci-tc.services.mozilla.com/... pkg=org.mozilla.firefox cmp=org.mozilla.firefox/org.mozilla.fenix.IntentReceiverActivity (has extras)} from uid 10231
01-06 10:40:56.022   912   912 D android.hardware.power@1.3-service.pixel-libperfmgr: LAUNCH: 1
01-06 10:40:56.036 21418 21418 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@d982f2b
01-06 10:40:56.039 21418 21418 W App     : Could not read from intent.
01-06 10:40:56.039 21418 21418 W App     : java.lang.NullPointerException: null cannot be cast to non-null type T
01-06 10:40:56.039 21418 21418 W App     : 	at mozilla.components.support.utils.SafeIntent$getParcelableExtra$1.invoke(SafeIntent.kt:3)
01-06 10:40:56.039 21418 21418 W App     : 	at mozilla.components.support.utils.SafeIntent.safeAccess(SafeIntent.kt:1)
01-06 10:40:56.039 21418 21418 W App     : 	at mozilla.components.support.utils.SafeIntent.getParcelableExtra(SafeIntent.kt:2)
01-06 10:40:56.039 21418 21418 W App     : 	at mozilla.components.feature.customtabs.CustomTabConfigHelperKt.createCustomTabConfigFromIntent(CustomTabConfigHelper.kt:5)
01-06 10:40:56.039 21418 21418 W App     : 	at mozilla.components.feature.customtabs.CustomTabIntentProcessor.process(CustomTabIntentProcessor.kt:9)
01-06 10:40:56.039 21418 21418 W App     : 	at org.mozilla.fenix.IntentReceiverActivity.onCreate(IntentReceiverActivity.kt:27)
01-06 10:40:56.039 21418 21418 W App     : 	at android.app.Activity.performCreate(Activity.java:7825)
01-06 10:40:56.039 21418 21418 W App     : 	at android.app.Activity.performCreate(Activity.java:7814)
01-06 10:40:56.039 21418 21418 W App     : 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
01-06 10:40:56.039 21418 21418 W App     : 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
01-06 10:40:56.039 21418 21418 W App     : 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
01-06 10:40:56.039 21418 21418 W App     : 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
01-06 10:40:56.039 21418 21418 W App     : 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
01-06 10:40:56.039 21418 21418 W App     : 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
01-06 10:40:56.039 21418 21418 W App     : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
01-06 10:40:56.039 21418 21418 W App     : 	at android.os.Handler.dispatchMessage(Handler.java:107)
01-06 10:40:56.039 21418 21418 W App     : 	at android.os.Looper.loop(Looper.java:214)
01-06 10:40:56.039 21418 21418 W App     : 	at android.app.ActivityThread.main(ActivityThread.java:7356)
01-06 10:40:56.039 21418 21418 W App     : 	at java.lang.reflect.Method.invoke(Native Method)
01-06 10:40:56.039 21418 21418 W App     : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
01-06 10:40:56.039 21418 21418 W App     : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
01-06 10:40:56.041  1430  5654 I ActivityTaskManager: START u0 {act=android.intent.action.VIEW cat=[mozilla.components.pwa.category.SHORTCUT] dat=https://firefox-ci-tc.services.mozilla.com/... pkg=org.mozilla.firefox cmp=org.mozilla.firefox/org.mozilla.fenix.customtabs.ExternalAppBrowserActivity (has extras)} from uid 10231
```

**Comment by Amejia481** [comment]
We opened a bug for this [on GV](https://bugzilla.mozilla.org/show_bug.cgi?id=1687540), this is the same issue as https://github.com/mozilla-mobile/fenix/issues/16998
