### ISSUE TITLE
RustErrorException - logins::ffi - Invalid login: Login already exists

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#9397]
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/8831884/?query=is%3Aunresolved

```
mozilla.components.support.rustlog.RustErrorException: logins::ffi - Invalid login: Login already exists
    at mozilla.components.support.rustlog.CrashReporterOnLog.invoke(RustLog.kt:9)
    at mozilla.appservices.rustlog.RawLogCallbackImpl.invoke(RustLogAdapter.kt:3)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:11)
    at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:1)
    at com.sun.jna.Native.invokeVoid(Native.java)
    at com.sun.jna.Function.invoke(Function.java:98)
    at com.sun.jna.Function.invoke(Function.java:22)
    at com.sun.jna.Library$Handler.invoke(Library.java:31)
    at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
    at $Proxy11.sync15_passwords_check_valid
    at mozilla.appservices.logins.DatabaseLoginsStorage.ensureValid(DatabaseLoginsStorage.kt:11)
    at mozilla.components.service.sync.logins.SyncableLoginsStorage$ensureValid$2.invokeSuspend(SyncableLoginsStorage.kt:2)
    at mozilla.components.service.sync.logins.SyncableLoginsStorage$ensureValid$2.invoke(SyncableLoginsStorage.kt:2)
    at androidx.core.app.AppOpsManagerCompat.startUndispatchedOrReturn(AppOpsManagerCompat.java:2)
    at kotlinx.coroutines.AwaitKt.withContext(Await.kt:9)
    at mozilla.components.service.sync.logins.SyncableLoginsStorage.ensureValid(SyncableLoginsStorage.kt:1)
    at mozilla.components.service.sync.logins.DefaultLoginValidationDelegate$ensureValidAsync$1.invokeSuspend(DefaultLoginValidationDelegate.kt:12)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7995)

**Comment by grigoryk** [comment]
So, we're expecting `ensureValid` to throw (its docs state that it'll throw on an invalid login), and catching `InvalidRecordException` to figure out which `InvalidLoginReason` we've hit. But somehow in this case we're hitting a different exception..?

**Comment by jonalmeida** [comment]
Closing; no more reports for this error.
