### ISSUE TITLE
Protobuf decode error: failed to decode Protobuf message: PasswordInfo.times_used: invalid wire type: StartGroup (expected Varint)

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#9400]
https://sentry.prod.mozaws.net/operations/firefox/issues/9275402/?query=is%3Aunresolved%20Protobuf%20decode%20error

Steady daily volume of these, last appeared 6 months ago in 79.0.0.
<img width="355" alt="Screen Shot 2021-01-13 at 9 45 12 PM" src="https://user-images.githubusercontent.com/465422/104549934-9f667e00-55e8-11eb-9dae-09ea9af4610f.png">

```
mozilla.appservices.logins.LoginsStorageException: Protobuf decode error: failed to decode Protobuf message: PasswordInfo.times_used: invalid wire type: StartGroup (expected Varint)
    at mozilla.appservices.logins.rust.RustError.intoException(RustError.kt:4)
    at mozilla.appservices.logins.DatabaseLoginsStorage.potentialDupesIgnoringUsername(DatabaseLoginsStorage.kt:24)
    at mozilla.components.service.sync.logins.SyncableLoginsStorage$getPotentialDupesIgnoringUsername$2.invokeSuspend(SyncableLoginsStorage.kt:2)
    at mozilla.components.service.sync.logins.SyncableLoginsStorage$getPotentialDupesIgnoringUsername$2.invoke(SyncableLoginsStorage.kt:2)
    at androidx.core.app.AppOpsManagerCompat.startUndispatchedOrReturn(AppOpsManagerCompat.java:2)
    at kotlinx.coroutines.AwaitKt.withContext(Await.kt:9)
    at mozilla.components.service.sync.logins.SyncableLoginsStorage.getPotentialDupesIgnoringUsername(SyncableLoginsStorage.kt:1)
    at mozilla.components.service.sync.logins.DefaultLoginValidationDelegate$getPotentialDupesIgnoringUsernameAsync$1.invokeSuspend(DefaultLoginValidationDelegate.kt:5)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8001)

**Comment by grigoryk** [comment]
Ah, this is same as https://github.com/mozilla-mobile/fenix/issues/13253 and https://github.com/mozilla/application-services/issues/3709

**Comment by jonalmeida** [comment]
Protobuf is dead, long life uniffi.
