### ISSUE TITLE
AddonManagerException - Unsupported URI scheme

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#9401]
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/9937132/?query=is%3Aunresolved%20level%3Ainfo

```
java.lang.IllegalArgumentException: Unsupported URI scheme
    at org.mozilla.geckoview.GeckoWebExecutor.fetch(GeckoWebExecutor.java:12)
    at mozilla.components.browser.engine.gecko.fetch.GeckoViewFetchClient.fetch(GeckoViewFetchClient.kt:39)
    at mozilla.components.feature.addons.amo.AddonCollectionProvider.fetchAvailableAddons(AddonCollectionProvider.kt:7)
    at mozilla.components.feature.addons.amo.AddonCollectionProvider.getAvailableAddons(AddonCollectionProvider.kt:5)
    at mozilla.components.feature.addons.AddonManager.getAddons(AddonManager.kt:9)
    at mozilla.components.feature.addons.AddonManager$getAddons$1.invokeSuspend
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)

mozilla.components.feature.addons.AddonManagerException: java.lang.IllegalArgumentException: Unsupported URI scheme
    at mozilla.components.feature.addons.AddonManager.getAddons(AddonManager.kt:66)
    at mozilla.components.feature.addons.AddonManager$getAddons$1.invokeSuspend
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
```

Seems like we have invalid (addon?) urls we're trying to fetch? cc @csadilek

**Comment by grigoryk** [comment]
According to @csadilek the problem seems to be within `GeckoWebExecutor.fetch` and how it's processing URLs we're passing to it.

**Comment by csadilek** [comment]
GV bug is: https://bugzilla.mozilla.org/show_bug.cgi?id=1686808

This is just logged as info and we also worked around this for icons because there it was crashing.

**Comment by csadilek** [comment]
GV fix worked. Closing.
