### ISSUE TITLE
PushError$Rust - Couldn't find com.sun.jna.Structure$FieldOrder.value

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#9402]
https://sentry.prod.mozaws.net/operations/firefox/issues/10106951/?query=is%3Aunresolved%20PushError%24Rust

```
java.lang.IncompatibleClassChangeError: Couldn't find com.sun.jna.Structure$FieldOrder.value
    at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:659)
    at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:641)
    at libcore.reflect.AnnotationAccess.getDeclaredAnnotation(AnnotationAccess.java:170)
    at libcore.reflect.AnnotationAccess.getAnnotation(AnnotationAccess.java:72)
    at java.lang.Class.getAnnotation(Class.java:343)
    at com.sun.jna.Structure.getFieldOrder(Structure.java:3)
    at com.sun.jna.Structure.fieldOrder(Structure.java:4)
    at com.sun.jna.Structure.getFields(Structure.java:5)
    at com.sun.jna.Structure.deriveLayout(Structure.java:1)
    at com.sun.jna.Structure.calculateSize(Structure.java:9)
    at com.sun.jna.Structure.calculateSize(Structure.java:1)
    at com.sun.jna.Structure.allocateMemory(Structure.java:3)
    at com.sun.jna.Structure.<init>(Structure.java:17)
    at com.sun.jna.Structure.<init>(Structure.java:6)
    at com.sun.jna.Structure.<init>(Structure.java:3)
    at com.sun.jna.Structure.<init>(Structure.java:1)
    at mozilla.appservices.push.RustError.<init>(RustError.kt:1)
    at mozilla.appservices.push.RustError$ByReference.<init>(RustError.kt:1)
    at mozilla.appservices.push.PushManager.<init>(PushManager.kt:4)
    at mozilla.components.feature.push.RustPushConnection.updateToken(Connection.kt:15)
    at mozilla.components.feature.push.AutoPushFeature$$special$$inlined$let$lambda$1.invokeSuspend(AutoPushFeature.kt:6)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:818)

mozilla.components.concept.push.PushError$Rust: Couldn't find com.sun.jna.Structure$FieldOrder.value
    at mozilla.components.feature.push.AutoPushFeature$$special$$inlined$exceptionHandler$1.handleException(CoroutineExceptionHandler.kt:5)
    at androidx.core.app.AppOpsManagerCompat.handleCoroutineException(AppOpsManagerCompat.java:2)
    at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Builders.common.kt:1)
    at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:14)
    at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:26)
    at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:2)
    at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:1)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:818)
```

`updateToken` is also in the stacktrace of this issue: https://github.com/mozilla-mobile/android-components/issues/7916

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8005)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796424

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
