### ISSUE TITLE
SQLiteConstraintException: UNIQUE constraint failed: recently_closed_tabs.uuid

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#9409]
https://sentry.prod.mozaws.net/share/issue/a451ccd82df841c6866c76f6c49fd25b/

```
android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: recently_closed_tabs.uuid (code 1555 SQLITE_CONSTRAINT_PRIMARYKEY[1555])
    at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(SQLiteConnection.java)
    at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:995)
    at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
    at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
    at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeInsert(FrameworkSQLiteStatement.java:1)
    at androidx.room.EntityInsertionAdapter.insertAndReturnId(EntityInsertionAdapter.java:3)
    at mozilla.components.feature.recentlyclosed.db.RecentlyClosedTabDao_Impl.insertTab(RecentlyClosedTabDao_Impl.java:3)
    at mozilla.components.feature.recentlyclosed.RecentlyClosedTabsStorage.addTabsToCollectionWithMax(RecentlyClosedTabsStorage.kt:26)
    at mozilla.components.feature.recentlyclosed.RecentlyClosedMiddleware$addTabsToStorage$1.invokeSuspend(RecentlyClosedMiddleware.kt:4)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
```

**Comment by pocmo** [comment]
This should not have happened after we switched to handling tabs from the undo action:
https://github.com/mozilla-mobile/android-components/pull/9379

I tried to reproduce this to change the UI tests to double click or swipe and click. But I wasn't able to reproduce this yet.

**Comment by pocmo** [comment]
The previous code generated a new ID whenever a closed tab was saved. This would prevent that problem. But I still wonder how it happens. Generating a new ID could cause duplicated tabs in theory.

**Comment by pocmo** [comment]
The only way I could imagine this happening is when the coroutines that save to disk or delete run in different orders or delayed, which may be possible with the IO dispatcher used. 🤔

**Comment by csadilek** [comment]
Looking at Sentry, our latest fix (single threaded executor) worked. So the coroutine's got launched out-of-order. I think we can close?

**Comment by pocmo** [comment]
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/10433826/?query=is%3Aunresolved

**Comment by csadilek** [comment]
Looked (and searched) again on Sentry to verify this didn't happen anymore after the latest fix.
