### ISSUE TITLE
Intermittent UI test failure - processCustomTabIntentWithAdditionalHeaders mozilla.components.feature.customtabs.CustomTabIntentProcessorTest.processCustomTabIntentWithAdditionalHeaders: sdk=28; resources=binary

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/android-components#9427]
Log: https://treeherder.mozilla.org/logviewer?job_id=326854161&repo=android-components

**Comment by Archaeopteryx** [comment]
See also https://treeherder.mozilla.org/logviewer?job_id=326912422&repo=android-components which is about `processPrivateCustomTabIntentWithDefaultHandlers`.

**Comment by jonalmeida** [comment]
Came here to post this as well.

In-lined logs:

```
[task 2021-01-18T14:50:24.509Z]     at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
[task 2021-01-18T14:50:24.509Z]     at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[task 2021-01-18T14:50:24.509Z]     at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:154)
[task 2021-01-18T14:50:24.509Z]     at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
[task 2021-01-18T14:50:24.509Z]     at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
[task 2021-01-18T14:50:24.509Z]     at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
[task 2021-01-18T14:50:24.509Z]     at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
[task 2021-01-18T14:50:24.509Z]     at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
[task 2021-01-18T14:50:24.509Z]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2021-01-18T14:50:24.509Z]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2021-01-18T14:50:24.509Z]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2021-01-18T14:50:24.509Z]     at java.lang.reflect.Method.invoke(Method.java:498)
[task 2021-01-18T14:50:24.509Z]     at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
[task 2021-01-18T14:50:24.509Z]     at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[task 2021-01-18T14:50:24.509Z]     at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
[task 2021-01-18T14:50:24.509Z]     at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
[task 2021-01-18T14:50:24.509Z]     at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
[task 2021-01-18T14:50:24.509Z]     at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:119)
[task 2021-01-18T14:50:24.509Z]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2021-01-18T14:50:24.509Z]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2021-01-18T14:50:24.509Z]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2021-01-18T14:50:24.509Z]     at java.lang.reflect.Method.invoke(Method.java:498)
[task 2021-01-18T14:50:24.509Z]     at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
[task 2021-01-18T14:50:24.509Z]     at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[task 2021-01-18T14:50:24.509Z]     at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
[task 2021-01-18T14:50:24.509Z]     at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
[task 2021-01-18T14:50:24.509Z]     at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
[task 2021-01-18T14:50:24.509Z]     at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
[task 2021-01-18T14:50:24.509Z]     at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
[task 2021-01-18T14:50:24.509Z]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[task 2021-01-18T14:50:24.509Z]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[task 2021-01-18T14:50:24.509Z]     at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
[task 2021-01-18T14:50:24.509Z]     at java.lang.Thread.run(Thread.java:748)
[task 2021-01-18T14:50:24.605Z]   FAILURE
[task 2021-01-18T14:50:24.605Z] 
[task 2021-01-18T14:50:24.605Z] java.lang.AssertionError: No action of type class mozilla.components.browser.state.action.EngineAction$LoadUrlAction found
[task 2021-01-18T14:50:24.605Z] 	at mozilla.components.support.test.middleware.CaptureActionsMiddleware.findFirstAction(CaptureActionsMiddleware.kt:33)
[task 2021-01-18T14:50:24.605Z] 	at mozilla.components.support.test.middleware.CaptureActionsMiddleware.assertFirstAction(CaptureActionsMiddleware.kt:54)
[task 2021-01-18T14:50:24.605Z] 	at mozilla.components.feature.customtabs.CustomTabIntentProcessorTest.processPrivateCustomTabIntentWithDefaultHandlers(CustomTabIntentProcessorTest.kt:153)
[task 2021-01-18T14:50:24.605Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by Archaeopteryx** [comment]
#4257 touched the test before the failures started. @pocmo please investigate.
