### ISSUE TITLE
Intermittent  test failure - BrowserAwesomeBar stops jobs when getting detached | mozilla.components.browser.awesomebar.BrowserAwesomeBarTest.BrowserAwesomeBar stops jobs when getting detached: sdk=28; resources=binary

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/android-components#9533]
Log: https://treeherder.mozilla.org/logviewer?job_id=328066207&repo=android-components

### Stacktrace:
```
TEST: BrowserAwesomeBar stops jobs when getting detached
  [Robolectric] mozilla.components.browser.awesomebar.BrowserAwesomeBarTest.BrowserAwesomeBar stops jobs when getting detached: sdk=28; resources=binary
  I/MonitoringInstr: Instrumentation started!
  Exception in thread "kotlinx.coroutines.DefaultExecutor" java.lang.StackOverflowError
  at org.mockito.internal.util.concurrent.WeakConcurrentMap$LatentKey.hashCode(WeakConcurrentMap.java)
  at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
  at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:964)
  at org.mockito.internal.util.concurrent.WeakConcurrentMap.containsKey(WeakConcurrentMap.java:76)
  at org.mockito.internal.util.concurrent.WeakConcurrentMap$WithInlinedExpunction.containsKey(WeakConcurrentMap.java:264)
  at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMock(MockMethodAdvice.java:121)
  at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMocked(MockMethodAdvice.java:126)
  at java.lang.Object.toString(Object.java:236)
  at java.util.concurrent.ThreadPoolExecutor.toString(ThreadPoolExecutor.java:1932)
  at kotlinx.coroutines.ExecutorCoroutineDispatcherBase.toString(Executors.kt:151)
  at java.lang.String.valueOf(String.java:2994)
  at java.lang.StringBuilder.append(StringBuilder.java:131)
  at kotlinx.coroutines.internal.DispatchedContinuation.toString(DispatchedContinuation.kt:251)
  at kotlinx.coroutines.DebugStringsKt.toDebugString(DebugStrings.kt:16)
  at kotlinx.coroutines.CancellableContinuationImpl.toString(CancellableContinuationImpl.kt:506)
  at kotlinx.coroutines.EventLoopImplBase$DelayedResumeTask.toString(EventLoop.common.kt:490)
  at java.lang.String.valueOf(String.java:2994)
  at java.lang.StringBuilder.append(StringBuilder.java:131)
  at kotlinx.coroutines.DisposeOnCancel.toString(CancellableContinuation.kt:385)
  at java.lang.String.valueOf(String.java:2994)
  at java.lang.StringBuilder.append(StringBuilder.java:131)
  at kotlinx.coroutines.CompletedContinuation.toString(CancellableContinuationImpl.kt)
  at java.lang.String.valueOf(String.java:2994)
  at java.lang.StringBuilder.append(StringBuilder.java:131)
  at kotlinx.coroutines.CancellableContinuationImpl.toString(CancellableContinuationImpl.kt:506)
  at kotlinx.coroutines.EventLoopImplBase$DelayedResumeTask.toString(EventLoop.common.kt:490)
  at java.lang.String.valueOf(String.java:2994)
  at java.lang.StringBuilder.append(StringBuilder.java:131)
  at kotlinx.coroutines.DisposeOnCancel.toString(CancellableContinuation.kt:385)
  at java.lang.String.valueOf(String.java:2994)
  at java.lang.StringBuilder.append(StringBuilder.java:131)
  at kotlinx.coroutines.CompletedContinuation.toString(CancellableContinuationImpl.kt)
  at java.lang.String.valueOf(String.java:2994)
  at java.lang.StringBuilder.append(StringBuilder.java:131)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8104)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794875

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
