### ISSUE TITLE
Crash in [@ android.database.sqlite.SQLiteDiskIOException: at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)]

### ISSUE THREAD

**Issue by fluffyemily** [mozilla-mobile/android-components#9537]
Crash report: https://crash-stats.mozilla.org/report/index/da205e0c-aa0d-4d56-bc8c-1584d0210128

Java stack trace:
```
android.database.sqlite.SQLiteDiskIOException
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:890)
	at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:635)
	at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:321)
	at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:292)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:216)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:194)
	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:493)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:200)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:192)
	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:864)
	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:849)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:724)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:714)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:295)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:238)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:2)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:1)
	at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:1)
	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:1)
	at androidx.room.RoomDatabase.query(RoomDatabase.java:2)
	at androidx.room.util.DBUtil.query(DBUtil.java:1)
	at mozilla.components.feature.downloads.db.DownloadDao_Impl$9.call(DownloadDao_Impl.java:1)
	at androidx.room.CoroutinesRoom$Companion$createFlow$1$1.invokeSuspend(CoroutinesRoom.kt:8)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8106)

**Comment by cpeterso** [comment]
Bugzilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1757967

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1792932

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
