### ISSUE TITLE
FXP-1491 ⁃ Investigate strange StrictMode violation in Nimbus

### ISSUE THREAD

**Issue by jhugman** [mozilla-mobile/android-components#9574]
When debugging the app, when setting a breakpoint during `createNimbus` from https://github.com/mozilla-mobile/fenix/pull/17684 a crash due to strict mode violation is seen.

```
3ac5c596-43dd-495c-a913-bfe9fa332386
java.lang.RuntimeException: StrictMode ThreadPolicy violation
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-4cb738e4-14ee-4b1f-b32d-04ce60210201
----
java.lang.RuntimeException: StrictMode ThreadPolicy violation
	at android.os.StrictMode$AndroidBlockGuardPolicy.onThreadPolicyViolation(StrictMode.java:1705)
	at android.os.StrictMode$AndroidBlockGuardPolicy.lambda$handleViolationWithTimingAttempt$0(StrictMode.java:1619)
	at android.os.-$$Lambda$StrictMode$AndroidBlockGuardPolicy$9nBulCQKaMajrWr41SB7f7YRT1I.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: android.os.strictmode.DiskReadViolation
	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
	at java.io.UnixFileSystem.list(UnixFileSystem.java:302)
	at java.io.File.list(File.java:1131)
	at java.io.File.listFiles(File.java:1216)
	at org.mozilla.fenix.experiments.NimbusSetupKt.createNimbus(NimbusSetup.kt:46)
	at org.mozilla.fenix.components.Analytics$experiments$2.invoke(Analytics.kt:109)
	at org.mozilla.fenix.components.Analytics$experiments$2.invoke(Analytics.kt:42)
	at org.mozilla.fenix.perf.LazyMonitored$lazyValue$1.invoke(LazyMonitored.kt:36)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.mozilla.fenix.perf.LazyMonitored.getValue(LazyMonitored.kt:43)
	at org.mozilla.fenix.components.Analytics.getExperiments(Unknown Source:2)
	at org.mozilla.fenix.home.HomeMenu$coreMenuItems$2.invoke(HomeMenu.kt:102)
	at org.mozilla.fenix.home.HomeMenu$coreMenuItems$2.invoke(HomeMenu.kt:33)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.mozilla.fenix.home.HomeMenu.getCoreMenuItems(Unknown Source:2)
	at org.mozilla.fenix.home.HomeMenu.<init>(HomeMenu.kt:216)
	at org.mozilla.fenix.home.HomeFragment.createHomeMenu(HomeFragment.kt:774)
	at org.mozilla.fenix.home.HomeFragment.onViewCreated(HomeFragment.kt:364)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:332)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2637)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2589)
	at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2723)
	at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:346)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1200)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2637)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2589)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
	at org.mozilla.fenix.HomeActivity.onStart(HomeActivity.kt:314)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
	at android.app.Activity.performStart(Activity.java:7157)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2937)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	... 5 more
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXP-1491)

**Comment by mcomella** [comment]
triage: csadilek mentions we've been unable to repro this error and the code has since changed. It doesn't look like we try to suppress this error though. Since we can't repro, I'm going to close. We can reopen if we see this violation again.
