### ISSUE TITLE
Crash in [@ android.database.sqlite.SQLiteDiskIOException: at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)]

### ISSUE THREAD

**Issue by fluffyemily** [mozilla-mobile/android-components#9612]
Crash report: https://crash-stats.mozilla.org/report/index/d7b11572-0074-4bde-a8f1-6e41c0210204

Java stack trace:
```
android.database.sqlite.SQLiteDiskIOException
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1093)
	at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:804)
	at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:490)
	at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:461)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:363)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:228)
	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:512)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:178)
	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:894)
	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:864)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:699)
	at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1520)
	at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:282)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:2)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:1)
	at androidx.room.RoomDatabase.beginTransaction(RoomDatabase.java:2)
	at mozilla.components.feature.recentlyclosed.db.RecentlyClosedTabDao_Impl$4.call(RecentlyClosedTabDao_Impl.java:1)
	at androidx.room.CoroutinesRoom$Companion$createFlow$1$1.invokeSuspend(CoroutinesRoom.kt:8)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
	at androidx.room.TransactionExecutor$1.run(TransactionExecutor.java:1)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8172)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795416

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
