### ISSUE TITLE
Intermittent Fatal exception - java.lang.IllegalArgumentException: Work with id 07bc9d46-6a2a-4ea0-94d1-057d32ad2c90 is not enqueued!

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/android-components#9816]
cc @badboy 

### Firebase Test Run:
https://console.firebase.google.com/project/moz-android-components-230120/testlab/histories/bh.acacddb44ee28c64/matrices/4840888030466358194
### Stacktrace:
```
 Fatal exception

java.lang.IllegalArgumentException: Work with id 07bc9d46-6a2a-4ea0-94d1-057d32ad2c90 is not enqueued!

     FATAL EXCEPTION: GleanAPIPool
Process: org.mozilla.samples.glean.debug, PID: 17497
java.lang.IllegalArgumentException: Work with id 07bc9d46-6a2a-4ea0-94d1-057d32ad2c90 is not enqueued!
	at androidx.work.testing.TestScheduler.setAllConstraintsMet(TestScheduler.java:110)
	at androidx.work.testing.TestWorkManagerImpl.setAllConstraintsMet(TestWorkManagerImpl.java:107)
	at mozilla.telemetry.glean.utils.WorkManagerUtilsKt$testFlushWorkManagerJob$1$1.invokeSuspend(WorkManagerUtils.kt:35)
	at mozilla.telemetry.glean.utils.WorkManagerUtilsKt$testFlushWorkManagerJob$1$1.invoke(Unknown Source:10)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:102)
	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:148)
	at kotlinx.coroutines.TimeoutKt.withTimeout(Timeout.kt:44)
	at mozilla.telemetry.glean.utils.WorkManagerUtilsKt$testFlushWorkManagerJob$1.invokeSuspend(WorkManagerUtils.kt:28)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at mozilla.telemetry.glean.utils.WorkManagerUtilsKt.testFlushWorkManagerJob(WorkManagerUtils.kt:27)
	at mozilla.telemetry.glean.utils.WorkManagerUtilsKt.testFlushWorkManagerJob$default(WorkManagerUtils.kt:26)
	at mozilla.telemetry.glean.scheduler.PingUploadWorker$Companion.enqueueWorker$glean_release(PingUploadWorker.kt:71)
	at mozilla.telemetry.glean.GleanInternalAPI.submitPingByNameSync$glean_release(Glean.kt:740)
	at mozilla.telemetry.glean.scheduler.MetricsPingScheduler.collectPingAndReschedule$glean_release(MetricsPingScheduler.kt:307)
	at mozilla.telemetry.glean.scheduler.MetricsPingScheduler.schedule(MetricsPingScheduler.kt:226)
	at mozilla.telemetry.glean.GleanInternalAPI$initializeInternal$1.invokeSuspend(Glean.kt:298)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
```

**Comment by badboy** [comment]
Looks like it didn't occur again since then, and thus really was an intermittent and I have nothing to debug this further.
