### ISSUE TITLE
Intermittent mozilla.components.support.locale.LocaleMiddlewareTest - GIVEN a locale has been chosen in the app WHEN we restore state THEN locale is retrieved from storage

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/android-components#9954]
Log: https://treeherder.mozilla.org/logviewer?job_id=334152569&repo=android-components

Failed the first 2 runs, succeeded for the third.
```
[task 2021-03-23T13:52:11.982Z]   TEST: when calling updateResources without a stored language we must not change the system locale
[task 2021-03-23T13:52:11.982Z]     [Robolectric] mozilla.components.support.locale.LocaleManagerTest.when calling updateResources without a stored language we must not change the system locale: sdk=28; resources=binary
[task 2021-03-23T13:52:12.082Z]     I/MonitoringInstr: Instrumentation started!
[task 2021-03-23T13:52:12.082Z]   SUCCESS
[task 2021-03-23T13:52:12.082Z] 
[task 2021-03-23T13:52:12.083Z] 
[task 2021-03-23T13:52:12.083Z] SUITE: mozilla.components.support.locale.LocaleMiddlewareTest
[task 2021-03-23T13:52:12.083Z]   TEST: GIVEN a locale has been chosen in the app WHEN we restore state THEN locale is retrieved from storage
[task 2021-03-23T13:52:12.083Z]     [Robolectric] mozilla.components.support.locale.LocaleMiddlewareTest.GIVEN a locale has been chosen in the app WHEN we restore state THEN locale is retrieved from storage: sdk=28; resources=binary
[task 2021-03-23T13:52:12.182Z]     I/MonitoringInstr: Instrumentation started!
[task 2021-03-23T13:52:12.482Z]     D [LocaleMiddleware] No recoverable locale has been set. Following device locale.
[task 2021-03-23T13:52:12.583Z]   FAILURE
[task 2021-03-23T13:52:12.583Z] 
[task 2021-03-23T13:52:12.583Z] org.mockito.exceptions.verification.TooLittleActualInvocations: 
[task 2021-03-23T13:52:12.583Z] localeManager.getCurrentLocale(
[task 2021-03-23T13:52:12.583Z]     android.app.Application@661f352b
[task 2021-03-23T13:52:12.583Z] );
[task 2021-03-23T13:52:12.583Z] Wanted 3 times:
[task 2021-03-23T13:52:12.583Z] -> at mozilla.components.support.locale.LocaleManager.getCurrentLocale(LocaleManager.kt:51)
[task 2021-03-23T13:52:12.583Z] But was 2 times:
[task 2021-03-23T13:52:12.583Z] -> at mozilla.components.support.locale.LocaleMiddlewareTest$GIVEN a locale has been chosen in the app WHEN we restore state THEN locale is retrieved from storage$1.invokeSuspend(LocaleMiddlewareTest.kt:61)
[task 2021-03-23T13:52:12.583Z] -> at mozilla.components.support.locale.LocaleMiddleware$restoreLocale$1.invokeSuspend(LocaleMiddleware.kt:49)
[task 2021-03-23T13:52:12.583Z] 
[task 2021-03-23T13:52:12.583Z] 	at mozilla.components.support.locale.LocaleManager.getCurrentLocale(LocaleManager.kt:51)
[task 2021-03-23T13:52:12.583Z] 	at mozilla.components.support.locale.LocaleMiddlewareTest$GIVEN a locale has been chosen in the app WHEN we restore state THEN locale is retrieved from storage$1.invokeSuspend(LocaleMiddlewareTest.kt:81)
[task 2021-03-23T13:52:12.583Z] 	at mozilla.components.support.locale.LocaleMiddlewareTest$GIVEN a locale has been chosen in the app WHEN we restore state THEN locale is retrieved from storage$1.invoke(LocaleMiddlewareTest.kt)
[task 2021-03-23T13:52:12.583Z] 	at kotlinx.coroutines.test.TestBuildersKt$runBlockingTest$deferred$1.invokeSuspend(TestBuilders.kt:50)
[task 2021-03-23T13:52:12.583Z] 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[task 2021-03-23T13:52:12.583Z] 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
[task 2021-03-23T13:52:12.583Z] 	at kotlinx.coroutines.test.TestCoroutineDispatcher.dispatch(TestCoroutineDispatcher.kt:50)
[task 2021-03-23T13:52:12.583Z] 	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:305)
[task 2021-03-23T13:52:12.583Z] 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
[task 2021-03-23T13:52:12.583Z] 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:27)
[task 2021-03-23T13:52:12.584Z] 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
[task 2021-03-23T13:52:12.584Z] 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158)
[task 2021-03-23T13:52:12.584Z] 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.async(Builders.common.kt:91)
[task 2021-03-23T13:52:12.584Z] 	at kotlinx.coroutines.BuildersKt.async(Unknown Source)
[task 2021-03-23T13:52:12.584Z] 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.async$default(Builders.common.kt:84)
[task 2021-03-23T13:52:12.584Z] 	at kotlinx.coroutines.BuildersKt.async$default(Unknown Source)
[task 2021-03-23T13:52:12.584Z] 	at kotlinx.coroutines.test.TestBuildersKt.runBlockingTest(TestBuilders.kt:49)
[task 2021-03-23T13:52:12.584Z] 	at kotlinx.coroutines.test.TestBuildersKt.runBlockingTest$default(TestBuilders.kt:45)
[task 2021-03-23T13:52:12.584Z] 	at mozilla.components.support.locale.LocaleMiddlewareTest.GIVEN a locale has been chosen in the app WHEN we restore state THEN locale is retrieved from storage(LocaleMiddlewareTest.kt:59)
[task 2021-03-23T13:52:12.584Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2021-03-23T13:52:12.584Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2021-03-23T13:52:12.584Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2021-03-23T13:52:12.584Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2021-03-23T13:52:12.584Z] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[task 2021-03-23T13:52:12.584Z] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[task 2021-03-23T13:52:12.584Z] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[task 2021-03-23T13:52:12.584Z] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[task 2021-03-23T13:52:12.584Z] 	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:601)
[task 2021-03-23T13:52:12.584Z] 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
[task 2021-03-23T13:52:12.584Z] 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
[task 2021-03-23T13:52:12.584Z] 	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:260)
[task 2021-03-23T13:52:12.584Z] 	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
[task 2021-03-23T13:52:12.584Z] 	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
[task 2021-03-23T13:52:12.584Z] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[task 2021-03-23T13:52:12.584Z] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[task 2021-03-23T13:52:12.584Z] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[task 2021-03-23T13:52:12.584Z] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[task 2021-03-23T13:52:12.584Z] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[task 2021-03-23T13:52:12.584Z] 	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
[task 2021-03-23T13:52:12.584Z] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[task 2021-03-23T13:52:12.584Z] 	at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:154)
[task 2021-03-23T13:52:12.584Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
[task 2021-03-23T13:52:12.584Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
[task 2021-03-23T13:52:12.584Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
[task 2021-03-23T13:52:12.584Z] 	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
[task 2021-03-23T13:52:12.584Z] 	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
[task 2021-03-23T13:52:12.584Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2021-03-23T13:52:12.584Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2021-03-23T13:52:12.584Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2021-03-23T13:52:12.584Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2021-03-23T13:52:12.584Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
[task 2021-03-23T13:52:12.585Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[task 2021-03-23T13:52:12.585Z] 	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
[task 2021-03-23T13:52:12.585Z] 	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
[task 2021-03-23T13:52:12.585Z] 	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
[task 2021-03-23T13:52:12.585Z] 	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:119)
[task 2021-03-23T13:52:12.585Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2021-03-23T13:52:12.585Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2021-03-23T13:52:12.585Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2021-03-23T13:52:12.586Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2021-03-23T13:52:12.586Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
[task 2021-03-23T13:52:12.586Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[task 2021-03-23T13:52:12.586Z] 	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
[task 2021-03-23T13:52:12.586Z] 	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
[task 2021-03-23T13:52:12.586Z] 	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
[task 2021-03-23T13:52:12.586Z] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
[task 2021-03-23T13:52:12.586Z] 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
[task 2021-03-23T13:52:12.586Z] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[task 2021-03-23T13:52:12.587Z] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[task 2021-03-23T13:52:12.587Z] 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
[task 2021-03-23T13:52:12.587Z] 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Amejia481** [comment]
cc @eliserichards
