### ISSUE TITLE
SystemEngine fails to initialize with Robolectric

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#997]
This was caused by the fix for #899. Since we now call `WebSettings.getDefaultUserAgent` when initializing the `SystemEngine`. In our Robolectric tests, we can set the internal `defaultUserAgent` to avoid this problem, but we didn't make this accessible for consumer tests.

```
java.lang.NullPointerException
	at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:313)
	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:383)
	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:194)
	at android.webkit.WebSettings.getDefaultUserAgent(WebSettings.java:1259)
	at mozilla.components.browser.engine.system.SystemEngine$Companion.initDefaultUserAgent(SystemEngine.kt:88)
	at mozilla.components.browser.engine.system.SystemEngine$Companion.access$initDefaultUserAgent(SystemEngine.kt:83)
	at mozilla.components.browser.engine.system.SystemEngine.<init>(SystemEngine.kt:27)
```

While this is just a testing problem, it prevents upgrading FireTV.

**Comment by csadilek** [comment]
The only workaround I see right now until we provide a way to mock this field from outside the package is to use reflection (terrible, but temporary :)):

```Kotlin
@Before
fun setup() {
  // This is setting a internal field just for testing purposes as
  // WebSettings.getDefaultUserAgent isn't mocked by Roboelectric
  val defaultUserAgentField = SystemEngine::class.java.getDeclaredField("defaultUserAgent")
  defaultUserAgentField.isAccessible = true
  defaultUserAgentField.set(null, "test-ua-string")
       
  // This is what we do:
  // SystemEngine.defaultUserAgent = "test-ua-string"
}
```

**Comment by Baron-Severin** [comment]
I swear a left a comment here earlier....

The workaround got me unstuck for now, so I think we're good until we get the more permanent fix in the next release.
