### ISSUE TITLE
Crash in [@ android.app.RemoteServiceException: at android.app.ActivityThread$H.handleMessage(ActivityThread.java)]

### ISSUE THREAD

**Issue by Tothepablo** [mozilla-mobile/android-components#9983]
Crash report: https://crash-stats.mozilla.org/report/index/04445745-591f-4403-9543-9bced0210308

Java stack trace:
```
android.app.RemoteServiceException
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1894)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7156)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8427)

**Comment by csadilek** [comment]
Duping to upstream issues: https://bugzilla.mozilla.org/show_bug.cgi?id=1651221
